Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "script.sh", privileged: false
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 2048
    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.synced_folder "../../../../", "/home/vagrant/browser-laptop", type: "rsync",
    rsync__exclude: ["node_modules/", ".git/"],
    rsync__args: ["--delete", "-z", "-r",]

  if Dir.exist?(File.dirname(__FILE__) + "/../../../../../electron")
    config.vm.provision "shell", inline: "cd /home/vagrant/electron && script/bootstrap.py -v", privileged: false
    config.vm.synced_folder "../../../../../electron", "/home/vagrant/electron", type: "rsync",
      rsync__exclude: ["out/", "node_modules/", "build/", "dist/", "external_binaries/", "vendor/", ".git/"],
      rsync__args: ["--delete", "-z", "-r"]
  end
end
