platform:
  - x86
  - x64

image: Visual Studio 2015
os: unstable

environment:
  nodejs_version: "6.1"

branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

pull_requests:
  do_not_increment_build_number: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:PLATFORM
  - node --version
  - npm --version
  - set npm_config_arch=%PLATFORM:x86=ia32%
  - npm install --progress false --depth 0

build: off

test_script:
  - npm run lint
  - npm test
