module.exports = {
  urlInput: '#urlInput',
  activeWebview: '.frameWrapper.isActive webview',
  activeTab: '.tab.active',
  activeTabTitle: '.tab.active .tabTitle',
  activeTabFavicon: '.tab.active .tabIcon',
  pinnedTabs: '.pinnedTabs',
  pinnedTabsTabs: '.pinnedTabs .tab',
  tabsTabs: '.tabs .tab',
  navigator: '#navigator',
  navigatorLoadTime: '#navigator .loadTime',
  newFrameButton: '.tabs .newFrameButton',
  tabPage: '.tabPage',
  tabPage1: '[data-tab-page="0"]',
  tabPage2: '[data-tab-page="1"]',
  closeTab: '.closeTab',
  urlbarIcon: '.urlbarIcon',
  urlBarSuggestions: '.urlBarSuggestions',
  titleBar: '#titleBar',
  navigatorBookmarked: '#navigator .endButtons .removeBookmarkButton',
  navigatorNotBookmarked: '#navigator .endButtons .bookmarkButton',
  bookmarksToolbar: '.bookmarksToolbar',
  notificationBar: '.notificationBar',
  errorContent: '.errorContent',
  errorUrl: '.errorUrl',
  errorText: '.errorText',
  findBar: '.findBar',
  findBarInput: '.searchStringContainer input',
  findBarMatches: '.foundResults',
  findBarMatchCase: '#caseSensitivityCheckbox',
  findBarNextButton: '.findButton.findNext',
  findBarPrevButton: '.findButton.findPrev',
  braveMenu: '.braveMenu:not(.braveShieldsDisabled)',
  braveMenuDisabled: '.braveMenu.braveShieldsDisabled',
  adsBlockedStat: '.braveryStat.adsBlockedStat',
  braveryPanel: '.braveryPanel',
  httpsEverywhereStat: '.braveryStat.redirectedResourcesStat',
  noScriptStat: '.braveryStat.noScriptStat',
  fpStat: '.braveryStat.fpStat',
  fpSwitch: '.fingerprintingProtectionSwitch .switchMiddle',
  noScriptSwitch: '.noScriptSwitch .switchMiddle',
  noScriptNavButton: '#navigator .noScript',
  backButton: '.backforward .back',
  forwardButton: '.backforward .forward',
  clearBrowsingDataPanel: '.clearBrowsingDataPanel',
  clearBrowsingDataButton: '.clearBrowsingDataButton',
  securityTab: '[data-l10n-id="security"]',
  saveButton: '[data-l10n-id="save"]',
  deleteButton: '[data-l10n-id="delete"]',
  autofillAddressPanel: '.autofillAddressPanel',
  autofillCreditCardPanel: '.autofillCreditCardPanel'
}
