module.exports = {
  APP_SET_URL: 1,
  APP_SET_NAVBAR_INPUT: 2,
  APP_NEW_FRAME: 3,
  APP_SET_ACTIVE_FRAME: 4,
  APP_TAB_DRAG_START: 5,
  APP_TAB_DRAG_STOP: 6,
  APP_TAB_DRAGGING_OVER_LEFT: 7,
  APP_TAB_DRAGGING_OVER_RIGHT: 8,
  APP_TAB_DRAGGING_ON: 9,
  APP_TAB_DRAG_EXIT: 10,
  APP_TAB_DRAG_EXIT_RIGHT: 11,
  APP_TAB_MOVE: 12
}
