module.exports = {
  APP_SET_URL: 1,
  APP_SET_NAVBAR_INPUT: 2,
  APP_NEW_FRAME: 3,
  APP_CLOSE_FRAME: 4,
  APP_SET_ACTIVE_FRAME: 5,
  APP_TAB_DRAG_START: 6,
  APP_TAB_DRAG_STOP: 7,
  APP_TAB_DRAGGING_OVER_LEFT: 8,
  APP_TAB_DRAGGING_OVER_RIGHT: 9,
  APP_TAB_DRAGGING_ON: 10,
  APP_TAB_DRAG_EXIT: 11,
  APP_TAB_DRAG_EXIT_RIGHT: 12,
  APP_TAB_MOVE: 13,
  APP_UPDATE_BACK_FORWARD: 14
}
