#!/bin/sh
set -exu

BUCKET=${1:-brave-rpm-nightly}
GPG_KEY="4A1B4360"
KEY_NAME=keys.asc
KEY_FILE=/tmp/${KEY_NAME}
TMP_REPO=/tmp/rpm_repo

echo "You'll want something like
%_signature gpg
%_gpg_path /home/posi/.gnupg
%_gpg_name Alex Newman
%_gpgbin /usr/bin/gpg"
echo "In your ~/.rpmmacros"

rm -rf $TMP_REPO
mkdir -pv $TMP_REPO/x86_64
cp dist/*.rpm $TMP_REPO/x86_64/
for rpm in dist/*.rpm ; do
  rpm --addsign  $rpm
done

for arch in $TMP_REPO/x86_64 ; do
  createrepo -v --deltas $arch/ 
done
for arch in $TMP_REPO/x86_64 ; do
  createrepo -v --update --deltas $arch/ 
done

gpg --export --armor ${GPG_KEY} > ${KEY_FILE}
aws s3 cp ${KEY_FILE} s3://${BUCKET}/keys.asc
aws s3api put-object-acl --acl public-read --bucket ${BUCKET} --key ${KEY_NAME}
aws s3 sync --acl public-read $TMP_REPO/ s3://$BUCKET/

