document.title=gs("About");var g_licensehost="lastpass.com";
function on_load(a){if(a){document.body.appendChild(document.createTextNode(gs("LastPass Chrome Toolbar")));getBG().LPISLOC&&document.body.appendChild(document.createTextNode(" ("+gs("Local")+")"));document.body.appendChild(document.createElement("br"));document.body.appendChild(document.createElement("br"));document.body.appendChild(document.createTextNode(gs("Version:")+" "+lpversion));document.body.appendChild(document.createElement("br"));document.body.appendChild(document.createTextNode(gs("Built:")+
" "+build_date));document.body.appendChild(document.createElement("br"));document.body.appendChild(document.createTextNode(gs("Binary Component:")+" "));getBG().have_nplastpass()?document.body.appendChild(document.createTextNode(gs("true")+" (NPAPI "+gs("Version").toLowerCase()+" "+getBG().get_nplastpass_version()+", "+gs("built")+" "+getBG().get_nplastpass_build_date_time()+")")):getBG().have_native_messaging()?document.body.appendChild(document.createTextNode(gs("true")+" ("+(g_isfirefoxsdk?gs("ctypes"):
gs("Native Messaging"))+" "+gs("Version").toLowerCase()+" "+getBG().g_native_messaging_version+", "+gs("built")+" "+getBG().g_native_messaging_build_date+" "+getBG().g_native_messaging_build_time+")")):getBG().have_pplastpass()?document.body.appendChild(document.createTextNode(gs("false")+" ("+gs("Native Client only")+")")):getBG().have_ws()?document.body.appendChild(document.createTextNode(gs("true")+" (Helper App)")):document.body.appendChild(document.createTextNode(gs("false")));document.body.appendChild(document.createTextNode(" "));
a=document.createElement("span");a.id="enable_binary_span";a.className="displaynone";var b=document.createElement("button");b.id="enable_binary_button";a.appendChild(b);document.body.appendChild(a);document.body.appendChild(document.createElement("br"));document.body.appendChild(document.createElement("br"));a=gs("Copyright 2008 LastPass. All Rights Reserved.\nPortions of this software were licensed from third parties as described at:")+" ";a=a.replace(" 2008 "," 2008-"+(new Date).getFullYear()+" ");
a=a.split("\n");document.body.appendChild(document.createTextNode(a[0]));document.body.appendChild(document.createElement("br"));document.body.appendChild(document.createTextNode(a[1]));getBG().g_hidelicenselink||(a=document.createElement("a"),a.setAttribute("target","_blank"),a.setAttribute("href","https://"+g_licensehost+"/docs/licenses.php"),set_innertext(a,"https://"+g_licensehost+"/docs/licenses.php"),document.body.appendChild(a));getBG().g_hideaboutmanuallink||(document.body.appendChild(document.createElement("br")),
document.body.appendChild(document.createElement("br")),a=document.createElement("a"),a.id="openhelp",a.setAttribute("href","#"),set_innertext(a,gs("Click here to view the LastPass User Manual")),document.body.appendChild(a),document.getElementById("openhelp").onclick=function(){getBG().openhelp();return!1});getBG().g_issafari&&(!getBG().have_nplastpass()&&!getBG().have_ws())&&(document.body.appendChild(document.createElement("br")),document.body.appendChild(document.createElement("br")),a=document.createElement("b"),
set_innertext(a,"Please Note (Yosemite Users):"),document.body.appendChild(a),document.body.appendChild(document.createTextNode(" In order to use the binary component, you must install the components and go to Safari Menu=>View=>Show LastPass Menu Bar.")));a=function(a){a?!getBG().have_nplastpass()&&(!getBG().have_native_messaging()&&!getBG().have_ws())&&(set_innertext(document.getElementById("enable_binary_button"),gs("Install Binary Component")),document.getElementById("enable_binary_button").onclick=
getBG().install_binary,document.getElementById("enable_binary_span").style.display="inline"):(set_innertext(document.getElementById("enable_binary_button"),gs("Enable Native Messaging")),document.getElementById("enable_binary_button").onclick=function(){getBG().request_native_messaging()},document.getElementById("enable_binary_span").style.display="inline")};if(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)!g_isfirefoxsdk&&!g_isedge&&(supports_native_messaging()&&getBG().g_do_native_messaging?
getBG().test_native_messaging(a):a(!0))}else get_data("about",function(){on_load(!0)})}document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){on_load()})});
