function verbose_log(d){(debug||"undefined"!=typeof verbose&&!0===verbose)&&lplog(d)}
function debug_checkpoint_handler(d,a){var b="";if(a&&is_user_debug_enabled()&&"undefined"!=typeof a.msg&&a.msg&&0<a.msg.length){try{b=JSON.parse(a.msg)}catch(c){console_error("json parse failed on '"+a.msg+"'")}console_log(sprintf("DEBUG [%s][%d][%s][t=%d][url=%s] %s",d,a.docnum,a.docstate,a.timestamp,a.url,b));b={cmd:"dbgCS",tabid:d,docnum:a.docnum,url:a.url,docstate:a.docstate,msg:b};"undefined"!=typeof a.history_cmd&&a.history_cmd&&(b.cmd=a.history_cmd);"undefined"!=typeof a.timestamp&&a.timestamp&&
(b.timestamp=a.timestamp);"undefined"!=typeof a.aid&&(b.aid=a.aid);"undefined"!=typeof a.num&&(b.num=a.num);"undefined"!=typeof a.param1&&(b.param1=a.param1);"undefined"!=typeof a.param2&&(b.param2=a.param2);"undefined"!=typeof a.param3&&(b.param3=a.param3);"undefined"!=typeof a.param4&&(b.param4=a.param4);"undefined"!=typeof a.param5&&(b.param5=a.param5);"undefined"!=typeof a.param6&&(b.param6=a.param6);"undefined"!=typeof a.param7&&(b.param7=a.param7);"undefined"!=typeof a.param8&&(b.param8=a.param8);
"undefined"!=typeof a.param9&&(b.param9=a.param9);write_history(b)}}function opendebugtab(){openURL(getchromeurl("debug.html"))}function is_user_debug_enabled(){return g_isdebug}
function trigger_notification(d,a,b,c){if(!g_isdebug)return!1;var g={9999:{aid:"9999",fields:[],save_all:0,action:"",attachkey:"",autologin:!1,basic_auth:"0",breached:"0",deleted:"0",fav:"0",groupid:"0",group:"Travel",fiid:"9999",genpw:!1,last_touch:"0",method:"",name:"fake site",never_autofill:!1,url:"http://nowhere.co",tld:"nowhere.co",pwch:"0",pwprotect:!1,notetype:"",realm_data:"",sharedfromaid:"",sn:!1,useusername:"uxuxuxux",customjs:"",unencryptedUsername:"uxuxuxux",noalert:"",vulnerable:"",
submit_id:"",username:"----------",password:"--------"}},f=!0,e=!0;c||(c={});switch(a){case "add":b||(b=gs("Should LastPass remember this password?"));"undefined"==typeof c.tld&&(c.url="http://nowhere.co",c.tld="nowhere.co");"undefined"==typeof c.formdata&&(c.formdata="\tusername\tuuuuuuuu\ttext\tseen\n\tpwd\tpppp\tpassword\tseen\n\tlocale\tde-DE\thidden\tnotseen\n",c.username="uuuuuuuu",c.password="pppp");break;case "change":f=!1;b||(b=gs("LastPass detected a password change for user:")+" whodat@nowhere.cc");
"undefined"==typeof c.newpw&&(c.newpw="abcde");"undefined"==typeof c.oldpw&&(c.oldpw="");"undefined"==typeof c.tld&&(c.tld="nowhere.co");"undefined"==typeof c.sitecount&&(c.sitecount=1);1===c.sitecount&&typeof("undefined"==c.singleaid)&&(c.singleaid=9999);break;case "fill":b||(b=gs("LastPass has filled your login information into the form on this page."));break;case "formfill":b||(b=gs("FillableFormDetected"));break;case "error":b||(b="Generic Error Message");"undefined"==typeof c.showFeedback&&(c.showFeeback=
!1);"undefined"==typeof c.showLogin&&(c.showLogin=!1);break;case "basicauth":"undefined"==typeof c.needbinary?c.needbinary=!0:e=c.needbinary?!0:!1;b||(b=e?gs("In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome."):gs("In order for LastPass to fill into basic authentication dialogs, you need to enable access for assistive devices."));break;default:b||(b="Test Message")}if("undefined"==typeof{add:"showaddnotification",fill:"showfillnotification",
change:"showchangenotification",error:"showerrornotification",basicauth:"showbasicauthnotification",context:"showcontext",formfill:"formfill",generic:"lpshownotification"}[a])return console.warn("invalid type "+a),!1;b={cmd:"lpshownotification",type:a,data:{text:b,notificationdata:f?LPJSON.stringify(c):c,do_40notify:g_40notify}};switch(a){case "fill":delete b.data.notificationdata;b.data.sites=LPJSON.stringify(g);break;case "formfill":delete b.data.notificationdata;b.data.aid=0;b.data.extra=void 0;
b.data.extra2=void 0;b.data.extra3=void 0;break;case "basicauth":delete b.data.notificationdata,b.data.needbinary=e}sendCS(d,b,"all");return!0};
