var Checkpoint=new checkpoint_lib;initCheckpoint();function initCheckpoint(){if("undefined"==typeof Checkpoint||null===Checkpoint)Checkpoint=new checkpoint_lib;return"undefined"==typeof Checkpoint||null===Checkpoint?!1:!0}function doCheckpoint(){return g_enable_checkpoint&&"undefined"!=typeof g_isdebug&&g_isdebug?(initCheckpoint(),Checkpoint.assert.apply(this,arguments)):!0}
function checkpoint_lib(){function d(a,b){return sprintf("%sproperty '%s' is missing or wrong type",b?"["+b+"] ":"",a)}function k(a,b){return sprintf("%sunexpected value of %s was found",b?"["+b+"] ":"",a)}function l(a,b){b=LPPerl.chomp(b);"undefined"!=typeof console&&console&&(a===n?console.warn(b):a===m?console.error(b):console.log(b));return!0}var c=this,j=0,f=0,g=0,h=0;if("undefined"!=typeof Date){var h=(new Date).getTime(),m=2,n=1;this.checkpoint=function(){return!0};this.init=function(){g=f=
j=0;h=(new Date).getTime()};this.reset=function(){c.init()};this.assert=function(){var a=arguments;if("undefined"==typeof g_isdebug||!g_isdebug)return g++,!0;var b=null;"undefined"!=typeof a[3]&&"function"==typeof a[3]&&(b=a[3],"undefined"!=typeof a[4]?b(a[4]):b());if(0>=a.length)return f++,b(),!1;if("undefined"!=typeof a[2]&&a[2])return g++,!0;if(!0===a[0])return j++,!0;f++;l(m,sprintf("ASSERT FAILED: %s !== true%s",a[0],a[1]?" : "+a[1]:""))};this.stats=function(){var a;a="undefined"!=typeof(new Date(h)).toUTCString?
(new Date(h)).toUTCString():parseInt(h/1E3).toString();return l(0,sprintf("Since %s, %d good, %d bad, %d skipped\n",a,j,f,g))};this.getstats=function(){return{good:j,bad:f,skipped:g}};this.validate_share_type=function(a,b){if(!a)return!1;var e;e=(e=(e=(e=(e=(e=(e=c.assert("string"==typeof a.id,d("id",b)))&&c.assert("string"==typeof a.sharekey,d("sharekey",b)))&&c.assert("string"==typeof a.sharename,d("sharename",b)))&&c.assert(c.in_array(a.readonly,["0","1"]),d("readonly",b)))&&c.assert(c.in_array(a.give,
["0","1"]),d("give",b)))&&c.assert("string"==typeof a.sharekeyaes||""===a.sharekeyaes,d("sharekeyaes",b)))&&c.assert(c.in_array(a.associative,[0,"0","1"]),d("associative",b));"undefined"!=typeof a.linkedshare&&(e=e&&c.assert(c.in_array(a.linkedshare,["0","1"]),d("linkedshare",b)));return e=(e=(e=(e=e&&c.assert("string"==typeof a.key,d("key",b)))&&c.assert("string"==typeof a.decsharename,d("decsharename",b)))&&c.assert(lpdec(a.sharename,a.key)===a.decsharename,k("sharename/decsharename",b)))&&c.assert(AES.hex2bin(lpmdec(a.sharekeyaes,
!0))===a.key,k("decrypted sharing key",b))};this.validate_shareinfo_type=function(a,b){if(!a)return!1;var e;return e=(e=(e=(e=(e=(e=(e=c.assert("string"==typeof a.id,d("id",b)))&&c.assert("string"==typeof a.sharekey,d("sharekey",b)))&&c.assert("string"==typeof a.decsharename,d("decsharename",b)))&&c.assert(c.in_array(a.readonly,["0","1"]),d("readonly",b)))&&c.assert(c.in_array(a.give,["0","1"]),d("give",b)))&&c.assert(c.in_array(a.associative,[0,"0","1"]),d("associative",b)))&&c.assert(c.in_array(a.linkedshare,
["0","1"]),d("linkedshare",b))};this.in_array=function(a,b){if("undefined"==typeof b||null===b)return!1;for(var c=b.length,d=0;d<=c;d++)if("undefined"!=typeof b[d]&&b[d]===a)return lpArrayOffset=d,!0;return!1};this.validate_fieldinfo=function(a){if(!a)return!1;var b=!0;if(null===a.name||"string"!=typeof a.name)console_warn("FAIL: field.name"),b=!1;if(null===a.type||"string"!=typeof a.type&&!lp_in_array(a.type,"text password button file hidden checkbox radio textarea submit image select select-one".split(" "))&&
!lp_in_array(a.type,"color date datetime datetime-local email month number range search tel time url week".split(" ")))console_warn("FAIL: field.type"),b=!1;"radio"==a.type||"checkbox"==a.type?!0!==a.checked&&!1!==a.checked&&(console_warn("FAIL: field.checked for "+a.type),b=!1):!1!==a.checked&&(b=!1);if("1"===a.otherlogin){""===a.url?(console_warn("FAIL: field.url should be set in addruid case"),b=!1):hex2url(a.url).match(/^https?:\/\//,"i")||(console_warn("FAIL: invalid field.url"),b=!1);if(""===
a.urid||"0"===a.urid)console_warn("FAIL: field.urid should be set in addurid case"),b=!1;!1!==a.otherfield&&(console_warn("FAIL: field.otherfield must be false in addurid case"),b=!1)}else"0"!==a.otherlogin&&""!==a.otherlogin&&(console_warn("FAIL: field.otherlogin [deprecated?]"),b=!1),""!==a.url&&(console_warn("FAIL: field.url should be empty in non-addurid case"),b=!1),"0"!==a.urid&&""!==a.urid&&(console_warn("FAIL: field.urid should be empty in non-addurid case"),b=!1);!0!==a.otherfield&&!1!==
a.otherfield&&(console_warn("FAIL: field.otherfield [deprecated?]"),b=!1);for(var c in a)a.hasOwnProperty(c)&&!lp_in_array(c,"name type value formname checked urid otherlogin url otherfield".split(" "))&&(console_warn("found an unexpected property in field info: "+c),b=!1);return b}}};
