var ContainerSelectionDialog=function(c){VaultItemDialog.call(this,c,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.selectedCollapsed=this.availableCollapsed=!1;var d=this;this.toggleCollapse=function(b,a,c){c=$(c.target);d[b]?(a.expandAll(),d[b]=!1,c.attr("title","Collapse All")):(a.collapseAll(),d[b]=!0,c.attr("title","Expand All"));c.toggleClass("selected")}};ContainerSelectionDialog.prototype=Object.create(VaultItemDialog.prototype);
ContainerSelectionDialog.prototype.constructor=ContainerSelectionDialog;
(function(){ContainerSelectionDialog.prototype.initialize=function(d){VaultItemDialog.prototype.initialize.apply(this,arguments);var b=this;d.find(".availableSearch").LP_addSearchHandlers("inputDialog",function(a){b.containers.available.applySearch(a)});d.find(".selectedSearch").LP_addSearchHandlers("inputDialog",function(a){b.containers.selected.applySearch(a)});d.find(".availableCollapseToggle").bind("click",function(a){b.toggleCollapse("availableCollapsed",b.containers.available,a)});d.find(".selectedCollapseToggle").bind("click",
function(a){b.toggleCollapse("selectedCollapsed",b.containers.selected,a)});b.availableContainerElement=d.find(".containerSelectionDialogAvailable");b.availableContainerElement.bind("dragover",function(a){0<b.selectedFromSelected.length&&(a.preventDefault(),a.stopPropagation())});b.availableContainerElement.bind("drop",function(){c(b.selectedFromSelected,b.containers.available)});b.selectedContainerElement=d.find(".containerSelectionDialogSelected");b.selectedContainerElement.bind("dragover",function(a){0<
b.selectedFromAvailable.length&&(a.preventDefault(),a.stopPropagation())});b.selectedContainerElement.bind("drop",function(){c(b.selectedFromAvailable,b.containers.selected)});b.availableVaultItemOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_ADD,{text:b.getAddToSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_ADD},add:function(){c(this.getItemsForAction(),b.containers.selected)}};b.availableGroupOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_ADD,
{text:b.getAddToSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_ADD},add:function(){c(this.getItemChildren(),b.containers.selected)}};b.selectedVaultItemOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE,{text:b.getRemoveFromSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){c(this.getItemsForAction(),b.containers.available)}};b.selectedGroupOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE,
{text:b.getRemoveFromSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){c(this.getItemChildren(),b.containers.available)}}};var c=function(d,b){d=d.slice();for(var a=0,c=d.length;a<c;++a){var e=d[a],f=e._parent._model,g=e._model;e.destruct();b.addChild(g.newDisplayObject(),f)}};ContainerSelectionDialog.prototype.getAddToSelectedText=function(){return Strings.translateString("Add to Selected")};ContainerSelectionDialog.prototype.getRemoveFromSelectedText=
function(){return Strings.translateString("Remove from Selected")};ContainerSelectionDialog.prototype.setup=function(c,b){this.selectedFromAvailable=[];this.selectedFromSelected=[];var a=this;a.containers.available=new Container(a.getAvailableItems(b),{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem noItemButtons",additionalGroupClasses:"dialogItemGroup",forceDrag:!0,allowDrop:!1,publishSelect:!1,dragstart:function(){a.selectedFromAvailable=LPTools.getDragItems()},
override:function(){return this instanceof GroupDisplay?a.availableGroupOverrides:a.availableVaultItemOverrides}});a.containers.available.initialize(a.availableContainerElement.get(0));a.containers.selected=new Container(a.getSelectedItems(b),{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem noItemButtons",additionalGroupClasses:"dialogItemGroup",forceDrag:!0,allowDrop:!1,publishSelect:!1,dragstart:function(){a.selectedFromSelected=LPTools.getDragItems()},override:function(){return this instanceof
GroupDisplay?a.selectedGroupOverrides:a.selectedVaultItemOverrides}});a.containers.selected.initialize(a.selectedContainerElement.get(0));VaultItemDialog.prototype.setup.apply(this,arguments)}})(document);
