var lpicon="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAAKCAMAAACOlf6TAAAAPFBMVEVMaXFaWlpZWVlZWVlZWVlYWFhaWlpaWlpZWVlZWVlaWlpYWFhaWlpaWlpaWlpeXl5ZWVlbW1tZWVlaWlqPt7PZAAAAE3RSTlMA44bOvDmzxKzRmRslLsgTFEZFj0O9XgAAAD9JREFUeF6FztsKgDAMBNFRa9LUu/v//yr4JqF4HgcWln+VxIEr7GSeysK2+/qmQRoJqVGk2kt32PEZJt45kTzdRQJNGXFLsAAAAABJRU5ErkJggg==",lpgenerateicon="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAnNCSVQICFXsRgQAAAAJcEhZcwAADdcAAA3XAUIom3gAAAAZdEVYdFNvZnR3YXJlAHd3dy5pbmtzY2FwZS5vcmeb7jwaAAABHklEQVQoz3WRMUtCYRSGj7RUEBQIjgmhg2CzsxGURENYe+Bgew1t/gEH/8DF2SG933O/IAoC/4BbRNIohOBSDS72NnhLs+JZDofnwMt5TTZPmApTPzffA0kCBggxICC5IFBiyARHjRqOCUNKc4Lf5JW+K3xduQJ93trpb4Ebxp2czGfp0vVZWSfHmLtYaK/zQUMmo+73/B51mYwGIikzGTuIsowMPQICemRklFG4KzNZdIxcUUYVxVRlrojcicxk11vInS8KXCCf/Qo54PF+2edpTvH51gpPvCgRC9ERoiKTtdPRoSxcoznNNXvUaWtJ5vYZccslI0Sw8GoZFSZxhvfo7FcXsnCbZ8SDO2D1j7JksmiDiKt/2oxJzHqc8glnzSOgfYOoRwAAAABJRU5ErkJggg==",
lpformfillicon="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAA3NCSVQICAjb4U/gAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAACpQTFRF////tra2rq6utbW1tLS0tLS0s7Ozs7Ozs7OztLS0s7Ozs7Ozs7Ozs7Oz5RWMIQAAAA10Uk5TAAcTMD1VYWh2mKyy++9xPvoAAABGSURBVAjXY2CAA9FyIAgEMnrvAsENIGOuMRDcBDEYuDcwQBhcC6CMnGNQxtybEAaTsbECmMEyc6YDKgMuBTMQbgXcUigAALv6JnRsfYWhAAAAAElFTkSuQmCC";
function lpcreate_icons(){for(var a=document.getElementsByTagName("form"),b=0;b<a.length;b++){var c=get_input_counts(a[b]);show_icons(a[b],c)}}function check_curr_password(a){var b=/(?:existing|old|curr).*pass/i;return b.test(a.name)||b.test(a.id)}
function get_input_counts(a){var b={text:0,password:0};a=a.elements;for(var c=0;c<a.length;c++)if(!(4>=(a[c].hasAttribute("maxlength")?a[c].getAttribute("maxlength"):1E4))){var d=a[c].type;"none"!=a[c].style.display&&"hidden"!=a[c].style.visibility&&("text"==d||"email"==d||"tel"==d?b.text++:"password"==d&&b.password++)}return b}function show_icons(a,b){3<b.text&&0<b.password?show_icons_formfill(a):3>=b.text&&1==b.password?show_icons_login(a):1<b.password&&show_icons_generate(a)}
function show_icons_formfill(a){for(var b=0,c=0;c<a.elements.length;c++)!b&&"text"==a.elements[c].type?(b=1,lpsetup_icon(a.elements[c],"formfill")):"password"==a.elements[c].type&&lpsetup_icon(a.elements[c],"generate")}
function show_icons_login(a){for(var b=0;b<a.elements.length;b++)if(!(4>=(a.elements[b].hasAttribute("maxlength")?a.elements[b].getAttribute("maxlength"):1E4)))"text"==a.elements[b].type||"email"==a.elements[b].type||"tel"==a.elements[b].type?lpsetup_icon(a.elements[b],"login"):"password"==a.elements[b].type&&lpsetup_icon(a.elements[b],"login")}
function show_icons_generate(a){for(var b=0;b<a.elements.length;b++)"password"==a.elements[b].type&&lpsetup_icon(a.elements[b],check_curr_password(a.elements[b])?"login":"generate")}
function lpsetup_icon(a,b){var c=lpicon;"generate"==b?c=lpgenerateicon:"formfill"==b&&(c=lpformfillicon);a.style.backgroundImage="url("+c+")";a.style.backgroundPosition="center right";a.style.backgroundRepeat="no-repeat";a.addEventListener("touchstart",function(a){var c=getAbsolutePos(document,a.target),f=a.touches[0].pageX+document.body.scrollLeft+document.documentElement.scrollLeft,h=a.touches[0].pageY+document.body.scrollTop+document.documentElement.scrollTop;a.handled=!1;if(c){var e=4;"function"==
typeof dp_to_px&&(e=dp_to_px(e));f>c.left+c.width-18-e&&(f<c.left+c.width+e&&h>c.top-e&&h<c.top+c.height+e)&&(a.handled=!0,a.preventDefault(),iconClicked(b))}})}
function getAbsolutePos(a,b){if(null!=b){if("function"!=typeof b.getBoundingClientRect)return null;var c=b.getBoundingClientRect(),d,g;d="undefined"==typeof c.width?c.right-c.left:c.width;g="undefined"==typeof c.height?c.bottom-c.top:c.height;var f=a.body.getBoundingClientRect();return{left:c.left+a.body.scrollLeft-f.left,top:c.top+a.body.scrollTop-f.top,width:d,height:g}}return null};
