var tz=document.getElementById("timezone");init_timezones();for(var i=0;i<all_timezones.length;i++)tz.options[tz.options.length]=new Option(all_timezones[i].name,all_timezones[i].value);
function onLoad(a){a?(getBG().g_create_account_data?(document.getElementById("email").value=getBG().g_create_account_data.email,document.getElementById("masterpassword").value=getBG().g_create_account_data.masterpassword,document.getElementById("passwordreminder").value=getBG().g_create_account_data.passwordreminder,document.getElementById("timezone").value=getBG().g_create_account_data.timezone,document.getElementById("terms").checked=!0,document.getElementById("data").checked=!0,document.getElementById("history").checked=
getBG().g_create_account_data.history,document.getElementById("improve").checked=getBG().g_create_account_data.improve):(tz.value=calculate_time_zone(!1),document.getElementById("passwordreminder").setAttribute("placeholder",gs("(Optional)"))),document.getElementById("email").focus(),update_password_meter(document.getElementById("email").value,document.getElementById("masterpassword").value),document.getElementById("createanaccount")&&set_innertext(document.getElementById("createanaccount"),gs("Create Account")),
document.getElementById("nothanks")&&set_innertext(document.getElementById("nothanks"),gs("No Thanks"))):get_data("create_account",function(){onLoad(!0)})}var dobeforeunload=!0;
function do_submit(){var a=document.getElementById("masterpassword").value,c=document.getElementById("confmasterpassword").value,d=document.getElementById("email").value,e=document.getElementById("passwordreminder").value,b="";""!=welcome_email_check&&"ok"!=welcome_email_check?b+=welcome_email_check+"\n\n":""==welcome_email_check&&5>d.length&&(b+=gs("It looks like you've entered an invalid or incomplete email address. Please try again.")+"\n\n");document.getElementById("terms").checked||(b+=gs("You must agree to the Terms and Conditions in order to continue")+
"\n\n");document.getElementById("data").checked||(b+=gs("You must agree to send your encrypted data to LastPass in order to use our product.\nYour data is encrypted before it is sent to our secure servers. No one at LastPass can read your confidential data, because this data is encrypted using your secret Master Password, and you should be the only person who knows your password.")+"\n\n");if(""!==b)return alert(b),!1;8>a.length&&(b+=gs("Sorry, your password is too short. It must be a minimum of 8 characters long for security reasons.")+
"\n\n");a==d&&(b+=gs("Sorry, your password can not be the same as your email address.")+"\n\n");if(a.match(/^password\d{0,3}$/i)||"12345678"==a||"123456789"==a||"1234567890"==a||a.match(/^lastpass\d{0,3}$/i)||"lastpass.com"==a||"qwertyuiop"==a||"abcd1234"==a)b+=gs("Your password is easily guessable, avoid simple runs of characters, or variations of 'password' or 'lastpass'.")+"\n\n";if(""!==b)return alert(b),!1;a!=c&&(b+=gs("Your Master Password and Confirm Master Password entries do not match, please enter them again.")+
"\n\n");a==e&&(b+=gs("Your Password Reminder can not be the same as your chosen Master Password for security reasons. Please edit your Reminder so that it does not contain your Master Password.")+"\n\n");if(""!==b)return alert(b),!1;dobeforeunload=!1;getBG().g_create_account_data=[];getBG().g_create_account_data.email=d;getBG().g_create_account_data.masterpassword=a;getBG().g_create_account_data.passwordreminder=e;getBG().g_create_account_data.timezone=document.getElementById("timezone").value;getBG().g_create_account_data.history=
document.getElementById("history").checked;getBG().g_create_account_data.improve=document.getElementById("improve").checked;getBG().update_create_account_data();redirect_to_url("reenter_password.html")}var welcome_email_check="";function checkEmail(){}
function lpCheckEmailResponse(a){if(4==a.readyState&&200==a.status&&a.responseText){var c=document.getElementById("emailerror");c.style.display="none";a=a.responseText;0<=a.indexOf("ok")?welcome_email_check="ok":0<=a.indexOf("emailinvalid")?welcome_email_check=gs("Invalid email address, try again"):0<=a.indexOf("mistype:")?(welcome_email_check="ok",c.style.display="block",set_innertext(c,a.substr(8))):welcome_email_check=gs("Email already in use, have you forgotten your password?")}};
