var CS_table=[];function CS_t(){}function getcsid(a,d){return("function"==typeof lp_sha256?lp_sha256:SHA256)(a+""+d)}function getcsinfo(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c=getcsid(a,d);if(null===c)return null;c=CS_table[c];"undefined"==typeof c&&(c=null);return c}
function setcsinfo(a,d,c){if(null===a||null===d||!c||"undefined"==typeof a||"undefined"==typeof d||null===c.docnum||null===c.tabid||null===c.url)return null;"number"==typeof a&&(a=a.toString());a=getcsid(a,d);c.csid&&(a&&a!=c.csid)&&L("warn: csid!=obj.csid");if(null===c.csid||"undefined"==typeof c.csid)c.csid=a;c.last_ts=(new Date).getTime();"undefined"==typeof CS_table&&(CS_table=[]);CS_table[a]=c;return!0}
function register_new_cs(a,d,c,b,f,e){if(null===a||null===d||!c||"undefined"==typeof a||"undefined"==typeof d)return null;write_history({cmd:"register_new_cs",docnum:d,tabid:a,docstate:f});"undefined"==typeof f&&(f=null);"undefined"==typeof e&&(e=null);"number"==typeof a&&(a=a.toString());var h=0,g=new CS_t;return g?(g.docnum=d,g.tabid=a,g.url=c,g.lastfill_aid=0,g.parent_docnum=b?d:g_CS_tops[a],g.docstate=f,g.flags=null,null!==e&&"object"==typeof e&&(g.flags=e,"undefined"!=typeof e.domain&&(g.domain=
e.domain,delete g.flags.domain),"undefined"!=typeof e.origin&&(g.origin=e.origin,delete g.flags.origin)),g.start_ts=(new Date).getTime(),g_cpwbot&&CPWbot_bg&&(h=CPWbot_bg.score_frame(a,{url:c,docnum:d})),g.importance=h,setcsinfo(a,d,g)):null}
function delete_cs_for_docnum(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c=!1,b;for(b in CS_table)CS_table.hasOwnProperty(b)&&b==getcsid(a,d)&&(c=!0,delete CS_table[b]);return c}
function delete_cs_for_tab(a){if(null===a||"undefined"==typeof a)return null;"number"==typeof a&&(a=a.toString());var d=!1,c;for(c in CS_table)if(CS_table.hasOwnProperty(c)){var b=CS_table[c];b&&b.tabid==a&&(d=!0,delete CS_table[c])}return d}
function update_cs_docstate(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c=d.docnum;if(null===c||"undefined"==typeof c)return null;var b=d.docstate;if(null===b||"undefined"==typeof b)return null;var f=!1,e=getcsinfo(a,c);e&&(e.docstate=b,f=setcsinfo(a,c,e));return f}
function update_cs_timestamp(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c=d.docnum;if(null===c||"undefined"==typeof c)return null;var b=getcsinfo(a,c);return b?setcsinfo(a,c,b):null}function count_cs_for_tabid(a){if(null===a||"undefined"==typeof a)return-1;"number"==typeof a&&(a=a.toString());var d=0,c,b;for(c in CS_table)CS_table.hasOwnProperty(c)&&(b=CS_table[c],b.tabid===a&&d++);return d}
function dumpinfo_for_tabid(a){if(!(null===a||"undefined"==typeof a)){"number"==typeof a&&(a=a.toString());var d,c,b;console.log("dumping info for tabid="+a);for(c in CS_table)CS_table.hasOwnProperty(c)&&(b=CS_table[c],d=(new Date).getTime(),b.tabid===a&&console.log("DUMPINFO [tabid:"+a+"][docnum:"+b.docnum+"] url="+b.url+" last_ts="+(d-b.last_ts)/1E3+"secs score="+b.importance+" killswitch?="+b.killswitch+" isTop?="+(b.parent_docnum==b.docnum?"true":"false")))}}
function find_docnum_for_tabid_by_url(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c,b,f;for(c in CS_table)if(CS_table.hasOwnProperty(c)&&(f=CS_table[c],f.tabid===a&&f.url==d)){b=f.docnum;break}return b}
function set_killswitch_value(a,d,c){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var b=getcsinfo(a,d);return b?(b.killswitch=c,setcsinfo(a,d,b)):!1}function get_killswitch_value(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c=getcsinfo(a,d),b=0;c&&(b=parseInt(c.killswitch),isNaN(b)&&(b=0));return b}
function skip_CS_by_score(a,d){if(null===a||null===d)return!0;var c=getcsinfo(a,d);if(!c)return!0;L("skip? [tabid="+a+"][docnum="+d+"] score="+c.importance);return-25>c.importance}function get_top_url(a,d){var c="",b=getcsinfo_top(a,d);if(b&&b.parent_docnum==b.docnum)c=b.url;else for(var f in CS_table)if(CS_table.hasOwnProperty(f)&&(b=CS_table[f],b.tabid===a&&b.parent_docnum==b.docnum)){c=b.url;break}return c}
function get_top_docnum(a,d){var c=0;i;var b=getcsinfo_top(a,d);if(b&&b.parent_docnum==b.docnum)c=b.docnum;else for(var f in CS_table)if(CS_table.hasOwnProperty(f)&&(b=CS_table[f],b.tabid===a&&b.parent_docnum==b.docnum)){c=b.docnum;break}return c}
function update_cs_docflags(a,d){if(null===a||null===d||"undefined"==typeof a||"undefined"==typeof d)return null;"number"==typeof a&&(a=a.toString());var c=d.docnum;if(null===c||"undefined"==typeof c)return null;var b=d.docflags,f=!1,e=getcsinfo(a,c);e&&"object"==typeof b&&(e.flags=b,"undefined"!=typeof b.domain&&(e.domain=b.domain,delete e.flags.domain),"undefined"!=typeof b.origin&&(e.origin=b.origin,delete e.flags.origin),f=setcsinfo(a,c,e));return f}
function getcsinfo_top(a,d){for(var c=null,b=-1,f=getcsinfo(a,d),e=null,h=0;10>h&&f;h++){if((e=getcsinfo(a,f.parent_docnum))&&f.parent_docnum==e.docnum){b=e.docnum;break}if(null==f.parent_docnum)break;f=e}0<=b&&(e=getcsinfo(a,b));e&&!isEmptyObject(e)&&(c=e);return c}
function update_cs_lastfill_aid(a,d){var c=!0;if(null===a||"undefined"==typeof a||"undefined"==typeof d)return!1;"number"==typeof a&&(a=a.toString());var b=get_top_docnum(a),f=getcsinfo(a,b);f&&(f.lastfill_aid=d,c=setcsinfo(a,b,f));return c}
function rebuild_cs_table(a){function d(c){if(0!=c.url.indexOf("chrome:")&&0!=c.url.indexOf("safari:")){var b=gettabid(c),d;for(d in g_CS[b]){var e=d,h=gettaburl(c),g=c.status,j=!1;d&&g_CS_tops[b]==d&&(j=!0);a?(g=getcsinfo(b,e))?(h!=g.url&&console.log(sprintf("[%s][%s] url mismatch %s != %s",b,e,h,g.url)),j!=(g.parent_docnum==g.docnum)&&console.log(sprintf("[%s][%s] isTop mismatch %s != %s ",b,e,h,j,g.parent_docnum==g.docnum))):console.log(sprintf("[%s][%s] seems like this frame exists but no entry found in CS table for it",
b,e)):register_new_cs(b,e,h,j,g,0)}}}get_all_windows({},function(a){var b,f;for(b=0;b<a.length;b++)if(g_ischrome)chrome.tabs.query({windowId:a[b].id},function(a){if(a&&0<a.length)for(var b=0;b<a.length;b++)d(a[b])});else{var e=get_tabs(a[b]);if(e&&"undefined"!=typeof e.length)for(f=0;f<e.length;f++)d(e[f])}})};
