DialogInput=function(){var u=function(a){var b={},d;for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]instanceof k?u(a[d]):!0);return b},k=function(){};k.prototype.validate=function(){var a=!0,b;for(b in this)this.hasOwnProperty(b)&&(a=this[b].validate()&&a);return a};k.prototype.clear=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clear()};k.prototype.clearErrors=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clearErrors()};k.prototype.adjustView=function(){for(var a in this)if(this.hasOwnProperty(a)){var b=
this[a];"function"===typeof b.adjustView&&b.adjustView()}};k.prototype.getValue=function(a){var b={},d;for(d in this)this.hasOwnProperty(d)&&(b[d]=this[d].getValue(a));return b};k.prototype.setValue=function(a){for(var b in this)this.hasOwnProperty(b)&&this[b].setValue(void 0===a[b]?"":a[b])};var r=function(a){this.items={};this.groupName=a};r.prototype.getValue=function(){for(var a in this.items)if(this.items[a].prop("checked"))return a};r.prototype.setValue=function(a){if(a=this.items[a])a.prop("checked",
!0);else for(var b in this.items)this.items[b].prop("checked",!1)};r.prototype.addRadioInput=function(a){var b=a.attr("value");if(b){if(a.attr("name")!==this.groupName)throw"RadioGroup member must have the same name attribute as the other radio inputs in the group (based on dialogField)!";this.items[b]=a}else throw"RadioGroup member must have a value!";};var c=function(a,b){this.setElement(a);this._errors=[];this._errorElement=null;this.disabled=!1;this.dialog=b;this.radioGroup=null};c.prototype.getNativeElement=
function(){return this.getElement().get(0)};c.prototype.getElement=function(){return this.input};c.prototype.setElement=function(a){this.input=a instanceof $?a:$(a)};c.prototype.default=function(){this.setValue("")};c.prototype.clearErrors=function(){this._errors=[];LPTools.removeErrorElements(this._errorElement);this._errorElement=null};c.prototype.validate=function(){return!0};c.prototype.addError=function(a,b){this._errors.push(b);if(!this._errorElement){var d={collection:this.input,dialog:a,alignTop:"SELECT"===
this.input.prop("nodeName").toUpperCase()};"checkbox"===this.input.attr("type")&&(d.collection=d.collection.add(this.input.next()),d.static=!0);this._errorElement=LPTools.buildErrorElement(d)}LPTools.buildErrorMessage(this._errorElement,this._errors)};c.prototype.focus=function(){this.input.focus()};c.prototype.disable=function(){this.disabled||(this.disabled=!0,this.input.prop("disabled",!0))};c.prototype.enable=function(){this.disabled&&(this.disabled=!1,this.input.prop("disabled",!1))};c.prototype.clear=
function(){if(this.input){switch(this.input.attr("type")){case "checkbox":case "radio":this.setValue(!1);break;default:this.setValue("")}this.input.passwordShown&&this.input.hidePassword()}};c.prototype.getValue=function(){switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.getValue();case "checkbox":return this.input.prop("checked");default:return this.input.val()||""}};c.prototype.setValue=function(a){var b=this.getValue();switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.setValue(a);
case "checkbox":this.input.prop("checked",a);break;default:this.input.val(a)}b!==a&&this.fireOnChange()};c.prototype.addRadioInput=function(a,b){null===this.radioGroup&&(this.radioGroup=new r(a),this.radioGroup.addRadioInput(this.input));this.radioGroup.addRadioInput(b instanceof $?b:$(b))};c.prototype.fireOnChange=function(){if(this.onChangeCallback)this.onChangeCallback(this.getValue())};c.prototype.onChange=function(a){this.onChangeCallback=a;var b=this;b.getElement().bind("change",function(){b.fireOnChange()})};
c.prototype.adjustView=function(){};var q=function(a,b){c.apply(this,arguments)};q.prototype=Object.create(c.prototype);q.prototype.constructor=q;q.prototype.setOptions=function(a){this.input.empty();for(var b=0,d=a.length;b<d;++b){var c=a[b],f=c.value,e=c.label;"string"===typeof c&&(f=e=c);this.input.append(LPTools.createElement("option",{value:f},e))}};var f=function(a,b){c.call(this);this.field=a;this.label=void 0===b?a:b?Strings.translateString(b):null};f.prototype=Object.create(c.prototype);
f.prototype.constructor=f;f.prototype.build=function(){var a="settingLabel";this.isTopAlign()&&(a+=" topAlign");var b=LPTools.createElement("tr"),d=LPTools.createElement("td");this.label&&b.appendChild(LPTools.createElement("td",a,this.label));b.appendChild(d);d.appendChild(this.buildInput());return b};f.prototype.buildInput=function(){var a=this.buildInputElement();this.setElement(a);return a};f.prototype.isTopAlign=function(){return!1};var l=function(a,b,d){f.call(this,a,b);this.options=d;this.adjusted=
!1};l.prototype=Object.create(f.prototype);l.prototype.constructor=l;l.prototype.buildInputElement=function(){return LPTools.createElement("input",{"class":"dialogInput",type:"text"})};l.prototype.buildInput=function(){var a=f.prototype.buildInput.apply(this,arguments),b=LPTools.getOption(this.options,"inputButton",null);if(b){var d=LPTools.createElement("div","relative");d.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton",b);var c=LPTools.getOption(this.options,
"inputButtonHandler",null);if(c){var e=this;LPPlatform.addEventListener(e.inputButtonElement,"click",function(){c.apply(e)})}d.appendChild(this.inputButtonElement);return d}return a};l.prototype.adjustView=function(){if(!this.adjusted){var a=parseInt(this.input.css("padding-right"));this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth());this.adjusted=!0}};var n=function(a,b){f.call(this,a,b)};n.prototype=Object.create(f.prototype);n.prototype.constructor=n;n.prototype.buildInputElement=
function(){return LPTools.createElement("input",{"class":"dialogInput",type:"password"})};n.prototype.build=function(){var a=f.prototype.build.apply(this,arguments);this.input.LP_addPasswordEye({includeGenerateButton:!0});return a};var p=function(a,b){f.call(this,a,b)};p.prototype=Object.create(f.prototype);p.prototype.constructor=p;p.prototype.buildInputElement=function(){return LPTools.createElement("textarea","dialogInput")};p.prototype.isTopAlign=function(){return!0};for(var m="January February March April May June July August September October November December".split(" "),
j="01 02 03 04 05 06 07 08 09 10 11 12".split(" "),g=[],e=0,s=m.length;e<s;++e){var t=e+1;g.push((10>t?"0"+t:t)+" - "+Strings.translateString(m[e]))}for(var v=[],e=0,s=m.length;e<s;++e)v.push({value:m[e],label:g[e]});for(var w=[],e=0,m=m.length;e<m;++e)w.push({value:j[e],label:g[e]});var h=function(a,b){f.call(this,a,LPTools.getOption(b,"label",void 0));this.includeDay=LPTools.getOption(b,"includeDay",!0)};h.prototype=Object.create(f.prototype);h.prototype.constructor=h;h.prototype.buildInputElement=
function(){var a="";this.includeDay||(a="monthYearDate");var a=LPTools.createElement("div",a),b=LPTools.createElement("div","dateInputMonth");this.monthInput=LPTools.createSelectElement(this.getMonthOptions());this.dayInput=null;this.includeDay&&(this.dayInput=LPTools.createElement("input",{"class":"dialogInput dateInputDay",type:"text"}));this.yearInput=LPTools.createElement("input",{"class":"dialogInput dateInputYear",type:"text"});b.appendChild(this.monthInput);a.appendChild(b);null!==this.dayInput&&
a.appendChild(this.dayInput);a.appendChild(this.yearInput);return a};h.prototype.clear=function(){this.monthInput&&(this.monthInput.value="");this.dayInput&&(this.dayInput.value="");this.yearInput&&(this.yearInput.value="")};h.prototype.getValue=function(){return this.toString()};h.prototype.setValue=function(a){a=this.parse(a);var b="",c="",e="";a&&(b=a.shift(),2===a.length&&(c=a.shift()),e=a.shift());this.monthInput.value=b;this.includeDay&&(this.dayInput.value=c);this.yearInput.value=e};j=function(a,
b){h.call(this,a,b)};j.prototype=Object.create(h.prototype);j.prototype.constructor=j;j.prototype.toString=function(){var a=this.monthInput.value;this.dayInput&&(a+=","+this.dayInput.value);return a+=","+this.yearInput.value};j.prototype.parse=function(a){return a?a.split(","):null};j.prototype.getMonthOptions=function(){return v};g=function(a,b){h.call(this,a,b)};g.prototype=Object.create(h.prototype);g.prototype.constructor=g;g.prototype.toString=function(){var a=this.yearInput.value+"-"+this.monthInput.value;
this.includeDay&&(a+="-"+this.dayInput.value);if("-"===a||"--"===a)a="";return a};g.prototype.parse=function(a){return a?(a=a.split("-"),a.push(a.shift()),a):null};g.prototype.getMonthOptions=function(){return w};return{Input:c,TextInput:l,PasswordInput:n,TextArea:p,NumericDateInput:g,AlphaDateInput:j,NestedFields:k,NativeSelect:q,getProperties:u}}();
