EditableFieldsDialog=function(b,d){d=d||{};d.views=[{selector:".mainView"},{selector:".formFieldsView",title:Strings.translateString("Edit Form Fields"),dynamicHeight:!1}];DialogWithGroupInput.call(this,b,d);this.postSetupData=this.fieldsTable=this.addFieldsButton=this.fieldsElement=null;this.editFormFieldsButton=$(LPTools.buildItemButton(Constants.ACTION_EDIT));this.editFormFieldsButton.attr("title",Strings.translateString("Edit Form Fields"))};EditableFieldsDialog.prototype=Object.create(DialogWithGroupInput.prototype);
EditableFieldsDialog.prototype.constructor=EditableFieldsDialog;
(function(){var b=function(a,c){DialogInput.Input.call(this,void 0);this.fieldElements=[];this.container=a;this.parentDialog=c};b.prototype=Object.create(DialogInput.Input.prototype);b.prototype.constructor=b;b.prototype.clear=function(){LPTools.removeDOMChildren(this.container)};b.prototype.getValue=function(){for(var a=[],c=0,e=this.fieldElements.length;c<e;++c){var d=this.fieldElements[c];d.data.value=d.input.getValue();a.push($.extend({},d.data))}return a};b.prototype.setValue=function(a){LPTools.removeDOMChildren(this.container);
this.fieldElements=[];for(var c=0,e=a.length;c<e;++c)this.addField(a[c]);LPTools.addZebraStriping(this.container)};b.prototype.addField=function(a){if("hidden"!==a.type){var c=LPTools.createElement("tr","settingsRow");c.appendChild(LPTools.createElement("td","settingLabel",a.name));var e="Form Field "+a.name,b=null;switch(a.type){case "radio":case "select":case "select-one":b=LPTools.createElement("input",{"class":"dialogInput",type:"text","aria-label":e});break;case "checkbox":b=LPTools.buildCheckbox(void 0,
{checkboxAttributes:{"aria-label":e}});break;default:b=LPTools.createElement("input",{"class":"dialogInput",type:a.type,"aria-label":e})}e=$(b);e=e.is("input")?b:e.find("input").get(0);e=new DialogInput.Input(e);this.fieldElements.push({data:a,input:e});e.setValue(a.value);var g=LPTools.createElement("td","formFieldValue"),f=LPTools.createElement("div");g.appendChild(f);f.appendChild(b);c.appendChild(g);b=LPTools.createElement("div","rightItemButtons");g=LPTools.buildItemButton(Constants.ACTION_REMOVE);
$(g).bind("click",d(this.parentDialog,this.container,c,this.fieldElements,a));b.appendChild(g);f.appendChild(b);this.container.appendChild(c);"password"===a.type&&e.getElement().LP_addPasswordEye({checkPermissionHandler:this.parentDialog.checkViewPasswordHandler})}};var d=function(a,c,b,d,g){return function(){for(var f=null,h=0,j=d.length;h<j;++h)if(d[h].data===g){f=h;break}if(null!==f){var k=function(){c.removeChild(b);LPTools.addZebraStriping(c);d.splice(f,1)};a.vaultItem?LPRequest.makeUpdateRequest(LPProxy.deleteField,
{parameters:[a.vaultItem,a.vaultItem._data.fields[f]],requestSuccessOptions:{closeDialog:!1},success:function(){k();a.vaultItem.removeField(f);a.originalData=a.getData(!1)},confirm:{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete field %1?",g.name)}}):k()}}};b.prototype.clearErrors=function(){};EditableFieldsDialog.prototype.initialize=function(a){DialogWithGroupInput.prototype.initialize.apply(this,arguments);this.formFieldsView=a.find(".formFieldsView");
this.fieldsTable=a.find(".fieldsTable");this.fieldsElement=a.find(".fieldsElement");this.addFieldsButton=a.find(".addFormFieldButton");this.inputFields.fields=new b(this.fieldsElement.get(0),this);this.addFieldsButton.bind("click",function(a){return function(){dialogs.addFormField.open({sourceDialog:a})}}(this))};EditableFieldsDialog.prototype.getNextViewButton=function(){return this.editFormFieldsButton};EditableFieldsDialog.prototype.setNextView=function(a){DialogWithGroupInput.prototype.setNextView.apply(this,
arguments);0<a?this.editFormFieldsButton.hide():this.editFormFieldsButton.show()};EditableFieldsDialog.prototype.postSetup=function(){DialogWithGroupInput.prototype.postSetup.apply(this,arguments);this.postSetupData=this.getData()};EditableFieldsDialog.prototype.clearFields=function(){DialogWithGroupInput.prototype.clearFields.apply(this,arguments);this.postSetupData=null};EditableFieldsDialog.prototype.getData=function(){var a=DialogWithGroupInput.prototype.getData.apply(this,arguments),c=this.postSetupData;
if(c&&c.fields&&a.fields)for(var b=a.unencryptedUsername!==c.unencryptedUsername,d=a.password!==c.password,g=null,f=null,h=0;h<a.fields.length;++h){var j=a.fields[h],k=c.fields[h];if(k){var l=j.value!==k.value;c.unencryptedUsername&&c.unencryptedUsername===k.value?b?j.value=a.unencryptedUsername:l&&null===g?a.unencryptedUsername=g=j.value:null!==g&&(j.value=g):c.password&&c.password===k.value&&(d?j.value=a.password:l&&null===f?a.password=f=j.value:null!==f&&(j.value=f))}}return a};EditableFieldsDialog.prototype.setup=
function(a,c){c.vaultItem?this.addFieldsButton.LP_show():this.addFieldsButton.LP_hide();this.editFormFieldsButton.LP_hide();this.$element.removeClass("saveAll");this.fieldsTable.append(this.fieldsElement);this.formFieldsView.append(this.addFieldsButton);if(c.defaultData&&c.defaultData.save_all||c.vaultItem&&c.vaultItem._data.save_all){this.$element.addClass("saveAll");var b=a.find(".saveAllFields");b.append(this.fieldsElement);b.after(this.addFieldsButton)}else c.vaultItem&&this.editFormFieldsButton.LP_show();
DialogWithGroupInput.prototype.setup.apply(this,arguments)};EditableFieldsDialog.prototype.checkViewPassword=function(a){this.vaultItem?this.vaultItem.canViewPassword()?LPProxy.reprompt(function(c){return function(){a();bg.loglogin(c.vaultItem.getID())}}(this),{types:AccountBaseWithFields.prototype.REPROMPT_TYPE_VIEW_PW}):Topics.get(Topics.ERROR).publish(Strings.translateString("This is a shared site. You are not permitted to view the password.")):a()}})();
var AddFormFieldDialog=function(b){Dialog.call(this,b,{closeButtonEnabled:!0,nextButtonText:Strings.translateString("Add"),title:Strings.translateString("Add Form Field"),dynamicHeight:!0,overlayDialog:!0});this.fieldsInput=null};AddFormFieldDialog.prototype=Object.create(Dialog.prototype);AddFormFieldDialog.prototype.constructor=AddFormFieldDialog;
AddFormFieldDialog.prototype.initialize=function(b){Dialog.prototype.initialize.apply(this,arguments);var d=this;d.inputFields.type.onChange(function(){var a=!1;return function(c){var b="checkbox"===c;b!==a&&(c=document.getElementById("addFormFieldDialogValue"),LPTools.removeDOMChildren(c),(a=b)?(b=LPTools.buildCheckbox(),c.appendChild(b),d.inputFields.value.setElement($(b).find("input"))):(b=LPTools.createElement("input",{"class":"dialogInput",type:"text"}),c.appendChild(b),d.inputFields.value.setElement(b)))}}())};
AddFormFieldDialog.prototype.setup=function(b,d){d.sourceDialog&&d.sourceDialog.vaultItem&&d.sourceDialog.vaultItem._data.save_all?$("#addFormFieldDialogFormName").LP_show():$("#addFormFieldDialogFormName").LP_hide();Dialog.prototype.setup.apply(this,arguments)};
AddFormFieldDialog.prototype.validate=function(b){var d=Dialog.prototype.validate.apply(this,arguments);if(b.name)for(var a=this.data.sourceDialog.inputFields.fields.getValue(),c=0,e=a.length;c<e;++c)a[c].name===b.name&&(this.addError("name","A field with this name already exists."),d=!1);else this.addError("name","Field Name is required."),d=!1;b.type||(this.addError("type","Field Type is required."),d=!1);return d};
AddFormFieldDialog.prototype.handleSubmit=function(b){var d=this.data.sourceDialog,a=$.extend({},b);d.vaultItem.processEnteredFieldData(b);LPRequest.makeUpdateRequest(LPProxy.addField,{parameters:[d.vaultItem,b],success:function(){d.vaultItem.addField(b);d.inputFields.fields.addField(a);d.originalData=d.getData(!1)}})};
