var ExtensionLoginDialogSimple=function(f){ExtensionLoginDialog.call(this,f,{confirmOnClose:!0,responsive:!1})};ExtensionLoginDialogSimple.prototype=Object.create(ExtensionLoginDialog.prototype);ExtensionLoginDialogSimple.prototype.constructor=ExtensionLoginDialogSimple;
(function(){function f(b,c,a){return function(g,h){var d=!1;a&&(b.clearError(c),d=a.validate(g,function(a){b.addError(c,a)},h));return d}}var d;ExtensionLoginDialogSimple.prototype.initialize=function(b){ExtensionLoginDialog.prototype.initialize.apply(this,arguments);var c=new FieldValidator({summary:{id:"validatorSummaryEmail",parentEl:$("label[for='loginDialogEmail'].error-summary"),labelEl:$("label[for='loginDialogEmail'].label")},validators:[{id:"emailRequired",name:LPTools.createElement("p",
null,Strings.translateString("Email required")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Please enter your email.")),isValid:function(a){return""!==a.email}}]});this.inputFields.email.validate=f(this,"email",c);c=new FieldValidator({summary:{id:"validatorSummaryPassword",parentEl:$("label[for='loginDialogPassword'].error-summary"),labelEl:$("label[for='loginDialogPassword'].label")},validators:[{id:"passwordRequired",name:LPTools.createElement("p",null,Strings.translateString("Password required")),
errorMsg:LPTools.createElement("p",null,Strings.translateString("Please enter your password.")),isValid:function(a){return""!==a.password}}]});this.inputFields.password.validate=f(this,"password",c);this.inputFields.rememberPassword.getElement().bind("click",function(a){var b=!1,c=function(){b=!0;a.inputFields.rememberPassword.setValue(!0);d.hide()};return function(){var e=a.inputFields.rememberPassword.getValue();!b&&e?(d.show(),dialogs.confirmation.open({title:Strings.translateString("Are you sure?"),
text:Strings.translateString("Saving your Master Password on this device is like leaving the keys in the door to your Vault.")+"<br/><br/>"+Strings.translateString("You should make sure this device is in a secure location and unlikely to be lost or stolen before enabling this option."),handler:c,closeHandler:function(){d.hide()},onResize:a.data.onResize}),a.inputFields.rememberPassword.setValue(!1)):b=!1}}(this));var a=this;a.inputFields.email.getElement().change(function(){a.inputFields.password.validate({email:a.inputFields.email.getValue()})});
a.inputFields.password.onChange(function(b){b&&a.inputFields.password.validate({password:b})});$("#forgotPassword").off("click");$("#forgotPassword").bind("click",function(){LPPlatform.openURL(LPPlatform.getBaseURL()+"forgot.php");a.close(!0)});$("#newToLastPass").off("click");$("#newToLastPass").bind("click",function(){a.data.isPopup?LPPlatform.openTabDialog("createAccountSimple"):dialogs.createAccountSimple.open();a.close(!0)});b.find(".showKeyboard").off("click");b.find(".showKeyboard").bind("click",
function(){a.data.isPopup?(LPPlatform.openTabDialog("loginSimple",{virtualKeyboard:!0}),a.close(!0)):a.toggleKeyboard()});c={parentEl:$("body")};a.data.isPopup&&(c.shadeStyle="light");d=new BackgroundOverlay(c);a.data.isPopup||$("body").addClass("login-background")};ExtensionLoginDialogSimple.prototype.close=function(b){if(b)Dialog.prototype.close.apply(this,arguments);else{var c=this;LPTools.getOption(c.data,"showcloseconfirm",!0)?(d.show(),dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit? You cannot use LastPass without logging in to an account."),
closeHandler:function(){d.hide()},handler:function(){c.close(!0)}})):c.close(!0)}};var e=null;ExtensionLoginDialogSimple.prototype.handleSubmit=function(b){b.email=bg.fix_username(b.email);bg.Preferences.set({rememberemail:b.rememberEmail,rememberpassword:b.rememberPassword});b.disablePasswordManager&&bg.disablepasswordmanager(!0);bg.make_lp_key_hash_iterations(b.email,b.password,bg.get_key_iterations(b.email),function(a,c){return function(d,e){a.g_manual_login=!0;a.LP_do_login(b.email,b.password,
b.rememberEmail,b.rememberPassword,null,b.rememberShowVault,d,e);c.data.isPopup&&c.close(!0)}}(bg,this));if(!this.data.isPopup){d.show(!0);var c=this,a=this.title;null===e&&(e=setInterval(function(){"undefined"===typeof VaultState&&bg.pollBackground&&bg.pollBackground();bg.lploggedin?(clearInterval(e),e=null,c.title===a&&c.close(!0)):"error"===bg.g_notification_type&&(clearInterval(e),e=null,dialogs.alert.open({title:Strings.translateString("Login Error"),text:Strings.translateString(bg.g_notification_data.msg),
onResize:c.data.onResize,handler:function(){d.hide()}}))},1E3))}};ExtensionLoginDialogSimple.prototype.addError=function(b,c){var a=this.inputFields[b];a&&(a._errors.push(c),a.clearErrors=function(){this._errors=[];a._errorElement&&a._errorElement.remove();this._errorElement=null;a.input[0].className=a.input[0].className.replace(" errorInput","")},a.input[0].className.includes("errorInput")||(a.input[0].className+=" errorInput"))};ExtensionLoginDialogSimple.prototype.clearError=function(b){(b=this.inputFields[b])&&
b.clearErrors()};ExtensionLoginDialogSimple.prototype.validateField=function(b,c,a,d){var e=!1;c&&(this.clearError(a),e=c.validate(b,function(b){this.addError(a,b)},!0),d&&(!1===e?d.hide():d.show()));return e};ExtensionLoginDialogSimple.prototype.validate=function(b){var c=Dialog.prototype.validate.apply(this,arguments),c=this.inputFields.email.validate(b);return c&=this.inputFields.password.validate(b)}})();
