var ExtensionCreateAccount=function(g){Dialog.call(this,g,{views:[{selector:"#emailEntry",nextButtonText:Strings.translateString("Create Account")},{selector:"#mpEntry",nextButtonText:Strings.translateString("Unlock my Vault")}],dynamicHeight:!1,responsive:!1,additionalHeaderClasses:["icon"],nextButtonText:Strings.translateString("Create Account"),buttonAlign:this.CENTER_ALIGN,hideBackButton:!0,largeButtons:!0,buttonsInsideContent:!0,title:Strings.translateString("Create Account"),hideHeaderTitle:!0})};
ExtensionCreateAccount.prototype=Object.create(CreateAccountDialog.prototype);ExtensionCreateAccount.prototype.constructor=ExtensionCreateAccount;
(function(){function g(b,d){LPServer.textRequest({type:"GET",url:"create_account.php",CSRFToken:!1,data:{username:b,check:"avail",mistype:1},success:d,error:d})}function f(e,d){return function(c,a){var j=!1;d&&(b.clearError(e),j=d.validate(c,function(a){b.addError(e,a)},a));return j}}var b,h,k;ExtensionCreateAccount.prototype.initialize=function(e){CreateAccountDialog.prototype.initialize.apply(this,arguments);$(".meterContainer").remove();this.inputFields.password.getElement().LP_addPasswordMeter(this.inputFields.email.getElement(),
!0);b=this;var d=this,c=e.find(".buttonContent"),a=e.find(".buttons").detach();c.append(a);new FieldToolTip({parentEl:e});k=new EmailToolTip({toolTipEl:e.find("#mpCurrentEmail"),parentEl:$("body"),emailField:b.inputFields.email,backActionFn:function(){b.showPreviousView()}});e.find("#signInBtn").bind("click",function(){event.preventDefault();$("[for^=createAccountEmail")[0].style.display="none";dialogs.loginSimple.open({isPopup:!1});d.close(!0)});c=LPTools.createElement("a",{"class":"pull-right",
href:"https://lastpass.com/forgot.php",target:"_blank"},Strings.translateString("Recovery Help"));a=LPTools.createElement("p",null,Strings.translateString("Email address already in use "));a.appendChild(c);c=new FieldValidator({summary:{id:"validatorSummaryEmail",parentEl:$("label[for='createAccountEmail'].error-summary")},validators:[{id:"404",errorMsg:LPTools.createElement("p",null,Strings.translateString("You have made too many attempts.")+"<br>"+Strings.translateString("Please wait 5 minutes then try again.")),
isValid:function(a){return!(a.response.status&&404===a.response.status)}},{id:"emailUsed",errorMsg:a,isValid:function(a){return"no"!==a.response}},{id:"emailInvalid",errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure to use a real email address")),isValid:function(a){return"ok"===a.response&&0!==a.response.indexOf("mistype:")&&"emailinvalid"!==a.response}}]});b.inputFields.email.validate=f("email",c);c=new FieldValidator({summary:{id:"validatorSummaryTermsAndConditions",parentEl:$("label[for='termsAndConditions'].error-summary")},
validators:[{id:"termsNotChecked",errorMsg:LPTools.createElement("p",null,Strings.translateString("Please agree to the Terms and Conditions")),isValid:function(a){return!0===a.termsAndConditions}}]});b.inputFields.termsAndConditions.validate=f("termsAndConditions",c);b.inputFields.email.onChange(function(a){a&&g(a,function(a){b.inputFields.email.validate({response:a})})});b.inputFields.password.onChange(function(a){a&&b.inputFields.password.validate({password:b.inputFields.password.getValue(),email:b.inputFields.email.getValue()})});
b.inputFields.password.getElement().keyup(function(){b.inputFields.password.validate({password:b.inputFields.password.getValue(),email:b.inputFields.email.getValue()},!0)});b.inputFields.reconfirm.onChange(function(a){a&&b.inputFields.reconfirm.validate({reconfirm:b.inputFields.reconfirm.getValue(),password:b.inputFields.password.getValue()})});b.inputFields.reminder.onChange(function(a){a&&b.inputFields.reminder.validate({reminder:b.inputFields.reminder.getValue(),password:b.inputFields.password.getValue()})});
h=new BackgroundOverlay({parentEl:$("body")});d.data.isPopup||$("body").addClass("login-background")};ExtensionCreateAccount.prototype.setNextView=function(b){Dialog.prototype.setNextView.apply(this,arguments);k.toggle(0<b)};ExtensionCreateAccount.prototype.close=function(b){if(b)Dialog.prototype.close.apply(this,arguments);else{var d=this;LPTools.getOption(d.data,"showcloseconfirm",!0)?(h.show(),dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit?  You cannot use LastPass without creating an account."),
closeHandler:function(){h.hide()},handler:function(){d.close(!0)}})):d.close(!0)}};ExtensionCreateAccount.prototype.clearError=function(b){(b=this.inputFields[b])&&b.clearErrors()};ExtensionCreateAccount.prototype.addError=function(b,d){var c=this.inputFields[b];c&&(c._errors.push(d),c.clearErrors=function(){this._errors=[];c._errorElement&&c._errorElement.remove();this._errorElement=null})};ExtensionCreateAccount.prototype.validate=function(e,d){if(0===this.currentViewIndex)g(e.email,function(a){(a=
b.inputFields.email.validate({response:a}))&&(a&=b.inputFields.termsAndConditions.validate(e));d&&d(a)});else if(this.currentViewIndex===this.views.length-1){var c=b.inputFields.password.validate(e),c=c&b.inputFields.reconfirm.validate(e),c=c&b.inputFields.reminder.validate(e);d&&d(c)}};ExtensionCreateAccount.prototype.submit=function(){try{var e=this.getData();this.validate(e,function(c){c&&(b.getNextViewButton()===b.nextButton&&b.views&&b.currentViewIndex<b.views.length-1?(c=new FieldValidator({summary:{id:"validatorSummaryPassword",
parentEl:$("label[for='createAccountDialogPassword'].error-summary"),labelEl:$("label[for='createAccountDialogPassword'].label"),errorMsg:LPTools.createElement("p",null,Strings.translateString("Sorry, your password is invalid"))},listParentEl:$("#mpValidators"),validators:[{id:"passwordLength",name:LPTools.createElement("p",null,Strings.translateString("At least 8 characters long")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Master Password must be at least 8 characters")),isValid:function(a){return!0===
(a.password&&8<=a.password.length)}},{id:"passwordSameAsEmail",name:LPTools.createElement("p",null,Strings.translateString("Not your email")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Master Password shouldn't contain your email")),isValid:function(a){return!0===(a.password&&a.email&&-1===a.password.toLowerCase().indexOf(a.email.toLowerCase())&&-1===a.email.toLowerCase().indexOf(a.password.toLowerCase()))}},{id:"easyPassword",name:LPTools.createElement("p",null,Strings.translateString("Not easily guessable")),
errorMsg:LPTools.createElement("p",null,Strings.translateString("That's in the top 100 most-used passwords")),isValid:function(a){return!0===(a.password&&!a.password.match(/^password\d{0,3}$/i)&&!a.password.match(/^lastpass\d{0,3}$/i)&&!a.password.match(/^.{0,7}$/)&&"12345678"!==a.password&&"123456789"!==a.password&&"1234567890"!==a.password&&"lastpass.com"!==a.password&&"qwertyuiop"!==a.password&&"abcd1234"!==a.password)}}]}),b.inputFields.password.validate=f("password",c),$("#twinsies").hide(),
c=new FieldValidator({summary:{id:"validatorSummaryReconfirm",parentEl:$("label[for='createAccountDialogConfirmPassword'].error-summary"),labelEl:$("label[for='createAccountDialogConfirmPassword'].label, #twinsies")},validators:[{id:"reconfirmSameAsPassword",name:LPTools.createElement("p",null,Strings.translateString("Reconfirm same as password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure this matches your Master Password")),isValid:function(a){return!0===(a.reconfirm&&
a.password===a.reconfirm)}}]}),b.inputFields.reconfirm.validate=f("reconfirm",c),c=new FieldValidator({summary:{id:"validatorSummaryReminder",parentEl:$("label[for='createAccountReminder'].error-summary"),labelEl:$("label[for='createAccountReminder'].label")},validators:[{id:"reminderNotPassword",name:LPTools.createElement("p",null,Strings.translateString("Reminder doesn't contain password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Reminder shouldn't contain your Master Password")),
isValid:function(a){return!(a.password&&-1!==a.reminder.toLowerCase().indexOf(a.password.toLowerCase()))}}]}),b.inputFields.reminder.validate=f("reminder",c),b.setNextView(b.currentViewIndex+1)):b.handleSubmit(e,this.data))})}catch(d){LPPlatform.logException(d)}};ExtensionCreateAccount.prototype.showInProcessOverlay=function(){h.show(!0)}})();
