function LPNG_humanize_fill(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=101;if(function(a,c){a||(a=LP_derive_doc());if(!a||!c)return!0;var b=c.field;if(!b)return!0;var g=c.type,k=c.value,l=c.allowforce,m=c.reqinfo,h=c.realurl,j=gettldcached(get_doc_location_href(a));if(skip_filling_field(b,j)||!c.is_launch&&should_ignore_autocompleteoff_bypref(a,b)||b.form&&!lpCheckWarnInsecure(b.form,b.form.ownerDocument,!1,l))return!0;b=LP_iscrossdomainok(a,j,b,g,k,m,h);return"calldelayed"==b?(console_warn("you lose"),
!0):!b?!0:!chkoriginok(a,h)?!0:!1}(c,b))return!1;"undefined"!=typeof b.beforeJS&&b.beforeJS&&LPNG_javascript_beforefield(c,b);"number"==typeof b.quant&&50<b.quant&&(a=b.quant);"undefined"==typeof b.send_keyevents&&(b.send_keyevents=!0);setTimeout(function(){LPNG_moveto_field(c,b);setTimeout(function(){LPNG_setval(c,b);setTimeout(function(){LPNG_moveout_field(c,b);"undefined"!=typeof b.afterJS&&b.afterJS&&LPNG_javascript_afterfield(c,b)},a)},a)},a);return!0}
function LPNG_moveto_field(c,b){c||(c=LP_derive_doc());if(!c||!b||!b.field)return!1;var a=b.field,d={},e=LP_getAbsolutePos(c,a);if(!e)return!1;d.target=a;d.posx=e.left;d.posy=e.top;LPNG_mouse_moveto(c,d);d.bubble=!1;LP_fireEvent(a,"mouseenter","MouseEvent",d);d.bubble=!0;LP_fireEvent(a,"mouseenter","MouseEvent",d);LPNG_do_focus(c,d);if(lp_in_array(a.type,["select","select-one"])){var e=a.selectedIndex,f=a.options;f.length>=e&&((e=f[e])&&e.value===b.value?pass:LP_humanizeClick(c,a,d))}else lp_in_array(a.type,
["radio","checkbox"])||LP_humanizeClick(c,a,d)}function LPNG_javascript_beforefield(c,b){c||(c=LP_derive_doc());return!c||!b||!b.beforeJS?!1:!0}
function LPNG_setval(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=b.field,d=b.type,e=b.checked,f=b.sharedsite,g=b.keyevents;if(!a||!d)return!1;(d=c)||(d=LP_derive_doc());!d||!b?d=!0:(d=b.field,d=LP_fieldIsDisabled(d)||LP_fieldIsReadOnly(d)?!0:!1);if(d)return!1;d=!1;switch(b.type){case "tel":case "number":case "url":case "text":a.value!=b.value&&("function"==typeof sendkey&&g&&(sendKey(KeyEvent.DOM_VK_SHIFT,a),sendKey(KeyEvent.DOM_VK_SPACE,a),sendKey(KeyEvent.DOM_VK_BACKSPACE,a)),a.value=b.value,
d=!0);lphighlightField(a);LP_getform_for_input(c,a);break;case "password":a.value!=b.value&&(a.value=b.value,d=!0);lphighlightField(a);LP_getform_for_input(c,a);if(f&&("undefined"==typeof g_isie||!g_isie))lpsharedpasswordfills[lpsharedpasswordfills.length]=a;break;case "checkbox":if(a.checked&&!e||!a.checked&&e){e={};e.target=a;if(f=LP_getAbsolutePos(c,a))e.posx=f.left,e.posy=f.top;LP_humanizeClick(c,a,e);d=!0}break;case "radio":if(a.checked&&!e||!a.checked&&e){e={};e.target=a;if(f=LP_getAbsolutePos(c,
a))e.posx=f.left,e.posy=f.top;LP_humanizeClick(c,a,e);d=!0}break;case "select":case "select-one":if(a.value!=b.value){if(g=a.options)for(d=0;d<g.length;d++)if(g[d].value===b.value){e={};e.target=g[d];if(f=LP_getAbsolutePos(c,g[d]))e.posx=f.left,e.posy=f.top;LP_humanizeClick(c,g[d],e);break}d=!0;a.value=b.value}break;case "textarea":a.value!=b.value&&(a.value=b.value,d=!0);lphighlightField(a);LP_getform_for_input(c,a);break;default:console_warn("unsupported type "+b.type)}d&&LPNG_do_input(c,b);return!0}
function LPNG_do_input(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=b.field,d=LP_getAbsolutePos(c,a);d&&LP_fireEvent(a,"input","Event",{evt_class:"Event",posx:d.posx,posy:d.posy});return!0}
function LPNG_moveout_field(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=b.field;if(!a)return!1;var d={},e=LP_getAbsolutePos(c,a);if(!e)return!1;d.target=a;d.posx=e.left;d.posy=e.top;LPNG_mouse_moveto(c,d);LPNG_do_unfocus(c,d);d.target=null;d.posx=e.left+2;d.posy=e.top+2;LPNG_mouse_moveto(c,d);d.bubble=!1;LP_fireEvent(a,"mouseleave","MouseEvent",d);d.bubble=!0;LP_fireEvent(a,"mouseout","MouseEvent",d)}
function LPNG_javascript_afterfield(c,b){c||(c=LP_derive_doc());return!c||!b||!b.afterJS?!1:!0}function LPNG_customjs(){}function LPNG_mouse_moveto(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=b.target;a||(a=c.documentElement);LP_fireEvent(a,"mousemove","MouseEvent",{evt_class:"MouseEvent",posx:b.posx,posy:b.posy});return!0}
function LPNG_do_focus(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=b.target;a||(a=c.documentElement);try{var d={evt_class:g_isie?"FocusEvent":"UIEvent",posx:b.posx,posy:b.posy};LP_fireEvent(a,"focus",g_isie?"FocusEvent":"UIEvent",d);d.bubble=!1;LP_fireEvent(a,"focusin",g_isie?"FocusEvent":"UIEvent",d)}catch(e){a.focus()}return!0}
function LPNG_do_unfocus(c,b){c||(c=LP_derive_doc());if(!c||!b)return!1;var a=b.target;a||(a=c.documentElement);try{var d={evt_class:g_isie?"FocusEvent":"UIEvent",posx:b.posx,posy:b.posy};LP_fireEvent(a,"blur",g_isie?"FocusEvent":"UIEvent",d);d.bubble=!1;LP_fireEvent(a,"focusout",g_isie?"FocusEvent":"UIEvent",d)}catch(e){a.blur()}return!0}function fillfield_handler(){}
function LPNG_pick_field(c,b){c||(c=LP_derive_doc());if(!c||!b)return null;var a=null,d=b.name,e=b.type,f=b.formname,g=b.otherfield;f&&(a="INPUT",e&&("select-one"==e.toLowerCase()?a="SELECT":"textarea"==e.toLowerCase()&&(a="TEXTAREA")),a=LP_getElementByIdOrName(c,d,a,f));if(a||(a=LP_getElementByIdOrName(c,d)))return a;if(g&&(e=c.getElementsByTagName("select-one"==e?"select":"textarea"==e?"textarea":"input"),d=d.match(/^(input|select|textarea)(\d+)$/)))a=parseInt(d[2]),a>e.length&&(a=e.length-1),a=
e[a];return a};
