function LP_floating_icon_exists(a,b){return!a&&(a=LP_derive_doc(),!a)?!1:null!=LP_getElementByIdOrName(a,LP_compute_floating_iconcontainer_id(a,b))}
function do_icon_mouseover(a,b,c){if(null==a||null==b||!c)return!1;c=LP_pickFieldName(a,c);var d=LP_compute_floating_icon_id(a,c),d=a.getElementById(d);if(is_your_popup_showing(a))return null!=d&&(d.style.opacity="1",d.style.filter="alpha(opacity=100)"),!1;if(null!=d){var e=!0;if(null!=a.getElementById(b)){b=!1;var h=getIconState(a,c);h&&(b=h.fillhint);"formfills"==b?(LP_has_highdef_display(f)?LP_set_image_src(d,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(d,g_40_icons.FormFill_dark),e=!1):"offersave"==
b?e=!1:"generate"==b&&(LP_has_highdef_display(f)?LP_set_image_src(d,g_40_icons["Generate_dark@2x"]):LP_set_image_src(d,g_40_icons.Generate_dark),e=!1)}if(e){var f=a.defaultView;f||(f=window);LP_has_highdef_display(f)?LP_set_image_src(d,g_40_icons["16x16_dark@2x"]):LP_set_image_src(d,g_40_icons["16x16"])}d.style.opacity="1";d.style.filter="alpha(opacity=100)"}g_do_icon_number_hint&&(f=LP_compute_floating_number_id(a,c),a=a.getElementById(f),null!=a&&g_icon_shading&&(a.style.backgroundColor="#CCFF99"))}
function do_icon_mouseout(a,b,c){if(null==a||null==b||!c)return!1;c=LP_pickFieldName(a,c);var d=LP_compute_floating_icon_id(a,c),d=a.getElementById(d);if(is_your_popup_showing(a))return null!=d&&(d.style.opacity="0.6"),!1;if(null!=d){if(null==a.getElementById(b))return!1;(b=a.defaultView)||(b=window);var e=!1,h=getIconState(a,c);h&&(e=h.fillhint);if(!e||"sites"!==e&&"formfills"!==e&&"generate"!==e&&"offersave"!==e)e="default";"default"==e||"sites"==e?(LP_has_highdef_display(b)?LP_set_image_src(d,
g_40_icons["16x16_dark@2x"]):LP_set_image_src(d,g_40_icons["16x16"]),d.style.opacity="0.6",d.style.filter="alpha(opacity=60)"):"formfills"==e?(LP_has_highdef_display(b)?LP_set_image_src(d,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(d,g_40_icons.FormFill_dark),d.style.opacity="0.6",d.style.filter="alpha(opacity=60)"):"generate"==e&&(LP_has_highdef_display(b)?LP_set_image_src(d,g_40_icons["Generate_dark@2x"]):LP_set_image_src(d,g_40_icons.Generate_dark),d.style.opacity="0.6",d.style.filter="alpha(opacity=60)")}g_do_icon_number_hint&&
(c=LP_compute_floating_number_id(a,c),a=a.getElementById(c),null!=a&&(g_icon_shading?a.style.backgroundColor="#FFFFFF":a.style.display=e&&g_icon_numbers&&1<g_icon_numbers[e]?"block":"none"))}
function change_clickable_icon_to_cancel(a,b,c){if(!a&&(a=LP_derive_doc(),!a))return!1;var d=a.defaultView;d||(d=window);c=LP_compute_floating_icon_id(a,c);c=a.getElementById(c);if(null!=c){if(null==a.getElementById(b))return!1;LP_has_highdef_display(d)?LP_set_image_src(c,g_40_icons["IF_Close@2x"]):LP_set_image_src(c,g_40_icons.IF_Close);c.style.opacity="0.6";c.style.filter="alpha(opacity=60)"}return!0}
function shouldCreateFloatingIcon(a,b,c){if(!a&&(a=LP_derive_doc(),!a)||!a||!b)return!1;if("stripe.com"==c)return!0;if("dominos.com"==c)return!1;if("metlife.com"==c&&-1!=a.location.href.indexOf("mybenefits.metlife.com"))return!0;if((a=LP_get_live_style(b))&&a.backgroundImage&&"none"!=a.backgroundImage&&!inputHasLPBackground(b))b=0<=a.backgroundImage.indexOf("blank")?!1:!0;else{if(a=g_trial_bg_expt)b?(b.style.backgroundImage="url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=)",
a=LP_get_live_style(b),b=!a||("none"==a.backgroundImage||!a.backgroundImage)||g_stylesheet_grubbing&&LP_input_has_bg_style_override(b.ownerDocument)?!1:!0):b=!1,a=!b;b=a?!0:!1}return b}
function LP_create_floating_icon(a,b,c,d){if(!a&&(a=LP_derive_doc(),!a)||!b)return!1;var e=a.defaultView;e||(e=window);var h=a.getElementsByTagName("body")[0],f,j;f=LP_pickFieldName(a,b);getIconState(a,f);var l=LP_compute_floating_iconcontainer_id(a,f);if(LP_floating_icon_exists(a,f))return!1;j=a.createElement("div");j.id=l;"undefined"!=typeof g_isfirefox&&g_isfirefox?(null==a.g_popup_divs&&(a.g_popup_divs={}),a.g_popup_divs[j.id]=j.id):g_popup_divs[j.id]=j.id;f=a.createElement("img");b.offsetHeight<
LPICON_WIDTH&&(f.height=b.offsetHeight,f.width=f.height);f.id=j.id+"_icon";l=!0;null!=c&&("formfills"==c?(LP_has_highdef_display(e)?LP_set_image_src(f,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(f,g_40_icons.FormFill_dark),f.style.opacity="0.6",f.style.filter="alpha(opacity=60)",l=!1):"generate"==c&&(LP_has_highdef_display(e)?LP_set_image_src(f,g_40_icons["Generate_dark@2x"]):LP_set_image_src(f,g_40_icons.Generate_dark),f.style.opacity="0.6",f.style.filter="alpha(opacity=60)",l=!1));l&&(LP_has_highdef_display(e)?
LP_set_image_src(f,g_40_icons["16x16_dark@2x"]):LP_set_image_src(f,g_40_icons["16x16"]),f.style.opacity="0.6",f.style.filter="alpha(opacity=60)");j.appendChild(f);"sites"==c&&LP_getloggedin()&&(!g_isfirefox&&!g_isie)&&b.setAttribute("autocomplete","off");g_do_icon_number_hint&&LP_create_floating_icon_hint(a,j.id,c,d)&&LP_set_floating_icon_hint(a,j.id,c,d);h.appendChild(j);j.style.maxHeight=LPICON_WIDTH+"px";j.style.verticalAlign="top";f.style.verticalAlign="top";"undefined"!=typeof g_docnum&&verbose_log("["+
g_docnum+"] setting up click listener on icon for "+LP_pickFieldName(a,b));g_icon_hover&&(LP_addEventHandler(j,"mouseover",function(c){do_icon_mouseover(a,j.id,b);LP_stopEventPropagation(c);return!1}),LP_addEventHandler(j,"mouseout",function(c){do_icon_mouseout(a,j.id,b);LP_stopEventPropagation(c);return!1}));g_icon_parent_hover&&(LP_addEventHandler(b,"mouseover",function(c){do_icon_mouseover(a,j.id,b);LP_stopEventPropagation(c);return!1}),LP_addEventHandler(b,"mouseout",function(c){do_icon_mouseout(a,
j.id,b);LP_stopEventPropagation(c);return!1}));LP_addEventHandler(h,"DOMsubtreemodified",function(){popupfill_resize(a);return!1},!1);LP_addEventHandler(h,"resize",function(){popupfill_resize(a);return!1},!1);h.onresize=onresize_handler;setprops_floating_icon(a,b,j,c,d);return!0}
function move_floating_icon(a,b,c,d){a||(a=LP_derive_doc());if(!a||!b)return!1;a.getElementsByTagName("body");var e;e=LP_pickFieldName(a,b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(!c){var h=getIconState(a,e);h&&(c=h.fillhint)}if(e=LP_getElementByIdOrName(a,LP_compute_floating_iconcontainer_id(a,e)))g_do_icon_number_hint&&(LP_getloggedin()?LP_set_floating_icon_hint(a,e.id,c,d):LP_delete_floating_icon_hint(a,e.id)),setprops_floating_icon(a,b,e,c,d);return!0}
function setprops_floating_icon(a,b,c,d,e){function h(a,b){if(!a||!b)return!1;var c=!1,d=a.getElementsByTagName("body")[0],e=b.parentNode;e&&(e!=d&&d)&&(e.removeChild(b),d.appendChild(b),c=!0);return c}if(a&&b&&c){var f=LP_pickFieldName(a,b);if(f=getIconState(a,f)){h(a,c);"absolute"!=c.style.position&&(c.style.position="absolute");var j=LP_getAbsolutePos(a,b);if(null!=j){if(b.offsetHeight>LPICON_WIDTH){var l=j.top+(b.offsetHeight-LPICON_WIDTH)/2+"px";c.style.top!=l&&(c.style.top=l)}else c.style.top!=
j.top+"px"&&(c.style.top=j.top+"px");f=!1==f.text_direction?j.left+2+"px":j.left+b.offsetWidth-LPICON_WIDTH-2+"px";c.style.left!=f&&(c.style.left=f);if(g_do_icon_number_hint){var g;null==g&&(g=a.getElementById(c.id+"_icon"));var f=parseInt(c.style.left),j=parseInt(c.style.top),m=a.getElementById(c.id+"_numspan");if(null!=m)if(h(a,m),null!=d&&null!=e&&null!=e[d]&&1<e[d]){var k=e[d];0<e[d]&&9>e[d]&&(k=" "+e[d]);k=LP_measureText(a,k,null,"font-size: 9px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;line-height:11px;");
if(null!=k){var n=j+("undefined"==typeof g.height||0==g.height?LPICON_HEIGHT:g.height)-k.height+6+"px",p=f+("undefined"==typeof g.width||0==g.width?LPICON_WIDTH:g.width)-k.width+2+"px",k="position:absolute !important; visibility:visible !important; border:0px !important; font-size:9px !important; font-family: Helvetica Neue,Helvetica,Arial,sans-serif; top:"+n+" !important; left:"+p+" !important; background-color: #808080; padding: 1px 2px !important; font-weight: bold !important; color:#ffffff !important; cursor: default; line-height:11px !important; max-width: 10px !important; ";
g="undefined"!=typeof window&&window?window:a.defaultView;g=LP_getComputedStyle(g,m);d=g.zIndex;""!==d&&"auto"!=d&&(k=k+"z-index:"+d+" !important;");if("absolute"!=g.position||"visible"!=g.visibility||"9px"!=g.fontSize||"1px 2px"!=g.padding||"11px"!=g.lineHeight||g.top!=n||g.left!=p)m.style.cssText=k}else k="display:none;",m.style.cssText=k}else k="display:none;",m.style.cssText=k}}else verbose_log("ERROR: unable to relocate clickable icon");d=getZIndex(a,b,0,0);null!=d?d++:d=CLICKABLE_ICON_ZINDEX;
c.style.zIndex!=d&&(c.style.zIndex=d);if(g_do_icon_number_hint&&null!=m&&(k=k+"z-index:"+(d+1)+" !important;",g="undefined"!=typeof window&&window?window:a.defaultView,g=LP_getComputedStyle(g,m),!g||"absolute"!=g.position||"visible"!=g.visibility||"9px"!=g.fontSize||"1px 2px"!=g.padding||"11px"!=g.lineHeight||g.top!=n||g.left!=p||g.zIndex!=d+1))m.style.cssText=k;c.style.display=checkIsDisplayed(a,b,0)?"":"none";g=c.childNodes[0];parseInt(b.offsetHeight)<LPICON_WIDTH?(b.offsetHeight!=g.height&&(g.height=
parseInt(b.offsetHeight)),b.offsetHeight!=g.height&&(g.width=g.height)):(g.height!=LPICON_WIDTH&&(g.height=LPICON_WIDTH),g.width!=LPICON_WIDTH&&(g.width=LPICON_WIDTH))}}}function refresh_floating_icon_number_hints(a){null==a&&(a=document);if(null!=a)if(LP_get_icon_divs(a),LP_getloggedin())for(i in iconidhash);else for(i in iconidhash){var b=a.getElementById(iconidhash[i]+"_numspan");b&&(b.parentNode.removeChild(b),verbose_log("deleting icon number for "+iconidhash[i]))}}
function LP_reset_icon_divs(a){if(!a&&(a=LP_derive_doc(),!a))return!1;"undefined"!=typeof g_isfirefox&&g_isfirefox?a.g_popup_divs={}:g_popup_divs={};return!0}function LP_store_icon_div(a,b){if(!a&&(a=LP_derive_doc(),!a))return!1;"undefined"!=typeof g_isfirefox&&g_isfirefox?(null==a.g_popup_divs&&(a.g_popup_divs={}),a.g_popup_divs[b]=b):g_popup_divs[b]=b;return!0}
function LP_delete_icon_div(a,b){"undefined"!=typeof g_isfirefox&&g_isfirefox?a&&delete a.g_popup_divs[b]:delete g_popup_divs[b];return!0}function LP_get_icon_divs(a){return!a&&(a=LP_derive_doc(),!a)?{}:"undefined"!=typeof g_isfirefox&&g_isfirefox?null==a.g_popup_divs?{}:a.g_popup_divs:null==g_popup_divs?{}:g_popup_divs}
function LP_set_floating_icon_hint(a,b,c,d){if(!a&&(a=LP_derive_doc(),!a))return!1;if(LP_getloggedin()){var e=a.getElementById(b+"_numspan");null!=e?(a="",b=LP_elt_get_text(e),null!=c&&null!=d&&null!=d[c]&&0<d[c]?("formfills"==c||"generate"==c)&&!1===g_show_icon_number_for_formfills?""!=b&&LP_elt_set_text(e,""):(a=9>d[c]?" "+d[c]:9<d[c]?"9+":" "+d[c],b!=a&&LP_elt_set_text(e,a)):LP_elt_set_text(e,"")):LP_create_floating_icon_hint(a,b,c,d);return!0}}
function LP_create_floating_icon_hint(a,b,c){if(!a&&(a=LP_derive_doc(),!a)||!b)return!1;var d=a.getElementsByTagName("body")[0];if(a.getElementById(b+"_numspan")||("formfills"==c||"generate"==c)&&!1===g_show_icon_number_for_formfills)return!1;a=a.createElement("div");a.id=b+"_numspan";a.style.position="absolute";a.style.top="-1000px";a.style.left="-1000px";d.appendChild(a);g_defensive&&LP_addEventHandler(a,"mousedown",function(a){LP_stopEventPropagation(a);return!1});return!0}
function LP_delete_floating_icon_hint(a,b){if(!a&&(a=LP_derive_doc(),!a))return!1;var c=a.getElementById(b+"_numspan");return null!=c?(c.parentNode.removeChild(c),!0):!1}function LP_delete_floating_icon(a,b){if(!a&&(a=LP_derive_doc(),!a))return!1;var c=a.getElementById(b);return null!=c?(c.parentNode.removeChild(c),!0):!1}
function relocate_popupfill_clickables(a){if(!a&&(a=LP_derive_doc(),!a))return null;if("function"==typeof a.getElementsByName){g_isfirefox&&verbose_log("relocate_popupfill_clickables doc is "+get_doc_location_href(a));var b=LP_get_icon_divs(a);if(isEmptyObject(b))return null;try{var c,d=0;for(c in b)if(b.hasOwnProperty(c)){var e=b[c].substr(LPMAGIC.length);if(null!=e&&0<e.length){var h=e,f=LP_getElementByIdOrName(a,h);if(null==f&&!g_double_password_hack&&!g_double_secret_password_hack)LP_delete_floating_icon(a,
b[c])&&(verbose_log("relocate: deleting orphaned icon container for "+e),d++),g_do_icon_number_hint&&LP_delete_floating_icon_hint(a,b[c])&&(verbose_log("relocate: deleting orphaned icon number for "+e),d++),delete b[c];else if(g_do_icon_number_hint){if(null!=a.getElementById(b[c])){var j="",l=getIconState(a,h);l&&(j=l.fillhint);null!=j&&"sites"!=j&&(j=null);h={};g_isfirefox?h[j]=l.fillhintnumber:(h.sites=0<g_icon_number_overrides.sites?g_icon_number_overrides.sites:g_icon_numbers.sites,h.formfills=
0<g_icon_number_overrides.formfills?g_icon_number_overrides.formfills:g_icon_numbers.formfills);move_floating_icon(a,f,j,h)}}else move_floating_icon(a,f)}}}catch(g){verbose_log("relocate_popupfill_clickables caught error:"+g.message),g_isfirefox&&end_weasel(a)}if(0<d)if(g_isfirefox){var m=lpGetBrowserForDocument(a);setTimeout(function(){LP.checkShouldRecheck(m)},500)}else setTimeout(function(){if(g_pending_recheck)verbose_log("skipped 1 recheck, 1 is already queued up, #7");else{var b=LP_get_last_url_history(a);
checkShouldRecheck({href:b.href,href_hash:b.href_hash})}},500)}}
function reset_floating_icon(a,b,c){if(!a&&(a=LP_derive_doc(),!a))return!1;var d=a.defaultView;d||(d=window);b=LP_pickFieldName(a,b);var e=getIconState(a,b);!c&&e&&(c=e.fillhint);e=LP_getElementByIdOrName(a,LP_compute_floating_iconcontainer_id(a,b));a=LP_getElementByIdOrName(a,LPMAGIC+b+"_icon");return e&&a?("formfills"==c?LP_has_highdef_display(d)?LP_set_image_src(a,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(a,g_40_icons.FormFill_dark):"generate"==c?LP_has_highdef_display(d)?LP_set_image_src(a,
g_40_icons["Generate_dark@2x"]):LP_set_image_src(a,g_40_icons.Generate_dark):LP_has_highdef_display(d)?LP_set_image_src(a,g_40_icons["16x16_dark@2x"]):LP_set_image_src(a,g_40_icons["16x16"]),a.style.opacity="0.6",a.style.filter="alpha(opacity=60)",!0):!1}
function getZIndex(a,b,c,d){LPCTR("getzindex");if(null==a||b==a.body||null==b||50<c)return null;var e=0,h=LP_getComputedStyle("undefined"!=typeof window&&window?window:a.defaultView,b);if(null==h)return null;if("absolute"==h.position||"relative"==h.position||"fixed"==h.position){if("auto"==h.zIndex||""===h.zIndex)return e=getZIndex(a,b.parentNode,c+1,d+1),null==e?0:parse_zindex(e);e=getZIndex(a,b.parentNode,c+1,parse_zindex(h.zIndex));return null==e?parse_zindex(h.zIndex)+1:parse_zindex(e)+1}if("auto"==
h.zIndex||""==h.zIndex)return e=getZIndex(a,b.parentNode,c+1,d+1),null==e?d+1:parse_zindex(e)+1;e=getZIndex(a,b.parentNode,c+1,parse_zindex(h.zIndex));return null==e?parse_zindex(h.zIndex):parse_zindex(e)+1}function end_weasel(a){if(do_experimental_popupfill&&(a||(a=document?document:LP.getBrowser().contentDocument),a)){var b;b=a&&null!=a.g_weasel_id?a.g_weasel_id:g_weasel_id;null!=b&&clearTimeout(b);g_isfirefox?a&&(a.g_weasel_id=null,a.g_weaseled=!1):(g_weasel_id=null,g_weaseled=!1)}}
function LP_compute_floating_iconcontainer_id(a,b){a||(a=LP_derive_doc());return!a||!b?"":LPMAGIC+b}function LP_compute_floating_icon_id(a,b){a||(a=LP_derive_doc());return!a||!b?"":LP_compute_floating_iconcontainer_id(a,b)+"_icon"}function LP_compute_floating_number_id(a,b){a||(a=LP_derive_doc());return!a||!b?"":LP_compute_floating_iconcontainer_id(a,b)+"_numspan"};
