var FolderDialog=function(a){DialogWithGroupInput.call(this,a,{additionalHeaderClasses:["icon"],dynamicHeight:!0})};FolderDialog.prototype=Object.create(DialogWithGroupInput.prototype);FolderDialog.prototype.constructor=FolderDialog;FolderDialog.prototype.open=function(a){a=a||{};a.title="Add Folder";a.vaultItem&&(a.title="Rename Folder");DialogWithGroupInput.prototype.open.call(this,a)};
FolderDialog.prototype.initialize=function(){DialogWithGroupInput.prototype.initialize.apply(this,arguments);this.inputFields.groupParent.onChange(function(a){document.getElementById("folderDialogCreateSubFolder").checked=""!==a});var a=this;LPPlatform.addEventListener(document.getElementById("folderDialogCreateSubFolder"),"change",function(b){b.target.checked||a.inputFields.groupParent.clear()})};
FolderDialog.prototype.setup=function(a,b){var c=document.getElementById("folderDialogCreateSubFolder");c.checked=!1;b.vaultItem instanceof SharedGroup?(c.setAttributeNode(document.createAttribute("disabled")),this.inputFields.groupParent.disable()):(c.removeAttribute("disabled"),this.inputFields.groupParent.enable());DialogWithGroupInput.prototype.setup.apply(this,arguments)};
FolderDialog.prototype.setGroupDropdownValues=function(a){a.unshift("");LPTools.setSelectOptions(this.inputFields.groupParent.getNativeElement(),a)};
FolderDialog.prototype.validate=function(a){var b=DialogWithGroupInput.prototype.validate.apply(this,arguments),c=a.groupName;a.groupParent&&(c=a.groupParent+"\\"+c);if(""===a.groupName)this.addError("groupName","Folder Name is required."),b=!1;else if(-1<a.groupName.indexOf(SharedGroup.prototype.SHARED_FOLDER_NAME_PREFIX))this.addError("groupName",Strings.translateString("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name.")),b=
!1;else{for(var e=LPProxy.getGroups(),d=0,f=e.length;d<f;++d)if(e[d].getName()===c){this.addError("groupName",Strings.translateString("That folder already exists."));b=!1;break}-1<a.groupName.indexOf("\\")&&(this.addError("groupName",Strings.translateString("Folder name cannot contain backslashes.")),b=!1)}return b};FolderDialog.prototype.allowNoneGroup=function(){return!1};FolderDialog.prototype.getGroupField=function(){return"groupParent"};
FolderDialog.prototype.add=function(a){(new Group).addFromDialog(a,a.groupParent?this.getGroup(a,!1):null)};var CreateSharedFolderDialog=function(a){Dialog.call(this,a,{additionalHeaderClasses:["icon"],dynamicHeight:!0,nextButtonText:"Create"})};CreateSharedFolderDialog.prototype=Object.create(Dialog.prototype);CreateSharedFolderDialog.prototype.constructor=CreateSharedFolderDialog;
(function(){CreateSharedFolderDialog.prototype.open=function(a){a=a||{};a.title=a.group?"Convert to Shared Folder":"Create New Shared Folder";a.group&&(a.defaultData={groupName:a.group.getName().replace("\\","-")});Dialog.prototype.open.call(this,a)};CreateSharedFolderDialog.prototype.validate=function(a){var b=Dialog.prototype.validate.apply(this,arguments);if(""===a.groupName)this.addError("groupName","Folder Name is required."),b=!1;else{for(var c=SharedGroup.prototype.SHARED_FOLDER_NAME_PREFIX+
a.groupName,e=LPProxy.getGroups(),d=0,f=e.length;d<f;++d)if(e[d].getName()===c){this.addError("groupName",Strings.translateString("That folder already exists."));b=!1;break}-1<a.groupName.indexOf("\\")&&(this.addError("groupName",Strings.translateString("Folder name cannot contain backslashes.")),b=!1)}return b};CreateSharedFolderDialog.prototype.getItemButtonActions=function(){return null};CreateSharedFolderDialog.prototype.setup=function(a,b){b.group?($("#createSharedFolderConvert").show(),$("#createSharedFolderNew").hide()):
($("#createSharedFolderConvert").hide(),$("#createSharedFolderNew").show());Dialog.prototype.setup.apply(this,arguments)};CreateSharedFolderDialog.prototype.handleSubmit=function(a){(new SharedGroup({group:a.groupName})).add(this.data.group,this.data.children)}})();
