var FormFillDialog=function(e){VaultItemDialog.call(this,e,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN})};FormFillDialog.prototype=Object.create(VaultItemDialog.prototype);FormFillDialog.prototype.constructor=FormFillDialog;
(function(){var e=function(a){DialogInput.Input.call(this,void 0);this.customFieldElements=[];this.container=a};e.prototype=Object.create(DialogInput.Input.prototype);e.prototype.constructor=e;e.prototype.clear=function(){for(var a=0,b=this.customFieldElements.length;a<b;++a){var c=this.customFieldElements[a];c.text.value="";c.value.value=""}};e.prototype.getValue=function(){for(var a=[],b=0,c=this.customFieldElements.length;b<c;++b){var d=this.customFieldElements[b],d={cfid:void 0===d.cfid?"0":d.cfid,
text:d.text.value,value:d.value.value};("0"!==d.cfid||d.text||d.value)&&a.push(d)}return a};e.prototype.setValue=function(a){LPTools.removeDOMChildren(this.container);this.customFieldElements=[];for(var b=0,c=a.length;b<c||3>b;++b){var d=this.addElement();if(b<c){var e=a[b];d.text.value=e.text;d.value.value=e.value;d.cfid=e.cfid}}};e.prototype.addElement=function(){var a=LPTools.createElement("tr","settingsRow"),b=LPTools.createElement("textarea","dialogInput"),c=LPTools.createElement("td");c.appendChild(b);
a.appendChild(c);var c=LPTools.createElement("textarea","dialogInput"),d=LPTools.createElement("td");d.appendChild(c);a.appendChild(d);this.container.appendChild(a);a={text:b,value:c};this.customFieldElements.push(a);return a};e.prototype.clearErrors=function(){};e.prototype.validate=function(){return!0};var f=function(a,b){this.container=a;this.countryCodeDropdown=b;this.countryCode=this.countryCodeDropdown.getValue();this.value=null;this.initialized=!1;this._errors=[];var c=this;c.countryCodeDropdown.onChange(function(a){c.initialized||
c.buildInput();c.setCountryCode(a)})};f.prototype.getElement=function(){return this.container};f.prototype.clearErrors=function(){this._errors=[];LPTools.removeErrorElements(this._errorElement);this._errorElement=null};f.prototype.validate=function(a,b,c){return c&&""===this.countryCodeDropdown.getValue()?(a.addError(b,Strings.translateString("Country must be entered for this phone number.")),!1):!0};f.prototype.addError=function(a,b){this._errors.push(b);this._errorElement||(this._errorElement=LPTools.buildErrorElement({collection:$(this.container),
dialog:a}));LPTools.buildErrorMessage(this._errorElement,this._errors)};f.prototype.buildInput=function(){LPTools.removeDOMChildren(this.container);this.isDomestic()?(this.container.appendChild(document.createTextNode("(")),this.areaCodeInput=LPTools.createElement("input",{"class":"dialogInput areaCode",type:"text",size:3,maxlength:3}),this.container.appendChild(this.areaCodeInput),this.container.appendChild(document.createTextNode(")")),this.phoneInput1=LPTools.createElement("input",{"class":"dialogInput phonePartOne",
type:"text",size:3,maxlength:3}),this.container.appendChild(this.phoneInput1),this.phoneInput2=LPTools.createElement("input",{"class":"dialogInput phonePartTwo",type:"text",size:4,maxlength:4}),this.container.appendChild(this.phoneInput2)):(this.ccInput=LPTools.createElement("input",{type:"text","class":"dialogInput countryCode",size:3,maxlength:3,disabled:!0}),this.container.appendChild(this.ccInput),this.phoneInput=LPTools.createElement("input",{"class":"dialogInput phone",type:"text"}),this.container.appendChild(this.phoneInput));
this.initialized=!0};f.prototype.isDomestic=function(){return"1"===PhoneFormatDropdown.prototype.COUNTRY_CODE_MAP[this.countryCode]};f.prototype.getNumericCountryCode=function(){return PhoneFormatDropdown.prototype.COUNTRY_CODE_MAP[this.countryCode]};f.prototype.setCountryCode=function(a){var b=this.isDomestic(),c=this.getValue(),d=this.getNumericCountryCode(),c=d?c.substring(d.length):c;this.countryCode=a;b!==this.isDomestic()&&this.buildInput();d=this.getNumericCountryCode();this.setValue(d?d+c:
"")};f.prototype.clear=function(){this.areaCodeInput&&(this.areaCodeInput.value="");this.phoneInput1&&(this.phoneInput1.value="");this.phoneInput2&&(this.phoneInput2.value="");this.ccInput&&(this.ccInput.value="");this.phoneInput&&(this.phoneInput.value="")};f.prototype.getValue=function(){this.initialized&&(this.value=this.isDomestic()?"1"+this.areaCodeInput.value+this.phoneInput1.value+this.phoneInput2.value:this.ccInput.value+this.phoneInput.value);return this.value};f.prototype.setValue=function(a){this.value=
a;if(this.initialized)if(this.isDomestic())this.areaCodeInput.value=a.substring(1,4),this.phoneInput1.value=a.substring(4,7),this.phoneInput2.value=a.substring(7);else{var b=this.getNumericCountryCode();b?(this.ccInput.value=b,this.phoneInput.value=a.substring(b.length)):(this.ccInput.value="",this.phoneInput.value="")}};FormFillDialog.prototype.validate=function(a){var b=VaultItemDialog.prototype.validate.apply(this,arguments);""===a.decprofilename&&(this.addError("decprofilename","Name is required."),
b=!1);a.creditmon&&(""===a.firstname&&(this.addError("firstname","First Name is required when Enable Free Credit Monitoring is checked."),b=!1),""===a.lastname&&(this.addError("lastname","Last Name is required when Enable Free Credit Monitoring is checked."),b=!1),""===a.birthday&&(this.addError("birthday","Birthday is required when Enable Free Credit Monitoring is checked."),b=!1),""===a.ssn&&(this.addError("ssn","Social Security Number is required when Enable Free Credit Monitoring is checked."),
b=!1),""===a.city&&(this.addError("city","City / Town is required when Enable Free Credit Monitoring is checked."),b=!1),""===a.state&&(this.addError("state","State is required when Enable Free Credit Monitoring is checked."),b=!1),""===a.zip&&(this.addError("zip","ZIP / Postal Code is required when Enable Free Credit Monitoring is checked."),b=!1),4>a.phone.length&&(this.addError("phone","Phone Number is required when Enable Free Credit Monitoring is checked."),b=!1),"US"!==a.country&&(this.addError("country",
"Credit monitoring is only available for addresses in the United States."),b=!1));return b};FormFillDialog.prototype.open=function(a){a=a||{};a.title=a.title||(void 0===a.vaultItem?"Add Form Fill":"Edit Form Fill");a.sourceFunction=LPProxy.getFormFillModel;VaultItemDialog.prototype.open.call(this,a)};FormFillDialog.prototype.buildPhoneInput=function(a,b,c,d){var e=LPTools.createElement("div"),g=new PhoneFormatDropdown;this.inputFields[b]=g;e.appendChild(g.select);a.appendChild(e);var e=LPTools.createElement("table",
"phoneNumber"),h=LPTools.createElement("tbody");b=LPTools.createElement("tr");a.appendChild(e);e.appendChild(h);h.appendChild(b);a=LPTools.createElement("td","phoneNumberCell");b.appendChild(a);this.inputFields[c]=new f(a,g);b.appendChild(LPTools.createElement("td","extensionLabel","ext."));c=LPTools.createElement("td","extensionCell");b.appendChild(c);g=LPTools.createElement("input",{"class":"dialogInput",type:"text"});c.appendChild(g);this.inputFields[d]=new DialogInput.Input(g)};FormFillDialog.prototype.getData=
function(a){var b=VaultItemDialog.prototype.getData.apply(this,arguments);b.state_name=void 0!==this.inputFields.state.options[b.state]?this.inputFields.state.options[b.state].label:b.state;for(var c=this.inputFields.country.getElement().prop("options"),d=0;d<c.length;d++)if(c[d].value===b.country){b.country_name=c[d].text;b.country_cc3l=c[d].getAttribute("data-cc3l");break}return b};FormFillDialog.prototype.defaultFields=function(a){a.defaultData=$.extend({profilelanguage:"en-US",profiletype:FormFill.prototype.FORM_FILL_TYPE_GENERIC},
a.defaultData);VaultItemDialog.prototype.defaultFields.call(this,a)};FormFillDialog.prototype.initialize=function(a){VaultItemDialog.prototype.initialize.apply(this,arguments);var b=this;b.inputFields.profiletype.onChange(function(a){a===FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD?b.$element.addClass("creditCard"):b.$element.removeClass("creditCard");b.selectFirstLeftMenuItem()});this.inputFields.custom_fields=new e(document.getElementById("custom_fields"));var c=this;$("#addCustomFieldButton").bind("click",
function(){c.inputFields.custom_fields.addElement().text.focus()});this.buildPhoneInput(document.getElementById("formFillDialogPhoneInput"),"phone3lcc","phone","phoneext");this.buildPhoneInput(document.getElementById("formFillDialogMobilePhoneInput"),"mobilephone3lcc","mobilephone","mobileext");this.buildPhoneInput(document.getElementById("formFillDialogEveningPhoneInput"),"evephone3lcc","evephone","eveext");this.buildPhoneInput(document.getElementById("formFillDialogFaxInput"),"fax3lcc","fax","faxext")};
FormFillDialog.prototype.setup=function(a,b){b.vaultItem?this.inputFields.profiletype.disable():this.inputFields.profiletype.enable();VaultItemDialog.prototype.setup.apply(this,arguments)};FormFillDialog.prototype.add=function(a){(new FormFill).addFromDialog(a)}})(document);
