var g_creditmonurl=null;function gt(a){a=a.replace(/<br\/>/g,"\n");a=gs(a,getlocale());return a=a.replace(/\n/,"<br/>")}function getlocale(){return document.getElementById("ff_language")?document.getElementById("ff_language").value:"en-US"}var prevlocale="";
function retranslate(){var a=getlocale();"es-ES"==prevlocale||"es-MX"==prevlocale||"ca-ES"==prevlocale?$("#last2").hide():"ja-JP"==prevlocale&&($("#first").show(),$("#middle").show(),$("#last").show(),$("#mobileemail").hide(),$("#nameja1").hide(),$("#nameja2").hide(),$("#nameja3").hide());"es-ES"==a||"es-MX"==a||"ca-ES"==a?$("#last2").show():"ja-JP"==a&&($("#first").hide(),$("#middle").hide(),$("#last").hide(),$("#mobileemail").show(),$("#nameja1").show(),$("#nameja2").show(),$("#nameja3").show());
prevlocale=a;0!=g_ff_type||"en-US"!=a?$("#creditmon").css("visibility","hidden"):"en-US"==a&&$("#creditmon").css("visibility","visible");bg=getBG();bg.g_showcredmon||$("#creditmon").css("visibility","hidden");$("#pff_cancel").val(gs("Cancel",getlocale()));$("#ff_addcustomfield").val(gs("Add another custom field",getlocale()));var b=[{"":gs("Please select",getlocale())},{mr:gs("Mr",getlocale())},{mrs:gs("Mrs",getlocale())},{ms:gs("Ms",getlocale())},{dr:gs("Dr",getlocale())}];populateselectex("ff_title",
b,"");b=[{"":gs("Please select",getlocale())},{m:gs("Male",getlocale())},{f:gs("Female",getlocale())}];populateselectex("ff_gender",b,"");b=[{"":gs("Please select",getlocale())},{"01":gs("January",getlocale())},{"02":gs("February",getlocale())},{"03":gs("March",getlocale())},{"04":gs("April",getlocale())},{"05":gs("May",getlocale())},{"06":gs("June",getlocale())},{"07":gs("July",getlocale())},{"08":gs("August",getlocale())},{"09":gs("September",getlocale())},{10:gs("October",getlocale())},{11:gs("November",
getlocale())},{12:gs("December",getlocale())}];populateselectex("ff_birthday_month",b,"");populateselectex("ff_ccstart_month",b,"");populateselectex("ff_ccexp_month",b,"");b=[{"":""}];for(a=1;31>=a;++a){var c={};c[10>a?"0"+a:""+a]=a;b.push(c)}populateselectex("ff_birthday_day",b,"");a=document.getElementById("ff_state").value;"CUSTOM"==a&&(a=document.getElementById("ff_statecustom").value);b=[{"":gs("Please select",getlocale())},{dummy3:g_DUMMYSTATE},{CUSTOM:gs("Custom Value",getlocale())},{dummy3:g_DUMMYSTATE},
{AL:"Alabama"},{AK:"Alaska"},{AZ:"Arizona"},{AR:"Arkansas"},{CA:"California"},{CO:"Colorado"},{CT:"Connecticut"},{DE:"Delaware"},{DC:"District of Columbia"},{FL:"Florida"},{GA:"Georgia"},{HI:"Hawaii"},{ID:"Idaho"},{IL:"Illinois"},{IN:"Indiana"},{IA:"Iowa"},{KS:"Kansas"},{KY:"Kentucky"},{LA:"Louisiana"},{ME:"Maine"},{MD:"Maryland"},{MA:"Massachusetts"},{MI:"Michigan"},{MN:"Minnesota"},{MS:"Mississippi"},{MO:"Missouri"},{MT:"Montana"},{NE:"Nebraska"},{NV:"Nevada"},{NH:"New Hampshire"},{NJ:"New Jersey"},
{NM:"New Mexico"},{NY:"New York"},{NC:"North Carolina"},{ND:"North Dakota"},{OH:"Ohio"},{OK:"Oklahoma"},{OR:"Oregon"},{PA:"Pennsylvania"},{RI:"Rhode Island"},{SC:"South Carolina"},{SD:"South Dakota"},{TN:"Tennessee"},{TX:"Texas"},{UT:"Utah"},{VT:"Vermont"},{VA:"Virginia"},{WA:"Washington"},{WV:"West Virginia"},{WI:"Wisconsin"},{WY:"Wyoming"},{dummy1:g_DUMMYSTATE},{AA:"Armed Forces Americas"},{AE:"Armed Forces EMEAC"},{AP:"Armed Forces Pacific"},{dummy2:g_DUMMYSTATE},{AS:"American Samoa"},{FM:"Federated States of Micronesia"},
{GU:"Guam"},{MH:"Marshall Islands"},{MP:"Northern Mariana Islands"},{PW:"Palau"},{PR:"Puerto Rico"},{VI:"Virgin Islands"},{dummy3:g_DUMMYSTATE},{AB:"Alberta"},{BC:"British Columbia"},{MB:"Manitoba"},{NB:"New Brunswick"},{NL:"Newfoundland and Labrador"},{NT:"Northwest Territories"},{NS:"Nova Scotia"},{NU:"Nunavut"},{ON:"Ontario"},{PE:"Prince Edward Island"},{QC:"Quebec"},{SK:"Saskatchewan"},{YT:"Yukon"}];populateselectex("ff_state",b,"");document.getElementById("ff_state").selectedIndex=2;document.getElementById("ff_statecustom").value=
a;b=[{"":gs("Please select",getlocale())},{AF:gs("Afghanistan",getlocale())},{AX:gs("Aland Islands",getlocale())},{AL:gs("Albania",getlocale())},{DZ:gs("Algeria",getlocale())},{AS:gs("American Samoa",getlocale())},{AD:gs("Andorra",getlocale())},{AO:gs("Angola",getlocale())},{AI:gs("Anguilla",getlocale())},{AQ:gs("Antarctica",getlocale())},{AG:gs("Antigua and Barbuda",getlocale())},{AR:gs("Argentina",getlocale())},{AM:gs("Armenia",getlocale())},{AW:gs("Aruba",getlocale())},{AU:gs("Australia",getlocale())},
{AT:gs("Austria",getlocale())},{AZ:gs("Azerbaijan",getlocale())},{BS:gs("Bahamas",getlocale())},{BH:gs("Bahrain",getlocale())},{BD:gs("Bangladesh",getlocale())},{BB:gs("Barbados",getlocale())},{BY:gs("Belarus",getlocale())},{BE:gs("Belgium",getlocale())},{BZ:gs("Belize",getlocale())},{BJ:gs("Benin",getlocale())},{BM:gs("Bermuda",getlocale())},{BT:gs("Bhutan",getlocale())},{BO:gs("Bolivia",getlocale())},{BA:gs("Bosnia and Herzegovina",getlocale())},{BW:gs("Botswana",getlocale())},{BV:gs("Bouvet Island",
getlocale())},{BR:gs("Brazil",getlocale())},{IO:gs("British Indian Ocean Territory",getlocale())},{BN:gs("Brunei Darussalam",getlocale())},{BG:gs("Bulgaria",getlocale())},{BF:gs("Burkina Faso",getlocale())},{BI:gs("Burundi",getlocale())},{KH:gs("Cambodia",getlocale())},{CM:gs("Cameroon",getlocale())},{CA:gs("Canada",getlocale())},{IC:gs("Canary Islands",getlocale())},{CV:gs("Cape Verde",getlocale())},{KY:gs("Cayman Islands",getlocale())},{CF:gs("Central African Republic",getlocale())},{TD:gs("Chad",
getlocale())},{CL:gs("Chile",getlocale())},{CN:gs("China",getlocale())},{CX:gs("Christmas Island",getlocale())},{CC:gs("Cocos (Keeling) Islands",getlocale())},{CO:gs("Colombia",getlocale())},{KM:gs("Comoros",getlocale())},{CG:gs("Congo",getlocale())},{CD:gs("Congo, the Democratic Republic of The",getlocale())},{CK:gs("Cook Islands",getlocale())},{CR:gs("Costa Rica",getlocale())},{CI:gs("Cote D'ivoire",getlocale())},{HR:gs("Croatia",getlocale())},{CU:gs("Cuba",getlocale())},{CY:gs("Cyprus",getlocale())},
{CZ:gs("Czech Republic",getlocale())},{DK:gs("Denmark",getlocale())},{DJ:gs("Djibouti",getlocale())},{DM:gs("Dominica",getlocale())},{DO:gs("Dominican Republic",getlocale())},{EC:gs("Ecuador",getlocale())},{EG:gs("Egypt",getlocale())},{SV:gs("El Salvador",getlocale())},{GQ:gs("Equatorial Guinea",getlocale())},{ER:gs("Eritrea",getlocale())},{EE:gs("Estonia",getlocale())},{ET:gs("Ethiopia",getlocale())},{FK:gs("Falkland Islands (Malvinas)",getlocale())},{FO:gs("Faroe Islands",getlocale())},{FJ:gs("Fiji",
getlocale())},{FI:gs("Finland",getlocale())},{FR:gs("France",getlocale())},{GF:gs("French Guiana",getlocale())},{PF:gs("French Polynesia",getlocale())},{TF:gs("French Southern Territories",getlocale())},{GA:gs("Gabon",getlocale())},{GM:gs("Gambia",getlocale())},{GE:gs("Georgia",getlocale())},{DE:gs("Germany",getlocale())},{GH:gs("Ghana",getlocale())},{GI:gs("Gibraltar",getlocale())},{GR:gs("Greece",getlocale())},{GL:gs("Greenland",getlocale())},{GD:gs("Grenada",getlocale())},{GP:gs("Guadeloupe",getlocale())},
{GU:gs("Guam",getlocale())},{GT:gs("Guatemala",getlocale())},{GG:gs("Guernsey",getlocale())},{GN:gs("Guinea",getlocale())},{GW:gs("Guinea-Bissau",getlocale())},{GY:gs("Guyana",getlocale())},{HT:gs("Haiti",getlocale())},{HM:gs("Heard Island and Mcdonald Islands",getlocale())},{VA:gs("Holy See (Vatican City State)",getlocale())},{HN:gs("Honduras",getlocale())},{HK:gs("Hong Kong",getlocale())},{HU:gs("Hungary",getlocale())},{IS:gs("Iceland",getlocale())},{IN:gs("India",getlocale())},{ID:gs("Indonesia",
getlocale())},{IR:gs("Iran (Islamic Republic Of)",getlocale())},{IQ:gs("Iraq",getlocale())},{IE:gs("Ireland",getlocale())},{IM:gs("Isle of Man",getlocale())},{IL:gs("Israel",getlocale())},{IT:gs("Italy",getlocale())},{JM:gs("Jamaica",getlocale())},{JP:gs("Japan",getlocale())},{JE:gs("Jersey",getlocale())},{JO:gs("Jordan",getlocale())},{KZ:gs("Kazakhstan",getlocale())},{KE:gs("Kenya",getlocale())},{KI:gs("Kiribati",getlocale())},{KP:gs("Korea, Democratic People's Republic Of",getlocale())},{KR:gs("Korea, Republic Of",
getlocale())},{KW:gs("Kuwait",getlocale())},{KG:gs("Kyrgyzstan",getlocale())},{LA:gs("Lao People's Democratic Republic",getlocale())},{LV:gs("Latvia",getlocale())},{LB:gs("Lebanon",getlocale())},{LS:gs("Lesotho",getlocale())},{LR:gs("Liberia",getlocale())},{LY:gs("Libyan Arab Jamahiriya",getlocale())},{LI:gs("Liechtenstein",getlocale())},{LT:gs("Lithuania",getlocale())},{LU:gs("Luxembourg",getlocale())},{MO:gs("Macao",getlocale())},{MK:gs("Macedonia, the Former Yugoslav Republic Of",getlocale())},
{MG:gs("Madagascar",getlocale())},{MW:gs("Malawi",getlocale())},{MY:gs("Malaysia",getlocale())},{MV:gs("Maldives",getlocale())},{ML:gs("Mali",getlocale())},{MT:gs("Malta",getlocale())},{MH:gs("Marshall Islands",getlocale())},{MQ:gs("Martinique",getlocale())},{MR:gs("Mauritania",getlocale())},{MU:gs("Mauritius",getlocale())},{YT:gs("Mayotte",getlocale())},{MX:gs("Mexico",getlocale())},{FM:gs("Micronesia, Federated States Of",getlocale())},{MD:gs("Moldova, Republic Of",getlocale())},{MC:gs("Monaco",
getlocale())},{MN:gs("Mongolia",getlocale())},{ME:gs("Montenegro",getlocale())},{MS:gs("Montserrat",getlocale())},{MA:gs("Morocco",getlocale())},{MZ:gs("Mozambique",getlocale())},{MM:gs("Myanmar",getlocale())},{NA:gs("Namibia",getlocale())},{NR:gs("Nauru",getlocale())},{NP:gs("Nepal",getlocale())},{NL:gs("Netherlands",getlocale())},{AN:gs("Netherlands Antilles",getlocale())},{NC:gs("New Caledonia",getlocale())},{NZ:gs("New Zealand",getlocale())},{NI:gs("Nicaragua",getlocale())},{NE:gs("Niger",getlocale())},
{NG:gs("Nigeria",getlocale())},{NU:gs("Niue",getlocale())},{NF:gs("Norfolk Island",getlocale())},{MP:gs("Northern Mariana Islands",getlocale())},{NO:gs("Norway",getlocale())},{OM:gs("Oman",getlocale())},{PK:gs("Pakistan",getlocale())},{PW:gs("Palau",getlocale())},{PS:gs("Palestinian Territories",getlocale())},{PA:gs("Panama",getlocale())},{PG:gs("Papua New Guinea",getlocale())},{PY:gs("Paraguay",getlocale())},{PE:gs("Peru",getlocale())},{PH:gs("Philippines",getlocale())},{PN:gs("Pitcairn",getlocale())},
{PL:gs("Poland",getlocale())},{PT:gs("Portugal",getlocale())},{PR:gs("Puerto Rico",getlocale())},{QA:gs("Qatar",getlocale())},{RE:gs("Reunion",getlocale())},{RO:gs("Romania",getlocale())},{RU:gs("Russian Federation",getlocale())},{RW:gs("Rwanda",getlocale())},{BL:gs("Saint Barthelemy",getlocale())},{SH:gs("Saint Helena",getlocale())},{KN:gs("Saint Kitts and Nevis",getlocale())},{LC:gs("Saint Lucia",getlocale())},{MF:gs("Saint Martin (French Part)",getlocale())},{PM:gs("Saint Pierre and Miquelon",
getlocale())},{VC:gs("Saint Vincent and the Grenadines",getlocale())},{WS:gs("Samoa",getlocale())},{SM:gs("San Marino",getlocale())},{ST:gs("Sao Tome and Principe",getlocale())},{SA:gs("Saudi Arabia",getlocale())},{SN:gs("Senegal",getlocale())},{RS:gs("Serbia",getlocale())},{SC:gs("Seychelles",getlocale())},{SL:gs("Sierra Leone",getlocale())},{SG:gs("Singapore",getlocale())},{SK:gs("Slovakia",getlocale())},{SI:gs("Slovenia",getlocale())},{SB:gs("Solomon Islands",getlocale())},{SO:gs("Somalia",getlocale())},
{ZA:gs("South Africa",getlocale())},{GS:gs("South Georgia and the South Sandwich Islands",getlocale())},{ES:gs("Spain",getlocale())},{LK:gs("Sri Lanka",getlocale())},{SD:gs("Sudan",getlocale())},{SR:gs("Suriname",getlocale())},{SJ:gs("Svalbard and Jan Mayen",getlocale())},{SZ:gs("Swaziland",getlocale())},{SE:gs("Sweden",getlocale())},{CH:gs("Switzerland",getlocale())},{SY:gs("Syrian Arab Republic",getlocale())},{TW:gs("Taiwan",getlocale())},{TJ:gs("Tajikistan",getlocale())},{TZ:gs("Tanzania, United Republic Of",
getlocale())},{TH:gs("Thailand",getlocale())},{TL:gs("Timor-Leste",getlocale())},{TG:gs("Togo",getlocale())},{TK:gs("Tokelau",getlocale())},{TO:gs("Tonga",getlocale())},{TT:gs("Trinidad and Tobago",getlocale())},{TN:gs("Tunisia",getlocale())},{TR:gs("Turkey",getlocale())},{TM:gs("Turkmenistan",getlocale())},{TC:gs("Turks and Caicos Islands",getlocale())},{TV:gs("Tuvalu",getlocale())},{UG:gs("Uganda",getlocale())},{UA:gs("Ukraine",getlocale())},{AE:gs("United Arab Emirates",getlocale())},{GB:gs("United Kingdom",
getlocale())},{US:gs("United States",getlocale())},{UM:gs("United States Minor Outlying Islands",getlocale())},{UY:gs("Uruguay",getlocale())},{UZ:gs("Uzbekistan",getlocale())},{VU:gs("Vanuatu",getlocale())},{VE:gs("Venezuela",getlocale())},{VN:gs("Viet Nam",getlocale())},{VG:gs("Virgin Islands (British)",getlocale())},{VI:gs("Virgin Islands (U.S.)",getlocale())},{WF:gs("Wallis and Futuna",getlocale())},{EH:gs("Western Sahara",getlocale())},{YE:gs("Yemen",getlocale())},{YU:gs("Yugoslavia",getlocale())},
{ZM:gs("Zambia",getlocale())},{ZW:gs("Zimbabwe",getlocale())}];for(a=0;a<b.length;a++)"undefined"!=typeof b[a][g_default_cc2]&&(g_default_ccname=b[a][g_default_cc2]);populateselectex("ff_country",b,"");b=[{"":gs("Please select",getlocale())},{AFG:gs("Afghanistan",getlocale())},{ALA:gs("Aland Islands",getlocale())},{ALB:gs("Albania",getlocale())},{DZA:gs("Algeria",getlocale())},{ASM:gs("American Samoa",getlocale())},{AND:gs("Andorra",getlocale())},{AGO:gs("Angola",getlocale())},{AIA:gs("Anguilla",
getlocale())},{ATA:gs("Antarctica",getlocale())},{ATG:gs("Antigua and Barbuda",getlocale())},{ARG:gs("Argentina",getlocale())},{ARM:gs("Armenia",getlocale())},{ABW:gs("Aruba",getlocale())},{AUS:gs("Australia",getlocale())},{AUT:gs("Austria",getlocale())},{AZE:gs("Azerbaijan",getlocale())},{BHS:gs("Bahamas",getlocale())},{BHR:gs("Bahrain",getlocale())},{BGD:gs("Bangladesh",getlocale())},{BRB:gs("Barbados",getlocale())},{BLR:gs("Belarus",getlocale())},{BEL:gs("Belgium",getlocale())},{BLZ:gs("Belize",
getlocale())},{BEN:gs("Benin",getlocale())},{BMU:gs("Bermuda",getlocale())},{BTN:gs("Bhutan",getlocale())},{BOL:gs("Bolivia",getlocale())},{BIH:gs("Bosnia and Herzegovina",getlocale())},{BWA:gs("Botswana",getlocale())},{BVT:gs("Bouvet Island",getlocale())},{BRA:gs("Brazil",getlocale())},{IOT:gs("British Indian Ocean Territory",getlocale())},{BRN:gs("Brunei Darussalam",getlocale())},{BGR:gs("Bulgaria",getlocale())},{BFA:gs("Burkina Faso",getlocale())},{BDI:gs("Burundi",getlocale())},{KHM:gs("Cambodia",
getlocale())},{CMR:gs("Cameroon",getlocale())},{CAN:gs("Canada",getlocale())},{ESC:gs("Canary Islands",getlocale())},{CPV:gs("Cape Verde",getlocale())},{CYM:gs("Cayman Islands",getlocale())},{CAF:gs("Central African Republic",getlocale())},{TCD:gs("Chad",getlocale())},{CHL:gs("Chile",getlocale())},{CHN:gs("China",getlocale())},{CXR:gs("Christmas Island",getlocale())},{CCK:gs("Cocos (Keeling) Islands",getlocale())},{COL:gs("Colombia",getlocale())},{COM:gs("Comoros",getlocale())},{COG:gs("Congo",getlocale())},
{COD:gs("Congo, the Democratic Republic of The",getlocale())},{COK:gs("Cook Islands",getlocale())},{CRI:gs("Costa Rica",getlocale())},{CIV:gs("Cote D'ivoire",getlocale())},{HRV:gs("Croatia",getlocale())},{CUB:gs("Cuba",getlocale())},{CYP:gs("Cyprus",getlocale())},{CZE:gs("Czech Republic",getlocale())},{DNK:gs("Denmark",getlocale())},{DJI:gs("Djibouti",getlocale())},{DMA:gs("Dominica",getlocale())},{DOM:gs("Dominican Republic",getlocale())},{ECU:gs("Ecuador",getlocale())},{EGY:gs("Egypt",getlocale())},
{SLV:gs("El Salvador",getlocale())},{GNQ:gs("Equatorial Guinea",getlocale())},{ERI:gs("Eritrea",getlocale())},{EST:gs("Estonia",getlocale())},{ETH:gs("Ethiopia",getlocale())},{FLK:gs("Falkland Islands (Malvinas)",getlocale())},{FRO:gs("Faroe Islands",getlocale())},{FJI:gs("Fiji",getlocale())},{FIN:gs("Finland",getlocale())},{FRA:gs("France",getlocale())},{GUF:gs("French Guiana",getlocale())},{PYF:gs("French Polynesia",getlocale())},{ATF:gs("French Southern Territories",getlocale())},{GAB:gs("Gabon",
getlocale())},{GMB:gs("Gambia",getlocale())},{GEO:gs("Georgia",getlocale())},{DEU:gs("Germany",getlocale())},{GHA:gs("Ghana",getlocale())},{GIB:gs("Gibraltar",getlocale())},{GRC:gs("Greece",getlocale())},{GRL:gs("Greenland",getlocale())},{GRD:gs("Grenada",getlocale())},{GLP:gs("Guadeloupe",getlocale())},{GUM:gs("Guam",getlocale())},{GTM:gs("Guatemala",getlocale())},{GGY:gs("Guernsey",getlocale())},{GIN:gs("Guinea",getlocale())},{GNB:gs("Guinea-Bissau",getlocale())},{GUY:gs("Guyana",getlocale())},
{HTI:gs("Haiti",getlocale())},{HMD:gs("Heard Island and Mcdonald Islands",getlocale())},{VAT:gs("Holy See (Vatican City State)",getlocale())},{HND:gs("Honduras",getlocale())},{HKG:gs("Hong Kong",getlocale())},{HUN:gs("Hungary",getlocale())},{ISL:gs("Iceland",getlocale())},{IND:gs("India",getlocale())},{IDN:gs("Indonesia",getlocale())},{IRN:gs("Iran (Islamic Republic Of)",getlocale())},{IRQ:gs("Iraq",getlocale())},{IRL:gs("Ireland",getlocale())},{IMM:gs("Isle of Man",getlocale())},{ISR:gs("Israel",
getlocale())},{ITA:gs("Italy",getlocale())},{JAM:gs("Jamaica",getlocale())},{JPN:gs("Japan",getlocale())},{JEY:gs("Jersey",getlocale())},{JOR:gs("Jordan",getlocale())},{KAZ:gs("Kazakhstan",getlocale())},{KEN:gs("Kenya",getlocale())},{KIR:gs("Kiribati",getlocale())},{PRK:gs("Korea, Democratic People's Republic Of",getlocale())},{KOR:gs("Korea, Republic Of",getlocale())},{KWT:gs("Kuwait",getlocale())},{KGZ:gs("Kyrgyzstan",getlocale())},{LAO:gs("Lao People's Democratic Republic",getlocale())},{LVA:gs("Latvia",
getlocale())},{LBN:gs("Lebanon",getlocale())},{LSO:gs("Lesotho",getlocale())},{LBR:gs("Liberia",getlocale())},{LBY:gs("Libyan Arab Jamahiriya",getlocale())},{LIE:gs("Liechtenstein",getlocale())},{LTU:gs("Lithuania",getlocale())},{LUX:gs("Luxembourg",getlocale())},{MAC:gs("Macao",getlocale())},{MKD:gs("Macedonia, the Former Yugoslav Republic Of",getlocale())},{MDG:gs("Madagascar",getlocale())},{MWI:gs("Malawi",getlocale())},{MYS:gs("Malaysia",getlocale())},{MDV:gs("Maldives",getlocale())},{MLI:gs("Mali",
getlocale())},{MLT:gs("Malta",getlocale())},{MHL:gs("Marshall Islands",getlocale())},{MTQ:gs("Martinique",getlocale())},{MRT:gs("Mauritania",getlocale())},{MUS:gs("Mauritius",getlocale())},{MYT:gs("Mayotte",getlocale())},{MEX:gs("Mexico",getlocale())},{FSM:gs("Micronesia, Federated States Of",getlocale())},{MDA:gs("Moldova, Republic Of",getlocale())},{MCO:gs("Monaco",getlocale())},{MNG:gs("Mongolia",getlocale())},{MNE:gs("Montenegro",getlocale())},{MSR:gs("Montserrat",getlocale())},{MAR:gs("Morocco",
getlocale())},{MOZ:gs("Mozambique",getlocale())},{MMR:gs("Myanmar",getlocale())},{NAM:gs("Namibia",getlocale())},{NRU:gs("Nauru",getlocale())},{NPL:gs("Nepal",getlocale())},{NLD:gs("Netherlands",getlocale())},{ANT:gs("Netherlands Antilles",getlocale())},{NCL:gs("New Caledonia",getlocale())},{NZL:gs("New Zealand",getlocale())},{NIC:gs("Nicaragua",getlocale())},{NER:gs("Niger",getlocale())},{NGA:gs("Nigeria",getlocale())},{NIU:gs("Niue",getlocale())},{NFK:gs("Norfolk Island",getlocale())},{MNP:gs("Northern Mariana Islands",
getlocale())},{NOR:gs("Norway",getlocale())},{OMN:gs("Oman",getlocale())},{PAK:gs("Pakistan",getlocale())},{PLW:gs("Palau",getlocale())},{PSE:gs("Palestinian Territories",getlocale())},{PAN:gs("Panama",getlocale())},{PNG:gs("Papua New Guinea",getlocale())},{PRY:gs("Paraguay",getlocale())},{PER:gs("Peru",getlocale())},{PHL:gs("Philippines",getlocale())},{PCN:gs("Pitcairn",getlocale())},{POL:gs("Poland",getlocale())},{PRT:gs("Portugal",getlocale())},{PRI:gs("Puerto Rico",getlocale())},{QAT:gs("Qatar",
getlocale())},{REU:gs("Reunion",getlocale())},{ROU:gs("Romania",getlocale())},{RUS:gs("Russian Federation",getlocale())},{RWA:gs("Rwanda",getlocale())},{BLM:gs("Saint Barthelemy",getlocale())},{SHN:gs("Saint Helena",getlocale())},{KNA:gs("Saint Kitts and Nevis",getlocale())},{LCA:gs("Saint Lucia",getlocale())},{MAF:gs("Saint Martin (French Part)",getlocale())},{SPM:gs("Saint Pierre and Miquelon",getlocale())},{VCT:gs("Saint Vincent and the Grenadines",getlocale())},{WSM:gs("Samoa",getlocale())},{SMR:gs("San Marino",
getlocale())},{STP:gs("Sao Tome and Principe",getlocale())},{SAU:gs("Saudi Arabia",getlocale())},{SEN:gs("Senegal",getlocale())},{SRB:gs("Serbia",getlocale())},{SYC:gs("Seychelles",getlocale())},{SLE:gs("Sierra Leone",getlocale())},{SGP:gs("Singapore",getlocale())},{SVK:gs("Slovakia",getlocale())},{SVN:gs("Slovenia",getlocale())},{SLB:gs("Solomon Islands",getlocale())},{SOM:gs("Somalia",getlocale())},{ZAF:gs("South Africa",getlocale())},{SGS:gs("South Georgia and the South Sandwich Islands",getlocale())},
{ESP:gs("Spain",getlocale())},{LKA:gs("Sri Lanka",getlocale())},{SDN:gs("Sudan",getlocale())},{SUR:gs("Suriname",getlocale())},{SJM:gs("Svalbard and Jan Mayen",getlocale())},{SWZ:gs("Swaziland",getlocale())},{SWE:gs("Sweden",getlocale())},{CHE:gs("Switzerland",getlocale())},{SYR:gs("Syrian Arab Republic",getlocale())},{TWN:gs("Taiwan",getlocale())},{TJK:gs("Tajikistan",getlocale())},{TZA:gs("Tanzania, United Republic Of",getlocale())},{THA:gs("Thailand",getlocale())},{TLS:gs("Timor-Leste",getlocale())},
{TGO:gs("Togo",getlocale())},{TKL:gs("Tokelau",getlocale())},{TON:gs("Tonga",getlocale())},{TTO:gs("Trinidad and Tobago",getlocale())},{TUN:gs("Tunisia",getlocale())},{TUR:gs("Turkey",getlocale())},{TKM:gs("Turkmenistan",getlocale())},{TCA:gs("Turks and Caicos Islands",getlocale())},{TUV:gs("Tuvalu",getlocale())},{UGA:gs("Uganda",getlocale())},{UKR:gs("Ukraine",getlocale())},{ARE:gs("United Arab Emirates",getlocale())},{GBR:gs("United Kingdom",getlocale())},{USA:gs("United States",getlocale())},{UMI:gs("United States Minor Outlying Islands",
getlocale())},{URY:gs("Uruguay",getlocale())},{UZB:gs("Uzbekistan",getlocale())},{VUT:gs("Vanuatu",getlocale())},{VEN:gs("Venezuela",getlocale())},{VNM:gs("Viet Nam",getlocale())},{VGB:gs("Virgin Islands (British)",getlocale())},{VIR:gs("Virgin Islands (U.S.)",getlocale())},{WLF:gs("Wallis and Futuna",getlocale())},{ESH:gs("Western Sahara",getlocale())},{YEM:gs("Yemen",getlocale())},{YUG:gs("Yugoslavia",getlocale())},{ZMB:gs("Zambia",getlocale())},{ZWE:gs("Zimbabwe",getlocale())}];for(a=0;a<b.length;a++)for(var d in b[a])b[a][d]==
g_default_ccname&&(g_default_cc3=d);populateselectex("ff_countryphone",b,"");populateselectex("ff_countryeve",b,"");populateselectex("ff_countryfax",b,"");populateselectex("ff_countrymobile",b,"");b=[{"":gs("Please select",getlocale())},{"-12:00,0":"(-12:00) "+gs("International Date Line West")},{"-11:00,0":"(-11:00) "+gs("Midway Island, Samoa")},{"-10:00,0":"(-10:00) "+gs("Hawaii")},{"-09:00,1":"(-09:00) "+gs("Alaska")},{"-08:00,1":"(-08:00) "+gs("Pacific Time (US & Canada)")},{"-07:00,0":"(-07:00) "+
gs("Arizona")},{"-07:00,1":"(-07:00) "+gs("Mountain Time (US & Canada)")},{"-06:00,0":"(-06:00) "+gs("Central America, Saskatchewan")},{"-06:00,1":"(-06:00) "+gs("Central Time (US & Canada), Guadalajara, Mexico City")},{"-05:00,0":"(-05:00) "+gs("Indiana, Bogota, Lima, Quito, Rio Branco")},{"-05:00,1":"(-05:00) "+gs("Eastern Time (US & Canada)")},{"-04:30,0":"(-04:30) "+gs("Caracas")},{"-04:00,1":"(-04:00) "+gs("Atlantic Time (Canada), Manaus, Santiago")},{"-04:00,0":"(-04:00) "+gs("La Paz")},{"-03:30,1":"(-03:30) "+
gs("Newfoundland")},{"-03:00,1":"(-03:00) "+gs("Greenland, Brasilia, Montevideo")},{"-03:00,0":"(-03:00) "+gs("Buenos Aires, Georgetown")},{"-02:00,1":"(-02:00) "+gs("Mid-Atlantic")},{"-02:00,0":"(-02:00) "+gs("South Georgia")},{"-01:00,1":"(-01:00) "+gs("Azores")},{"-01:00,0":"(-01:00) "+gs("Cape Verde Is.")},{"00:00,0":"(00:00) "+gs("Casablanca, Monrovia, Reykjavik")},{"00:00,1":"(00:00) "+gs("GMT: Dublin, Edinburgh, Lisbon, London")},{"+01:00,1":"(+01:00) "+gs("Amsterdam, Berlin, Rome, Vienna, Prague, Brussels")},
{"+01:00,0":"(+01:00) "+gs("West Central Africa")},{"+02:00,1":"(+02:00) "+gs("Amman, Athens, Istanbul, Beirut, Cairo, Jerusalem")},{"+02:00,0":"(+02:00) "+gs("Harare, Pretoria")},{"+03:00,1":"(+03:00) "+gs("Baghdad")},{"+03:00,0":"(+03:00) "+gs("Kuwait, Riyadh, Nairobi, Moscow, St. Petersburg, Volgograd")},{"+03:30,1":"(+03:30) "+gs("Tehran")},{"+04:00,0":"(+04:00) "+gs("Abu Dhabi, Muscat, Tbilisi, Izhevsk")},{"+04:00,1":"(+04:00) "+gs("Baku, Yerevan")},{"+04:30,0":"(+04:30) "+gs("Kabul")},{"+05:00,1":"(+05:00) "+
gs("GMT+5")},{"+05:00,0":"(+05:00) "+gs("Islamabad, Karachi, Tashkent, Ekaterinburg")},{"+05:30,0":"(+05:30) "+gs("Chennai, Kolkata, Mumbai, New Delhi, Sri Jayawardenepura")},{"+05:45,0":"(+05:45) "+gs("Kathmandu")},{"+06:00,0":"(+06:00) "+gs("Astana, Dhaka, Novosibirsk")},{"+06:00,1":"(+06:00) "+gs("Almaty")},{"+06:30,0":"(+06:30) "+gs("Yangon (Rangoon)")},{"+07:00,1":"(+07:00) "+gs("GMT+7")},{"+07:00,0":"(+07:00) "+gs("Bangkok, Hanoi, Jakarta, Krasnoyarsk")},{"+08:00,0":"(+08:00) "+gs("Beijing, Hong Kong, Singapore, Taipei, Irkutsk")},
{"+08:00,1":"(+08:00) "+gs("Ulaan Bataar, Perth")},{"+09:00,1":"(+09:00) "+gs("GMT+9")},{"+09:00,0":"(+09:00) "+gs("Seoul, Osaka, Sapporo, Tokyo, Yakutsk")},{"+09:30,0":"(+09:30) "+gs("Darwin")},{"+09:30,1":"(+09:30) "+gs("Adelaide")},{"+10:00,0":"(+10:00) "+gs("Brisbane, Guam, Port Moresby, Vladivostok")},{"+10:00,1":"(+10:00) "+gs("Canberra, Melbourne, Sydney, Hobart")},{"+11:00,0":"(+11:00) "+gs("Magadan, Solomon Is., New Caledonia")},{"+12:00,1":"(+12:00) "+gs("Auckland, Wellington")},{"+12:00,0":"(+12:00) "+
gs("Fiji, Kamchatka, Marshall Is.")},{"+13:00,0":"(+13:00) "+gs("Nuku'alofa")}];populateselectex("ff_timezone",b,"");0!=getlocale().indexOf("en")?$("#pff_done").width("260px"):$("#pff_done").width("180px");"add"==g_cmd?($("#pff_delete").hide(),0==g_ff_type?($("#pff_title").text(gs("Add Form Fill profile",getlocale())),$("#pff_done").val(gs("Add Form Fill profile",getlocale()))):($("#pff_title").text(gs("Add Credit Card profile",getlocale())),$("#pff_done").val(gs("Add Credit Card profile",getlocale())))):
"edit"==g_cmd&&($("#pff_delete").val(gs("Delete",getlocale())),0==g_ff_type?($("#pff_title").text(gs("Edit Form Fill profile",getlocale())),$("#pff_done").val(gs("Save Form Fill profile",getlocale()))):($("#pff_title").text(gs("Edit Credit Card profile",getlocale())),$("#pff_done").val(gs("Save Credit Card profile",getlocale()))));d=document.getElementsByTagName("span");for(a=0;a<d.length;a++)if("ff_customfieldcol1span"==d[a].className)set_innertext(d[a],gs("Custom field #",getlocale()));else if("formfilltranslation"==
d[a].className&&(b=d[a].innerHTML.match(/\x3c!--(.*)--\x3e/)))LP_decimate_children(d[a]),d[a].appendChild(document.createComment(b[1])),d[a].appendChild(document.createTextNode(gs(b[1],getlocale())))}
function on_load(a){clearData();if(a){bg=getBG();(!bg||!bg.g_formfill_data)&&setTimeout(function(){getBG().closecurrenttab("formfill.html")},0);g_creditmonurl=bg.getbaseurl()+"creditmon.php";g_data=bg.g_formfill_data;bg.g_formfill_data=null;g_cmd=g_data.cmd;g_ff_type=g_data.type;g_aFF=g_data.data;g_aCustomFields=[];for("edit"==g_cmd&&(g_aFF=ff_convertdatainverse(g_aFF));3>g_aCustomFields.length;)g_aCustomFields.push({cfid:"0",text:"",textalt:"",value:""});g_ff_numcustomfields=g_aCustomFields.length;
g_cc3lphone_map={AFG:"93",ALA:"358",ALB:"355",DZA:"213",ASM:"1",AND:"376",AGO:"244",AIA:"1",ATA:"672",ATG:"1",ARG:"54",ARM:"374",ABW:"297",AUS:"61",AUT:"43",AZE:"994",BHS:"1",BHR:"973",BGD:"880",BRB:"1",BLR:"375",BEL:"32",BLZ:"501",BEN:"229",BMU:"1",BTN:"975",BOL:"591",BIH:"387",BWA:"267",BVT:"47",BRA:"55",IOT:"246",BRN:"673",BGR:"359",BFA:"226",BDI:"257",KHM:"855",CMR:"237",CAN:"1",CPV:"238",CYM:"1",CAF:"236",TCD:"235",CHL:"56",CHN:"86",CXR:"61",CCK:"61",COL:"57",COM:"269",COG:"242",COD:"243",COK:"682",
CRI:"506",CIV:"225",HRV:"385",CUB:"53",CYP:"357",CZE:"420",DNK:"45",DJI:"253",DMA:"1",DOM:"1",ECU:"593",EGY:"20",SLV:"503",GNQ:"240",ERI:"291",EST:"372",ETH:"251",FLK:"500",FRO:"298",FJI:"679",FIN:"358",FRA:"33",GUF:"594",PYF:"689",ATF:"596",GAB:"241",GMB:"220",GEO:"995",DEU:"49",GHA:"233",GIB:"350",GRC:"30",GRL:"299",GRD:"1",GLP:"590",GUM:"1",GTM:"502",GGY:"44",GIN:"224",GNB:"245",GUY:"592",HTI:"509",HMD:"672",VAT:"379",HND:"504",HKG:"852",HUN:"36",ISL:"354",IND:"91",IDN:"62",IRN:"98",IRQ:"964",
IRL:"353",IMM:"44",ISR:"972",ITA:"39",JAM:"1",JPN:"81",JEY:"44",JOR:"962",KAZ:"7",KEN:"254",KIR:"686",PRK:"850",KOR:"82",KWT:"965",KGZ:"996",LAO:"856",LVA:"371",LBN:"961",LSO:"266",LBR:"231",LBY:"218",LIE:"423",LTU:"370",LUX:"352",MAC:"853",MKD:"389",MDG:"261",MWI:"265",MYS:"60",MDV:"960",MLI:"223",MLT:"356",MHL:"692",MTQ:"596",MRT:"222",MUS:"230",MYT:"262",MEX:"52",FSM:"691",MDA:"373",MCO:"377",MNG:"976",MNE:"382",MSR:"1",MAR:"212",MOZ:"258",MMR:"95",NAM:"264",NRU:"674",NPL:"977",NLD:"31",ANT:"599",
NCL:"687",NZL:"64",NIC:"505",NER:"227",NGA:"234",NIU:"683",NFK:"672",MNP:"1",NOR:"47",OMN:"968",PAK:"92",PLW:"680",PSE:"970",PAN:"507",PNG:"675",PRY:"595",PER:"51",PHL:"63",PCN:"872",POL:"48",PRT:"351",PRI:"1",QAT:"974",REU:"262",ROU:"40",RUS:"7",RWA:"250",BLM:"590",SHN:"290",KNA:"1",LCA:"1",MAF:"590",SPM:"508",VCT:"1",WSM:"685",SMR:"378",STP:"239",SAU:"966",SEN:"221",SRB:"381",SYC:"248",SLE:"232",SGP:"65",SVK:"421",SVN:"386",SLB:"677",SOM:"252",ZAF:"27",SGS:"995",ESP:"34",LKA:"94",SDN:"249",SUR:"597",
SJM:"47",SWZ:"268",SWE:"46",CHE:"41",SYR:"963",TWN:"886",TJK:"992",TZA:"255",THA:"66",TLS:"670",TGO:"228",TKL:"690",TON:"676",TTO:"1",TUN:"216",TUR:"90",TKM:"993",TCA:"1",TUV:"688",UGA:"256",UKR:"380",ARE:"971",GBR:"44",USA:"1",UMI:"1",URY:"598",UZB:"998",VUT:"678",VEN:"58",VNM:"84",VGB:"1",VIR:"1",WLF:"681",ESH:"212",YEM:"967",YUG:"381",ZMB:"260",ZWE:"263",ESC:"34"};g_default_cc2=bg.countryfromip;g_default_cc3=g_default_ccname="";g_DUMMYSTATE="----------";g_mobileenc=!1;$(document).ready(function(){$.ajaxSetup({dataType:"json",
timeout:15E3,global:!1,type:"POST",cache:!1});bg.g_generatedpw&&$("#pwprotect").css("visibility","hidden");1==g_ff_type&&$("#creditmon").css("visibility","hidden");for(var a=[{"zh-CN":gs("Chinese (Simplified)")},{"zh-TW":gs("Chinese (Traditional)")},{"da-DK":gs("Danish")},{"nl-NL":gs("Dutch")},{"en-US":gs("English")},{"en-GB":gs("English (United Kingdom)")},{"fi-FI":gs("Finnish")},{"fr-FR":gs("French")},{"fr-CA":gs("French (Canada)")},{"de-DE":gs("German")},{"hu-HU":gs("Hungarian")},{"it-IT":gs("Italian")},
{"ja-JP":gs("Japanese")},{"ko-FR":gs("Korean")},{"nb-NO":gs("Norwegian")},{"pl-PL":gs("Polish")},{"pt-PT":gs("Portuguese")},{"pt-BR":gs("Portuguese (Brazilian)")},{"ru-RU":gs("Russian")},{"sk-SK":gs("Slovak")},{"es-ES":gs("Spanish")},{"es-MX":gs("Spanish (Mexico)")},{"sv-SE":gs("Swedish")}],c=[],d=0;d<a.length;d++)for(var e in a[d])for(var g in g_langs)if("en-GB"==e){if("en_GB"==g){c[c.length]=a[d];break}}else if("es-MX"==e){if("es_419"==g){c[c.length]=a[d];break}}else if(g.substring(0,2)==e.substring(0,
2)){c[c.length]=a[d];break}a=c;c=getBG().lpGetPref("language","");""==c&&(c=navigator.language);var c=c.replace(/_/,"-"),f="en-US";states=[];for(d=0;d<a.length;d++)for(e in a[d])if(0==e.toLowerCase().indexOf(c.toLowerCase())&&(f=e),"undefined"!=typeof translations&&"undefined"!=typeof translations[e]){states[e]=[];for(g=1;"undefined"!=typeof translations[e]["state"+g];g++)states[e].push([translations[e]["state"+g],translations[e]["state"+g]])}populateselectex("ff_language",a,f);retranslate();a={};
e={};LP_decimate_children(document.getElementById("ff_customfieldstable"));for(d in g_aCustomFields)"remove"!=d&&(d=parseInt(d),g=document.createElement("tr"),g.className="ff_customfieldrow",c=document.createElement("td"),c.className="ff_customfieldcol1",f=document.createElement("span"),f.className="ff_customfieldcol1span",set_innertext(f,gs("Custom field #",getlocale())),c.appendChild(f),c.appendChild(document.createTextNode(d+1)),g.appendChild(c),c=document.createElement("td"),c.className="ff_customfieldcol2",
f=document.createElement("textarea"),f.id="ff_customtext"+d,0==d&&(f.className="ff_focus"),c.appendChild(f),g.appendChild(c),a["ff_customtext"+d]=function(){ttabove(this,gt("The text beside, the name of, or the ID of the form field to be filled.<br/>If multiple items are to be matched, specify each match on a separate line."))},e["ff_customtext"+d]=function(){ttoff()},c=document.createElement("td"),c.className="ff_customfieldcol2",f=document.createElement("textarea"),f.id="ff_customvalue"+d,c.appendChild(f),
g.appendChild(c),a["ff_customvalue"+d]=function(){ttabove(this,gt("The value to be filled"))},e["ff_customvalue"+d]=function(){ttoff()},document.getElementById("ff_customfieldstable").appendChild(g));for(d in a)document.getElementById(d).addEventListener("mouseover",a[d]);for(d in e)document.getElementById(d).addEventListener("mouseout",e[d]);0==g_ff_type?($("#ff_tabspacer").hide(),$("#ff_tabpersonal").click()):($("#ff_tabspacer").show(),$("#ff_tabpersonal").hide(),$("#ff_tabaddress").hide(),$("#ff_tabcontact").hide(),
$("#ff_tabbankaccount").hide(),$("#ff_tabcustomfields").hide(),$("#ff_tabcreditcard").click());setTimeout(function(){$("#ff_name").focus().select()},0);"add"==g_cmd?pff_init_add():"edit"==g_cmd&&pff_init_edit();retranslate();fix_states();$("#ff_creditmon").click(function(){ff_checkcreditmon()});ff_fix_birthday()})}else get_data("formfill",function(){on_load(!0)})}
function clearData(){for(var a=document.getElementsByTagName("input"),b=0;b<a.length;b++)a[b].value="";a=document.getElementsByTagName("textarea");for(b=0;b<a.length;b++)a[b].value=""}function ttabove(a,b){tt(a,b,"t","fl",[-5,0])}function ttabover(a,b){tt(a,b,"t","fr",[-5,0])}
function tt(a,b,c,d,e,g){a=$(a);g=$(g?g:"#tooltip");if(b)for(var f=g.get(),k=0;k<f.length;k++){LP_decimate_children(f[k]);for(var n=b.split("<br/>"),l=0;l<n.length;l++)0<l&&f[k].appendChild(document.createElement("br")),f[k].appendChild(document.createTextNode(n[l]))}g.show();f=a.offset();b=f.top;"t"==c?b-=g.outerHeight():"m"==c?b-=(g.outerHeight()-a.outerHeight())/2:"b"==c?b+=a.outerHeight():"ft"!=d&&"fb"==d&&(b-=g.outerHeight()-a.outerHeight());c=f.left;"l"==d?c-=g.outerWidth():"m"==d?c-=(g.outerWidth()-
a.outerWidth())/2:"r"==d?c+=a.outerWidth():"fl"!=d&&"fr"==d&&(c-=g.outerWidth()-a.outerWidth());e&&(b+=e[0],c+=e[1]);g.css({left:c,top:b,opacity:0.9}).show()}function ttoff(){$("#tooltip").hide()}var g_dialogonce=!0;
function dialog_show(a,b){"undefined"==typeof b||b?($("#dialog .close").show(),g_dialogonce&&(g_dialogonce=!1,$("#dialog .close").click(function(){dialog_hide()}))):$("#dialog .close").hide();dialog_hide();for(var c=$("#dialog .content").get(),d=0;d<c.length;d++)for(var e=0;e<a.length;e++)c[d].appendChild(a[e]);var c=$("#dialog"),e=$(window),d=e.width(),e=e.height(),g=c.width(),f=c.height();c.css({left:Math.floor((d-g)/2),top:Math.floor((e-f)/2),opacity:0.9}).show();c=$("#modaldialog");c.css({width:d,
height:e,opacity:0.5}).show()}function dialog_hide(){for(var a=$("#dialog .content").get(),b=0;b<a.length;b++)LP_decimate_children(a[b]);$("#dialog").hide();$("#modaldialog").hide();return!1}var g_ff_selectedtabid="";
function ffshow(a){$(".ff_tab").children("span").css({color:"#4c4c4c","border-bottom":"none"});var b=$("#"+a.replace(/pane/,"tab"));b.children("span").css({color:"#e0322d","border-bottom":"2px solid #e0322d"});$(".ff_pane").hide();$("#"+a).show();$("#"+a+" .ff_focus").focus().select();g_ff_selectedtabid=b.attr("id");return!1}
function ff_addcustomfield(){var a=document.createElement("tr");a.className="ff_customfieldrow";var b=document.createElement("td");b.className="ff_customfieldcol1";var c=document.createElement("span");c.className="ff_customfieldcol1span";set_innertext(c,gs("Custom field #",getlocale()));b.appendChild(c);b.appendChild(document.createTextNode(g_ff_numcustomfields+1));a.appendChild(b);b=document.createElement("td");b.className="ff_customfieldcol2";c=document.createElement("textarea");c.id="ff_customtext"+
g_ff_numcustomfields;b.appendChild(c);a.appendChild(b);b=document.createElement("td");b.className="ff_customfieldcol2";c=document.createElement("textarea");c.id="ff_customvalue"+g_ff_numcustomfields;b.appendChild(c);a.appendChild(b);document.getElementById("ff_customfieldstable").appendChild(a);document.getElementById("ff_customtext"+ +g_ff_numcustomfields).addEventListener("mouseover",function(){ttabove(this,gt("The text beside, the name of, or the ID of the form field to be filled.<br/>If multiple items are to be matched, specify each match on a separate line."))});
document.getElementById("ff_customtext"+ +g_ff_numcustomfields).addEventListener("mouseout",function(){ttoff()});document.getElementById("ff_customvalue"+ +g_ff_numcustomfields).addEventListener("mouseover",function(){ttabove(this,gt("The value to be filled"))});document.getElementById("ff_customvalue"+ +g_ff_numcustomfields).addEventListener("mouseout",function(){ttoff()});$("#ff_customtext"+g_ff_numcustomfields).select().focus();++g_ff_numcustomfields;return!1}
function ff_fix_birthday(){var a=parseInt($("#ff_birthday_month").val()),b=parseInt($("#ff_birthday_year").val()),a=(2==a?""==b||isNaN(b)?29:ff_checkleapyear(b)?29:28:4==a||6==a||9==a||11==a?30:31)+1,b=$("#ff_birthday_day")[0],c;b.selectedIndex>=a&&(b.selectedIndex=a-1);for(c=b.options.length-1;c>=a;--c)b.options[c]=null;for(c=b.options.length;c<a;++c)b.options[c]=new Option(c,c)}function ff_checkleapyear(a){return 0==a%4&&(0!=a%100||0==datea%400)?!0:!1}
function onkeyupnpa(a,b){var c=b.keyCode,d=$(a).attr("id").replace(/npa/,"nxx");48<=c&&(57>=c&&3==a.value.length)&&$("#"+d).focus().select()}function onkeydownnxx(a,b){if(8==b.keyCode&&0==a.value.length){var c=$(a).attr("id").replace(/nxx/,"npa");$("#"+c).focus().select();b.preventDefault?b.preventDefault():b.returnValue=!1}}function onkeyupnxx(a,b){var c=b.keyCode;48<=c&&(57>=c&&3==a.value.length)&&(c=$(a).attr("id").replace(/nxx/,"xxxx"),$("#"+c).focus().select())}
function onkeydownxxxx(a,b){if(8==b.keyCode&&0==a.value.length){var c=$(a).attr("id").replace(/xxxx/,"nxx");$("#"+c).focus().select();b.preventDefault?b.preventDefault():b.returnValue=!1}}function onkeyupxxxx(a,b){var c=b.keyCode;48<=c&&(57>=c&&4==a.value.length)&&(c=$(a).attr("id").replace(/xxxx/,"ext"),$("#"+c).focus().select())}
function onkeydownext(a,b){if(8==b.keyCode&&0==a.value.length){var c=$(a).attr("id").replace(/ext/,"dom"),c=$(a).attr("id").replace(/ext/,$("#"+c).is(":visible")?"xxxx":"intnum");$("#"+c).focus().select();b.preventDefault?b.preventDefault():b.returnValue=!1}}
function fix_phone(a){var b=$(a),c=b.attr("id").replace(/ff_country/,"");a=$("#ff_dom"+c);var d=$("#ff_npa"+c),e=$("#ff_nxx"+c),g=$("#ff_xxxx"+c),f=$("#ff_int"+c),k=$("#ff_intcc"+c);$("#ff_intnum"+c);c=$("#ff_ext"+c);b=b.val();b=""==b?"":g_cc3lphone_map[b];switch(b){case "":d.attr("disabled",!0);e.attr("disabled",!0);g.attr("disabled",!0);c.attr("disabled",!0);k.val("");f.hide();a.show();break;case "1":d.removeAttr("disabled");e.removeAttr("disabled");g.removeAttr("disabled");c.removeAttr("disabled");
k.val("");a.show();f.hide();k.val("");f.hide();a.show();break;default:c.removeAttr("disabled"),k.val(b),f.show(),a.hide()}}
function ff_setdefaults(){$("#ff_country").val(g_default_cc2);$("#ff_timezone").val(calculate_time_zone(!0));$("#ff_countryphone").val(g_default_cc3);$("#ff_countryeve").val(g_default_cc3);$("#ff_countryfax").val(g_default_cc3);$("#ff_countrymobile").val(g_default_cc3);fix_phone($("#ff_countryphone"));fix_phone($("#ff_countryeve"));fix_phone($("#ff_countryfax"));fix_phone($("#ff_countrymobile"))}
function ff_state_changed(){var a=$("#ff_state"),b=$("#ff_statecustom");$("#ff_state :selected").text()==g_DUMMYSTATE?(a.val(""),b.hide()):"CUSTOM"==a.val()?(b.show(),b.focus()):b.hide()}
function ff_checkphonenumber(a){var b=$("#ff_country"+a),c=$("#ff_dom"+a),d=$("#ff_npa"+a),e=$("#ff_nxx"+a),g=$("#ff_xxxx"+a);$("#ff_int"+a);$("#ff_intcc"+a);var f=$("#ff_intnum"+a);a=$("#ff_ext"+a);if(""==b.val())return!0;if(!a.val().match(/^\d*$/))return $("#ff_tabcontact").click(),a.css("background","#FFCBD6").focus().select(),!1;if("none"!=c.css("display")){f=d.val();b=e.val();c=g.val();if(""==f+b+c)return!0;a=!0;f.match(/^\d{3}$/)||($("#ff_tabcontact").click(),d.css("background","#FFCBD6").focus().select(),
a=!1);b.match(/^\d{3}$/)||($("#ff_tabcontact").click(),e.css("background","#FFCBD6").focus().select(),a=!1);c.match(/^\d{4}$/)||($("#ff_tabcontact").click(),g.css("background","#FFCBD6").focus().select(),a=!1);if(!a)return!1}else{d=f.val();if(""==d)return!0;if(!d.match(/^\d*$/))return $("#ff_tabcontact").click(),f.css("background","#FFCBD6").focus().select(),!1}return!0}
function ff_checkbirthday(){if(""==$("#ff_birthday_year").val()&&""==$("#ff_birthday_month").val()&&""==$("#ff_birthday_day").val())return!0;var a=!0;$("#ff_birthday_year").val().match(/^\d{4}$/)||($("#ff_tabpersonal").click(),$("#ff_birthday_year").css("background","#FFCBD6").focus().select(),a=!1);$("#ff_birthday_month").val().match(/^\d{2}$/)||($("#ff_tabpersonal").click(),$("#ff_birthday_month").css("background","#FFCBD6").focus().select(),a=!1);$("#ff_birthday_day").val().match(/^\d{2}$/)||($("#ff_tabpersonal").click(),
$("#ff_birthday_day").css("background","#FFCBD6").focus().select(),a=!1);return!a?!1:!0}
function ff_checkccstart(){if(""==$("#ff_ccstart_year").val()&&""==$("#ff_ccstart_month").val())return!0;var a=!0;$("#ff_ccstart_year").val().match(/^\d{4}$/)||($("#ff_tabcreditcard").click(),$("#ff_ccstart_year").css("background","#FFCBD6").focus().select(),a=!1);$("#ff_ccstart_month").val().match(/^\d{2}$/)||($("#ff_tabcreditcard").click(),$("#ff_ccstart_month").css("background","#FFCBD6").focus().select(),a=!1);return!a?!1:!0}
function ff_checkccexp(){if(""==$("#ff_ccexp_year").val()&&""==$("#ff_ccexp_month").val())return!0;var a=!0;$("#ff_ccexp_year").val().match(/^\d{4}$/)||($("#ff_tabcreditcard").click(),$("#ff_ccexp_year").css("background","#FFCBD6").focus().select(),a=!1);$("#ff_ccexp_month").val().match(/^\d{2}$/)||($("#ff_tabcreditcard").click(),$("#ff_ccexp_month").css("background","#FFCBD6").focus().select(),a=!1);return!a?!1:!0}
function ff_checkccnum(){return!$("#ff_ccnum").val().match(/^(?:\d{10,19}|)$/)?($("#ff_tabcreditcard").click(),$("#ff_ccnum").css("background","#FFCBD6").focus().select(),!1):!0}function ff_checkcccsc(){return!$("#ff_cccsc").val().match(/^(?:\d{3,4}|)$/)?($("#ff_tabcreditcard").click(),$("#ff_cccsc").css("background","#FFCBD6").focus().select(),!1):!0}
function ff_checkccissuenum(){return!$("#ff_ccissuenum").val().match(/^(?:\d{1,3}|)$/)?($("#ff_tabcreditcard").click(),$("#ff_ccissuenum").css("background","#FFCBD6").focus().select(),!1):!0}function ff_checkemail(){return""!=$("#ff_email").val()&&!check_email($("#ff_email").val())?($("#ff_tabcontact").click(),$("#ff_email").css("background","#FFCBD6").focus().select(),!1):!0}
function ff_checkbankacctnum(){return!$("#ff_bankacctnum").val().match(/^[0-9A-Za-z]*$/)?($("#ff_tabbankaccount").click(),$("#ff_bankacctnum").css("background","#FFCBD6").focus().select(),!1):!0}function ff_checkbankroutingnum(){return!$("#ff_bankroutingnum").val().match(/^[0-9-]*$/)?($("#ff_tabbankaccount").click(),$("#ff_bankroutingnum").css("background","#FFCBD6").focus().select(),!1):!0}
function ff_checkcustom(){for(i=0;i<g_ff_numcustomfields;++i){if(""!=$("#ff_customtext"+i).val()&&""==$("#ff_customvalue"+i).val())return $("#ff_tabcustomfields").click(),$("#ff_customvalue"+i).css("background","#FFCBD6").focus().select(),!1;if(""==$("#ff_customtext"+i).val()&&""!=$("#ff_customvalue"+i).val())return $("#ff_tabcustomfields").click(),$("#ff_customtext"+i).css("background","#FFCBD6").focus().select(),!1}return!0}
function ff_getprettyphone(a){return 11!=a.length?a:"("+a.substring(1,4)+") "+a.substring(4,7)+"-"+a.substring(7)}
function ff_checkcreditmon(){$("#ff_firstname").css("background","");$("#ff_lastname").css("background","");$("#ff_birthday_year").css("background","");$("#ff_birthday_month").css("background","");$("#ff_birthday_day").css("background","");$("#ff_ssn").css("background","");$("#ff_address1").css("background","");$("#ff_address2").css("background","");$("#ff_address3").css("background","");$("#ff_city").css("background","");$("#ff_state").css("background","");$("#ff_statecustom").css("background","");
$("#ff_country").css("background","");$("#ff_zip").css("background","");$("#ff_countryphone").css("background","");$("#ff_npaphone").css("background","");$("#ff_nxxphone").css("background","");$("#ff_xxxxphone").css("background","");$("#ff_extphone").css("background","");$("#ff_creditmon").css("background","");if($("#ff_creditmon").attr("checked")){if("US"!=$("#ff_country").val())return $("#ff_tabaddress").click(),$("#ff_country").css("background","#FFCBD6"),alert("Credit monitoring is only available for addresses in the United States.\n\nPlease either disable credit monitoring, or enter a valid US address and try again."),
$("#ff_country").focus().select(),!1;var a=[],b="",c=$("#ff_zip").val(),c=c.replace(/[^0-9]/g,"");5!=c.length&&9!=c.length&&(b="ff_tabaddress",a.push("ff_zip"));if(""==("CUSTOM"==$("#ff_state").val()?$("#ff_statecustom").val():$("#ff_state").val()))b="ff_tabaddress",a.push("ff_state"),a.push("ff_statecustom");""==$("#ff_city").val()&&(b="ff_tabaddress",a.push("ff_city"));""==$("#ff_address1").val()&&(b="ff_tabaddress",a.push("ff_address1"));c=$("#ff_ssn").val();c=c.replace(/[^0-9]/g,"");4>c.length&&
(b="ff_tabpersonal",a.push("ff_ssn"));""==ff_getbirthday()&&(b="ff_tabpersonal",a.push("ff_birthday_year"),a.push("ff_birthday_month"),a.push("ff_birthday_day"));1>ff_getval("#ff_lastname","#ff_lastnameja1").length&&(b="ff_tabpersonal",a.push("ff_lastname"));1>ff_getval("#ff_firstname","#ff_firstnameja1").length&&(b="ff_tabpersonal",a.push("ff_firstname"));var c="",d=!1,e=ff_getphonenumber("phone");"USA"!=ff_getphone3lcode("phone")?(""==b&&(b="ff_tabcontact"),0==a.length&&(d=!0),a.push("ff_xxxxphone"),
a.push("ff_nxxphone"),a.push("ff_npaphone"),a.push("ff_countryphone"),c="To enable credit monitoring, the phone number country must be 'United States'."):11!=e.length&&(""==b&&(b="ff_tabcontact"),0==a.length&&(d=!0),a.push("ff_xxxxphone"),a.push("ff_nxxphone"),a.push("ff_npaphone"),c="To enable credit monitoring, you must enter your valid phone number.");if(0<a.length){ffshow(b);$("#"+b).click();$("#ff_creditmon").css("background","#FFCBD6");for(b=0;b<a.length;++b)$("#"+a[b]).css("background","#FFCBD6").focus().select();
d?alert(c):alert("Credit monitoring requires that all of the following information be entered:\n\nFirst name\nLast name\nAddress\nCity\nState\nZip Code\nSocial Security Number\nBirthday\nPhone Number\n\nPlease either disable credit monitoring, or enter all of the required information and try again.");return!1}}return!0}
function ff_getphonenumber(a){var b=$("#ff_country"+a),c=$("#ff_dom"+a),d=$("#ff_npa"+a),e=$("#ff_nxx"+a),g=$("#ff_xxxx"+a);$("#ff_int"+a);$("#ff_intcc"+a);var f=$("#ff_intnum"+a);$("#ff_ext"+a);if(""==b.val())return"";a=g_cc3lphone_map[b.val()];c="none"!=c.css("display")?a+d.val()+e.val()+g.val():a+f.val();c=c.replace("-","");c=c.replace("(","");c=c.replace(")","");c=c.replace(".","");c=c.replace(" ","");c==a&&(c="");return c}
function ff_getphone3lcode(a){return""==ff_getphonenumber(a)?"":$("#ff_country"+a).val()}function ff_getphoneext(a){return $("#ff_ext"+a).val()}function ff_getbirthday(){if(!ff_checkbirthday())return"";var a=$("#ff_birthday_year").val()+"-"+$("#ff_birthday_month").val()+"-"+$("#ff_birthday_day").val();return"--"==a?"":a}function ff_getccstart(){if(!ff_checkccstart())return"";var a=$("#ff_ccstart_year").val()+"-"+$("#ff_ccstart_month").val();return"-"==a?"":a}
function ff_getccexp(){if(!ff_checkccexp())return"";var a=$("#ff_ccexp_year").val()+"-"+$("#ff_ccexp_month").val();return"-"==a?"":a}function ff_getval(a,b){return"ja-JP"==$("#ff_language").val()?$(b).val():$(a).val()}
function ff_getalldata(){var a={name:$("#ff_name").val(),language:$("#ff_language").val(),title:$("#ff_title").val(),firstname:ff_getval("#ff_firstname","#ff_firstnameja1"),firstname2:$("#ff_firstnameja2").val(),firstname3:$("#ff_firstnameja3").val(),middlename:$("#ff_middlename").val(),lastname:ff_getval("#ff_lastname","#ff_lastnameja1"),lastname2:ff_getval("#ff_lastname2","#ff_lastnameja2"),lastname3:$("#ff_lastnameja3").val(),username:$("#ff_username").val(),gender:$("#ff_gender").val(),birthday:ff_getbirthday(),
ssn:$("#ff_ssn").val(),company:$("#ff_company").val(),address1:$("#ff_address1").val(),address2:$("#ff_address2").val(),address3:$("#ff_address3").val(),city:$("#ff_city").val(),county:$("#ff_county").val(),state:"CUSTOM"==$("#ff_state").val()?$("#ff_statecustom").val():$("#ff_state").val(),zip:$("#ff_zip").val(),country:$("#ff_country").val(),timezone:$("#ff_timezone").val(),email:$("#ff_email").val(),mobileemail:$("#ff_mobileemail").val(),telphone:ff_getphonenumber("phone"),tel3lphone:ff_getphone3lcode("phone"),
telextphone:ff_getphoneext("phone"),televe:ff_getphonenumber("eve"),tel3leve:ff_getphone3lcode("eve"),telexteve:ff_getphoneext("eve"),telmobile:ff_getphonenumber("mobile"),tel3lmobile:ff_getphone3lcode("mobile"),telextmobile:ff_getphoneext("mobile"),telfax:ff_getphonenumber("fax"),tel3lfax:ff_getphone3lcode("fax"),telextfax:ff_getphoneext("fax"),ccname:$("#ff_ccname").val(),ccnum:$("#ff_ccnum").val(),ccstart:ff_getccstart(),ccexp:ff_getccexp(),cccsc:$("#ff_cccsc").val(),ccissuenum:$("#ff_ccissuenum").val(),
bankname:$("#ff_bankname").val(),bankacctnum:$("#ff_bankacctnum").val(),bankroutingnum:$("#ff_bankroutingnum").val(),notes:$("#ff_notes").val(),country_cc3l:iso2to3($("#ff_country").val()),country_name:$("#ff_country :selected").text(),state_name:"CUSTOM"==$("#ff_state").val()?$("#ff_statecustom").val():$("#ff_state :selected").text(),driverlicensenum:"",taxid:""};for(i=j=0;i<g_ff_numcustomfields;++i)""!=$("#ff_customtext"+i).val()&&(a["customtext"+j]=$("#ff_customtext"+i).val(),a["customvalue"+j]=
$("#ff_customvalue"+i).val(),++j);return a}
function ff_convertdatainverse(a){var b={};"undefined"!=typeof a.sharefolderid&&(b.sharefolderid=a.sharefolderid);b.group="undefined"!=typeof a.group?a.group:"";b.ffid=a.ffid;b.type=a.profiletype;b.name=a.profilename;b.language=a.profilelanguage;b["protected"]=a.pwprotect?1:0;b.creditmon=a.creditmon?1:0;b.title=a.title;b.firstname=a.firstname;b.firstname2=a.firstname2;b.firstname3=a.firstname3;b.middlename=a.middlename;b.lastname=a.lastname;b.lastname2=a.lastname2;b.lastname3=a.lastname3;b.username=
a.username;b.gender=a.gender;b.birthday=a.birthday;b.ssn=a.ssn;b.company=a.company;b.address1=a.address1;b.address2=a.address2;b.address3=a.address3;b.city=a.city;b.county=a.county;b.state=a.state;b.zip=a.zip;b.country=a.country;b.timezone=a.timezone;b.email=a.email;b.mobileemail=a.mobileemail;b.telphone=a.phone;b.tel3lphone=a.phone3lcc;b.telextphone=a.phoneext;b.televe=a.evephone;b.tel3leve=a.evephone3lcc;b.telexteve=a.eveext;b.telmobile=a.mobilephone;b.tel3lmobile=a.mobilephone3lcc;b.telextmobile=
a.mobileext;b.telfax=a.fax;b.tel3lfax=a.fax3lcc;b.telextfax=a.faxext;b.ccname=a.ccname;b.ccnum=a.ccnum;b.ccstart=a.ccstart;b.ccexp=a.ccexp;b.cccsc=a.cccsc;b.ccissuenum=a.ccissuenum;b.bankname=a.bankname;b.bankacctnum=a.bankacctnum;b.bankroutingnum=a.bankroutingnum;b.notes=a.notes;b.country_cc3l=a.country_cc3l;b.country_name=a.country_name;b.state_name=a.state_name;b.driverlicensenum=a.driverlicensenum;b.taxid=a.taxid;for(i=0;i<getcount(a.custom_fields);++i){var c=a.custom_fields[i];g_aCustomFields.push({cfid:c.cfid,
text:c.text,textalt:c.alttext,value:c.value})}return b}
function ff_convertdata(a){var b={};"undefined"!=typeof a.sharefolderid&&(b.sharefolderid=a.sharefolderid);b.group="undefined"!=typeof a.group?a.group:"";b.profiletype=a.type;b.profilename=a.name;b.profilelanguage=a.language;b.pwprotect=1==a["protected"]?"on":"";b.creditmon=1==a.creditmon?"on":"";b.title=a.title;b.firstname=a.firstname;b.firstname2=a.firstname2;b.firstname3=a.firstname3;b.middlename=a.middlename;b.lastname=a.lastname;b.lastname2=a.lastname2;b.lastname3=a.lastname3;b.username=a.username;
b.gender=a.gender;b.birthday=a.birthday;b.ssn=a.ssn;b.company=a.company;b.address1=a.address1;b.address2=a.address2;b.address3=a.address3;b.city=a.city;b.county=a.county;b.state=a.state;b.zip=a.zip;b.country=a.country;b.timezone=a.timezone;b.email=a.email;b.mobileemail=a.mobileemail;b.phone=a.telphone;b.phone3lcc=a.tel3lphone;b.phoneext=a.telextphone;b.evephone=a.televe;b.evephone3lcc=a.tel3leve;b.eveext=a.telexteve;b.mobilephone=a.telmobile;b.mobilephone3lcc=a.tel3lmobile;b.mobileext=a.telextmobile;
b.fax=a.telfax;b.fax3lcc=a.tel3lfax;b.faxext=a.telextfax;b.ccname=a.ccname;b.ccnum=a.ccnum;b.ccstart=a.ccstart;b.ccexp=a.ccexp;b.cccsc=a.cccsc;b.ccissuenum=a.ccissuenum;b.bankname=a.bankname;b.bankacctnum=a.bankacctnum;b.bankroutingnum=a.bankroutingnum;b.notes=a.notes;b.country_cc3l=a.country_cc3l;b.country_name=a.country_name;b.state_name=a.state_name;b.driverlicensenum=a.driverlicensenum;b.taxid=a.taxid;for(i=j=0;i<g_ff_numcustomfields;++i)if(""!=$("#ff_customtext"+i).val()){b["customfield"+(j+
1)+"cfid"]="undefined"!=typeof g_aCustomFields&&"undefined"!=typeof g_aCustomFields[j]&&"undefined"!=typeof g_aCustomFields[j].cfid?g_aCustomFields[j].cfid:0;b["customfield"+(j+1)+"value"]=encrypt($("#ff_customvalue"+i).val());a=$("#ff_customtext"+i).val().split("\n");var c="undefined"!=typeof a[1]?a[1]:"";b["customfield"+(j+1)+"text"]=encrypt("undefined"!=typeof a[0]?a[0]:"");b["customfield"+(j+1)+"alttext"]=encrypt(c);++j}for(;3>j;)b["customfield"+(j+1)+"cfid"]="undefined"!=typeof g_aCustomFields&&
"undefined"!=typeof g_aCustomFields[j]&&"undefined"!=typeof g_aCustomFields[j].cfid?g_aCustomFields[j].cfid:0,b["customfield"+(j+1)+"value"]="",b["customfield"+(j+1)+"text"]="",b["customfield"+(j+1)+"alttext"]="",++j;for(;"undefined"!=typeof g_aCustomFields&&"undefined"!=typeof g_aCustomFields[j]&&"undefined"!=typeof g_aCustomFields[j].cfid;)b["customfield"+(j+1)+"cfid"]="undefined"!=typeof g_aCustomFields&&"undefined"!=typeof g_aCustomFields[j]&&"undefined"!=typeof g_aCustomFields[j].cfid?g_aCustomFields[j].cfid:
0,b["customfield"+(j+1)+"value"]="",b["customfield"+(j+1)+"text"]="",b["customfield"+(j+1)+"alttext"]="",++j;return b}function pff_delete(){if(!bg.lploggedin)return!1;confirmex(gs("Are you sure you would like to delete this form fill profile?",getlocale()),function(){bg.deleteformfill(g_aFF.ffid);setTimeout(function(){getBG().closecurrenttab("formfill.html")},0)});return!1}function pff_save(){if("add"==g_cmd)return pff_save_add();if("edit"==g_cmd)return pff_save_edit()}
function pff_cancel(){setTimeout(function(){getBG().closecurrenttab("formfill.html")},0)}function pff_init_add(){$("#pff_delete").hide();ff_setdefaults()}
function pff_save_add(){if(!bg.lploggedin)return!1;if(""==$("#ff_name").val())return $("#ff_name").css("background","#FFCBD6").focus().select(),!1;if(!ff_checkemail()||!ff_checkphonenumber("phone")||!ff_checkphonenumber("eve")||!ff_checkphonenumber("fax")||!ff_checkphonenumber("mobile")||!ff_checkbirthday()||!ff_checkccnum()||!ff_checkccstart()||!ff_checkccexp()||!ff_checkcccsc()||!ff_checkccissuenum()||!ff_checkbankacctnum()||!ff_checkbankroutingnum()||!ff_checkcustom()||!ff_checkcreditmon())return!1;
if(!$("#ff_creditmon").attr("checked"))return pff_save_add2(),!1;ff_creditmon("add")}
function pff_save_add2(a){var b="undefined"!=typeof a&&""!=b?a:"";a=ff_getalldata();var c={};for(i in a)c[i]=encrypt(a[i]);c.type=g_ff_type;c["protected"]=$("#ff_protected").attr("checked")?1:0;c.creditmon=$("#ff_creditmon").attr("checked")?1:0;var d=ff_convertdata(c);d.ffid=0;d.deleteext=0;""!=b&&(d.newffid=b);b=null;g_mobileenc=!0;a=ff_getalldata();c={};for(i in a)c[i]=encrypt(a[i]);c.type=g_ff_type;c["protected"]=$("#ff_protected").attr("checked")?1:0;c.creditmon=$("#ff_creditmon").attr("checked")?
1:0;b=ff_convertdata(c);b.pwprotect="on"==b.pwprotect?!0:!1;b.creditmon="on"==b.creditmon?!0:!1;b.ffid=0;b.deleteext=0;b.decprofilename=a.name;b.cmd="add";g_mobileenc=!1;bg.addeditformfill(d,b);setTimeout(function(){getBG().closecurrenttab("formfill.html")},0);return!1}
function pff_init_edit(){ff_setdefaults();var a=decrypt(g_aFF.birthday).replace(/\D/g,"");$("#ff_birthday_year").val(a.substring(0,4));$("#ff_birthday_month").val(a.substring(4,6));$("#ff_birthday_day").val(a.substring(6,8));ff_fix_birthday();a=decrypt(g_aFF.ccstart);$("#ff_ccstart_year").val(a.substring(0,4));$("#ff_ccstart_month").val(a.substring(5,7));a=decrypt(g_aFF.ccexp);$("#ff_ccexp_year").val(a.substring(0,4));$("#ff_ccexp_month").val(a.substring(5,7));$("#ff_name").val(decrypt(g_aFF.name));
$("#ff_protected").attr("checked",1==g_aFF["protected"]);$("#ff_creditmon").attr("checked",1==g_aFF.creditmon);$("#ff_language").val(decrypt(g_aFF.language));$("#ff_title").val(decrypt(g_aFF.title));$("#ff_firstname").val(decrypt(g_aFF.firstname));$("#ff_firstnameja1").val(decrypt(g_aFF.firstname));$("#ff_firstnameja2").val(decrypt(g_aFF.firstname2));$("#ff_firstnameja3").val(decrypt(g_aFF.firstname3));$("#ff_middlename").val(decrypt(g_aFF.middlename));$("#ff_lastname").val(decrypt(g_aFF.lastname));
$("#ff_lastname2").val(decrypt(g_aFF.lastname2));$("#ff_lastnameja1").val(decrypt(g_aFF.lastname));$("#ff_lastnameja2").val(decrypt(g_aFF.lastname2));$("#ff_lastnameja3").val(decrypt(g_aFF.lastname3));$("#ff_username").val(decrypt(g_aFF.username));$("#ff_gender").val(decrypt(g_aFF.gender));$("#ff_ssn").val(decrypt(g_aFF.ssn));$("#ff_company").val(decrypt(g_aFF.company));$("#ff_address1").val(decrypt(g_aFF.address1));$("#ff_address2").val(decrypt(g_aFF.address2));$("#ff_address3").val(decrypt(g_aFF.address3));
$("#ff_city").val(decrypt(g_aFF.city));$("#ff_county").val(decrypt(g_aFF.county));var b=decrypt(g_aFF.state);"dummy3"==b&&(b="");$("#ff_state option").each(function(){var a=$(this);if("CUSTOM"!=b&&a.val()==b&&a.text()!=g_DUMMYSTATE)return a.attr("selected",!0),!1});$("#ff_state").val("CUSTOM");$("#ff_statecustom").val(b);ff_state_changed();$("#ff_zip").val(decrypt(g_aFF.zip));""!=g_aFF.country&&$("#ff_country").val(decrypt(g_aFF.country));""!=g_aFF.timezone&&$("#ff_timezone").val(decrypt(g_aFF.timezone));
$("#ff_email").val(decrypt(g_aFF.email));$("#ff_mobileemail").val(decrypt(g_aFF.mobileemail));ff_setphone("phone",g_aFF);ff_setphone("eve",g_aFF);ff_setphone("fax",g_aFF);ff_setphone("mobile",g_aFF);$("#ff_ccname").val(decrypt(g_aFF.ccname));$("#ff_ccnum").val(decrypt(g_aFF.ccnum));$("#ff_cccsc").val(decrypt(g_aFF.cccsc));$("#ff_ccissuenum").val(decrypt(g_aFF.ccissuenum));$("#ff_bankname").val(decrypt(g_aFF.bankname));$("#ff_bankacctnum").val(decrypt(g_aFF.bankacctnum));$("#ff_bankroutingnum").val(decrypt(g_aFF.bankroutingnum));
$("#ff_notes").val(decrypt(g_aFF.notes));a=g_aCustomFields.length;for(i=0;i<a;++i){var c=decrypt(g_aCustomFields[i].text),d=decrypt(g_aCustomFields[i].textalt),e=decrypt(g_aCustomFields[i].value);""!=d&&(c+="\n"+d);$("#ff_customtext"+i).val(c);$("#ff_customvalue"+i).val(e)}}
function pff_save_edit(){if(!bg.lploggedin)return!1;if(""==$("#ff_name").val())return $("#ff_name").css("background","#FFCBD6").focus().select(),!1;if(!ff_checkemail()||!ff_checkphonenumber("phone")||!ff_checkphonenumber("eve")||!ff_checkphonenumber("fax")||!ff_checkphonenumber("mobile")||!ff_checkbirthday()||!ff_checkccnum()||!ff_checkccstart()||!ff_checkccexp()||!ff_checkcccsc()||!ff_checkccissuenum()||!ff_checkbankacctnum()||!ff_checkbankroutingnum()||!ff_checkcustom()||!ff_checkcreditmon())return!1;
if(!$("#ff_creditmon").attr("checked"))return pff_save_edit2(),!1;ff_creditmon("edit")}
function pff_save_edit2(){var a=ff_getalldata(),b={};for(i in a)b[i]=encrypt(a[i]);b.type=g_ff_type;b["protected"]=$("#ff_protected").attr("checked")?1:0;b.creditmon=$("#ff_creditmon").attr("checked")?1:0;var c=ff_convertdata(b);c.ffid=g_aFF.ffid;c.deleteext=0;b=c;b.decprofilename=a.name;b.cmd="edit";b=null;g_mobileenc=!0;a=ff_getalldata();b={};for(i in a)b[i]=encrypt(a[i]);b.type=g_ff_type;b["protected"]=$("#ff_protected").attr("checked")?1:0;b.creditmon=$("#ff_creditmon").attr("checked")?1:0;b=
ff_convertdata(b);"undefined"!=typeof g_aFF.sharefolderid&&(b.sharefolderid=g_aFF.sharefolderid);b.group="undefined"!=typeof g_aFF.group?g_aFF.group:"";b.pwprotect="on"==b.pwprotect?!0:!1;b.creditmon="on"==b.creditmon?!0:!1;b.ffid=g_aFF.ffid;b.deleteext=0;b.decprofilename=a.name;b.cmd="edit";g_mobileenc=!1;bg.addeditformfill(c,b);setTimeout(function(){getBG().closecurrenttab("formfill.html")},0);return!1}
function ff_setphone(a,b){var c=decrypt(b["tel"+a]).replace(/\D/g,""),d=decrypt(b["tel3l"+a]),e=decrypt(b["telext"+a]).replace(/\D/g,"");$("#ff_ext"+a).val(e);if("undefined"!=typeof g_cc3lphone_map[d]){var e=g_cc3lphone_map[d],c=c.substring(e.length),g=$("#ff_country"+a),f=$("#ff_dom"+a),k=$("#ff_npa"+a),n=$("#ff_nxx"+a),l=$("#ff_xxxx"+a),m=$("#ff_int"+a),h=$("#ff_intcc"+a),p=$("#ff_intnum"+a);g.val(d);"1"==e?(m.hide(),f.show(),k.val(c.substring(0,3)),n.val(c.substring(3,6)),l.val(c.substring(6,10))):
(f.hide(),m.show(),h.val(e),p.val(c));fix_phone($("#ff_country"+a))}}var g_creditmonfrom=null;
function ff_creditmon(a){g_creditmonfrom=a;var b=ff_getval("#ff_firstname","#ff_firstnameja1"),c=ff_getval("#ff_lastname","#ff_lastnameja1"),d=ff_getbirthday(),e=$("#ff_ssn").val(),g=$("#ff_address1").val(),f=$("#ff_address2").val(),k=$("#ff_address3").val();$("#ff_city").val();"CUSTOM"==$("#ff_state").val()?$("#ff_statecustom").val():$("#ff_state").val();$("#ff_country").val();$("#ff_zip").val();var n=ff_getprettyphone(ff_getphonenumber("phone"));a=document.createElement("div");a.className="creditmondiv";
var l=document.createElement("table");l.className="creditmontable";var m=document.createElement("tr"),h=document.createElement("td");h.className="creditmontd";set_innertext(h,"Name");m.appendChild(h);h=document.createElement("td");h.className="creditmontd2";set_innertext(h,b+" "+c);m.appendChild(h);l.appendChild(m);m=document.createElement("tr");h=document.createElement("td");h.className="creditmontd";set_innertext(h,"Birthday");m.appendChild(h);h=document.createElement("td");h.className="creditmontd2";
set_innertext(h,d);m.appendChild(h);l.appendChild(m);m=document.createElement("tr");h=document.createElement("td");h.className="creditmontd";set_innertext(h,"Social Security Number");m.appendChild(h);h=document.createElement("td");h.className="creditmontd2";set_innertext(h,e);m.appendChild(h);l.appendChild(m);m=document.createElement("tr");h=document.createElement("td");h.className="creditmontd";set_innertext(h,"Phone Number");m.appendChild(h);h=document.createElement("td");h.className="creditmontd2";
set_innertext(h,n);m.appendChild(h);l.appendChild(m);m=document.createElement("tr");h=document.createElement("td");h.className="creditmontd";set_innertext(h,"Address");m.appendChild(h);h=document.createElement("td");h.className="creditmontd2";b=g;""!=f&&(b+=", "+f);""!=k&&(b+=", "+k);set_innertext(h,b);m.appendChild(h);l.appendChild(m);a.appendChild(l);f=[];k=document.createElement("div");k.className="creditmondiv2";l=document.createElement("div2");l.className="creditmondiv2";l.appendChild(document.createTextNode("Only the below information will be sent to LastPass."));
l.appendChild(document.createElement("br"));l.appendChild(document.createTextNode("Other confidential Form Fill Profile information, such as credit card numbers, will not be sent."));k.appendChild(l);k.appendChild(document.createElement("br"));k.appendChild(a);k.appendChild(document.createElement("br"));l=document.createElement("div");l.className="creditmondiv4";l.appendChild(document.createTextNode("I have read and agree with the "));a=document.createElement("a");a.setAttribute("target","_blank");
a.setAttribute("href","https://lastpass.com/creditmonitoring.php?cmd=showterms");set_innertext(a,"LastPass Terms and Conditions");l.appendChild(a);k.appendChild(l);f.push(k);f.push(document.createElement("br"));a=document.createElement("form");a.id="lpform2";k=document.createElement("input");k.setAttribute("type","submit");k.id="ffiagree";k.setAttribute("value","I AGREE");a.appendChild(k);a.appendChild(document.createTextNode("\u00a0\u00a0\u00a0"));k=document.createElement("input");k.setAttribute("type",
"submit");k.id="ffidonotagree";k.setAttribute("value","I DO NOT AGREE");a.appendChild(k);f.push(a);dialog_show(f,!1);document.getElementById("lpform2")&&(document.getElementById("lpform2").onsubmit=function(){return!1});document.getElementById("ffiagree").addEventListener("click",function(){ff_creditmon2()});document.getElementById("ffidonotagree").addEventListener("click",function(){dialog_hide()});return!1}
function ff_creditmon2(){$("#ffiagree").attr("disabled","true").hide();$("#ffidonotagree").attr("disabled","true").hide();var a=ff_getval("#ff_firstname","#ff_firstnameja1"),b=ff_getval("#ff_lastname","#ff_lastnameja1"),c=ff_getbirthday(),d=$("#ff_ssn").val(),e=$("#ff_address1").val(),g=$("#ff_address2").val(),f=$("#ff_address3").val(),k=$("#ff_city").val(),n="CUSTOM"==$("#ff_state").val()?$("#ff_statecustom").val():$("#ff_state").val(),l=$("#ff_country").val(),m=$("#ff_zip").val(),h=ff_getphonenumber("phone"),
a={cmd:"enroll",firstname:a,lastname:b,birthday:c,ssn:d,address1:e,address2:g,address3:f,city:k,state:n,country:l,zip:m,phone:h,ffid:g_aFF&&"undefined"!=typeof g_aFF.ffid?g_aFF.ffid:"0"};g_aFF&&"undefined"!=typeof g_aFF.sharefolderid&&(a.sharedfolderid=g_aFF.sharefolderid);var c=b="",p;for(p in a)b+=c+encodeURIComponent(p)+"="+encodeURIComponent(a[p]),c="&";getBG().enable_credit_monitoring(b,function(a){a=JSON.parse(a.responseText);if(!0!=a.success){0<a.reason2.indexOf("enrollment error")||0<a.reason2.indexOf("monitoring failed")?
alert("ERROR: Credit monitoring could not be enabled.\n\nLastPass could not find credit data based on the information you entered.\n\nPlease double check the entered information and try again.\nIf you are under the age of 18, then it likely that you do not have any credit data.\n\n"+a.reason2):""!=a.reason2?alert("ERROR: An error occurred.\n\n"+a.reason2):alert("ERROR: An error occurred while attempting to contact the LastPass server.");dialog_hide();var b=[];"Zip code does not match state."==a.reason2?
(a="ff_tabaddress",ffshow(a),$("#"+a).click(),b.push("ff_state"),b.push("ff_statecustom"),b.push("ff_zip")):-1!=a.reason2.indexOf("You have another Fill Form profile with an identical SSN")&&(a="ff_tabpersonal",ffshow(a),$("#"+a).click(),b.push("ff_ssn"));for(a=0;a<b.length;++a)$("#"+b[a]).css("background","#FFCBD6").focus().select()}else alert("Credit monitoring is now enabled for your account!\n\nWe will now continuously monitor for changes in your credit report. If we detect a change, we will send you an alert to notify you.\n\nIf you receive an alert from us, you can view intricate details of the alert by upgrading to LastPass Premium credit monitoring or can consider requesting a free annual credit report to obtain further details."),
ff_creditmon3("undefined"!=typeof a.newffid?a.newffid:"",a.subscriberid)},function(){alert("ERROR: The LastPass server could not be contacted.");dialog_hide()})}function ff_creditmon3(a){if("add"==g_creditmonfrom)return pff_save_add2(a);if("edit"==g_creditmonfrom)return pff_save_edit2()}function encrypt(a){return g_mobileenc?bg.lpmenc_acct(a,!0,g_aFF?g_aFF:{},bg.g_shares):bg.lpenc_acct(a,g_aFF?g_aFF:{},bg.g_shares)}function decrypt(a){return bg.lpmdec_acct(a,!0,g_aFF?g_aFF:{},bg.g_shares)}
Array.prototype.remove=function(a,b){var c=this.slice((b||a)+1||this.length);this.length=0>a?this.length+a:a;return this.push.apply(this,c)};function trunc(a,b){return a.length<=b?a:a.substr(0,b)+"..."}function hover_checkmouseenter(a,b){if(a.contains&&b.fromElement)return!a.contains(b.fromElement);if(b.relatedTarget)return!hover_contains(a,b.relatedTarget)}
function hover_checkmouseleave(a,b){if(a.contains&&b.toElement)return!a.contains(b.toElement);if(b.relatedTarget)return!hover_contains(a,b.relatedTarget)}function hover_contains(a,b){var c=!1;do{if(c=a==b)break;if("undefined"==typeof b.parentNode)break;b=b.parentNode}while(null!=b);return c}
function populateselect(a,b,c){var d,e=null;LP_decimate_children(document.getElementById(a));for(d in b){var e=null==e&&null!=c&&d==c?"selected":"",g=document.createElement("option");g.setAttribute("value",d);""!=e&&g.setAttribute("selected",e);set_innertext(g,b[d]);document.getElementById(a).appendChild(g)}}
function populateselectex(a,b,c){var d=document.getElementById(a).selectedIndex,e,g,f,k;LP_decimate_children(document.getElementById(a));for(e in b)if("remove"!=e){for(g in b[e])f=g,k=b[e][g];var n=document.createElement("option");n.setAttribute("value",f);null!=c&&f==c&&n.setAttribute("selected","selected");set_innertext(n,k);document.getElementById(a).appendChild(n)}0<=d&&(document.getElementById(a).selectedIndex=d)}
fix_states=function(){var a=document.getElementById("ff_state"),b=a.value;"CUSTOM"==b&&(b=document.getElementById("ff_statecustom").value);if(0==states["en-US"].length){states["en-US"]=[];for(var c=4;c<a.options.length;c++)states["en-US"].push([a.options[c].value,a.options[c].text])}a.options.length=4;for(var d="undefined"!=typeof states[getlocale()]&&0<states[getlocale()].length?states[getlocale()]:states["en-US"],e=!1,c=0;c<d.length;c++)a.options[a.options.length]=new Option(d[c][1],d[c][0]),d[c][0]==
b&&(a.selectedIndex=a.options.length-1,e=!0);document.getElementById("ff_statecustom").value=e?"":b;e||(a.selectedIndex=""!=b?2:0);ff_state_changed();"ff_tabaddress"==g_ff_selectedtabid&&(ffshow("ff_panenotes"),ffshow("ff_paneaddress"))};
