function hasNever(a,b,d,c){if("undefined"==typeof g_neverurls||null===g_neverurls)g_neverurls={};var f=a=lpcanonizeUrl(a);0<a.length&&"/"==a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));if(g_neverurls[d]&&0<g_neverurls[d].length){for(var e=!1,g=0;g_neverurls[d]&&g<g_neverurls[d].length;g++){var h=g_neverurls[d][g];if(h==b||h==a){e=!0;break}}if(!e)return!0}for(g=0;g_neverurls[c]&&g<g_neverurls[c].length;g++)if(h=g_neverurls[c][g],h==b||h==a||h==f)return!0;return!1}
function hasNeverAutologin(a,b){return hasNever(a,b,"onlyautologins","neverautologins")}function hasNeverFormFill(a,b){return hasNever(a,b,"onlyformfills","neverformfills")}function hasNeverSave(a,b){return hasNever(a,b,"onlyaccounts","neveraccounts")}function hasNeverShowIcon(a,b){return hasNever(a,b,"onlyshowicons","nevershowicons")}function hasNeverGenerate(a,b){return hasNever(a,b,"onlygenerates","nevergenerates")}
function hasNeverEnableLP(a,b){return hasNever(a,b,"onlyenablelp","neverenablelp")}function hasNeverMPReuse(a,b){return hasNever(a,b,"onlympwreuse","nevermpwreuse")}var g_accessibility_enabled=-1;
function handleFill(a,b){var d=!1,c=null;if((!lploggedin||null!=grid_getdata("active"))&&!skiplogin()||("undefined"==typeof b||!b)||!check_for_frame_mismatch_ok(a,b.fromiframe,gs("Are you sure you would like your LastPass site information to be filled into the following site?"),b.cmd))return!1;g_fillfield_did_fillbest[a.toString()]=!1;if("autofillaid"==b.cmd||"autologinaid"==b.cmd){var f=b.aid;g_last_launch[f]=(new Date).getTime();if("undefined"!=typeof g_sites[f]){var d="autologinaid"==b.cmd,e=!0,
g=get_record(f);b.no_manualfill_on_saveall&&g.save_all&&(e=!1);b.from_iframe&&!g.save_all&&(e=!0);c=b.from_iframe?!0:!1;g_fillfield_confirm_perfield={};fill({tabid:a,acct:g_sites[f],docid:null,submit:d,doconfirm:!d,docnum:"all",allowforce:!0,skip_pwprotect:!1,manualfill:e,automaticallyFill:null,skip_basicauth:null,from_iframe:c,desc:b.cmd});return!0}return!1}if("undefined"==typeof b.url)return!1;"undefined"!=typeof b.username_val&&(g_username_vals[b.url]=b.username_val);var e=b.url,h=lp_gettld_url(e),
k=0;if(null===b.aid||"undefined"==typeof b.aid)if(g=getcsinfo(a,g_CS_tops[a]))k=g.lastfill_aid,0<k&&console_warn("initiating fill without aid but PRIOR FILL was done for "+k);if(lp_url_is_lastpass(e))return!1;if("undefined"==typeof g_launches[a]||!g_launches[a])null!=g_pending_launch&&(g_launches[a]=g_pending_launch);"undefined"!=typeof g_launches[a]&&g_launches[a]&&(f=g_launches[a],"undefined"!=typeof g_sites[f]&&(g=get_record(f),g_fillfield_confirm_perfield={},check_ident_aid(f)&&compare_tlds(h,
lp_gettld_url(g_sites[f].url))&&(is_guiless()?fill({tabid:a,acct:g,docid:null,submit:!1,doconfirm:!1,docnum:"all",allowforce:!0,skip_pwprotect:!1,manualfill:!1,automaticallyFill:!1,desc:"FILL_F2"}):(c=b.from_iframe?!0:!1,fill({tabid:a,acct:g,docid:null,submit:!0,doconfirm:!1,docnum:b.docnum,allowforce:!1,skip_pwprotect:!0,manualfill:null,automaticallyFill:null,skip_basicauth:null,from_iframe:c,desc:"FILL_F3"}),c=f),"undefined"!=typeof b.numpass&&0<b.numpass?g_pending_launch=g_launches[a]=null:setTimeout(function(){g_pending_launch=
g_launches[a]=null},1E3))));var r=getsites(h),r=reorderOnURL(r,e,!0);hasNeverAutologin(e,h)&&(r=[]);g=b.topurl!=e?lp_gettld_url(b.topurl):"";""!=g&&hasNeverAutologin(b.topurl,g)&&(r=[]);for(var p in r){try{if(islastpass&&g_ischrome&&!g_isedge&&1==r[p].basic_auth&&0>=g_accessibility_enabled&&0==lpGetPref("basicauthnever",0))if(g_is_mac&&have_binary_function("accessibility_enabled"))call_binary_function("accessibility_enabled",function(a){g_accessibility_enabled=a?1:0;0==g_accessibility_enabled&&setTimeout(function(){get_selected_tab(null,
function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:0,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to enable access for assistive devices."),do_40notify:g_40notify})})},100)});else if((g_is_win||g_is_mac)&&!have_binary())g_accessibility_enabled=0,setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:1,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome."),
do_40notify:g_40notify})})},100)}catch(t){}h=!1;f=r[p].aid;if(check_ident_aid(f)&&"undefined"!=typeof g_sites[f]&&(g=get_record(f))){g.never_autofill&&(h=!0);if(g.pwprotect||g_prompts.login_site_prompt)h=!0;if(!g.genpw&&!(0==g.fields.length&&""==g.username)){0==g.url.indexOf("https://")&&0!=e.indexOf("https://")&&(h=!0);g_fillfield_confirm_perfield={};0==parseInt(lpGetPref("automaticallyFill",1))&&0==parseInt(lpGetPref("highlightFields",1))&&(h=!0);if(!h){if(c&&c!=f){verbose_log("did_launched_aid != aid "+
c+"!="+f);continue}if(0<k&&f!=k){console_warn("IGNORING non-aid fill; would fill and override previous fill "+f+"!="+k);continue}if(f=!g.save_all)"undefined"==typeof g_fillfieldsmatches[e]&&(g_fillfieldsmatches[e]=[]),g_fillfieldsmatches[e][g_fillfieldsmatches[e].length]=g,g_fillfieldsmatchescurridx[e]=0;k=parseInt(lpGetPref("automaticallyFill",1));fill({tabid:a,acct:g,docid:b.docid,submit:null,doconfirm:f,docnum:b.docnum,allowforce:null,skip_pwprotect:!0,manualfill:null,automaticallyFill:k,desc:"FILL_F4"})}0!=
lpGetPref("showFillNotificationBar",1)&&(get_selected_tab(null,function(){sendCS(a,{cmd:"showfillnotification",text:gs("LastPass has filled your login information into the form on this page."),sites:cache_usernames(r),docnum:b.docnum,do_40notify:g_40notify})}),d=!0);break}}}!d&&0==lpGetPref("showNotificationsAfterClick",1)&&checkgenpwfillforms(a,e);return!0}
function checkWeakDuplicateBreached(a,b,d){if(g_showweakdupalerts&&qualifyForWeakCheck(getpasswordfromacct(a))&&(g_ischrome||g_issafari||g_isfirefoxsdk))!1==g_disablepwalerts&&("undefined"==typeof a.noalert||"1"!=a.noalert)&&getWeakAndDuplicateIds(g_username_hash,g_username,function(c){var f=null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?1:0,e=issharedfolder(g_shares,a.group),e=!checkreadonly(e,!0),f=!f&&!e&&"1"==a.pwch?1:0;isBreachedSite(a)?(g_notification_type=
"lpalert",g_badgedata={cmd:"notification",type:"lpalert"},g_notification_data={cmd:"notification",type:"lpalert",data:{lpa_title:gs("This site was affected by a breach!"),lpa_msg:gs("The account you are logging into was either hacked or was reusing a password a password from a site that was hacked. You should take action now to change this password"),lpa_secondary_msg:gs("Use the Security Challenge to see other affected sites"),lpa_onclicktext:gs("Change Passwords Now"),lpa_onclickurl:base_url+"misc_challenge.php?breachid="+
a.breached}},set_badge(g_notification_data,b),drawIconAtRotation(0)):isDuplicateSite(c[0],a.aid)?(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:a.aid,name:a.name,username:getusernamefromacct(a),alerttype:"duplicate",tld:d,tabid:b,pwch:f},set_badge(g_notification_data,b),drawIconAtRotation(0)):isWeakPassword(c[1],a.aid)&&(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:a.aid,name:a.name,username:getusernamefromacct(a),alerttype:"weak",
tld:d,tabid:b,pwch:f},set_badge(g_notification_data,b),drawIconAtRotation(0))})}
function checkgenpwfillforms(a,b,d){var c=lp_gettld_url(b),f=1!=lpGetPref("showGenerateNotifications",1)||hasNeverGenerate(b,c),e=1!=lpGetPref("showFormFillNotifications",1)||hasNeverFormFill(b,c),g=[];if(do_experimental_popupfill){for(var h=0;h<g_formfills.length;h++)check_ident_ffid(g_formfills[h].ffid)&&(g[g.length]=g_formfills[h]);0==g.length&&(e=!0);b={cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:e,sites:cache_usernames(reorderOnURL(getsites(c),b,!0,!0)),formfills:LPJSON.stringify(g),
active:g_popupfill_last_active[a],activefieldid:g_popupfill_last_active_fieldid[a]};d||(b.ff=g_cachedffdat);sendCS(a,b,"all")}else{if(!e){for(h=0;h<g_formfills.length;h++)check_ident_ffid(g_formfills[h].ffid)&&(g[g.length]=g_formfills[h]);0==g.length&&(e=!0)}if(!f||!e)b={cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:e,sites:cache_usernames(reorderOnURL(getsites(c),b,!0,!0)),formfills:LPJSON.stringify(g)},d||(b.ff=g_cachedffdat),sendCS(a,b,"all")}}
function cache_usernames(a){for(var b in a)a[b].useusername=getusernamefromacct(a[b]);return LPJSON.stringify(a)}
function handleNever(a,b){if("neverautofill"==b.cmd){var d=b.aid;if("undefined"==typeof g_sites[d])return;g_sites[d].never_autofill=!0;g_sites[d].autologin=!1;d="aid="+en(d);lpMakeRequest(base_url+"set_never_autofill.php",d,null,null)}else if("neverdomain"==b.cmd||"neverpage"==b.cmd){var c="neverdomain"==b.cmd?lp_gettld_url(b.url):lpcanonizeUrl(b.url),d="url="+en(AES.url2hex(c));"undefined"!=typeof b.fromsave&&b.fromsave?g_neverurls.neveraccounts.push(c):"undefined"!=typeof b.fromgenerate&&b.fromgenerate?
(d+="&type=1",g_neverurls.nevergenerates.push(c)):"undefined"!=typeof b.fromformfill&&b.fromformfill?(d+="&type=2",g_neverurls.neverformfills.push(c)):"undefined"!=typeof b.fromshowicons&&b.fromshowicons?(d+="&type=6",g_neverurls.nevershowicons.push(c)):"undefined"!=typeof b.neverforall&&b.neverforall?(g_neverurls.neveraccounts.push(c),g_neverurls.nevergenerates.push(c),g_neverurls.neverformfills.push(c),g_neverurls.neverautologins.push(c),g_neverurls.nevershowicons.push(c),d+="&type=7"):"undefined"!=
typeof b.neverenablelp&&b.neverenablelp?(g_neverurls.neverenablelp.push(c),d+="&type=8"):(d+="&type=3",g_neverurls.neverautologins.push(c));lpMakeRequest(base_url+"add_never.php",d,null,null)}g_local_accts_version++;rewritelocalfile()}
function handleSave(a,b){function d(a){if(!a)return!1;var b=["text","email","tel","url"],c;for(c in b)if(b.hasOwnProperty(c)&&a==b[c])return!0;return!1}var c=!1;if(g_cpwbot&&CPWbot_bg&&a==CPWbot_bg.get_pwchangetabid())return L("handleSave(tab:"+a+", state="+CPWbot_bg.g_pwchangestate+")"),console_log("Skipping save because driving a password change"),!1;var f=get_ff_translation("ff_currpass_regexp");if("undefined"==typeof SAVEALLFORMSUBMITS&&(!lploggedin||lp_url_is_lastpass(b.url,!0)||lp_url_is_lastpassext(b.url)))return!1;
for(var e=b.formdata.split("\n"),g=!1,h=!1,k=null,r="",p="",t=[],j=[],s=0,v=0,m=0,l=0,y=0,x=0;x<e.length;x++){var n=e[x].split("\t");if(!(4!=n.length&&5!=n.length)){decodeURIComponent(n[2]);var q=n[3];"password"==q?s++:"hidden"==q?y++:d(q)&&v++;"password"==q&&(5>n.length||5<=n.length&&"seen"==n[4])?m++:d(q)&&(5>n.length||5<=n.length&&"seen"==n[4])&&l++}}for(v=0;v<e.length;v++)if(l=e[v],l=l.split("\t"),!(4!=l.length&&5!=l.length)){n=decodeURIComponent(l[2]);y=l[3];x=!0;g&&(5<=l.length&&"notseen"==
l[4])&&(x=!1);if((!g||!h)&&d(y)&&0<n.length)x&&(r=n,g=!0),!1==h&&"undefined"!=typeof SpecialSites[lpcanonizeUrl(b.url)]&&(h=!0);if(!("password"==y&&5<=l.length&&"notseen"==l[4]&&1<s&&0<m)&&"password"==y&&(x||!1==h))if(x=decodeURIComponent(l[1]),t[j.length]={name:x,value:n},j[j.length]=n,!h&&n.length&&(p=n,h=!0),null==k&&(n=RegExp(f,"i"),x&&(x==b.current_pw_field_name||n.exec(x))))k=j.length-1}if(h){b.username=r;b.password=p;!g&&1<j.length&&(j[0]!=j[1]&&null==k)&&(b.username=j[0],b.password=j[1]);
f=lp_gettld_url(b.url);b.tld=f;h=null;l=!1;m=s="";1<j.length&&j[j.length-1]==j[j.length-2]&&""!=j[j.length-1]&&t[j.length-1].name!=t[j.length-2].name?(l=!0,s=j[j.length-1],h=1,3==j.length&&(j[0]!=j[1]&&j[1]==j[2])&&(m=j[0])):1<j.length&&j[0]==j[1]&&""!=j[0]&&t[0].name!=t[1].name?(l=!0,s=j[0],h=2):1<j.length&&(j[0]!=j[1]&&""!=j[0]&&null!=k)&&(0==k&&2==j.length?(s=j[1],h=3):1==k&&2==j.length?(s=j[0],h=4):(s="",h=6));t=l||null!=k&&s;k=[];if(t&&(k=getsites(f,!0),b.createacct=2==j.length||0<array_length(k),
b.createacct)){for(var B=q="",w="",D="",v=0;v<e.length&&!(l=e[v],l=l.split("\t"),!(4!=l.length&&5!=l.length)&&(y=l[3],""==q&&(d(y)&&""!=l[1]&&""!=l[2])&&(x=decodeURIComponent(l[1]),n=get_ff_translation("ff_username_regexp"),""!=n&&(n=RegExp(n,"i"),n.exec(x)&&(q=x,B=decodeURIComponent(l[2])))),""==w&&(d(y)&&""!=l[1]&&""!=l[2])&&(x=decodeURIComponent(l[1]),y=get_ff_translation("ff_email_regexp"),""!=y&&(n=RegExp(y,"i"),n.exec(x)&&(w=x,D=decodeURIComponent(l[2])))),""!=q&&""!=w));v++);""==q&&(q=w,B=
D);b.username_field=q;""!=B&&(b.username=B)}if(t&&0<array_length(k)){if(verbose_log("looking for newpw="+(g_show_pw_in_logs||g_isadmin?s:"REDACTED")+" tld="+f+" in g_didchangepw"),g="undefined"!=typeof g_didchangepw[SHA256(s+f)]&&g_didchangepw[SHA256(s+f)]>(new Date).getTime()-6E5,verbose_log("already processed pw ="+(g_show_pw_in_logs||g_isadmin?s:"REDACTED")+" tld="+f+" is "+g),!g&&(g_notification_type="change",b.newpw=s,b.oldpw=m,g_notification_data=b,sendTS({cmd:"notification",type:"change"}),
c=!0,0!=lpGetPref("showChangeNotificationBar",1))){var e=k,u;b.sitecount=array_length(e);if(1==array_length(e))for(v in e){b.singleaid=v;u=gs("LastPass detected a password change for user:")+" "+getusernamefromacct(g_sites[v]);break}else u=gs("LastPass detected a password change for domain:")+" "+f;sendCS(a,{cmd:"showchangenotification",text:u,notificationdata:b,do_40notify:g_40notify});g_persistent_notifications[a]={cmd:"showchangenotification",text:u,notificationdata:b,do_40notify:g_40notify};write_history({cmd:"showchangenotification",
aid:b.singleaid,spin:h,tld:b.tld,url:b.url,msg:u})}}else{if(hasNeverSave(b.url,f)||("undefined"!=typeof b.topdocurl&&hasNeverSave(b.topdocurl),lp_gettld_url(b.topdocurl)))return!1;var e=getsites(f),z;for(z in e)if(check_ident_aid(z)&&"undefined"!=typeof g_sites[z]&&(u=get_record(z),e=getusernamefromacct(u),v=getpasswordfromacct(u),(!g||r==lpmdec_acct(u.username,!0,u,g_shares)||value_is_masked(r)||r==e)&&(p==lpmdec_acct(u.password,!0,u,g_shares)||p==v)||(u.save_all&&isMatch(u,g,r,p)||r==lpmdec_acct(u.username,
!0,u,g_shares)&&""==p)||g&&(r==lpmdec_acct(u.username,!0,u,g_shares)||value_is_masked(r)||r==e)&&j&&2==j.length&&(j[0]==lpmdec_acct(u.password,!0,u,g_shares)||j[1]==lpmdec_acct(u.password,!0,u,g_shares))&&(p===j[0]||p===j[1])))return!1;g_notification_type="save";g_notification_data=b;0!=lpGetPref("showSaveSiteNotifications",0)&&(sendTS({cmd:"notification",type:"save"}),c=!0);0!=lpGetPref("showSaveNotificationBar",1)&&lpCheckAddSite(b.username,b.password,f)&&(u=gs("Should LastPass remember this password?"),
g_persistent_notifications[a]={cmd:"showaddnotification",text:u,notificationdata:LPJSON.stringify(b),do_40notify:g_40notify,tutorialData:g_introTutorialStatus.getInternalData()},sendCS(a,{cmd:"showaddnotification",text:u,notificationdata:LPJSON.stringify(b),do_40notify:g_40notify,tutorialData:g_introTutorialStatus.getInternalData()},"streetscape.com"==f?"all":null),write_history({cmd:"showaddnotification",username:b.username,tld:f,url:b.url,msg:u,spin:null}),c=!0)}}return c}
function lpCheckAddSite(a,b,d){var c=lp_get_gmt_timestamp(),f=[],e;for(e in g_rejectedaddsites){var g=g_rejectedaddsites[e];c>g.rejectedTime+600&&(f[f.length]=e)}for(e=f.length-1;0<=e;e--)g_rejectedaddsites.splice(f[e],1);for(e in g_rejectedaddsites)if(g=g_rejectedaddsites[e],g.username==a&&lpdec(g.encryptedPassword)==b&&compare_tlds(g.tld,d))return!1;return!0}var lastupdatefields="";
function handleUpdateFields(a,b){var d=b.aid,c=g_sites[d];if(!c)return!1;var f=issharedfolder(g_shares,c.group);if(!checkreadonly(f,!0))return!1;var e=[],g=[],h=updateAndEncryptData(b.formdata,e,g,c),k=SHA256(h);if(k==lastupdatefields)return!1;lastupdatefields=k;update_username_from_fields_if(c,e);for(k=c.fields.length-1;0<=k;k--)!c.fields[k].otherfield&&"1"!=c.fields[k].otherlogin&&c.fields.splice(k,1);for(k=0;k<e.length;k++)c.fields[c.fields.length]=e[k];g_local_accts_version++;rewritelocalfile();
d="data="+en(bin2hex(h))+"&ref="+en(url2hex(b.url))+"&updatefields=1&aid="+en(d);d+=!1==f?"":"&sharedfolderid="+en(f.id);c.postdata=d;c.posturl=base_url+"gm_deliver.php";c.newvalues=g;updateFieldsFromSubmit(d,c);return!0}
function handleAddUrid(a,b){var d=b.aid,c=g_sites[d],f=issharedfolder(g_shares,c.group);if(checkreadonly(f,!0)){for(var e=[],g=0;g<c.fields.length;g++)"1"==c.fields[g].otherlogin&&!lp_in_array(c.fields[g].urid,e)&&(e[e.length]=c.fields[g].urid);if(!(10<=e.length)){var h=[],e=[],k=updateAndEncryptData(b.formdata,h,e,c);update_username_from_fields_if(c,h);for(g=0;g<h.length;g++)h[g].otherlogin="1",h[g].url=url2hex(b.url),c.fields[c.fields.length]=h[g];g_local_accts_version++;rewritelocalfile();d="data="+
en(bin2hex(k))+"&ref="+en(url2hex(b.url))+"&addurid=1&aid="+en(d);d+=!1==f?"":"&sharedfolderid="+en(f.id);c.postdata=d;c.posturl=base_url+"gm_deliver.php";c.newvalues=e;updateFieldsFromSubmit(d,c)}}}
function update_username_from_fields_if(a,b){for(var d=get_ff_translation("ff_combineddummy_regexp"),c=RegExp(d,"i"),f=0,d="",e=0;e<b.length;e++)if("text"==b[e].type||"email"==b[e].type||"tel"==b[e].type||"url"==b[e].type)if(!c.exec(b[e].name)&&!c.exec(b[e].id)&&!("answer"==b[e].id||"answer"==b[e].name))if(d=b[e].value,2<=++f)break;if(1==f&&""!=d){for(e=c=0;e<a.fields.length;e++)if(!a.fields[e].otherfield&&("text"==a.fields[e].type||"email"==a.fields[e].type||"tel"==a.fields[e].type||"url"==a.fields[e].type)){c++;
break}0==c&&(a.username=d,a.unencryptedUsername=lpdec_acct(crypto_btoa(a.username),a,g_shares))}}function handleSaveAll(a,b){b.save_all=1;g_site_data=b;VaultToggle.useVault4_0()?LPPlatform.openTabDialog("site",{saveAllData:b}):openURL(getchromeurl("site.html"))}
function isMatch(a,b,d,c){b=b?!1:!0;for(var f=!1,e=0;e<a.fields.length;e++)if(!("text"!=a.fields[e].type&&"password"!=a.fields[e].type&&"email"!=a.fields[e].type&&"tel"!=a.fields[e].type&&"url"!=a.fields[e].type)){var g=lpmdec_acct(a.fields[e].value,!0,a,g_shares);if(("text"==a.fields[e].type||"email"==a.fields[e].type||"tel"==a.fields[e].type||"url"==a.fields[e].type)&&d==g)b=!0;"password"==a.fields[e].type&&c==g&&(f=!0)}return b&&f?!0:!1}var g_reqindex=0;
function fill(a){var b=a.tabid,d=a.acct;if(null==b||!d)return!1;var c=a.docid,f=a.submit,e=a.doconfirm,g=a.docnum,h=a.allowforce,k=a.skip_pwprotect,r=a.skip_basicauth,p=a.from_iframe,t=a.desc,j=a.manualfill;j||(j=!1);var s=a.automaticallyFill;if("undefined"==typeof s||null==s)s=1;write_history({cmd:t,tabid:b,docnum:g,aid:d.aid,submit:f,doconfirm:e,allowforce:h});verbose_log("tabid="+b+"\nacct.aid="+d.aid+"\ndocid="+c+"\nsubmit="+f+"\ndoconfirm="+e+"\ndocnum="+g+"\nallowforce="+h+"\nskip_pwprotect="+
k+"\nmanualfill="+j+"\nautomaticallyFill="+s+"\nskip_basicauth="+r+"\nfrom_iframe="+p+"\ndesc="+t);var v=!1,m=!1,l=!1,y=0;!k&&(d.pwprotect||g_prompts.login_site_prompt)?(console_log("FILL : Showing Security Prompt"),security_prompt(function(){setTimeout(function(){var a=get_record(d.aid);fill({tabid:b,acct:a,docid:c,submit:f,doconfirm:e,docnum:g,allowforce:h,skip_pwprotect:!0,manualfill:j,automaticallyFill:null,skip_basicauth:null,from_iframe:p,desc:"fill_PW"})},100)},null,null,!0,d.aid,!0)):get_selected_tab(null,
function(a){if(!r&&s&&(h||1==d.basic_auth)&&gettabid(a)==b&&g_ischrome&&have_binary_function("fill_basicauth")){a=getusernamefromacct(d);var n=getpasswordfromacct(d);if(""!=a||""!=n){write_history({cmd:"check_autologin1",tabid:b,aid:d.aid,submit:q});var q=check_autologin(f,d),B=lp_gettld_url(d.url),w=lp_gettld_url(g_basicauth_origurl);compare_tlds(B,w)&&(B=w);call_binary_function("fill_basicauth",a,n,h?!0:!1,B,q?!0:!1,function(a){a?g_basicauth_found=!1:fill({tabid:b,acct:d,docid:c,submit:f,doconfirm:e,
docnum:g,allowforce:h,skip_pwprotect:k,manualfill:j,automaticallyFill:s,skip_basicauth:!0,desc:"FILLBASIC"})});return}}is_guiless()&&(s=1);update_cs_lastfill_aid(b,d.aid);B=d.tld;customjs_has_humanize(d.aid)&&(v=!0);customjs_has_v2humanize(d.aid)&&(m=!0);customjs_has_force_fillbest(d.aid)&&(l=!0);q=d.fields;n=q.length?q.length:0;e=1==e?1:0;h=h?1:0;p=p?1:0;a=null!=d.sharedfromaid&&""!=d.sharedfromaid&&"0"!=d.sharedfromaid&&"null"!=d.sharedfromaid?1:0;0==n&&(!h&&customjs_has_userpass_overrides(d.aid))&&
(h=!0);if(0!=n){for(w=B=n=0;w<q.length;w++)q[w]&&(("text"==q[w].type||"email"==q[w].type||"tel"==q[w].type)&&B++,"password"==q[w].type&&n++);var D=!d.save_all&&0==n;!D&&("undefined"!=typeof SpecialSites[lpcanonizeUrl(d.url)]&&!d.save_all)&&(D=!0);for(var u=[],w=0;w<q.length;w++)if(q[w])if(!d.save_all&&1==e&&"password"!=q[w].type&&!h&&!D)verbose_log("initial fill attempt on page, skipping non-password "+q[w].name);else{var z=q[w],C=z.value,A=z.type;if(!("undefined"!=typeof d.captcha_id&&""!=d.captcha_id&&
d.captcha_id==z.name&&"text"==A)){if("text"==A||"password"==A||"email"==A||"tel"==A||"textarea"==A||"url"==A)C=lpmdec_acct(C,!0,d,g_shares);if(!(""!=z.name&&"undefined"!=typeof u[z.name+C+z.type])){u[z.name+C+z.type]=1;if(""==C||null===C)("text"==A||"email"==A||"tel"==A)&&1==B?C=getusernamefromacct(d):"password"==A&&1==n&&(C=getpasswordfromacct(d));if(""==C||null===C)verbose_log("value is empty, will not fill "+z.name);else{verbose_log("Sending FillRequest: "+w+"\ntype="+A+"\nname="+z.name+"\nvalue=<hidden>");
var E="undefined"!=typeof g_launches[b]&&g_launches[b]&&g_launches[b]==d.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[d.aid]&&25E3>=(new Date).getTime()-g_last_launch[d.aid]?!0:!1,F={from:"fillfield_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;v&&y++;fillfieldCS(b,g,d.aid,{reqinfo:F,docid:c,sharedsite:a,automaticallyFill:s,is_launch:E,manualfill:j,name:z.name,value:C,type:A,checked:z.checked,otherfield:z.otherfield,doconfirm:e||
d.save_all&&"password"==A?1:2,allowforce:h,sharedsite:a,from_iframe:p,humanize:v,v2humanize:m,delayquants:y,force_fillbest:l,originator:t},f)}}}}}else h&&(console_log("no fields. finding best match "+getusernamefromacct(d)+" and <hidden>"),E="undefined"!=typeof g_launches[b]&&g_launches[b]&&g_launches[b]==d.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[d.aid]&&25E3>=(new Date).getTime()-g_last_launch[d.aid]?!0:!1,console_log("Sending fillbest from A reqindex="+g_reqindex),
F={from:"fillbest_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,fillbestCS(b,g,d.aid,{reqinfo:F,docid:c,updatefields:1,addurid:0,sharedsite:a,automaticallyFill:s,is_launch:E,humanize:v}));h&&logLoginAndCheckWeakPassword(b,d);1!=e&&(q=check_autologin(f,d),"undefined"!=typeof AUTOSUBMIT&&(q=!0),write_history({cmd:"check_autologin2",tabid:b,aid:d.aid,submit:q,docnum:g}),"string"==typeof d.custom_js&&""!=d.custom_js&&sendCS(b,{cmd:"run_custom_js",docid:c,
custom_js:d.custom_js,username:getusernamefromacct(d),password:lpmdec_acct(d.password,!0,d,g_shares),onlyfill:q?0:1,loc:3},g),("string"!=typeof d.custom_js||-1==d.custom_js.indexOf("lpdontsubmit"))&&q&&submitCS(b,g,d.aid,{docid:c,humanize:v,delayquants:y}))})}
function logLoginAndCheckWeakPassword(a,b){get_all_windows({populate:!0},function(d){for(var c=0;c<d.length;c++)for(var f=0;f<get_tabs_length(d[c]);f++){var e=get_tabs(d[c])[f];if(gettabid(e)==a&&(checkWeakDuplicateBreached(b,a,lp_gettld_url(gettaburl(e))),(g_loglogins||LPISLOC)&&"undefined"==typeof g_loggedLogins[b.aid]))g_loggedLogins[b.aid]="1",loglogintab(b.aid,e)}})}function showpageoverlay(a){sendCS(a,{cmd:"showoverlay",urlprefix:getchromeurl("",!0)})}
function check_autologin(a,b){var d=!1;if(a)d=!0;else if(b.autologin){var c=(new Date).getTime(),f=parseInt(lpGetPref("autoautoVal",25));if(isNaN(f)||""==f||0>=f)f=25;var e=c-1E3*f;"undefined"==typeof b.last_auto_login||isNaN(b.last_auto_login)||b.last_auto_login<e?(console_log("Launching autologin"),b.last_auto_login=c,d=!0):(write_history({cmd:"check_autologin",msg:sprintf("last autologin to %s was too soon, %s < %s, pref=%d seconds",lp_gettld_url(b.url),(new Date(b.last_auto_login)).toUTCString(),
(new Date(e)).toUTCString(),f)}),console_log("last autologin too soon!"))}return d}
function fillfieldsconfirm(a){if(!a||!lploggedin)return!1;var b=a.url,d="undefined"!=typeof a.topurl?a.topurl:"",c=lp_gettld_url(b),f=a.result,e=a.aid,g=a.docid,h=a.tabid,k=a.doconfirm,r=a.from_iframe?!0:!1,p=a.manualfill,t=a.allowforce,j=!1,s="undefined"!=typeof a.automaticallyFill?a.automaticallyFill:1,t=a.force_fillbest,v=a.name,m=get_record(e);if(!m)return!1;v&&(g_fillfield_confirm_perfield[v]=f?!0:!1);if(hasNeverAutologin(b,c)||d&&d!=b&&hasNeverAutologin(d,c))j=!0;if(f&&(g_do_totp&&(d=getusernamefromacct(m),
""!=d&&(g_usercache[c]=d)),logLoginAndCheckWeakPassword(h,m),2==k))return r&&(p&&!j)&&sendCS(h,{cmd:"conditionalforcefill",reqinfo:y,username:getusernamefromacct(m),password:getpasswordfromacct(m),aid:m.aid,sharedsite:l,automaticallyFill:s,from_iframe:r},a.docnum),!0;if(j)return!1;var l=null!=m.sharedfromaid&&""!=m.sharedfromaid&&"0"!=m.sharedfromaid&&"null"!=m.sharedfromaid?1:0;if(m.save_all){if(!f&&sufficient_condition_fill_saveall(m))return console.log("sufficient successful fills, ignoring failed fill result on saveall fill"),
!0;if(!f||p){b="undefined"!=typeof g_launches[h]&&g_launches[h]&&g_launches[h]==m.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[m.aid]&&25E3>=(new Date).getTime()-g_last_launch[m.aid]?!0:!1;console_log("Sending fillbest from B reqindex="+g_reqindex);var y={from:"fillbest_B",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;fillbestCS(h,a.docnum,m.aid,{reqinfo:y,docid:g,updatefields:0,addurid:0,sharedsite:l,automaticallyFill:s,
is_launch:b,saveall:m.saveall?!0:!1})}}else if(f){m=get_record(e);p=t=null;r&&a.manualfill&&(t=p=!0);var x;fill({tabid:h,acct:m,docid:g,submit:null,doconfirm:!1,docnum:a.docnum,allowforce:t,skip_pwprotect:!0,manualfill:p,automaticallyFill:s,skip_basicauth:!1,from_iframe:r,desc:"FILL_F5"});delete g_fillfieldsmatches[b];delete g_fillfieldsmatchescurridx[b]}else if(a.allowforce||t&&!g_fillfield_did_fillbest[h.toString()]&&!sufficient_condition_fill_nonsaveall(m))t&&(g_fillfield_did_fillbest[h.toString()]=
!0),b="undefined"!=typeof g_launches[h]&&g_launches[h]&&g_launches[h]==m.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[m.aid]&&25E3>=(new Date).getTime()-g_last_launch[m.aid]?!0:!1,console_log("Sending fillbest from C reqindex="+g_reqindex),y={from:"fillbest_C",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,fillbestCS(h,a.docnum,e,{reqinfo:y,docid:g,updatefields:0,addurid:p?1:0,sharedsite:l,automaticallyFill:s,is_launch:b,
force_fillbest:t});else{if(e=g_fillfieldsmatches[b]){p=!1;for(m=0;m<e.length;m++){l=e[m].aid;if(p){(m=g_sites[l])&&(x=!1);fill({tabid:h,acct:m,docid:g,submit:null,doconfirm:!0,docnum:a.docnum,allowforce:null,skip_pwprotect:!0,manualfill:null,automaticallyFill:s,skip_basicauth:x,from_iframe:r,desc:"FILL_F6"});return}m==g_fillfieldsmatchescurridx[b]&&(g_fillfieldsmatchescurridx[b]++,p=!0)}}delete g_fillfieldsmatches[b];delete g_fillfieldsmatchescurridx[b]}return!0}
function web2plug(a){if("2"==a.rsa){g_local_key=AES.hex2bin(a.key);g_local_key_hex=a.key;g_local_key_hash=SHA256(g_local_key);rsa_userchangedpassword();a=opendb();createDataTable(a);if(a&&!LPISLOC)if(g_indexeddb)a.transaction("LastPassData","readwrite").objectStore("LastPassData")["delete"](g_username_hash+"_accts");else a.transaction(function(a){a.executeSql("DELETE FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"accts"],function(){},function(a,b){console_log(b)})});
lpWriteKeyFile()}else""!=g_username&&null!=g_username&&g_username!=a.username?loggedOut(!1,"web2plug"):(g_local_key=AES.hex2bin(a.key),g_local_key_hex=a.key,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile())}function recover(a,b,d,c){var f=lpParseUri(b);b=f.directory;f=f.file;b=b.replace(/^\/~[^/]*/,"");""!=b&&"/"!=b&&"/sso/"!=b||"recover.php"==f&&GetOTPHash(null,a,d,c)}
function loginfromwebsite(a){if(""!=a.wxusername&&""!=a.keyhex){var b=opendb();createSavedLoginsTable(b);if(b){1==a.rememberemail?(L("remembering email"),set_default_login_username(a.wxusername)):L("not remembering email");var d=function(c,d){if(0<d.rows.length){var e=d.rows.item(0).password,f=function(c){var e=get_key_iterations(a.wxusername);make_lp_key_iterations(a.wxusername,c,e,function(c){AES.bin2hex(c)!=a.keyhex&&(g_indexeddb?(c=d.rows.item(0),c.password="",b.transaction("LastPassSavedLogins2",
"readwrite").objectStore("LastPassSavedLogins2").put(c)):b.transaction(function(b){b.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",[a.wxusername],function(){},function(a,b){console_log(b)})}))})};1==d.rows.item(0)["protected"]?unprotect_data(e,!1,f):2==d.rows.item(0)["protected"]&&f(lpdec(e,AES.hex2bin(SHA256(a.wxusername))))}};if(g_indexeddb){var c={rows:{item:function(a){return this[a]},length:0}};b.transaction("LastPassSavedLogins2","readonly").objectStore("LastPassSavedLogins2").openCursor(IDBKeyRange.only(a.wxusername)).onsuccess=
function(a){a.target.result&&""!=a.target.result.value.password&&(c.rows[c.rows.length]=a.target.result.value,c.rows.length++);d(null,c)}}else b.transaction(function(b){b.executeSql("SELECT * FROM LastPassSavedLogins2 WHERE username = ? AND password != ''",[a.wxusername],d,function(){})})}""!=a.wxsessid&&(lp_phpsessid=a.wxsessid);var f=AES.hex2bin(a.keyhex),e=null!=g_local_key?AES.bin2hex(g_local_key):"";if(!lploggedin||!(g_username==a.wxusername&&e==a.keyhex))lploggedin&&g_username==a.wxusername?
(g_local_key=f,g_local_key_hex=a.keyhex,g_local_key_hash=SHA256(g_local_key)):(lploggedin&&""!=g_username&&loggedOut(!1,"differentuser"),g_local_key=f,g_local_key_hex=a.keyhex,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile(),LP.lplogincheck(!0,null,a.wxusername,a.wxhash))}else lploggedin||LP.lplogincheck(!0)}
function reorderOnURL(a,b,d,c){var f=lpParseUri(b),e=lpcanonizeUrl(b,f),g="string"==typeof f.path?f.path.split("/"):[],h=lp_gettld_url(b),k=[],r;for(r in a)if(check_ident_aid(r)&&(a=g_sites[r],!("undefined"==typeof a||"undefined"==typeof a.url)))if(a.save_all||!d||!(""==a.unencryptedUsername&&""==a.password))if(!c||accthaspassword(a)){var p=lpParseUri(a.url);a.realmmatch=(b==g_basicauth_url||b==g_basicauth_origurl)&&(lpmdec_acct(a.realm_data,!0,a,g_shares)==g_basicauth_realm||g_basicauth_found&&""==
g_basicauth_realm&&1==a.basic_auth);a.servermatch=f.host==p.host;a.portmatch=compare_ports(f,p);a.serverportmatch=a.servermatch&&a.portmatch?1:0;a.usernamematch="undefined"!=typeof g_username_vals[b]&&""!=g_username_vals[b]&&g_username_vals[b]==a.unencryptedUsername;a.urlmatch=lpcanonizeUrl(a.url)==e?!0:!1;var p="string"==typeof p.path?p.path.split("/"):[],t;for(t=0;t<g.length&&t<p.length&&p[t]==g[t];t++);a.pathlevelmatch=t;a.fieldmatchcount=0;k.push(a)}k.sort(lp_aids_sort_func);return k=checkurlrules(g_urlrules,
k,h,"string"==typeof f.path?f.path:"",f.host,g_sites,get_port(f))}
function lp_aids_sort_func(a,b){return a.realmmatch!=b.realmmatch?a.realmmatch?-1:1:a.usernamematch!=b.usernamematch?a.usernamematch?-1:1:a.fav!=b.fav?"1"==a.fav?-1:1:a.urlmatch!=b.urlmatch?a.urlmatch?-1:1:a.serverportmatch&&b.serverportmatch&&a.pathlevelmatch!=b.pathlevelmatch?a.pathlevelmatch>b.pathlevelmatch?-1:1:a.serverportmatch!=b.serverportmatch?a.serverportmatch?-1:1:a.servermatch!=b.servermatch?a.servermatch?-1:1:a.fieldmatchcount!=b.fieldmatchcount?a.fieldmatchcount>b.fieldmatchcount?-1:
1:a.last_touch!=b.last_touch?a.last_touch>b.last_touch?-1:1:a.name!=b.name?a.name<b.name?-1:1:0}function lp_sort_case_insensitive_name(a,b){a=a.name.toLowerCase();b=b.name.toLowerCase();return a<b?-1:1}
function launchautologin(a,b){if(check_ident_aid(a)){var d=g_sites[a];d&&(!b&&(d.pwprotect||g_prompts.login_site_prompt)?d.pwprotect&&needs_secure_reprompt(d)?security_prompt(function(){launchautologin(a,!0)},null,null,!0,d.aid,!1):security_prompt(function(){launchautologin(a,!0)}):(g_last_launch[d.aid]=(new Date).getTime(),openURL(d.url,function(a,b){g_launches[gettabid(a)]=b},d.aid)))}}
function is_max_frames_exceeded(a,b){var d=10;if(null==b)return!0;try{var c=g_CS_tops[a],f=g_CS[a][c],e="",e=g_ischrome&&f?lp_gettld_url(f.sender.tab.url):lp_gettld_url(gettaburl(f));"undefined"==typeof c?L("still waiting for topdoc to register for [tab:"+a+"] tld="+e):L("topdoc="+c+" tld="+e);e&&"dailykos.com"==e&&(d=40)}catch(g){console.error("is_max_frames_exceeded: "+g)}debug&&(c=count_cs_for_tabid(a),0<c&&console.warn("is_max_frames_exceeded: CS table count="+c+", global g_CS_count="+g_CS_count[a]),
dumpinfo_for_tabid(a));g_skip_ad_frames&&(d=25);return b[a]>d}
function fillbestCS(a,b,d,c){"number"==typeof d&&(d=d.toString());var f=get_record(d);update_cs_lastfill_aid(a,d);var e=null;if("undefined"==typeof a||!f)return!1;c||(c={aid:d});c.cmd="fillbest";"undefined"==typeof c.clearfilledfieldsonlogoff&&(c.clearfilledfieldsonlogoff=lpGetPref("clearfilledfieldsonlogoff",0));"undefined"==typeof c.realurl&&(c.realurl=f.url);f.save_all&&(e=get_SAED_username_password_fields(f));"undefined"==typeof c.username&&(c.username=f.save_all&&e&&0<e.length?e[0]:getusernamefromacct(f));
"undefined"==typeof c.password&&(c.password=f.save_all&&e&&0<e.length?e[1]:getpasswordfromacct(f));"undefined"==typeof c.custom_js&&(c.custom_js=f.custom_js);"undefined"==typeof c.domains&&(c.domains=getacceptabletlds(f.url));"undefined"==typeof c.is_launch&&(c.is_launch="undefined"!=typeof g_launches[a]&&g_launches[a]&&g_launches[a]==f.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[f.aid]&&25E3>=(new Date).getTime()-g_last_launch[f.aid]?!0:!1);"undefined"==typeof c.automaticallyFill&&
(c.automaticallyFill=1);"undefined"==typeof c.updatefields&&(c.updatefields=0);"undefined"==typeof c.addurid&&(c.addurid=0);"undefined"==typeof c.aid&&(c.aid=d);"undefined"==typeof c.sharedsite&&(c.sharedsite=null!=f.sharedfromaid&&""!=f.sharedfromaid&&"0"!=f.sharedfromaid&&"null"!=f.sharedfromaid?1:0);"undefined"==typeof c.dontfillautocompleteoff&&(c.dontfillautocompleteoff=getInt(lpGetPref("dontfillautocompleteoff",0)));"undefined"==typeof c.saveall&&(c.saveall=f.saveall?!0:!1);"undefined"==typeof c.topurl&&
(c.topurl=get_top_url(a,b));write_history({cmd:"fillbestCS",tabid:a,docnum:b,aid:d,username:c.username,force_fillbest:c.force_fillbest,custom_js:c.custom_js});sendCS(a,c,b);return!0}
function fillfieldCS(a,b,d,c,f){"number"==typeof d&&(d=d.toString());var e=get_record(d);if("undefined"==typeof a||!e)return!1;c||(c={aid:d});c.cmd="fillfield";"undefined"==typeof c.clearfilledfieldsonlogoff&&(c.clearfilledfieldsonlogoff=lpGetPref("clearfilledfieldsonlogoff",0));"undefined"==typeof c.dontfillautocompleteoff&&(c.dontfillautocompleteoff=getInt(lpGetPref("dontfillautocompleteoff",0)));"undefined"==typeof c.realurl&&(c.realurl=e.url);"undefined"==typeof c.aid&&(c.aid=d);"undefined"==
typeof c.tabid&&(c.tabid=a);"undefined"==typeof c.custom_js&&(c.custom_js=e.custom_js);"undefined"==typeof c.domains&&(c.domains=getacceptabletlds(e.url));"undefined"==typeof c.is_launch&&(c.is_launch="undefined"!=typeof g_launches[a]&&g_launches[a]&&g_launches[a]==e.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[e.aid]&&25E3>=(new Date).getTime()-g_last_launch[e.aid]?!0:!1);"undefined"==typeof c.automaticallyFill&&(c.automaticallyFill=1);"undefined"==typeof c.from_iframe&&
(c.from_iframe=0);"undefined"==typeof c.formname&&(c.formname="");"undefined"==typeof c.type&&(c.type="text");"undefined"==typeof c.doconfirm&&(c.doconfirm=2);if("undefined"==typeof c.delayquants||!parseInt(c.delayquants))c.delayquants=0;"undefined"==typeof c.topurl&&(c.topurl=get_top_url(a,b));""!=e.custom_js&&(c.username=getusernamefromacct(e),c.password=getpasswordfromacct(e),c.onlyfill=f?0:1);if("undefined"==typeof c.name||"undefined"==typeof c.value)return console_error("missing required fields!"),
!1;write_history({cmd:"fillfieldCS",tabid:a,docnum:b,aid:c.aid,name:c.name,custom_js:c.custom_js,manualfill:c.manualfill,is_launch:c.is_launch,originator:c.originator,delay:c.humanize?c.delayquants:null});c.humanize&&c.delayquants?setTimeout(function(){sendCS(a,c,b)},c.delayquants*HUMANIZE_DELAY_QUANTUM):sendCS(a,c,b);return!0}
function submitCS(a,b,d,c){"number"==typeof d&&(d=d.toString());var f=get_record(d);if("undefined"==typeof a||!f)return!1;var e="undefined"!=typeof f.submit_id?f.submit_id:"",g="undefined"!=typeof f.submit_html?f.submit_html:"",h="undefined"!=typeof f.submit_js?f.submit_js:"";c||(c={aid:d});c.cmd="submit";"undefined"==typeof c.aid&&(c.aid=d);"undefined"==typeof c.custom_js&&(c.custom_js=f.custom_js);"undefined"==typeof c.submit_id&&(c.submit_id=e);"undefined"==typeof c.submit_html&&(c.submit_html=
g);"undefined"==typeof c.submit_js&&(c.submit_js=h);if("undefined"==typeof c.delayquants||!parseInt(c.delayquants))c.delayquants=0;is_guiless()&&"bankofamerica.com"==lp_gettld_url(f.url)?pass:(write_history({cmd:"submitCS",tabid:a,docnum:b,aid:d,submit_id:e,submit_js:h,delay:c.humanize?c.delayquants:null}),c.humanize&&c.delayquants?setTimeout(function(){sendCS(a,c,b)},c.delayquants*HUMANIZE_DELAY_QUANTUM):sendCS(a,c,b));return!0}
function customjs_has_humanize(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("lphumanize")?!0:!1}function customjs_has_v2humanize(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("lpv2humanize=1")?!0:!1}function customjs_has_dontsubmit(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("lpdontsubmit")?!0:!1}
function check_for_frame_mismatch_ok(a,b,d,c){if(!d||null==a)return!1;var f=0;"undefined"!=typeof b&&b&&(f=b);return f&&!frame_and_topdoc_has_same_domain(a)&&(ftd_report_error(a,c?c:"unknown"),!lpConfirmYesNo(d+"\n\n"+lp_gettld_url(ftd_get_frameparenturl(a))))?!1:!0}function set_casper_active_tab(a,b){g_iscasper&&a&&(a.casper_activeTab=g_CS[g_CS_tops[b]]);return!0}function get_casper_active_tab(a){return g_iscasper&&a&&a.casper_activeTab?a.casper_activeTab:null}
function count_fillfield_confirms(){var a=0,b;for(b in Object.keys(g_fillfield_confirm_perfield))!0===g_fillfield_confirm_perfield[b]&&a++;return a}
function sufficient_condition_fill_saveall(a){if(!a)return!1;var b,d=null,c=null;if(3<=count_fillfield_confirms()){for(b in a.fields)if(a.fields.hasOwnProperty(b)&&a.fields[b]&&("text"==a.fields[b].type||"email"==a.fields[b].type||"tel"==a.fields[b].type)&&""!=a.fields[b].value){d=a.fields[b].name;break}for(b in a.fields)if(a.fields.hasOwnProperty(b)&&a.fields[b]&&"password"==a.fields[b].type&&""!=a.fields[b].value){c=a.fields[b].name;break}if(d&&c)return!0}return!1}
function customjs_has_force_fillbest(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("__lpforcefillbest")?!0:!1}function sufficient_condition_fill_nonsaveall(a){if(!a)return!1;var b=null,d=null;return 2<=count_fillfield_confirms()&&(b=getusernamefromacct(a),d=getpasswordfromacct(a),b&&d)?!0:!1}
function customjs_has_userpass_overrides(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&(0<=a.custom_js.indexOf("lpcurrpass")||0<=a.custom_js.indexOf("lpcurruser"))?!0:!1}function clearformsCS(a,b){if(!a)return!1;if("undefined"==typeof b||null===b)b="all";write_history({cmd:"clearformsCS",tabid:a,docnum:b});sendCS(a,{cmd:"clearforms"},b);return!0};
