document.title=gs("My LastPass Vault");document.getElementById("lp_docwrite_homelocal21")&&set_innertext(document.getElementById("lp_docwrite_homelocal21"),gs("Log Out"));document.getElementById("lp_docwrite_homelocal22")&&set_innertext(document.getElementById("lp_docwrite_homelocal22"),gs("Open Favorites"));document.getElementById("lp_docwrite_homelocal23")&&set_innertext(document.getElementById("lp_docwrite_homelocal23"),gs("Bookmarklets"));
document.getElementById("lp_docwrite_homelocal24")&&set_innertext(document.getElementById("lp_docwrite_homelocal24"),gs("History"));document.getElementById("lp_docwrite_homelocal25")&&set_innertext(document.getElementById("lp_docwrite_homelocal25"),gs("Import"));document.getElementById("lp_docwrite_homelocal26")&&set_innertext(document.getElementById("lp_docwrite_homelocal26"),gs("Export"));
document.getElementById("lp_docwrite_homelocal27")&&set_innertext(document.getElementById("lp_docwrite_homelocal27"),gs("One Time Passwords"));document.getElementById("lp_docwrite_homelocal28")&&set_innertext(document.getElementById("lp_docwrite_homelocal28"),gs("Show Deleted Sites"));document.getElementById("lp_docwrite_homelocal29")&&set_innertext(document.getElementById("lp_docwrite_homelocal29"),gs("Actions"));
document.getElementById("lp_docwrite_homelocal30")&&set_innertext(document.getElementById("lp_docwrite_homelocal30"),gs("Generate Secure Password"));document.getElementById("lp_docwrite_homelocal210")&&set_innertext(document.getElementById("lp_docwrite_homelocal210"),gs("Admin Console"));document.getElementById("lp_docwrite_homelocal211")&&set_innertext(document.getElementById("lp_docwrite_homelocal211"),gs("Manage Shared Folders"));
document.getElementById("lp_docwrite_homelocal212")&&set_innertext(document.getElementById("lp_docwrite_homelocal212"),gs("Account Settings"));document.getElementById("lp_docwrite_homelocal212a")&&set_innertext(document.getElementById("lp_docwrite_homelocal212a"),gs("Tools"));document.getElementById("lp_docwrite_homelocal212b")&&set_innertext(document.getElementById("lp_docwrite_homelocal212b"),gs("Select Identity"));
document.getElementById("lp_docwrite_homelocal212c")&&set_innertext(document.getElementById("lp_docwrite_homelocal212c"),gs("Open Favorites in Tabs"));document.getElementById("lp_docwrite_homelocal212d")&&set_innertext(document.getElementById("lp_docwrite_homelocal212d"),gs("Generate Secure Password"));document.getElementById("lp_docwrite_homelocal212e")&&set_innertext(document.getElementById("lp_docwrite_homelocal212e"),gs("Advanced Tools"));
document.getElementById("lp_docwrite_homelocal212f")&&set_innertext(document.getElementById("lp_docwrite_homelocal212f"),gs("Bookmarklets"));document.getElementById("lp_docwrite_homelocal212g")&&set_innertext(document.getElementById("lp_docwrite_homelocal212g"),gs("One Time Passwords"));document.getElementById("lp_docwrite_homelocal212h")&&set_innertext(document.getElementById("lp_docwrite_homelocal212h"),gs("Show Deleted Items"));
document.getElementById("lp_docwrite_homelocal212i")&&set_innertext(document.getElementById("lp_docwrite_homelocal212i"),gs("View History"));document.getElementById("lp_docwrite_homelocal212j")&&set_innertext(document.getElementById("lp_docwrite_homelocal212j"),gs("Import"));document.getElementById("lp_docwrite_homelocal212k")&&set_innertext(document.getElementById("lp_docwrite_homelocal212k"),gs("Export"));
document.getElementById("lp_docwrite_homelocal213")&&set_innertext(document.getElementById("lp_docwrite_homelocal213"),gs("Add Site"));document.getElementById("lp_docwrite_homelocal214")&&set_innertext(document.getElementById("lp_docwrite_homelocal214"),gs("Add Secure Note"));document.getElementById("lp_docwrite_homelocal215")&&set_innertext(document.getElementById("lp_docwrite_homelocal215"),gs("Create Group"));
document.getElementById("lp_docwrite_homelocal216")&&set_innertext(document.getElementById("lp_docwrite_homelocal216"),gs("User Manual"));document.getElementById("lp_docwrite_homelocal216a")&&set_innertext(document.getElementById("lp_docwrite_homelocal216a"),gs("Tutorials"));document.getElementById("lp_docwrite_homelocal216c")&&set_innertext(document.getElementById("lp_docwrite_homelocal216c"),gs("Log Out"));
document.getElementById("lp_docwrite_homelocal217")&&set_innertext(document.getElementById("lp_docwrite_homelocal217"),gs("Security Challenge"));document.getElementById("lp_docwrite_homelocal217a")&&set_innertext(document.getElementById("lp_docwrite_homelocal217a"),gs("Expand All Folders"));document.getElementById("lp_docwrite_homelocal217b")&&set_innertext(document.getElementById("lp_docwrite_homelocal217b"),gs("Collapse All Folders"));
document.getElementById("lp_docwrite_homelocal218")&&set_innertext(document.getElementById("lp_docwrite_homelocal218"),gs("Vault"));document.getElementById("lp_docwrite_homelocal219")&&set_innertext(document.getElementById("lp_docwrite_homelocal219"),gs("Form Fill Profiles"));document.getElementById("lp_docwrite_homelocal220")&&set_innertext(document.getElementById("lp_docwrite_homelocal220"),gs("Identities"));
document.getElementById("lp_docwrite_homelocal221")&&set_innertext(document.getElementById("lp_docwrite_homelocal221"),gs("Shares"));document.getElementById("lp_docwrite_homelocal222")&&set_innertext(document.getElementById("lp_docwrite_homelocal222"),gs("Credit Monitoring"));document.getElementById("lp_docwrite_homelocal223")&&set_innertext(document.getElementById("lp_docwrite_homelocal223"),gs("Enterprise"));
document.getElementById("lp_docwrite_homelocal224")&&set_innertext(document.getElementById("lp_docwrite_homelocal224"),gs("Tutorials"));document.getElementById("lp_docwrite_homelocal225")&&set_innertext(document.getElementById("lp_docwrite_homelocal225"),upperFirstChar(gs("Name")));document.getElementById("lp_docwrite_homelocal226")&&set_innertext(document.getElementById("lp_docwrite_homelocal226"),upperFirstChar(gs("Actions")));
document.getElementById("lp_docwrite_homelocal227")&&set_innertext(document.getElementById("lp_docwrite_homelocal227"),upperFirstChar(gs("Username")));document.getElementById("lp_docwrite_homelocal228")&&set_innertext(document.getElementById("lp_docwrite_homelocal228"),upperFirstChar(gs("Last used")));document.getElementById("lp_docwrite_homelocal229")&&set_innertext(document.getElementById("lp_docwrite_homelocal229"),gs("Help spread the word"));
document.getElementById("lp_docwrite_homelocal229a")&&set_innertext(document.getElementById("lp_docwrite_homelocal229a"),gs("Invite Friends To Try LastPass"));document.getElementById("lp_docwrite_homelocal230")&&set_innertext(document.getElementById("lp_docwrite_homelocal230"),gs("Do you like LastPass?"));document.getElementById("lp_docwrite_homelocal231a")&&set_innertext(document.getElementById("lp_docwrite_homelocal231a"),gs("Give the Gift of LastPass"));
document.getElementById("lp_docwrite_homelocal231")&&set_innertext(document.getElementById("lp_docwrite_homelocal231"),gs("Tell a friend!"));document.getElementById("lp_docwrite_homelocal232")&&set_innertext(document.getElementById("lp_docwrite_homelocal232"),gs("GET FREE PREMIUM"));document.getElementById("lp_docwrite_homelocal233")&&set_innertext(document.getElementById("lp_docwrite_homelocal233"),gs("Link Personal Account"));
document.getElementById("lp_docwrite_homelocal234")&&set_innertext(document.getElementById("lp_docwrite_homelocal234"),gs("Remove Linked Personal Account"));document.getElementById("lp_docwrite_homelocal235")&&set_innertext(document.getElementById("lp_docwrite_homelocal235"),gs("LastPass Legacy"));
if(g_issafari||g_isopera)document.getElementById("searchx")&&(document.getElementById("searchx").src=getchromeurl("images/cancel.png"),document.getElementById("searchx").style.marginTop="-2px"),document.getElementById("enterpriseicon")&&(document.getElementById("enterpriseicon").src=getchromeurl("images/enterprise.png")),document.getElementById("managedicon")&&(document.getElementById("managedicon").src=getchromeurl("images/manage_shared.png")),document.getElementById("linkicon")&&(document.getElementById("linkicon").src=
getchromeurl("images/link_account.png")),document.getElementById("linkicon2")&&(document.getElementById("linkicon2").src=getchromeurl("images/link_account.png")),document.getElementById("settingsicon")&&(document.getElementById("settingsicon").src=getchromeurl("images/settings.png")),document.getElementById("addsiteicon")&&(document.getElementById("addsiteicon").src=getchromeurl("images/add_site.png")),document.getElementById("securenoteicon")&&(document.getElementById("securenoteicon").src=getchromeurl("images/secure_note2.png")),
document.getElementById("creategroupicon")&&(document.getElementById("creategroupicon").src=getchromeurl("images/create_group.png")),document.getElementById("lpexpandimg")&&(document.getElementById("lpexpandimg").src=getchromeurl("images/folder_open.png")),document.getElementById("lpcollapseimg")&&(document.getElementById("lpcollapseimg").src=getchromeurl("images/folder_close.png")),document.getElementById("searchicon")&&(document.getElementById("searchicon").src=getchromeurl("images/search_lite.png"));
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){onLoad()});window.addEventListener("unload",function(){onUnLoad()});window.addEventListener("resize",function(){onResize()});document.getElementById("searchform").onsubmit=function(){SearchTree();return!1};document.getElementById("lpwebsiteeventform").onsubmit=function(){website_event();return!1};document.getElementById("lplogoff").onclick=function(){logoff();return!1};document.getElementById("lpopenfavorites").onclick=
function(){closepopup();getBG().lpevent("v_of");getBG().openfavorites();return!1};document.getElementById("lpbookmarklets").onclick=function(){closepopup();getBG().lpevent("v_bk");callServerFunction("bookmarklets");return!1};document.getElementById("lphistory").onclick=function(){closepopup();getBG().lpevent("v_his");callServerFunction("history");return!1};document.getElementById("lpimport").onclick=function(){closepopup();getBG().lpevent("v_i");getBG().openimport();return!1};document.getElementById("lpexport").onclick=
function(){closepopup();getBG().lpevent("v_e");getBG().openexport();return!1};document.getElementById("lpadvtools").onclick=function(){return!1};document.getElementById("lpotp").onclick=function(){closepopup();getBG().lpevent("v_otp");openinparent("otp.php");return!1};document.getElementById("lpdeleted").onclick=function(){closepopup();getBG().lpevent("v_sd");getBG().unlock_plug2web();openinparent("",{ac:"1",showdeleted:"1"});return!1};document.getElementById("lpenterprise").onclick=function(){getBG().lpevent("v_ec");
openinparent("enterprise_home.php");return!1};document.getElementById("lpsharedfolders").onclick=function(){getBG().lpevent("v_sf");callServerFunction("sharedfolders");return!1};document.getElementById("lpsettings").onclick=function(){getBG().lpevent("v_set");callServerFunction("settings");return!1};document.getElementById("lpadd").onclick=function(){openaddbytab();return!1};document.getElementById("lpaddnote").onclick=function(){getBG().openaddsecurenote();return!1};document.getElementById("lpcreategroup").onclick=
function(){creategroup();return!1};document.getElementById("lphelp").onclick=function(){getBG().lpevent("v_hlp");openinparent("help.php");return!1};document.getElementById("lpseccheck").onclick=function(){getBG().lpevent("v_sc");getBG().openseccheck();return!1};document.getElementById("lpexpandall").onclick=function(){expandall();return!1};document.getElementById("lpcollapseall").onclick=function(){collapseall();return!1};document.getElementById("lpfriendemail").onclick=function(){openinparent("friendemail.php");
return!1};document.getElementById("lpgift").onclick=function(){openinparent("gift.php?f=0002");return!1};document.getElementById("q").addEventListener("keyup",function(a){34==a.keyCode||33==a.keyCode||40==a.keyCode||38==a.keyCode?MoveFocus(a):gSearchWhileType&&13!=a.keyCode&&(document.getElementById("q"),document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png",SearchTree())});document.getElementById("searchxlink").onclick=function(){""==document.getElementById("q").value?document.getElementById("searchx").src=
gLocalBaseUrl+"images/search.png":(document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png",getBG().lpevent("v_x"),clearTree());document.getElementById("q").focus();return!1};document.getElementById("logo").addEventListener("click",function(){document.location.href=getpartnerurl(g_urlprefix)});document.getElementById("identity").addEventListener("change",function(){changeidentity(this.value,!1);return!1});document.getElementById("sites").addEventListener("click",function(){ontabchange(this)});
document.getElementById("ff").addEventListener("click",function(){ontabchange(this)});document.getElementById("ident").addEventListener("click",function(){ontabchange(this)});document.getElementById("shares").addEventListener("click",function(){ontabchange(this)});document.getElementById("credmon").addEventListener("click",function(){ontabchange(this)});document.getElementById("enterprise").addEventListener("click",function(){ontabchange(this)});document.getElementById("chooser").addEventListener("click",
function(){toggleUserCol()});document.getElementById("lplinkpersonal").onclick=function(){getBG().lpevent("v_lp");callServerFunction("linkpersonal");return!1};document.getElementById("lpremovepersonal").onclick=function(){getBG().lpevent("v_rp");callServerFunction("removepersonal",get_personal_linked(),getBG().g_token);return!1};document.getElementById("toolsturner").addEventListener("click",function(){showTools();return!1});document.getElementById("lptutorials").addEventListener("click",function(){openinparent("support_screencasts.php");
return!1});document.getElementById("lppopuplink").onclick=function(){"block"===document.getElementById("lppopup").style.display?closepopup():(getBG().lpevent("v_pop"),showpopup());return!1};document.getElementById("legacy_a").onclick=function(){getBG().lpevent("v_lg");getBG().openlastpasslegacy();return!1};window.addEventListener("resize",hide_promo);hide_promo();setTimeout(hide_promo,2E3)});
function hide_promo(){if("1"!=getBG().g_enterpriseuser){var a="",a=-1!=$("#lpfriendemail").css("display").indexOf("block")?"#lpfriendemail":-1!=$("#lpgift").css("display").indexOf("block")?"#lpgift":pick_promo();$(a).css("display","block");$("#actions").height()>=$(a).position().top&&$(a).css("display","none")}}function pick_promo(){var a=new Date,b=Math.floor(100*Math.random());return 10==a.getMonth()&&25<=a.getDate()||11==a.getMonth()&&25>=a.getDate()&&25<b?"#lpgift":"#lpfriendemail"}
function showTools(){var a=document.getElementById("turnericon").classList.toggle("turn90");document.getElementById("toolspane").style.display=a?"block":"none";hide_promo()}g_isfirefoxsdk&&document.getElementById("searchicon")&&(document.getElementById("searchicon").style.position="absolute",document.getElementById("searchicon").style.top="2px");
