var g_fromwelcome=-1!=document.location.href.indexOf("?fromwelcome=1"),g_results=null;function onLoad(){populate()}
function populate(){var b=getBG();b.have_binary_function("get_chrome_passwords")?b.call_binary_function("get_chrome_passwords",function(a){a||(a=[]);g_results=a;var b=[];for(a=0;a<g_results.length;a++)if("undefined"!=typeof g_results[a].username&&""!=g_results[a].username||"undefined"!=typeof g_results[a].password&&""!=g_results[a].password)b[b.length]=g_results[a];g_results=b;b=[];event_handlers={};for(a in g_results)b.push(getsitehtml(g_results,a));b.push('<div id="gridclear" class="clear"/>');
document.getElementById("gridsite").innerHTML=b.join("");for(a in event_handlers)document.getElementById(a).addEventListener("click",event_handlers[a])}):g_isfirefoxsdk||(document.getElementById("needbinaryspan").style.display="inline")}function sp(b,a){b.innerHTML==gs("Show")?set_innertext(b,g_results[a].password):set_innertext(b,gs("Show"))}var MAX_SITENAME_LEN=30,MAX_SITEUSERNAME_LEN=15;
function getsitehtml(b,a){id=a;name=trunc(b[a].url,MAX_SITENAME_LEN);username="undefined"!=typeof b[a].username?trunc(b[a].username,MAX_SITEUSERNAME_LEN):"";event_handlers["link"+id]=function(){sp(this,this.id.substring(4))};return'<div class="site" id="site'+id+'"><div class="border"><div class="sitename"><span class="content">'+name+'</span></div><div class="siteusername"><span class="content">'+username+'</span></div><div class="sitepassword"><span class="content"><a id="link'+id+'" href="#">'+
gs("Show")+'</a></span></div><div class="siteimport"><input type="checkbox" id="import'+id+'" checked></div></div></div>'}function trunc(b,a){return b.length<=a?b:b.substr(0,a)+"..."}function select_all(){for(var b=0;b<g_results.length;b++)document.getElementById("import"+b).checked=!0}function unselect_all(){for(var b=0;b<g_results.length;b++)document.getElementById("import"+b).checked=!1}
function checkdup(b,a){if("http://sn"==b.url)return!1;var c=getBG().getsites(a),e;for(e in c)if((c=getBG().g_sites[e])&&c.unencryptedUsername==b.username&&getBG().lpmdec_acct(c.password,!0,c,getBG().g_shares)==b.password)return!0;return!1}
function lpimport(){for(var b=[],a="cmd=uploadaccounts&username="+getBG().en(getBG().g_username),c=0,e=0;e<g_results.length;e++)if(document.getElementById("import"+e).checked){var d=g_results[e],f=getname_url(d.url);if(!checkdup(d,lp_gettld_url(d.url))){for(var a=a+("&url"+c+"="+getBG().en(getBG().bin2hex(punycode.URLToASCII(d.url)))),a=a+("&username"+c+"="+getBG().en(getBG().lpenc(d.username))),a=a+("&password"+c+"="+getBG().en(getBG().lpenc(d.password))),a=a+("&type"+c+"=ie"),a=a+("&usernamefield"+
c+"="+getBG().en(d.username_field)),a=a+("&passwordfield"+c+"="+getBG().en("*"+d.password_field)),g,h=1;1E3>=h;h++)if(g=f,1<h&&(g+=" ("+h+")"),!lp_in_array(g,b)){b[b.length]=g;break}a+="&name"+c+"="+getBG().en(getBG().lpenc(g));c++;getBG().LPISLOC&&lpImportChromePasswordLocal(d)}}getBG().LPISLOC&&(getBG().g_local_accts_version++,getBG().rewritelocalfile());a+=getBG().get_identity_param();getBG().lpMakeRequest(base_url+"lastpass/api.php",a,lpUploadAccountsResponse)}
function lpImportChromePasswordLocal(b){var a=getBG(),c=a.createNewAcct();c.aid=get_new_id();c.name=lp_gettld_url(b.url);c.url=b.url;var e=lp_gettld_url(c.url);c.tld=e;c.unencryptedUsername=b.username;c.username=a.lpmenc(b.username,!0);c.password=a.lpmenc(b.password,!0);var d=get_new_id();c.urid=d;addfield(c,b.username_field,"text",a.lpmenc(b.username,!0),d);addfield(c,b.password_field,"password",a.lpmenc(b.password,!0),d);"undefined"==typeof a.g_tlds[c.tld]&&(a.g_tlds[c.tld]=[]);a.g_tlds[c.tld][c.aid]=
!0;a.add_ident_aid(c.aid);if("undefined"!=typeof a.g_equivalentdomains[e]&&(b=a.g_equivalentdomains[e],"undefined"!=typeof a.g_equivalentdomains[b]))for(e=0;e<a.g_equivalentdomains[b].length;e++)d=a.g_equivalentdomains[b][e],"undefined"==typeof a.g_tlds[d]&&(a.g_tlds[d]=[]),a.g_tlds[d][aid]=!0;a.g_sites[c.aid]=c}function addfield(b,a,c,e,d){var f={otherfield:!1};f.name=a;f.type=c;f.value=e;f.formname="";f.checked=!1;f.urid=d;f.otherlogin="0";f.url="";b.fields[b.fields.length]=f}
function lpUploadAccountsResponse(b){b&&(4==b.readyState&&200==b.status)&&(0<b.responseText.indexOf("OK")?(getBG().get_accts(),getBG().refresh_windows(),alert(gs("Your Google Chrome passwords have been imported successfully.")),g_fromwelcome?redirect_to_url("configure_formfill.html"):getBG().closecurrenttab("import.html")):alert(gs("An error occurred while importing your Google Chrome passwords.")))}
function cancel(){g_fromwelcome?redirect_to_url("configure_formfill.html"):getBG().closecurrenttab("import.html")}function getbinary(){var b=getBG();b&&b.install_binary()};
