var reprompt_callback=null,reprompt_error_callback=null;g_fixpbkdf2=!0;var login_submitted=!1,fromcs=!1,numfailed=0;
function do_submit(){if(login_submitted)return!1;var a=!1;-1!=window.location.search.indexOf("&securereprompt=1")&&window.location.search.indexOf("aid="!=-1)&&(a=!0);login_submitted=!0;var b=fix_username(document.getElementById("u").value),c=document.getElementById("p").value;document.getElementById("p").value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";var d=get_key_iterations(b);!1==a?(getBG().console_log("login calculating key"),getBG().make_lp_key_hash_iterations(b,
c,d,function(a,d){getBG().console_log("login calculating key completed");document.getElementById("p").blur();if(null!=reprompt_callback){var e=getBG();if(a==e.g_local_key){var j=0;document.getElementById("donotrepromptfor").checked&&(j=document.getElementById("donotrepromptforsecs").value);e.lpPutUserPref("reprompttime",j);e.lpWriteAllPrefs();"function"==typeof e.set_last_reprompt_time&&e.set_last_reprompt_time();reprompt_error_callback=null;e.select_selectedtabid();reprompt_callback();setTimeout(function(){window.close()},
0)}else alert(gs("Invalid Password.")),login_submitted=!1,2>numfailed?(numfailed++,document.getElementById("p").value="",document.getElementById("p").focus()):setTimeout(function(){closePop()},0)}else(e=getBG())?(document.getElementById("rememberpassword").checked||(document.getElementById("p").value=""),"block"==document.getElementById("disablepasswordmanagerrow").style.display&&e.disablepasswordmanager(document.getElementById("disablepasswordmanager").checked),e.g_manual_login=!0,e.LP_do_login(b,
c,document.getElementById("rememberemail").checked,document.getElementById("rememberpassword").checked,null,document.getElementById("showvault").checked,a,d),reprompt_error_callback=null,c="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",setTimeout(function(){closePop()},0)):alert(gs("Can't find hidden LastPass window"))})):getBG().make_lp_key_hash_iterations(b,c,d,function(a,b){secure_reprompt_callback(a,b)});return!1}var passwords=[];
function setup_reprompt(){document.getElementById("reprompttext").style.display="block";document.getElementById("deleteicon").style.display="none";document.getElementById("rememberemailrow").style.display="none";document.getElementById("rememberpasswordrow").style.display="none";document.getElementById("showvaultrow").style.display="none";document.getElementById("donotrepromptforrow").style.display="block";document.getElementById("screenkeyboardcontainer").style.display="none";document.getElementById("forgotcontainer").style.display=
"none";document.getElementById("u").disabled=!0;setTimeout(function(){document.getElementById("p").focus()},100);document.getElementById("links").style.display="none";document.title=set_innertext(document.getElementById("logintitletxt"),gs("Reprompt"));setTimeout(function(){document.getElementById("p").focus()},150);0<window.location.search.indexOf("fromcs=1")&&(fromcs=!0)}
function load(a){try{var b="undefined"!=typeof chrome&&("undefined"!=typeof chrome.runtime||"undefined"!=typeof chrome.extension);if(!b&&!a&&("undefined"==typeof safari||"undefined"==typeof safari.extension.globalPage))get_data("login",function(){load(!0)});else{if(b){var c=window.getComputedStyle(document.body,null);100>parseInt(c.width)&&(document.body.style.minWidth="810px",document.body.style.minHeight="333px")}document.getElementById("screenkeyboard")&&(document.getElementById("screenkeyboard").title=
gs("Screen Keyboard"));getBG().LPISLOC&&(document.getElementById("forgotcontainer").style.display=document.getElementById("screenkeyboardcontainer").style.display=document.getElementById("createaccountcontainer").style.display="none");getBG().g_hidecreate&&(document.getElementById("createaccountcontainer").style.display="none");if(getBG().g_hidevault||getBG().g_hideshowvault)document.getElementById("showvaultrow").style.display="none";getBG().g_hidescreenkeyboard&&(document.getElementById("screenkeyboardcontainer").style.display=
"none");var d=getBG();can_chrome_do_math()||d.openURL(getchromeurl("mathfail.html"));if(null!=d.g_reprompt_callback){reprompt_callback=d.g_reprompt_callback;d.g_reprompt_callback=null;reprompt_error_callback=d.g_reprompt_error_callback;d.g_reprompt_error_callback=null;setup_reprompt();document.getElementById("u").value=d.g_username;var g=d.lpGetPref("reprompttime",0);document.getElementById("donotrepromptfor").checked=0<g;document.getElementById("donotrepromptforsecs").value=g;getBG().can_allow_reprompt_skip()||
(document.getElementById("donotrepromptfor").checked=!1,document.getElementById("donotrepromptfor").disabled=!0,document.getElementById("donotrepromptforsecs").disabled=!0)}else{var h=d.lpGetPref("rememberemail",1),e=d.lpGetPref("rememberpassword",-1),j=d.lpGetPref("showvault",-1);document.getElementById("rememberemail").checked=1==h?!0:!1;document.getElementById("rememberpassword").checked=1==e?!0:!1;document.getElementById("showvault").checked=1==j?!0:!1;getBG().g_hidescreenkeyboard&&(document.getElementById("screenkeyboardcontainer").style.display=
"none");getBG().g_db_transaction_tested=getBG().g_db_transaction_worked=!1;populate_usernames();g_isfirefoxsdk&&getBG().remembersignons?(document.getElementById("disablepasswordmanagerrow").style.display="block",document.getElementById("disablepasswordmanager").checked=0==getBG().lpGetPref("disableffpwasked",0)?!0:!1):b&&("undefined"!=typeof d.chrome.privacy&&"undefined"!=typeof d.chrome.privacy.services&&"undefined"!=typeof d.chrome.privacy.services.passwordSavingEnabled)&&d.chrome.privacy.services.passwordSavingEnabled.get({},
function(a){"controllable_by_this_extension"==a.levelOfControl&&a.value&&(document.getElementById("disablepasswordmanagerrow").style.display="block",document.getElementById("disablepasswordmanager").checked=0==getBG().lpGetPref("disableffpwasked",0)?!0:!1)})}var f=document.getElementById("logincontainer").clientHeight;document.getElementsByTagName("html")[0].style.height=document.getElementsByTagName("body")[0].style.height=f+"px";fix_firefox_height()}}catch(p){getBG().console_log(p.message)}}
window.addEventListener("keydown",function(a){handle_keydown(a)},!1);
function populate_usernames(){getBG().get_saved_logins(function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c].username,passwords[b[c]]=a[c].password,1==a[c]["protected"]?function(a,b){getBG().unprotect_data(b,!1,function(c){passwords[a]=c;document.getElementById("p").value==b&&(document.getElementById("p").value=c)})}(b[c],passwords[b[c]]):2==a[c]["protected"]&&(passwords[b[c]]=lpdec(passwords[b[c]],AES.hex2bin(SHA256(b[c]))));b.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});create_combo("u",
b,!0,document,"","deleteicon",-45,g_isfirefoxsdk?6:-2);b="";c=document.location.href.indexOf("sesameusername=");-1!=c&&(b=document.location.href.substr(c+15),c=b.indexOf("&"),-1!=c&&(b=b.substring(0,c)),b=decodeURIComponent(b));0<a.length||""!=b?(a=""!=b?b:a[0].username,b="undefined"!=typeof passwords[a]?passwords[a]:"",document.getElementById("u")&&(document.getElementById("u").value=a),document.getElementById("p")&&document.getElementById("p").focus(),""!=b&&(document.getElementById("p").value=
b,-1==rememberpassword&&(document.getElementById("rememberpassword").checked=!0),document.getElementById("login").focus())):document.getElementById("u").focus();g_ischrome&&(-1!=navigator.userAgent.indexOf("Chrome/4")||-1!=navigator.userAgent.indexOf("Chrome/5"))&&setTimeout(function(){test_db_failed(1)},5E3);check_remember_password()})}
function handle_keydown(a){var b=0!=a.keyCode?a.keyCode:a.charCode;g_issafari&&(68==b&&a.ctrlKey)&&(LP_decimate_children(document.body),b=document.createElement("pre"),set_innertext(b,getBG().g_console_log),document.body.appendChild(b),a.cancelBubble=!0,a.preventDefault(),a.stopPropagation())}
function test_db_failed(a){L("test_db_failed timeout: "+a);getBG().g_db_transaction_tested=!0;getBG().g_db_transaction_worked||(document.getElementById("u").focus(),create_combo("u",[],!0,document,"","deleteicon",-45,g_isfirefoxsdk?6:-2))}
function username_changed(){var a=document.getElementById("u").value;"undefined"!=typeof passwords[a]&&""!=passwords[a]?(document.getElementById("p").value=passwords[a],document.getElementById("rememberpassword").checked=!0):(document.getElementById("p").value="",document.getElementById("rememberpassword").checked=!1);check_remember_password()}
function check_remember_password(){if(document.getElementById("u")){var a=document.getElementById("u").value,b="undefined"!=typeof chrome&&("undefined"!=typeof chrome.runtime||"undefined"!=typeof chrome.extension);localStorage_getItem(SHA256(a)+".noremember")&&null==getBG().g_reprompt_callback?b?(document.getElementById("rememberpasswordrow").style.display="none",a=document.getElementById("logincontainer").clientHeight,document.getElementsByTagName("html")[0].style.height=document.getElementsByTagName("body")[0].style.height=
a+"px"):(document.getElementById("rememberpassword").checked=!1,document.getElementById("rememberpassword").disabled="disabled"):b?document.getElementById("rememberpasswordrow").style.display="block":document.getElementById("rememberpassword").disabled=""}}
function delete_user(){var a=document.getElementById("u").value;getBG().delete_saved_login(a);delete passwords[a];delete_combo_item("u",a);document.getElementById("u").value="";for(var b in passwords){document.getElementById("u").value=b;break}username_changed()}function retsubmit(a){return 13==a.keyCode?(do_submit(),!1):!0}function glow(a){a.className+=" glow"}function dim(a){a.className=a.className.replace(/\bglow\b/,"")}
function closePop(){"undefined"!=typeof chrome&&("undefined"!=typeof chrome.runtime||"undefined"!=typeof chrome.extension)&&parent?-1!=document.location.href.indexOf("login.html")&&-1==document.location.search.indexOf("inline")?getBG().closecurrenttab("login.html"):parent.window_close():g_ismaxthon?(window.close(),setTimeout(function(){window.external.mxGetRuntime().getActionByName("lppanel").hide()},0)):g_isfirefoxsdk?(getBG().closecurrenttab("login.html"),dispatch_message("closepop",{})):"undefined"!=
typeof getBG().closePop?getBG().closePop():window.close()}function oninitlogin(){}function onshowlogin(){parent.body&&(parent.body.style.margin="0px");-1==location.search.indexOf("foo")&&(location.href="lp_toolstrip.html?browseraction=1&foo")}function onhidelogin(){parent.body&&(parent.body.style.margin="8px")}
function secure_reprompt_callback(a,b){process_response=function(c){if(4==c.readyState&&200==c.status){var d=JSON.parse(c.response);if(1!==d.success)a==f.g_local_key?(reprompt_callback(),setTimeout(function(){window.close()},0)):alert("Incorrect Password");else{c=0;document.getElementById("donotrepromptfor").checked&&(c=document.getElementById("donotrepromptforsecs").value);var f=getBG();f.lpPutUserPref("reprompttime",c);f.lpWriteAllPrefs();"function"==typeof f.set_last_reprompt_time&&f.set_last_reprompt_time();
var f=d.secret,g=d.save_all,h=d.aid,d=d.fields,k=get_record(h,!0);secure_reprompt_cached_acct=[];for(var l in k)secure_reprompt_cached_acct[l]=k[l];!0==g&&(secure_reprompt_cached_acct.save_all=!0);for(var n in d){l=d[n][0];var g=d[n][1],m;for(m in k.fields)secure_reprompt_cached_acct.fields[m].name==l&&(secure_reprompt_cached_acct.fields[m].value=g)}"http://sn"==k.url?secure_reprompt_cached_acct.extra=f:secure_reprompt_cached_acct.password=f;getBG().SecureReprompter.add_secret(h,secure_reprompt_cached_acct,
c,b);fromcs?reprompt_callback(f):reprompt_callback();setTimeout(function(){window.close()},0)}}};var c=window.location.search.slice(1),d=c.split("&"),g=null,h;for(h in d)if(0==d[h].indexOf("aid=")){g=d[h].split("=")[1];break}d=get_record(g);typeof d.sharefolderid&&d.sharefolderid&&(c+="&sharedfolderid="+encodeURIComponent(d.sharefolderid));getBG().lpMakeRequest(base_url+"secure_reprompt.php","hash="+encodeURIComponent(b)+"&"+c,process_response,null)};
