var g_maxchars=0,g_maxcharsmatch=0,g_menuwidth=0,g_menuwidthmatch=0,g_menus=[],g_menutitles=[],g_menuspeed=1E4,g_hoverrow=null,g_autoclickenabled=!1,g_is_mac=-1!=navigator.appVersion.indexOf("Mac"),g_submenulistener=-1,g_new_menu=!0,g_iname=null,g_menu=null,g_pointer=null,g_pointer_stack=[],g_ids=[],MAXNAME=40;function onheightmenu(){return getBG().getmenuheight(!0,!0,!0,g_browseraction)}function oninitmenu(){}
function onshowmenu(){lpdbg("menu","in onshowmenu");getBG().lpevent("m_mnpop");g_new_menu?setTimeout(function(){menu3()},0):(rebuildmenu(),setTimeout(function(){menuconnectevents()},100));if(g_isfirefoxsdk&&(document.getElementById("body").style.overflowX="hidden",getBG().g_is_linux||getBG().g_is_mac))document.getElementById("body").style.backgroundColor="white"}function onhidemenu(){$("#menu").html("")}
function getSiteMenuTitle(a,c){var b=c?getusernamefromacct(a):a.username,b=null==b?"":b,d=a.name+(""==b?"":" ("+b+")");d.length>g_maxcharsmatch&&(d=a.name,d=null==d?"":d,d.length>MAXNAME-3&&(d=d.substring(0,MAXNAME)+"..."),b.length>=g_maxcharsmatch-d.length-3&&(b=b.substring(0,g_maxcharsmatch-d.length-3)+"..."),d+=""==b?"":" ("+b+")");return d}var g_login_logoff_time=0;
function menuaction(a,c){L("TSM : menuaction cmd="+a);g_hoverrow=null;var b=getBG();if(b){var d="",h="",g="";0==a.indexOf("identity")&&"identityadd"!=a&&(h=a.substring(8),"all"==h&&(h=""),a="identityswitch");if(0==a.indexOf("matchopen"))d=a.substring(9),L("menuopen: "+d+" title: "+c),menuopen("match"+d,"match",c);else if(0==a.indexOf("opendelete"))b=a.substring(10),menuopendelete(b,c);else{0==a.indexOf("matchedit")?(d=a.substring(9),a="matchedit"):0==a.indexOf("matchfill")?(d=a.substring(9),a="matchfill"):
0==a.indexOf("matchcopyusername")?(d=a.substring(17),a="matchcopyusername"):0==a.indexOf("matchcopypassword")?(d=a.substring(17),a="matchcopypassword"):0==a.indexOf("matchcopyurl")?(d=a.substring(12),a="matchcopyurl"):0==a.indexOf("matchcopynote")?(d=a.substring(13),a="matchcopynote"):0==a.indexOf("matchdelete")?(d=a.substring(11),a="matchdelete"):0==a.indexOf("matchgotourl")&&(d=a.substring(12),a="matchgotourl");0==a.indexOf("recentlyused")?(d=a.substring(12),a="clear"==d?"clearrecent":"site"):0==
a.indexOf("site")&&"siteadd"!=a?(d=a.substring(4),a="site"):0==a.indexOf("note")&&"noteadd"!=a?(d=a.substring(4),a="note"):0==a.indexOf("applicationlaunch")?(d=a.substring(17),a="applicationlaunch"):0==a.indexOf("applicationcopyusername")?(d=a.substring(23),a="applicationcopyusername"):0==a.indexOf("applicationcopypassword")?(d=a.substring(23),a="applicationcopypassword"):0==a.indexOf("applicationcopyurl")?(d=a.substring(18),a="applicationcopyurl"):0==a.indexOf("applicationedit")?(d=a.substring(15),
a="applicationedit"):0==a.indexOf("applicationdelete")?(d=a.substring(17),a="applicationdelete"):0==a.indexOf("fillforms")?(g=a.substring(9),a="fillforms"):0==a.indexOf("editprofile")&&(g=a.substring(11),a="editprofile");0==d.indexOf("matchingsites")&&(d=d.substring(13));switch(a){case "logout":case "logoff":b.lpevent("m_lo");b.loggedOut(!1,"menu");g_login_logoff_time=(new Date).getTime();break;case "vault":b.lpevent("m_ov");b.openvault();break;case "openfavorites":b.lpevent("m_of");b.openfavorites();
break;case "preferences":b.lpevent("m_op");b.openprefs();break;case "help":b.lpevent("m_oh");b.openhelp();break;case "gift":b.lpevent("m_gift");b.openURL("https://lastpass.com/gift.php?f=0001");break;case "premium":b.lpevent("m_oprem");b.openpremium();break;case "enterprise":b.lpevent("m_oent");b.openURL("https://lastpass.com/enterprise_trial.php?f=mnu");break;case "entconsole":b.lpevent("m_oec");b.openentconsole();break;case "server":b.upgradetoserver();break;case "saveall":b.lpevent("m_saed");b.saveall();
break;case "tools":case "feedback":b.openfeedback();break;case "generate":b.lpevent("m_gen");if(g_browseraction&&!g_ismaxthon){hidemenu();openmole("lpgeneratecont");return}b.opengenpw();break;case "search":b.lpevent("m_os");b.opensearch();break;case "recheck":b.lpevent("m_rec");b.recheckpage();break;case "refresh":b.lpevent("m_ref");b.refreshsites();break;case "importgooglechrome":b.lpevent("m_igoo");b.openimportchrome();break;case "lpimport":b.lpevent("m_i");b.openimport();break;case "importfirefoxgo":break;
case "importfirefoxhelp":break;case "import1passwordgo":break;case "import1passwordhelp":break;case "importkeepassgo":break;case "importkeepasshelp":break;case "importlastpassgo":break;case "importlastpasshelp":break;case "importmsipasswordkeepergo":break;case "importmsipasswordkeeperhelp":break;case "importmypasswordsafego":break;case "importmypasswordsafehelp":break;case "importpasspackgo":break;case "importpasspackhelp":break;case "importpasswordagentgo":break;case "importpasswordagenthelp":break;
case "importpasswordkeepergo":break;case "importpasswordkeeperhelp":break;case "importpasswordsafego":break;case "importpasswordsafehelp":break;case "importroboformgo":break;case "importroboformhelp":break;case "importturbopasswordsgo":break;case "importturbopasswordshelp":break;case "importcsvgo":break;case "importcsvhelp":break;case "exportchrome":break;case "exportcsv":b.lpevent("m_e");b.openexport();break;case "exportlastpass":b.lpevent("m_elp");b.openlastpassexport();break;case "exportwlan":b.lpevent("m_ewlan");
b.wlanexport();break;case "exportformfill":b.lpevent("m_eff");b.formfillexport();break;case "printsites":b.lpevent("m_p");b.openprint(!1);break;case "printnotes":b.lpevent("m_pn");b.openprint(!0);break;case "update":if(b.lpevent("m_up"),hidemenu(),b.checkforupdates(),g_isopera||g_ismaxthon||g_issafari||g_isfirefoxsdk)break;else return;case "clear":b.lpevent("m_cl");b.clearCache(!1,!0,!1);break;case "sessions":b.lpevent("m_ses");b.opensessions();break;case "myaccount":b.lpevent("m_mya");b.openmyaccount();
break;case "seccheck":b.lpevent("m_sec");b.openseccheck();break;case "about":b.lpevent("m_abt");b.openabout();break;case "addsite":b.lpevent("m_add");b.openaddsite();break;case "addnote":b.lpevent("m_addn");b.openaddsecurenote();break;case "clearrecent":b.lpevent("m_clrrec");b.clearrecent();break;case "legacy":b.lpevent("m_lg");b.openlastpasslegacy();break;case "console":b.lpevent("m_dbgcon");b.opendebugtab();break;case "identityswitch":b.lpevent("m_swid");b.switch_identity(h);break;case "identityadd":b.lpevent("m_addid");
b.add_identity();break;case "site":b.lpevent("m_ls");b.launch(d);break;case "siteadd":b.lpevent("m_add2");b.openaddsite();break;case "note":b.lpevent("m_ln");b.launch(d);break;case "noteadd":b.lpevent("m_addn2");b.openaddsecurenote();break;case "applicationlaunch":b.lpevent("m_la");b.launch("app"+d);break;case "applicationcopyusername":b.lpevent("m_cau");b.copyusername("app"+d);break;case "applicationcopypassword":b.lpevent("m_cap");b.copypassword("app"+d);break;case "applicationcopyurl":b.lpevent("m_caurl");
b.copyurl("app"+d);break;case "applicationedit":b.lpevent("m_ea");b.editAid("app"+d);break;case "applicationdelete":b.lpevent("m_da");b.deleteAid("app"+d);break;case "fillforms":b.lpevent("m_ff");b.fillform(g);break;case "editprofile":b.lpevent("m_ef");b.editprofile(g);break;case "addprofile":b.lpevent("m_af");b.addprofile();break;case "addcreditcard":b.lpevent("m_acc");b.addcreditcard();break;case "clearforms":b.lpevent("m_clrf");b.clearforms();break;case "chooseprofilecc":b.lpevent("m_cpcc");if(g_browseraction&&
!g_ismaxthon){hidemenu();openmole("lpchooseprofilecc");return}b.openchooseprofilecc();break;case "matchedit":b.lpevent("m_me");b.editAid(d);break;case "matchfill":b.lpevent("m_mf");b.fillaid(d);break;case "matchcopyusername":b.lpevent("m_mcu");b.copyusername(d);break;case "matchcopypassword":b.lpevent("m_mcp");b.copypassword(d);break;case "matchcopyurl":b.lpevent("m_mcurl");b.copyurl(d);break;case "matchcopynote":b.lpevent("m_mcn");b.copynote(d);break;case "matchdelete":b.lpevent("m_md");b.deleteAid(d,
null);break;case "matchgotourl":b.lpevent("m_mg2");b.gotourl(d,null);break;case "movematching":b.lpPutUserPref("toplevelmatchingsites",1);b.lpWriteAllPrefs();(g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_prefs("menu");break;default:L("TSM : INVALID MENU ACTION cmd="+a)}closemole()}}}function deletenever(a){a=getBG().getnevers()[a];getBG().deleteNever(a);closemole()}
function rightclickmenuaction(a){var c="";if(0==a.indexOf("site")&&"siteadd"!=a)c=a.substring(4),a="match_noautofill"+c;else if(0==a.indexOf("recentlyused"))c=a.substring(12),a="match_noautofill"+c;else if(0==a.indexOf("note")&&"noteadd"!=a)c=a.substring(4),a="match_note"+c;else return!0;menuopen(a,"match","");return!1}
function getmenu(){var a=getBG();g_iname=getIdentityName();var c={identityall:{title:gs("All")}};""==a.g_identity&&(c.identityall.icon="images/checkmark.gif");for(f in a.g_identities)c["identity"+a.g_identities[f].iid]={title:a.g_identities[f].deciname},a.g_identities[f].iid==a.g_identity&&(c["identity"+a.g_identities[f].iid].icon="images/checkmark.gif");c.linebreak0=null;c.identityadd={title:gs("Add Identity")};var b={},d=1==a.lpGetPref("showAcctsInGroups",1),h={},g,e,j=!1,n=[],k=[],r=!1;for(g in a.g_sites)if(a.check_ident_aid(g)&&
"http://group"!=a.g_sites[g].url){j=!0;e=a.g_sites[g].group;if(null==e||""==e)e=gs("(none)");for(var l=e.split("\\"),m="",f=0;f<l.length;f++)0==f&&"\\"==e[0]?(m+="\\",f++):""!=m&&(m+="\\"),m+=l[f],lp_in_array(m,n)||(n[n.length]=m);k[k.length]=a.g_sites[g];"1"==a.g_sites[g].fav&&(r=!0)}n.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});var q=d&&(r||1<n.length);q&&r&&(h[gs("favorites")]={title:gs("favorites"),children:{}});for(var u=n.length,l=[],f=0;f<u;f++){e=n[f];var p=e.lastIndexOf("\\"),
m=-1==p||0==p?e:e.substring(p+1),m={title:m,children:{}};l[e]=m;-1==p||0==p?q&&(h[e+"sites"]=m):(p=e.substring(0,p),"undefined"!=typeof l[p]&&"undefined"!=typeof l[p].children&&(l[p].children[e.replace(/\\/g,"~|~")+"sites"]=m))}k.sort(function(a,b){return a.last_touch>b.last_touch?-1:1});for(var v=a.getClearRecentTime(),u=a.lpGetPref("recentUsedCount",10),f=0;f<k.length&&f<u;f++)k[f].last_touch<v||(b["recentlyused"+k[f].aid]={title:getSiteMenuTitle(k[f],!0),icon:a.geticonurl(k[f].fiid,!0)});0==array_length(b)?
b.recentlyused0={title:gs("None Available")}:(b.linebreak0=null,b.recentlyusedclear={title:gs("Clear Recent")});e=a.getmatchingsites(!1,!0,!1);var v=getMatchingSitesHtml(e),n=g_maxcharsmatch,s=MAXNAME;g_maxcharsmatch=33;MAXNAME=34;for(f=0;f<e.length;f++){g=e[f].aid;var m="matchedit"+g,p="matchcopyusername"+g,w="matchcopypassword"+g,x="matchcopyurl"+g,y="matchcopynote"+g,z="matchdelete"+g,t=[];t["matchfill"+g]={title:gs("AutoFill")};t[m]={title:gs("Edit")};getBG().can_copy_to_clipboard()&&(t[p]={title:gs("Copy Username")},
t[w]={title:gs("Copy Password")},t[x]={title:gs("Copy URL")},t[y]={title:gs("Copy Note")});t[z]={title:gs("Delete")};v["matchingsites"+e[f].aid]={title:getSiteMenuTitle(e[f],!1),icon:a.geticonurl(e[f].fiid,!1),children:t}}g_maxcharsmatch=n;MAXNAME=s;k.sort(function(a,b){return a.name.toLowerCase()<b.name.toLowerCase()?-1:1});for(f=0;f<k.length;f++){q&&"1"==k[f].fav&&"undefined"!=typeof h[gs("favorites")]&&"undefined"!=typeof h[gs("favorites")].children&&(h[gs("favorites")].children["site"+k[f].aid]=
{title:getSiteMenuTitle(k[f],!0),icon:a.geticonurl(k[f].fiid)});e=k[f].group;if(null==e||""==e)e=gs("(none)");m={title:getSiteMenuTitle(k[f],!0),icon:a.geticonurl(k[f].fiid)};q?"undefined"!=typeof l[e]&&"undefined"!=typeof l[e].children&&(l[e].children["site"+k[f].aid]=m):h["site"+k[f].aid]=m}j&&(h.linebreak0=null);h.siteadd={title:gs("Add Site")};k={};j=!1;n=[];q=[];for(g in a.g_securenotes)if(a.check_ident_aid(g)){j=!0;e=a.g_securenotes[g].group;if(null==e||""==e)e=gs("(none)");if(e!=gs("Secure Notes")){l=
e.split("\\");m="";for(f=0;f<l.length;f++)""!=m&&(m+="\\"),m+=l[f],lp_in_array(m,n)||(n[n.length]=m)}q[q.length]=a.g_securenotes[g]}k.noteadd={title:gs("Add Secure Note")};j&&(k.linebreak0=null);n.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});j=d&&1<n.length;l=[];for(f=0;f<n.length;f++)e=n[f],p=e.lastIndexOf("\\"),m=-1==p?e:e.substring(p+1),m={title:m,children:{}},l[e]=m,-1==p?j&&(k[e+"notes"]=m):(p=e.substring(0,p),"undefined"!=typeof l[p]&&"undefined"!=typeof l[p].children&&(l[p].children[e.replace(/\\/g,
"~|~")+"notes"]=m));q.sort(function(a,b){return a.name.toLowerCase()<b.name.toLowerCase()?-1:1});for(f=0;f<q.length;f++){e=q[f].group;if(null==e||""==e)e=gs("(none)");j&&e!=gs("Secure Notes")&&"undefined"!=typeof l[e]&&"undefined"!=typeof l[e].children&&(l[e].children["note"+q[f].aid]={title:q[f].name,icon:a.geticonurl(q[f].fiid)})}for(f=0;f<q.length;f++)if(e=q[f].group,!j||e==gs("Secure Notes"))k["note"+q[f].aid]={title:q[f].name,icon:a.geticonurl(q[f].fiid,!0)};q="undefined"!=typeof a.g_have_application?
a.g_have_application:!1;s={};n=[];j=[];for(g in a.g_applications)if(a.check_ident_appaid(g)){q=!0;e=a.g_applications[g].group;if(null==e||""==e)e=gs("(none)");if(e!=gs("Applications")){l=e.split("\\");m="";for(f=0;f<l.length;f++)""!=m&&(m+="\\"),m+=l[f],lp_in_array(m,n)||(n[n.length]=m)}j[j.length]=a.g_applications[g]}n.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});d=d&&1<n.length;l=[];for(f=0;f<n.length;f++)e=n[f],p=e.lastIndexOf("\\"),m=-1==p?e:e.substring(p+1),m={title:m,children:{}},
l[e]=m,-1==p?d&&(s[e+"applications"]=m):(p=e.substring(0,p),"undefined"!=typeof l[p]&&"undefined"!=typeof l[p].children&&(l[p].children[e.replace(/\\/g,"~|~")+"applications"]=m));j.sort(function(a,b){return a.name.toLowerCase()<b.name.toLowerCase()?-1:1});for(f=0;f<j.length;f++){e=j[f].group;if(null==e||""==e)e=gs("(none)");d&&e!=gs("Applications")&&("undefined"!=typeof l[e]&&"undefined"!=typeof l[e].children)&&(l[e].children["application"+j[f].appaid]={title:j[f].name,icon:a.geticonurlfromrecord(j[f]),
children:{}},a.g_is_win&&getBG().have_binary()&&(l[e].children["application"+j[f].appaid].children["applicationlaunch"+j[f].appaid]={title:gs("Launch")}),a.can_copy_to_clipboard()&&(l[e].children["application"+j[f].appaid].children["applicationcopyusername"+j[f].appaid]={title:gs("Copy Username")},l[e].children["application"+j[f].appaid].children["applicationcopypassword"+j[f].appaid]={title:gs("Copy Password")}),l[e].children["application"+j[f].appaid].children["applicationedit"+j[f].appaid]={title:gs("Edit")},
l[e].children["application"+j[f].appaid].children["applicationdelete"+j[f].appaid]={title:gs("Delete")})}for(f=0;f<j.length;f++)if(e=j[f].group,!d||e==gs("Applications"))g="application"+j[f].appaid,s[g]={title:j[f].name,icon:a.geticonurlfromrecord(j[f]),children:{}},"undefined"!=typeof s[g]&&"undefined"!=typeof s[g].children&&(a.g_is_win&&getBG().have_binary()&&(s[g].children["applicationlaunch"+j[f].appaid]={title:gs("Launch")}),a.can_copy_to_clipboard()&&(s[g].children["applicationcopyusername"+
j[f].appaid]={title:gs("Copy Username")},s[g].children["applicationcopypassword"+j[f].appaid]={title:gs("Copy Password")}),s[g].children["applicationedit"+j[f].appaid]={title:gs("Edit")},s[g].children["applicationdelete"+j[f].appaid]={title:gs("Delete")});d={};l=g=j=!1;for(f in a.g_formfills)a.check_ident_ffid(a.g_formfills[f].ffid)&&(j=!0,d["fillforms"+a.g_formfills[f].ffid]={title:a.g_formfills[f].decprofilename,icon:a.geticonFF(a.g_formfills[f].ffid)},0==a.g_formfills[f].profiletype&&(g=!0),""!=
a.g_formfills[f].ccnum&&(l=!0));if(j)for(f in d.linebreak0=null,d.editprofiles={title:gs("Edit"),children:{}},a.g_formfills)a.check_ident_ffid(a.g_formfills[f].ffid)&&"undefined"!=typeof d.editprofiles&&"undefined"!=typeof d.editprofiles.children&&(d.editprofiles.children["editprofile"+a.g_formfills[f].ffid]={title:a.g_formfills[f].decprofilename,icon:a.geticonFF(a.g_formfills[f].ffid)});d.addprofile={title:gs("Add Profile")};d.addcreditcard={title:gs("Add Credit Card")};d.clearforms={title:gs("Clear Forms")};
g&&(l&&!g_ismaxthon)&&(d.chooseprofilecc={title:gs("Choose Profile and Credit Card")});f=""!=a.g_identity?" ("+g_iname+")":"";a={logoff:{icon:"images/power_off.png",title:gs("Log Out:")+" "+a.g_username+f,cmd:"logoff"},linebreak1:null,vault:{icon:"images/icon_vault.png",title:gs("My LastPass Vault"),hotkey:"Ctrl+Alt+H",cmd:"vault",hidden:a.g_hidevault},recent:{icon:"images/icon_recent.png",title:gs("Recently Used"),children:b},matchingsites:{icon:"images/icon_recent.png",title:gs(""),children:v,hidden:!0},
sites:{icon:"images/icon_sites.png",title:gs("Sites"),children:h},notes:{icon:"images/icon_notes.png",title:gs("Secure Notes"),hidden:a.g_hidenotes,children:k},applications:{icon:"images/icon_applications.png",title:gs("Applications"),hidden:!q,children:s},formfill:{icon:"images/icon_formfill.png",title:gs("Fill Forms"),children:d},preferences:{icon:"images/icon_preferences.png",title:gs("Preferences"),cmd:"preferences"},help:{icon:"images/icon_help.png",title:gs("Help..."),cmd:"help"},tools:{icon:"images/icon_tools.png",
title:gs("Tools"),children:getTools(r,g_iname,c)},generate:{icon:"images/keyboard.png",title:gs("Generate Secure Password"),key:"Alt+G",cmd:"generate"},entconsole:{icon:"images/lock.png",title:gs("Admin Console"),cmd:"entconsole",hidden:!a.g_iscompanyadmin},linebreak2:null,premium:{icon:"images/icon_premium.png",title:gs("Go Premium!"),cmd:"premium",hidden:a.LPISLOC||a.g_hidegopremium},server:{icon:"images/icon_premium.png",title:gs("Upgrade to LastPass Online!"),cmd:"server",hidden:!a.LPISLOC},saveall:{icon:"images/icon_saveall.png",
title:gs("Save All Entered Data"),cmd:"saveall"},matchscroll:null};0==u&&delete a.recent;return a}
function getMatchingSitesHtml(a){var c={},b=getBG();g_maxcharsmatch=33;MAXNAME=34;for(var d=0;d<a.length;d++){var h=a[d].aid,g="matchedit"+h,e="matchcopyusername"+h,j="matchcopypassword"+h,n="matchcopyurl"+h,k="matchcopynote"+h,r="matchdelete"+h,l=[];l["matchfill"+h]={title:gs("AutoFill")};l[g]={title:gs("Edit")};getBG().can_copy_to_clipboard()&&(l[e]={title:gs("Copy Username")},l[j]={title:gs("Copy Password")},l[n]={title:gs("Copy URL")},l[k]={title:gs("Copy Note")});l[r]={title:gs("Delete")};c["matchingsites"+
a[d].aid]={title:getSiteMenuTitle(a[d],!1),icon:b.geticonurl(a[d].fiid,!1),children:l}}return c}function getToolsHtml(){var a="<div id='mainmenu'><div id='stdmenu'>",c=getTools(haveFav(),g_iname,{}),b;for(b in c)a=c[b]?a+("<div class='"+(c[b].children?"arrow":"")+"' id='"+ofa(b)+"'>"+of(c[b].title)+"<span></span></div>"):a+"<hr/>";return a+"</div></div>"}function haveFav(){var a=getBG();for(aid in a.g_sites)if(a.check_ident_aid(aid)&&"1"==a.g_sites[aid].fav)return!0;return!1}
function getTools(a,c,b){var d=getBG();return{seccheck:{icon:"images/tick.png",title:gs("Security Challenge"),hidden:d.LPISLOC||d.g_hideseccheck},identities:{icon:"images/icon_identities.png",title:gs("Identities")+" ("+of(c)+")",hidden:d.g_hideidentities,children:b},legacy:{icon:"",title:gs("LastPass Legacy"),hidden:!d.g_legacy_enabled||!is_user_premium()},console:{icon:"",title:gs("Debug Console"),hidden:!d.is_user_debug_enabled()},openfavorites:{icon:"images/icon_favorites.png",title:gs("Open Favorites"),
cmd:"openfavorites",hidden:!a||d.g_hideopenfavs},search:{icon:"images/search-icon-blue.gif",title:gs("Site Search"),key:"Alt+W",hidden:d.g_hidesearch||g_new_menu},recheck:{icon:"images/page_gear.png",title:gs("Recheck Page"),key:"Alt+I",hidden:d.g_hiderecheckpage||g_new_menu},about:{icon:"images/icon16.png",title:gs("About..."),hidden:d.g_hideabout},linebreak0:null,lpmoretools:{icon:"images/export.png",title:gs("Advanced Tools"),hidden:!g_new_menu,children:{search:{icon:"images/search-icon-blue.gif",
title:gs("Site Search"),key:"Alt+W",hidden:d.g_hidesearch},recheck:{icon:"images/page_gear.png",title:gs("Recheck Page"),key:"Alt+I",hidden:d.g_hiderecheckpage},refresh:{icon:"images/reload.gif",title:gs("Refresh Sites"),hidden:d.LPISLOC},clear:{icon:"images/computer_delete.png",title:gs("Clear Local Cache"),hidden:d.LPISLOC},update:{icon:"images/exclamation.png",title:gs("Check For Updates"),hidden:g_isopera||g_ismaxthon||d.g_hidecheckupdates},linebreak0:null,myaccount:{icon:"images/group_key.png",
title:gs("My Account"),hidden:!islastpass},sessions:{icon:"images/group_key.png",title:gs("Other Sessions"),hidden:d.LPISLOC||d.g_hidesessions},lpexport:{icon:"images/export.png",title:gs("Export To"),hidden:d.g_hideexport,children:{exportcsv:{title:gs("LastPass CSV File")},exportlastpass:{title:gs("LastPass Encrypted File"),hidden:!d.have_binary()},exportwlan:{title:gs("Wi-Fi Passwords"),hidden:!islastpass||!d.g_is_win||!d.have_binary()},exportformfill:{title:gs("Form Fill Profiles")}}}}},lpimport:{icon:"images/import.png",
title:gs("Import"),hidden:!g_isopera&&!is_opera_chromium()&&!g_ismaxthon&&!g_issafari&&!g_isfirefoxsdk||d.g_hideimport},importmenu:{icon:"images/import.png",title:gs("Import From"),hidden:d.g_hideimport||g_isopera||is_opera_chromium()||g_ismaxthon||g_issafari||g_isfirefoxsdk,children:{importgooglechrome:{title:gs("Google Chrome Password Manager"),hidden:!d.g_is_win&&!d.g_is_mac&&!d.g_is_linux},lpimport:{title:gs("Other"),hidden:d.LPISLOC}}},lpexport:{icon:"images/export.png",title:gs("Export To"),
hidden:d.g_hideexport||g_new_menu,children:{exportcsv:{title:gs("LastPass CSV File")},exportlastpass:{title:gs("LastPass Encrypted File"),hidden:!d.have_binary()},exportwlan:{title:gs("Wi-Fi Passwords"),hidden:!islastpass||!d.g_is_win||!d.have_binary()},exportformfill:{title:gs("Form Fill Profiles")}}},print:{icon:"images/printer.png",title:gs("Print"),hidden:d.g_hideprint,children:{printsites:{title:gs("Sites")},printnotes:{title:gs("Secure Notes"),hidden:d.g_hidenotes}}},update:{icon:"images/exclamation.png",
title:gs("Check For Updates"),hidden:g_isopera||g_ismaxthon||d.g_hidecheckupdates||g_new_menu},clear:{icon:"images/computer_delete.png",title:gs("Clear Local Cache"),hidden:d.LPISLOC||g_new_menu},refresh:{icon:"images/reload.gif",title:gs("Refresh Sites"),hidden:d.LPISLOC||g_new_menu},sessions:{icon:"images/group_key.png",title:gs("Other Sessions"),hidden:d.LPISLOC||d.g_hidesessions||g_new_menu},linebreak2:null,addsite:{icon:"images/site_add.png",title:gs("Add Site")},saveall:{icon:"images/icon_saveall.png",
title:gs("Save All Entered Data"),hidden:!g_new_menu},addnote:{icon:"images/note_add.png",title:gs("Add Secure Note"),hidden:d.g_hidenotes}}}
function rebuildmenu(){var a=g_isopera?' style="overflow-x:hidden;min-width:400px;"':"";g_hoverrow=null;var c;c='<div id="menutitle"></div>'+('<div id="backbutton1" class="backbutton"><img src="backarrow.png"/> '+gs("Back").toUpperCase()+"</div>");c+='<table cellspacing="0"><tr>';c+='<td>&nbsp;<div id="menu0"></div></td>';c+='<td>&nbsp;<div id="menu1"></div></td>';c+="</tr></table>";c+='<div id="backbutton2" class="backbutton"><img src="backarrow.png"/> '+gs("Back").toUpperCase()+"</div>";$("#menucontainer").html(c);
$(".backbutton").hover(function(){g_hoverrow=$(this).attr("id");setTimeout(function(){menuautoclick(g_hoverrow)},1E3);$(this).css({background:"url(backbgover.png) repeat-x"})},function(){g_hoverrow=null;$(this).css({background:"url(backbg.png) repeat-x"})}).click(function(){popmenu()});var b=getmenu();g_maxchars=40;g_maxcharsmatch=31;g_menuwidth=9*g_maxchars;g_menuwidthmatch=9*g_maxcharsmatch;"en-US"==getBG().lpGetPref("language","en-US")&&(g_maxcharsmatch=50);c="";var d,h,g;for(d in b)if("matchscroll"==
d){g=getBG().getnevers();h=!0;for(d in g){h&&(h=!1,c+='\n<div class="neverdiv"></div>');var e=gs("Never Add Site");"neverautologins"==g[d].type&&(e=gs("Never AutoLogin"));"nevergenerates"==g[d].type&&(e=gs("Never Generate Password"));"neverformfills"==g[d].type&&(e=gs("Never Fill Forms"));"nevershowicons"==g[d].type&&(e=gs("Never Show Context Icons"));1==g[d].domain&&(e+=" "+gs("(domain)"));c+="<div"+a+'">';c+='<div class="floatleft newmenurow" id="opendelete'+d+'" data-lptitle="'+ofja(e)+'">';c+=
'<div class="menuitemdiv" data-lpwidth="'+g_menuwidth+'" data-lpbackground="close.png">'+e+"</div>";c+='<img src="arrow.png">&nbsp;';c+="</div>";c+='<div class="clearboth"></div>';c+="</div>"}g=getBG().getmatchingsites();if(0<g.length)for(d in c+='\n<div class="matchingsitesdiv"></div>',g)g.hasOwnProperty(d)&&(h="match"+g[d].aid,e=getSiteMenuTitle(g[d],!1),c+="<div"+a+'">',c+='<div id="menurow'+ofja(h)+'" class="floatleft newmenurow" data-lptitle="'+ofja(e)+'">',c+='<div class="menuitemdiv" data-lpwidth="'+
g_menuwidthmatch+'" data-lpbackground="'+getBG().geticonurl(g[d].fiid)+'">'+ofja(e)+"</div>",c+='<img src="arrow.png" alt="expand"/>&nbsp;',c+='<div class="clearboth"></div>',c+="</div>",c+='<img src="fill.png" alt="autofill" class="cursorpointer" title="'+gs("AutoFill")+'" id="matchfill'+g[d].aid+'"/>&nbsp;',getBG().can_copy_to_clipboard()&&(c+='<img src="copyusername.png" alt="copyusername" class="cursorpointer" title="'+gs("Copy Username")+'" id="matchcopyusername'+g[d].aid+'"/>&nbsp;',c+='<img src="copypassword.png" alt="copypassword" class="cursorpointer" title="'+
gs("Copy Password")+'" id="matchcopypassword'+g[d].aid+'"/>&nbsp;',c+='<img src="copyurl.png" alt="copyurl" class="cursorpointer" title="'+gs("Copy URL")+'" id="matchcopyurl'+g[d].aid+'"/>&nbsp;'),c+="&nbsp;&nbsp;&nbsp;&nbsp;",c+='<div class="clearboth"></div>',c+="</div>")}else null==b[d]?c+='\n<div class="nulldiv"></div>':"premium"==b[d].cmd&&(getBG().g_premium_exp>lp_get_local_timestamp()||getBG().g_enterpriseuser)||(e=b[d].title,e.length>g_maxchars&&(e=e.substring(0,g_maxchars-3)+"..."),g="",
"undefined"!=typeof b[d].children?g=' data-lpmenurowtype="1" data-lptitle="'+ofja(e)+'"':"undefined"!=typeof b[d].cmd&&(g=' data-lpmenurowtype="2" data-lpcmd="'+ofja(b[d].cmd)+'"'),h="",b[d].hidden&&(h=" displaynone"),c+='<div id="menurow'+ofja(d)+'" class="newmenurow'+h+'"'+a+g+">",c+='<div class="menuitemdiv" data-lpwidth="'+g_menuwidth+'" data-lpbackground="'+b[d].icon+'">'+of(e)+"</div>","undefined"!=typeof b[d].children&&(c+='<img src="arrow.png" alt="expand"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'),
c+='<div class="clearboth"></div>',c+="</div>");c+="<div><br/><br/><br/></div>";pushmenu(c,"");resize_menu()}function getIdentityName(){var a=getBG(),c="";if(""==a.g_identity)c=gs("All");else for(var b in a.g_identities)if(a.g_identities[b].iid==a.g_identity){c=a.g_identities[b].deciname;break}return c}
function hasApplication(){if("undefined"!=typeof getBG().g_have_application&&getBG().g_have_application)return!0;for(var a in getBG().g_applications)if(getBG().check_ident_appaid(a))return!0;return!1}
function menu3(){lpdbg("menu","in menu3");var a=getBG();g_iname=getIdentityName();var c=""!=a.g_identity?" ("+g_iname+")":"",b=a.getmatchingsites(!1,!0,!1),d=b.length,h=parseInt(a.lpGetPref("toplevelmatchingsites",0)),g=1==parseInt(a.lpGetPref("usepopupfill",1)),e=0==d||h?" displaynone":"",j=getBG().can_copy_to_clipboard(),b=0!=d&&h?"<hr/>"+addKidsHtml("mainmenu",getMatchingSitesHtml(b),j,"top"):"",j="png";"undefined"!=typeof safari&&(j="png");var n=!a.g_hidevault?"<div id='vault' class=''><img id='vaultsvg' src='./images/vault."+
j+"'/><span></span><p>"+gs("My LastPass Vault")+"</p></div>":"",k=!a.g_hidenotes?"<div id='notes' class='arrow ricon'><img id='securenotesvg' src='./images/secure_note."+j+"'/><span></span><p>"+gs("Secure Notes")+"</p></div>":"",r=hasApplication()?"<div id='applications' class='arrow ricon'><span></span><p>"+gs("Applications")+"</p></div>":"",d="<div id='mainmenu'><div id='topbar'><input id='menusearch' type='text' class='iconize' placeholder='"+gs("Search LastPass Vault")+"'/><div id='xsearchbar'><img id='xsearchimg' src='images/search.png'/></div><div id='searchbar'></div></div><div id='searchresults' class='displaynone'></div><div id='stdmenu'>"+
n+"<div id='sites' class='arrow ricon'><img id='sitessvg' src='./images/sites."+j+"'/><span></span><p>"+gs("Sites")+"</p></div><div id='formfill' class='arrow ricon'><img id='formfillsvg' src='./images/formfill."+j+"'/><span></span><p>"+gs("Form Fills")+"</p></div><div id='generate' class='arrow ricon'><img id='generatesvg' src='./images/generate."+j+"'/><span></span><p>"+gs("Generate Secure Password")+"</p></div>"+k+r+"<hr/><div id='matchingsites' class='arrow"+e+"'>"+gs("Show Matching Sites")+"<span id='matchingnum'>"+
d+"</span><span></span></div><div id='recent' class='arrow'>"+gs("Recently Used")+"<span></span></div><hr/><div id='tools' class='arrow'>"+gs("Tools")+"<span></span></div><div id='preferences' class=''>"+gs("Preferences")+"<span></span></div><div id='help' class=''>"+gs("Help")+"<span></span></div>"+(a.g_iscompanyadmin?"<div id='entconsole' class=''>"+gs("Admin Console")+"<span></span></div>":"")+showPromo();2==getBG().g_lp_model&&null==localStorage_getItem("menupromo")&&(!getBG().g_enterpriseuser&&
getBG().g_premium_exp<=lp_get_local_timestamp()?d+="<div id='premium' class=''>"+gs("Upgrade to Premium")+"<span class='menux'></span></div>":getBG().g_enterpriseuser||(d+="<div id='enterprise' class=''>"+gs("Try LastPass Enterprise")+"<span class='menux'></span></div>"));d+="<hr/><div id='logoff' class='logoff'>"+gs("Log Out:")+" "+a.g_username+c+"<span></span></div>"+b+"</div></div>";lpdbg("menu","setting menucontainer html");$("#menucontainer").html(d);lpdbg("menu","set menucontainer html");g_isfirefoxsdk&&
(document.getElementById("menusearch").style.outlineStyle="solid",document.getElementById("xsearchbar").style.left="85%");focusme_style();document.getElementById("menusearch").addEventListener("keydown",function(a){menusearch_keydown(a)});document.getElementById("menusearch").addEventListener("keyup",function(a){menusearch_keyup(a)});document.getElementById("xsearchbar").addEventListener("click",function(){document.getElementById("menusearch").value="";populatemenu();document.getElementById("xsearchimg").src=
"images/search.png";document.getElementById("menusearch").focus()});$("#stdmenu").children("div").click(function(a){var b=a.target.id;""==b&&(b=a.target.parentNode.id);moveMenu(b,a)});$("#matchingnum").click(function(a){moveMenu("matchingsites",a)});$(".menux").click(function(){localStorage_setItem("menupromo","1");$("#premium").hide();$("#enterprise").hide();return!1});$(".menuxdark").click(function(){localStorage_setItem("giftpromo","1");$("#gift").hide();return!1});$("#menusearch").focus();h&&
($("#stdmenu").children("div").children("usericon").click(function(a){handlecopyclick(a,0)}),$("#stdmenu").children("div").children("passicon").click(function(a){handlecopyclick(a,1)}),g||$("#stdmenu").children("div").children("fillicon").click(function(a){menuaction("matchfill"+getaid(a.target.parentNode));a.stopPropagation();return!1}));g_kbselected=null;MAXNAME=60;g_maxcharsmatch=44;$(".ricon").mouseover(function(){null!==g_kbselected&&g_kbselected.removeClass("kbselected");g_kbselected=$("#"+
this.id);g_kbselected.addClass("kbselected");this.childNodes[0].style.opacity=1});$(".ricon").mouseout(function(){null!==g_kbselected&&g_kbselected.removeClass("kbselected");this.childNodes[0].style.opacity=0.6});setTimeout(function(){g_pointer=g_menu=getmenu();g_ids=[];g_pointer_stack=[]},0);g_isfirefoxsdk||(a=document.getElementById("menucontainer").clientHeight,document.getElementsByTagName("html")[0].style.height=document.getElementsByTagName("body")[0].style.height=a+"px");document.getElementById("menucontainer").style.display=
"none";setTimeout(function(){$("#menusearch").focus();document.getElementById("menucontainer").style.display="block"},100);setTimeout(function(){$("#menusearch").focus();document.getElementById("menucontainer").style.display="block"},300);setTimeout(function(){$("#menusearch").focus()},300);resize_menu()}
function showPromo(){if(!islastpass||getBG().g_enterpriseuser)return"";var a=new Date;return null==localStorage_getItem("giftpromo")&&(10==a.getMonth()&&25<=a.getDate()||11==a.getMonth()&&25>=a.getDate())?"<div id='gift'><img src='./images/gift.png'/><xicon class='menuxdark'></xicon><span></span><p>"+gs("Give the Gift of LastPass Premium")+"</p></div>":""}
function getaid(a){(a=a.id)&&0==a.indexOf("topmatchingsites")&&(a=a.substring(3));a&&0==a.indexOf("matchingsites")&&(a=a.substring(13));return a}function moveMenu(a,c){null==g_pointer&&(g_pointer=g_menu=getmenu());0==a.indexOf("topmatchingsites")&&(g_pointer=g_menu.matchingsites.children,a=a.substring(3));g_pointer[a]&&g_pointer[a].children?(c.stopPropagation(),c.preventDefault(),updateMenu(a)):menuaction(a)}
function addKidsHtml(a,c,b,d){var h;d||(d="");h="<input id='focusme' type='text' class='iconize'/>";var g=1==parseInt(getBG().lpGetPref("usepopupfill",1)),e;for(e in c)if(c[e]){if(!("undefined"!=typeof c[e].hidden&&c[e].hidden)){var j="",n="";"tools"!=a&&"lpmoretools"!=a?(n="undefined"!=typeof c[e].icon?"<img src='"+ofa(c[e].icon)+"'/>":"",c[e].children?j="arrow":c[e].icon&&"identities"!=a&&(j="hasaction")):j=c[e].children?"arrow":"";h+="<div class='"+j+"' id='"+ofa(d+e)+"'>"+n+of(c[e].title)+"<span></span>"+
(b?"<passicon title='"+gs("Copy Password")+"'></passicon><usericon title='"+gs("Copy Username")+"'></usericon>":"")+(b&&!g?"<fillicon title='"+gs("AutoFill")+"'></fillicon>":"")+"</div>"}}else h+="<hr/>";return h}
function updateMenu(a){var c="<div id='backrow'><span></span>"+gs("BACKUPPER")+"</div>",c=c+"<div id='mainmenu'><div id='stdmenu'>",b=g_pointer[a].children,d="matchingsites"==a&&getBG().can_copy_to_clipboard(),c=c+addKidsHtml(a,b,d);"matchingsites"==a&&(c+="<hr/><div id='movematching'>"+gs("Move matching sites to top menu")+"</div>");c+="</div></div>";g_pointer_stack.push(g_pointer);g_ids.push(a);g_pointer=b;$("#menucontainer").fadeOut(100,function(){$("#menucontainer").html(c);$("#menucontainer").fadeIn(100);
$("#stdmenu").children("div").click(function(a){moveMenu(a.target.id,a)});$("#stdmenu").children("div").bind("contextmenu",function(a){handleeditclick(a)});d&&($("#stdmenu").children("div").children("usericon").click(function(a){handlecopyclick(a,0)}),$("#stdmenu").children("div").children("passicon").click(function(a){handlecopyclick(a,1)}),$("#stdmenu").children("div").children("fillicon").click(function(a){menuaction("matchfill"+getaid(a.target.parentNode));a.stopPropagation();return!1}),$("#movematching").click(function(){getBG().lpPutUserPref("toplevelmatchingsites",
1);getBG().lpWriteAllPrefs();(g_isopera||g_ismaxthon||g_isfirefoxsdk)&&getBG().update_prefs("menu")}));"matchingsites"==a||"sites"==a||"tools"==a||"lpmoretools"==a||"applications"==a?$("#stdmenu").children("div").children("span").click(function(a){moveMenu(a.target.parentNode.id,a)}):$("#stdmenu").children("div").children("span").click(function(a){handleeditclick(a)});$("#backrow").click(function(){goback()});reInitKbSelected()});resize_menu()}
function handlecopyclick(a,c){var b=null;a&&(a.stopPropagation(),a.preventDefault(),b="contextmenu"==a.type&&"DIV"==a.target.tagName?a.target.id:a.target.parentNode.id);getBG();b&&0==b.indexOf("matchingsites")?b=b.substring(13):b&&0==b.indexOf("topmatchingsites")&&(b=b.substring(16));0==c?(getBG().lpevent("m_mcu"),getBG().copyusername(b)):1==c&&(getBG().lpevent("m_mcp"),getBG().copypassword(b));closemole()}
function goback(){g_kbselected=g_kbsubselected=null;if(1>=g_pointer_stack.length)document.getElementById("password_button")&&(document.getElementById("password_button").style.display="none"),menu3();else{g_pointer_stack.pop();g_ids.pop();g_pointer=g_pointer_stack.pop();var a=g_ids.pop();updateMenu(a)}}function get_key_code(a){a=a.charCode?a.charCode:a.keyCode?a.keyCode:a.which?a.which:0;9==a&&(a=40);return a}var g_kbselected=null;
function menusearch_keydown(a){var c=$("#stdmenu").is(":visible"),b=get_key_code(a);if(40==b||38==b){if(null==g_kbselected)if(c)g_kbselected=$("#stdmenu").children("div:first"),g_kbselected.addClass("kbselected");else{if(g_kbselected=$("#searchresults").children("div:first"))g_kbselected.addClass("kbselected"),$("#searchresults").scrollTop()}else{var d=40==b?g_kbselected.next():g_kbselected.prev();if(c){if(!d[0])return!1;for(;"DIV"!==d[0].tagName||-1<d[0].className.indexOf("displaynone");)d=40==b?
d.next():d.prev();g_kbselected.removeClass("kbselected");d.addClass("kbselected");g_kbselected=d}else d.length&&(g_kbselected.removeClass("kbselected"),d.addClass("kbselected"),g_kbselected=d,scrollSelected(40==b))}$("#menusearch").focus();a.preventDefault();a.stopPropagation();return!1}if(39==b||13==b)return c&&(g_kbselected.click(),g_kbselected=null),!1;37==b&&(a=document.getElementById("backrow"),"backbtn"!==typeof backbt&&a.click());return!0}var g_kbsubselected=null;
function invisiblenavs_key(a){if(document.getElementById("invisiblenav"))if(a=get_key_code(a),37==a)goback();else if(13==a)g_kbsubselected.click();else if(40==a||38==a)if(null==g_kbsubselected){if(g_kbsubselected=$("#stdmenu").children("div:first"))g_kbsubselected.addClass("kbselected"),$("#stdmenu").is(":visible")||$("#stdmenu").scrollTop()}else{var c=40==a?g_kbsubselected.next():g_kbsubselected.prev();c.length&&(g_kbsubselected.removeClass("kbselected"),c.addClass("kbselected"),g_kbsubselected=
c,scrollSelected(40==a))}}
function menusearch_keyup(a){""==document.getElementById("menusearch").value?document.getElementById("xsearchimg").src="images/search.png":document.getElementById("xsearchimg").src="images/cancel.png";var c=get_key_code(a);if(40!=c&&38!=c&&13!=c&&39!=c)return g_kbselected&&(g_kbselected.removeClass("kbselected"),g_kbselected=null),populatemenu(),!0;13==c&&g_kbselected?(c=g_kbselected.attr("id"),menuaction("site"+c)):39==c&&g_kbselected&&(c=g_kbselected.attr("id"),handleeditclick(a,c));$("#menusearch").focus();
a.preventDefault();a.stopPropagation();return!1}function scrollSelected(a){var c=$("#searchresults").height(),b=g_kbselected.height(),d=$("#searchresults").scrollTop();if(a)g_kbselected.position().top>c&&(a=g_kbselected.position().top+d-b-15,$("#searchresults").animate({scrollTop:a},100));else if(g_kbselected.position().top<b){a=d-g_kbselected.position().top-b-15;if(0>a||a<b)a=0;$("#searchresults").animate({scrollTop:a},20)}}
function clearsearch(){$("#searchresults").fadeOut(200,function(){$("#stdmenu").fadeIn(200)})}
function populatemenu(){var a=$("#menusearch").val();if(""==a)clearsearch();else{$("#stdmenu").is(":visible")&&$("#stdmenu").fadeOut(200,function(){$("#searchresults").fadeIn(200)});var c=getBG(),b=c.g_prompts.edit_sn_prompt?!1:c.get_searchNotesPref(),a=search_results(a,b,"searchresults",!0);a.sort(getBG().lp_sort_case_insensitive_name);b="";if(a.length)for(var d in a)var h=c.geticonurl(a[d].fiid,"http://sn"==a[d].url),g="undefined"!=typeof a[d].appaid?"app"+a[d].appaid:a[d].aid,e=getSiteMenuTitle(a[d],
!0),b=b+("<div id='"+ofa(g)+"'><img src='"+h+"'/>"+of(e)+"<span></span></div>");else b+="<p class='noresults'>"+gs("No matches found. Please search again.")+"</p>";$("#searchresults").html(b);$("#searchresults").children("div").click(function(a){handlelaunchclick(a)});$("#searchresults").children("div").children("span").click(function(a){handleeditclick(a)});$("#searchresults").children("div").bind("contextmenu",function(a){handleeditclick(a)});resize_menu();setTimeout(resize_menu,1E3);setTimeout(resize_menu,
2E3)}}
function handleeditclick(a,c){a&&(a.stopPropagation(),a.preventDefault(),"contextmenu"==a.type&&"DIV"==a.target.tagName?c=a.target.id:"keyup"!=a.type&&(c=a.target.parentNode.id));if("movematching"!=c){getBG();var b="match"+c;if(0==c.indexOf("site"))c=c.substring(4);else if(0==c.indexOf("recentlyused"))c=c.substring(12),b=getBG().g_securenotes[c]?"match_note"+c:"match"+c;else if(0==c.indexOf("note"))c=c.substring(4),b="match_note"+c;else if(0==c.indexOf("fillforms"))c=c.substring(9),b="match_ff"+c;
else if(0==c.indexOf("application")){moveMenu(c,a);return}if(b=findmatchmenuchildren(b,a)){var d="<div id='backrow'><span></span>"+gs("BACKUPPER")+"</div>",d=d+getnameandfavicon(c),d=d+"<input id='invisiblenav' type='hidden'><div id='mainmenu'><div id='stdmenu'>",h;for(h in b)d+="<div id='"+ofa(h)+"'>"+of(b[h].title)+"</div>";d+="</div></div>";g_pointer_stack.push(g_pointer);g_ids.push(c);g_pointer=null;$("#menucontainer").fadeOut(100,function(){$("#menucontainer").html(d);$("#menucontainer").fadeIn(100);
$("#stdmenu").children("div").click(function(a){menuaction(a.target.id)});$("#backrow").click(function(){goback()});-1==g_submenulistener&&(g_submenulistener=document.body.addEventListener("keydown",function(a){invisiblenavs_key(a)}))});resize_menu()}}}
function getnameandfavicon(a){var c=!1,b=getBG().g_sites[a];b||(b=getBG().g_securenotes[a],c=!0);if(b)return a=getBG().geticonurl(b.fiid,c),"<hr/><div class='editname'><img src='"+a+"'/> "+of(b.name)+"</div><hr/>";for(var d in getBG().g_formfills)if(b=getBG().g_formfills[d],b.ffid==a)return a=getBG().geticonFF(a),"<hr/><div class='editname'><img src='"+a+"'/> "+of(b.decprofilename)+"</div><hr/>";return""}function handlelaunchclick(a){menuaction("site"+a.target.id)}
function pushmenu(a,c){var b=$("#menu0"),d=$("#menu1"),h=d.width(),g=!1;g_is_mac&&b.scrollTop(0);if(a){g_menus.push(a);if(1==g_menus.length){b.html(a);setup_event_handlers();return}d.html(a)}var e=Math.abs(parseInt(b.css("margin-left").replace("px","")));e<g_menuwidth&&(e=e+g_menuspeed<g_menuwidth?e+g_menuspeed:g_menuwidth,b.css("margin-left",-e+"px"),e==g_menuwidth?b.hide():g=!0);2!=g_menus.length&&h<g_menuwidth&&(0==h&&d.show(),h=h+g_menuspeed<g_menuwidth?h+g_menuspeed:g_menuwidth,d.width(h),g=
!0);g?setTimeout(function(){pushmenu(null,es(c))},0):(b.html(d.html()).css("margin-left","0px"),d.hide().html("").css("width","0px"),b.show(),setTimeout(function(){menuconnectevents()},100),c=quoteprettyprint(c),g_menutitles.push(c),$("#menutitle").html(of(c)).show(),$(".backbutton").show());setup_event_handlers()}
function popmenu(a){var c=$("#menu0"),b=$("#menu1"),d=b.width(),h=!1;a||(c.hide().html(g_menus[g_menus.length-2]).css("margin-left",g_menuwidth+"px"),b.css("width",g_menuwidth+"px").html(g_menus[g_menus.length-1]).show(),g_menus.pop(),d=g_menuwidth);0<d&&(d=0<d-g_menuspeed?d-g_menuspeed:0,b.width(d),0==d?b.hide():h=!0);a=Math.abs(parseInt(c.css("margin-left").replace("px","")));a==g_menuwidth&&c.show();0<a&&(a=0<a-g_menuspeed?a-g_menuspeed:0,c.css("margin-left",-a+"px"),h=!0);h?setTimeout(function(){popmenu(1)},
0):(b.html(""),setTimeout(function(){menuconnectevents()},100),g_menutitles.pop(),1==g_menus.length?($("#menutitle").hide().html(""),$(".backbutton").hide()):$("#menutitle").html(of(g_menutitles[g_menutitles.length-1])));setup_event_handlers()}
function menuconnectevents(){$(".newmenurow").hover(function(){g_hoverrow=$(this).attr("id");setTimeout(function(){menuautoclick(g_hoverrow)},1E3);var a=$(this).css({background:"#316AC5",color:"#fff"});"undefined"!=typeof a.children&&a.children("img").attr("src","arrowon.png")},function(){g_hoverrow=null;var a=$(this).css({background:"#fff",color:"#000"});"undefined"!=typeof a.children&&a.children("img").attr("src","arrow.png")})}
function menuautoclick(a){if(g_autoclickenabled&&a==g_hoverrow)if(g_hoverrow=null,"backbutton1"==a||"backbutton2"==a)$("#"+a).click();else{var c=a.substring(7),b=0==c.indexOf("match")?"match":null;null!=getmenuchildren(c,b)&&$("#"+a).click()}}
function menuopen(a,c,b){var d=g_isopera?' style="overflow-x:hidden;min-width:400px;"':"";L("menuopen cmd="+a+" menutitle="+b);c=getmenuchildren(a,c);if(null==c)L("No children for cmd="+a+" menutitle="+b);else{a="";var h,g,e,j;for(j in c)if(g=c[j],null==g)a+='\n<div class="nulldiv"></div>';else{e=g.title;e.length>g_maxchars&&(e=e.substring(0,g_maxchars-3)+"...");h=' data-lptitle="'+ofja(e)+'"';h="undefined"!=typeof g.children?h+' data-lpmenurowtype="1"':h+' data-lpmenurowtype="3"';bgicon="undefined"!=
typeof g.icon?' data-lpbackground="'+g.icon+'"':"";var n="";g.hidden&&(n=" displaynone");a+='<div id="menurow'+ofja(j)+'" class="newmenurow'+n+'"'+d+h+">";a+='<div class="menuitemdiv" data-lpwidth="'+g_menuwidth+'"'+bgicon+'">'+of(e)+"</div>";"undefined"!=typeof g.children&&(a+='<img src="arrow.png" alt="expand"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;');a+='<div class="clearboth"></div>';a+="</div>"}pushmenu(a,b)}}function addslashes(a){a=a.replace(/'/g,"\\'");return a=a.replace(/"/g,'\\"')}
function quoteprettyprint(a){a=a.replace(/\\\\\\/g,"\\");a=a.replace(/\\'/g,"'");return a=a.replace(/\\"/g,'"')}function menuopendelete(a,c){var b="",d=gs("Delete"),b=b+('<div data-lpmenurowtype="4" id="menurow'+es(a)+'" class="newmenurow">'),b=b+('<div class="menuitemdiv" data-lpwidth="'+g_menuwidth+'">'+ofja(d)+"</div>"),b=b+'<div class="clearboth"></div></div>';pushmenu(b,c)}function getmenuchildren(a,c){var b=null;return"match"==c&&(b=findmatchmenuchildren(a),null!=b)?b:findmenuchildren(a)}
function findmenuchildren(a,c){var b,d="undefined"==typeof c?getmenu():c,h;for(h in d){b=addslashes(h);if(h==a||b==a)return null==d[h]||"undefined"==typeof d[h].children?null:d[h].children;if(null!=d[h]&&"undefined"!=typeof d[h].children&&(b=findmenuchildren(a,d[h].children),null!=b))return b}return null}
function findmatchmenuchildren(a){if(0!=a.indexOf("match"))return null;var c={},b=!0,d=!0,h=!0,g=!0,e=!1,j=!0,n=!1,k=null,r=!1,l=!1;if(0==a.indexOf("match_noautofill"))b=!1,n=!0,k=a.substring(16);else if(0==a.indexOf("match_note"))r=!0,k=a.substring(10);else{if(0==a.indexOf("match_ff"))return k=a.substring(8),c["editprofile"+k]={title:gs("Edit")},c["fillforms"+k]={title:gs("Fill")},c;if(0==a.indexOf("matcheditprofiles"))return null;if(0==a.indexOf("matcheditprofile"))return k=a.substring(16),c["editprofile"+
k]={title:gs("Edit")},c["fillforms"+k]={title:gs("Fill")},c;if(0==a.indexOf("matchsite"))k=a.substring(9);else if(a.match(/^match(app)?\d/))k=a.substring(5),r="undefined"!=typeof getBG().g_securenotes[k],l=is_application(k);else return null}r?(g=b=!1,e=!0,j=!1,n=!0,h="undefined"!=typeof getBG().g_securenotes[k]&&"undefined"!=typeof getBG().g_securenotes[k].notetype?getBG().g_securenotes[k].notetype:"",d="undefined"!=typeof sntemplates[h]&&"undefined"!=typeof sntemplates[h].Username,h="undefined"!=
typeof sntemplates[h]&&"undefined"!=typeof sntemplates[h].Password):l&&(j=g=b=!1);if(b){b=!1;a=getBG().getmatchingsites(!1,!0,!1);for(r=0;r<a.length;r++)if(a[r].aid==k){b=!0;break}}a="matchedit"+k;var r="matchfill"+k,l="matchcopyusername"+k,m="matchcopypassword"+k,f="matchcopyurl"+k,q="matchcopynote"+k,u="matchdelete"+k,k="matchgotourl"+k;n&&(c[a]={title:gs("Edit")});b&&(c[r]={title:gs("AutoFill")});getBG().can_copy_to_clipboard()&&(d&&(c[l]={title:gs("Copy Username")}),h&&(c[m]={title:gs("Copy Password")}),
g&&(c[f]={title:gs("Copy URL")}),e&&(c[q]={title:gs("Copy Note")}));n||(c[a]={title:gs("Edit")});j&&(c[k]={title:gs("Go to URL")});c[u]={title:gs("Delete")};return c}function focusme_style(){var a=document.getElementById("focusme");a&&(a.style.width="0px",a.style.height="0px",a.style.position="absolute",a.style.border="none",a.style.outline="none")}
function reInitKbSelected(){var a=document.getElementById("focusme");a&&$("#stdmenu").is(":visible")&&(focusme_style(),g_isfirefoxsdk&&(a.value=" "),a.addEventListener("keydown",function(a){menusearch_keydown(a)}),a.addEventListener("keyup",function(a){menusearch_keyup(a)}),a.focus())}function resize_menu(){g_isfirefoxsdk&&setTimeout(function(){getBG().resize_panel(390,$(document.body).height()+2,!0)},125)};
