LPServer=function(){var m=null,d=null,s,t=function(a,b){var c=a,e={},n;for(n in c){var d=c[n]||"";if("object"===typeof d)for(var h in d)e[n+"["+h+"]"]=d[h];else e[n]=d}a=e;b=b||"";var c=[],f;for(f in a)e=a[f],"object"===typeof e?c=c.concat(t(e,f)):(b&&(f=b+"["+f+"]"),c.push(f+"="+encodeURIComponent(e)));return c};s=function(a){return t(a).join("&")};var u=function(a){var b=s(a.data),c=new XMLHttpRequest;a.success&&(c.onload=function(){if(4===c.readyState)if(200===c.status)switch(a.dataType){case "xml":a.success(c.responseXML,
c.responseText);break;case "json":var b=null;try{b=JSON.parse(c.responseText)}catch(e){}a.success(b,c.responseText);break;default:a.success(c.responseText)}else a.error&&a.error(c,c.statusText)});a.error&&(c.onerror=function(){a.error(c,c.statusText)});var e=a.url;"GET"===a.type&&0<b.length&&(e=a.url+"?"+b);c.open(a.type||"GET",e,!0);"POST"===a.type?(c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.send(b)):c.send()},v=function(a){return function(){a()}},h=function(a,b,c,e){f(a,
b,c,e)||b.error(c)},f,w=function(a,b,c,e){return a&&(a=a[c],"function"===typeof a)?(a(e,b),!0):!1};f=function(a,b,c,e){a=w(a,b,c,e);return a=w(b.callbacks,b,c,e)||a};var x=function(a,b){try{g.logException(a)}catch(c){}a instanceof k?b.error(a.message):b.error()},B=function(a,b){return function(c,e){try{f(a,b,e)||(null===c&&e?b.error("invalidxml"):A(c,a,b))}catch(d){x(d,b)}}},l=function(a,b){var c=a.getElementsByTagName(b);return 0<c.length?c[0]:null},p=function(a,b){var c=l(a,b);return c?c.textContent:
""},A=function(a,b,c){var e=l(a,"result"),d=l(a,"ok"),j=l(a,"error"),g=l(a,"failed");if(e){var d=e.getAttribute("rc"),j=e.getAttribute("msg"),g=e.getAttribute("success"),k=e.getAttribute("ok");if(d){h(b,c,d,e);return}if(j){h(b,c,j,e);return}if(g){h(b,c,g,e);return}if(k){h(b,c,"ok");return}e=e.textContent.trim();if("ok"===e){if(!f(b,c,"ok")){h(b,c,p(a,"status"));return}}else if("bad"===e){c.error(p(a,"message"));return}}else{if(d){h(b,c,"ok",d);return}if(j){f(b,c,j.getAttribute("cause"),j)||h(b,c,
j.getAttribute("message"),j);return}if(g){h(b,c,g.getAttribute("reason"),g);return}}"function"===typeof c.error&&c.error()},C=function(a,b){return function(c,e){try{if(null===c&&e)b.error("invalidjson");else{if(c.error){h(a,b,c.error,c);return}if(c.res)if("success"===c.res){if(f(a,b,c.res,c))return}else{h(a,b,c.res,c);return}else if(f(a,b,c.reason,c)||f(a,b,c.status,c)||f(a,b,c.cmd,c))return}if(a&&"function"===typeof a["default"])a["default"](c,b);else"function"===typeof b.success&&b.success(c)}catch(d){x(d,
b)}}},q=function(a){a.userSupplied=a.userSupplied||{};a.type=void 0===a.type?"POST":a.type;a.url=g.getBaseURL()+a.url;if(a.userSupplied.requestArgs)for(var b in a.userSupplied.requestArgs)a.userSupplied.requestArgs[b]&&(a.data[b]=a.userSupplied.requestArgs[b]);a.userSupplied.error&&(a.error=v(a.userSupplied.error));if(a.data&&void 0===a.data.token&&(void 0===a.CSRFToken||a.CSRFToken)){if(null===m){b=a.userSupplied.error;g.ajax({type:"POST",url:g.getBaseURL()+"getCSRFToken.php",success:function(b){m=
b;a.data.token=m;g.ajax(a)},error:v(b)});return}a.data.token=m}g.ajax(a)},y=function(a,b){var c={};switch(typeof b.success){case "string":c[b.success]=b.userSupplied.success;b.success=a(c,b.userSupplied);break;case "function":c["default"]=b.success;b.success=a(c,b.userSupplied);break;default:if(b.callbacks||b.userSupplied&&(b.userSupplied.success||b.userSupplied.callbacks))b.success=a(b.callbacks,b.userSupplied)}},z=function(a,b,c){c=c||[];for(var e in b){var d=a[e],f=b[e];if("object"===typeof f)z(d,
f,c.concat(e));else if(typeof d!==f)throw c.push(e),"Extension is missing the following property: "+c.join(".")+" ("+f+")";}},r=function(a,b,c){a=a.getAttribute(b);return void 0===a?c:a},D={StringUtils:{translate:"function"},AES:{Encrypt:"function",Decrypt:"function",hex2bin:"function",bin2hex:"function"},enc:"function",dec:"function",RSAKey:"function",createRandomHexString:"function",parse_public_key:"function",parse_private_key:"function",enccbc:"function",make_lp_key_iterations:"function",make_lp_hash_iterations:"function"},
E={RSAKey:!0},g={ajax:u,translate:function(){return d.StringUtils.translate.apply(d.StringUtils,arguments)},logException:function(){},hex2bin:function(){return d.AES.hex2bin.apply(d.AES,arguments)},bin2hex:function(){return d.AES.bin2hex.apply(d.AES,arguments)},encryptAES:function(a,b){return 0<a.length?d.AES.Encrypt({pass:b,data:a,b64:!0,bits:256}):a},decryptAES:function(a,b){return d.AES.Decrypt({pass:b,data:a,b64:!0,bits:256})},encrypt:function(a,b){return d.enc(a,b)},decrypt:function(a,b){try{return d.dec(a,
b)}catch(c){return""}},createRandomHexString:function(){return d.createRandomHexString.apply(d,arguments)},parsePublicKey:function(){return d.parse_public_key.apply(d,arguments)},parsePrivateKey:function(a,b){b=b||d.rsaprivatekeyhex;if(!b)throw"rsaprivatekeyhex required for this action.";return d.parse_private_key(a,b)},extractPrivateKey:function(a,b){return d.rsa_extract_privatekey(a,b)},encryptCBC:function(){return d.enccbc.apply(d,arguments)},makeKey:function(){return d.make_lp_key_iterations.apply(d,
arguments)},makeHash:function(){return d.make_lp_hash_iterations.apply(d,arguments)},getBaseURL:function(){return d.base_url||""},getLocalKey:function(){return d.g_local_key},setLocalKey:function(a){d.g_local_key=a}},k=function(a){this.message=a;this.stack=Error().stack};k.prototype=Object.create(Error.prototype);k.prototype.name="ClientException";k.prototype.constructor=k;return{ajax:u,getRecordsFromResponse:function(a,b,c){for(var e=[],d=0;d<c;++d)e.push(r(a,b+d));return e},jsonRequest:function(a){y(C,
a);a.dataType="json";q(a)},xmlRequest:function(a){y(B,a);a.dataType="xml";q(a)},textRequest:function(a){a.dataType="text";q(a)},initialize:function(a,b){z(a,D);for(var c in b)g[c]=b[c];for(var e in E)g[e]=a[e];d=a},ext:g,getNodes:function(a,b){return a.getElementsByTagName(b)},getNode:l,getNodeText:p,getAttr:r,getAttrInt:function(a,b,c){a=parseInt(r(a,b,c));return isNaN(a)?c:a},extend:function(a){a=a||{};for(var b=1,c=arguments.length;b<c;++b){var e=arguments[b],d;for(d in e)a[d]=e[d]}return a},extendCallback:function(a,
b){return function(){b.apply(window,arguments);a&&a.apply(window,arguments)}},ClientException:k,clearCSRFToken:function(){m=null}}}();
