var gLastLoginState=0,gAccts_version=-1,gCurr_username="",gTimerId=null,gIconsLength=0,gLastSearch="",gIdentity="",gSearchWhileType=!0,gTreeHeightOffset=147,gPollInterval=500,gHidePreferences=!1,gLocalBaseUrl="",g_hideprofilecopy=1,g_hideidentcopy=1,g_localvault=1,g_showrows=1,g_autoselectcredmontab=0,g_partnername="",g_hideenterprisetab=!1,g_CNTsearch_it=0,g_CNTsearch_string_tokenize=0,g_CNTinit_vault=0,g_CNTpopulate=0,g_CNTsearch_tree=0,g_CNTclear_tree=0,event_handlers={},event_handlers_onmouseover=
{},event_handlers_onmouseout={},event_handlers_onclick={},styles={},VIEWS={TREE:0,GRID:1},g_view=VIEWS.TREE,g_groupidmap=[],g_idgroupmap=[],g_dolegacy=null;function getpartnerurl(a){""!=g_partnername&&(a+=(0<=a.indexOf("?")?"&":"?")+"partnername="+encodeURIComponent(g_partnername));return a}function fix_group(a){a==g_xlat_none&&(a="");return a}
function onLoad(a,b){try{if("undefined"!=typeof g_is_safari&&"undefined"==typeof LPFromWebsite)50>a?(a++,setTimeout(function(){onLoad(a)},25)):document.location.href=document.location.href;else if("undefined"==typeof g_is_safari&&!b)get_data("vault",function(){onLoad(a,!0)});else if("function"!=typeof getBG||"undefined"==typeof getBG()||null==getBG())setTimeout(function(){onLoad()},50);else{var c=getBG();g_urlprefix=c.base_url;var f=document.createElement("base");f.href=g_urlprefix;document.head.appendChild(f);
0<document.location.href.lastIndexOf("/")&&(gLocalBaseUrl=document.location.href.substr(0,document.location.href.lastIndexOf("/")+1));c.LPISLOC&&(document.getElementById("accountsettingscontainer").style.display="none");c.g_hideidentities&&(document.getElementById("identitycontainer").style.display="none");c.g_hideseccheck&&(document.getElementById("seccheckcontainer").style.display="none");refresh_legacy_link(document);sr(document,"submit","value","Searchproper");document.getElementById("q").setAttribute("placeholder",
gs("Search Vault"));LP_decimate_children(document.getElementById("lpusername"));var g=document.createElement("b"),j=document.createElement("a");j.setAttribute("href","");j.id="lpusernamelink";set_innertext(j,gs("Login"));g.appendChild(j);document.getElementById("lpusername").appendChild(g);onResize();inittabs();setusernametext(c.g_username);g_view==VIEWS.GRID&&grid_init_vault_search();$("#gridview").click(function(){g_view=VIEWS.GRID;populate(gLastSearch);showView()});$("#listview").click(function(){g_view=
VIEWS.TREE;populate(gLastSearch);showView()});gTimerId=setInterval(function(){checkLoggedInHome()},gPollInterval);var k=getcolvisibility("usernamecol"),h=getcolvisibility("ltnamecol");document.getElementById("usercol").className=k?"usercolvisible":"usercolhidden";document.getElementById("ltcol").className=h?"ltcolvisible":"ltcolhidden";document.getElementById("ltcol").style.paddingRight=k?"calc(5% + 20px)":"5%";create_combo("grpsel",[]);document.getElementById("grpsel_combo").style.height="150px";
document.getElementById("grpsel_combo").style.overflow="auto";document.getElementById("q").focus();c&&convert_object_to_array(c.g_identities).length?showhide_ident_actions(I_SHOW):showhide_ident_actions(I_HIDE);document.getElementById("addsecurenote").style.display=c.g_hidenotes?"none":"block";document.getElementById("lpimport").style.display=c.g_hideimport?"none":"block";document.getElementById("lpexport").style.display=c.g_hideexport?"none":"block";g_xlat_runame=gs("recently usedlower");g_xlat_pendingname=
gs("(New Pending Share Offers)");g_xlat_favorites=gs("favorites");g_xlat_edit=gs("Edit");g_xlat_delete=gs("Delete");g_xlat_share=gs("Share");g_xlat_none=gs("(none)");g_xlat_chpw=gs("Change Password");getBG().VaultToggle.supportsVault4_0()||(document.getElementById("vaultToggle").style.display="none")}}catch(p){alert("homelocal2 onLoad:"+p)}}function onUnLoad(){gTimerId&&(clearInterval(gTimerId),gTimerId=null);saveGroupState()}
function onResize(){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.height=document.body.clientHeight-gTreeHeightOffset+20+"px");document.getElementById("thetree")&&(document.getElementById("thetree").style.height=document.body.clientHeight-gTreeHeightOffset-14+"px");document.getElementById("thegrid")&&(document.getElementById("thegrid").style.height=document.body.clientHeight-gTreeHeightOffset+20+"px")}
function checkLoggedInHome(a){try{var b=getBG(),c=b.lploggedin;if(("undefined"!=typeof g_issafari&&g_issafari||"undefined"!=typeof g_isopera&&g_isopera||"undefined"!=typeof g_ismaxthon&&g_ismaxthon||"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk)&&!a)b.update_state("vault");else{a="";c&&(a=b.g_username,refresh_ident_actions());if(c!=gLastLoginState||a!=gCurr_username)if(g_cachedOpenGroups=null,c)window_load_loggedin(a);else{try{var f={"static":"{}"};g_view==VIEWS.TREE?$(function(){$("#thetree").tree({data:{type:"json",
opts:f}})}):($("#thegrid").scrollTop(),$("#thegrid").empty())}catch(g){}finish_vault_search();g_lastnodeid=g_rootnodeid=null;window_load_loggedoff();update_identity_popup()}gLastLoginState=c;g_username=lpusername=gCurr_username=a;if(gLastLoginState){var j=b.g_local_accts_version;if(j>gAccts_version||b.IsIconsUpdated(gIconsLength)||b.g_identity!=gIdentity)window_load_loggedin(a),finish_vault_search(),gAccts_version=j,massoperation=!0,populateNewData(gLastSearch),massoperation=!1,saveGroupState(),populateff(gLastSearch),
populateident(gLastSearch),update_identity_popup(),setusernametext(a),showads()}}}catch(k){alert("checkLoggedInHome:"+k)}}
function setusernametext(a){var b=getBG(),c=document.getElementById("lplogoff");if(b.lploggedin){c.style.display="block";var c="",f;for(f in b.g_identities)if(b.g_identities.hasOwnProperty(f)&&b.g_identity==b.g_identities[f].iid){c=b.g_identities[f].deciname;break}""==c?set_innertext(document.getElementById("lpusername"),of(a)):set_innertext(document.getElementById("lpusername"),of(a+" ("+c+")"))}else LP_decimate_children(document.getElementById("lpusername")),a=document.createElement("b"),b=document.createElement("a"),
b.setAttribute("href",""),b.id="lpusernamelink",set_innertext(b,gs("Login")),a.appendChild(b),document.getElementById("lpusername").appendChild(a),c&&(c.style.display="none")}
function window_load_loggedin(a){var b=getBG();document.getElementById("identity").disabled=0;document.getElementById("enterpriseaction").style.display=!g_hideenterprisetab&&getBG().g_iscompanyadmin?"list-item":"none";document.getElementById("enterprise").style.display=g_hideenterprisetab||"1"==getBG().g_enterpriseuser?"none":"table-cell";"1"==b.g_enterpriseuser&&(document.getElementById("lpfriendemail").style.display=document.getElementById("lpgift").style.display="none");document.getElementById("addsharedfolder").style.display=
b.g_folder_sharing_enabled?"list-item":"none";document.getElementById("shares").style.display=b.g_hidesharing||!b.g_folder_sharing_enabled?"none":"table-cell";document.getElementById("credmon").style.display="1"==getBG().g_showcredmon?"table-cell":"none";document.getElementById("linkpersonal").style.display="1"==getBG().g_enterpriseuser&&!g_hideenterprisetab&&""==get_personal_linked()?"list-item":"none";document.getElementById("removepersonal").style.display="1"==getBG().g_enterpriseuser&&!g_hideenterprisetab&&
""!=get_personal_linked()?"list-item":"none";setusernametext(a);getBG().get_securityChallengeScore(function(a){var b=!1,g;for(g in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(g)){b=!0;break}a&&b&&(document.getElementById("securitycheckscore").style.display="block",document.getElementById("securitycheckscore").style.color="#fff",document.getElementById("securitycheckscore").style.backgroundColor=getscorecolor(a),set_innertext(document.getElementById("securitycheckscore"),parseInt(a)+"%"),document.getElementById("securitycheckscore").style.display=
"inline")});refresh_legacy_link(document);g_local_key=getBG().g_local_key;g_key_iterations=getBG().get_key_iterations(a)}
function showads(){getBG().lploggedin&&getBG().g_premium_exp<lp_get_local_timestamp()&&"1"!=getBG().g_enterpriseuser&&-1==document.location.href.indexOf("cmd=video")?("none"==getComputedStyle(document.getElementById("adframe")).display&&(document.getElementById("adframe").style.display="block",document.getElementById("rightside").style.display="block",document.getElementById("adframe").setAttribute("src",getpartnerurl(g_urlprefix+"ads.php?nobr=1&noga=1&rand="+Math.floor(1E3*Math.random())))),document.getElementById("friend").style.display=
"block"):(document.getElementById("adframe").style.display="none",document.getElementById("rightside").style.display="none",document.getElementById("friend").style.display="none")}
function window_load_loggedoff(){gAccts_version=-1;gIconsLength=0;g_local_key=null;LP_decimate_children(document.getElementById("lpusername"));var a=document.createElement("b"),b=document.createElement("a");b.setAttribute("href","");b.id="lpusernamelink";set_innertext(b,gs("Login"));a.appendChild(b);document.getElementById("lpusername").appendChild(a);document.getElementById("q").value="";document.getElementById("credmon").style.display="none";document.getElementById("adframe").style.display="none";
document.getElementById("rightside").style.display="none";document.getElementById("friend").style.display="none";document.getElementById("enterpriseaction").style.display="none";document.getElementById("enterprise").style.display=g_hideenterprisetab?"none":"table-cell";document.getElementById("addsharedfolder").style.display="none";document.getElementById("linkpersonal").style.display="none";document.getElementById("removepersonal").style.display="none";for(a=0;a<tabnames.length;a++)"treepane"!=tabnames[a]&&
cleartab(tabnames[a]);setusernametext(getBG().g_username);document.getElementById("securitycheckscore").style.display="none";refresh_legacy_link(document)}
function populateNewData(a){var b=!1,c;for(c in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(c)){b=!0;break}if(!b)for(c in getBG().g_securenotes)if(getBG().g_securenotes.hasOwnProperty(c)){b=!0;break}var f=!1;for(c in getBG().g_pendings)if(getBG().g_pendings.hasOwnProperty(c)){f=!0;break}!b&&!f?document.getElementById("sitesiframe")||(b=document.getElementById("treepane"),a=document.createElement("iframe"),a.id="sitesiframe",a.className="overviewiframe",a.src=getpartnerurl("sites_overview.php?version="+
encodeURIComponent(lpversion)),b.appendChild(a),document.getElementById("thetree").style.display="none",document.getElementById("thegrid").style.display="none"):(document.getElementById("sitesiframe")&&(b=document.getElementById("treepane"),b.removeChild(document.getElementById("sitesiframe")),g_view==VIEWS.TREE?document.getElementById("thetree").style.display="block":document.getElementById("thegrid").style.display="block"),showView(),g_view==VIEWS.GRID&&grid_init_vault_search(),g_view!=VIEWS.GRID&&
populate(a,!0),SearchTree(0,!0,!0))}function showView(){g_view==VIEWS.TREE?($("#thetree").show(),$("#headerli").show(),$("#thegrid").hide()):($("#thetree").hide(),$("#headerli").hide(),$("#thegrid").show())}function isSafariNative(){return"undefined"!=typeof LPFromWebsite&&("undefined"==typeof g_issafari||!g_issafari)}
function update_identity_popup(){for(var a=getBG(),b=document.getElementById("identity");b.length;)b.remove(0);var c=document.createElement("option");c.text=gs("All");c.value="";""==a.g_identity&&(c.selected=1);b.appendChild(c);var f=0,g;for(g in a.g_identities)a.g_identities.hasOwnProperty(g)&&(c=document.createElement("option"),c.text=a.g_identities[g].deciname,c.value=a.g_identities[g].iid,a.g_identity==a.g_identities[g].iid&&(c.selected=1),b.appendChild(c),f++);0<f&&!getBG().g_hideidentities?
document.getElementById("identitycontainer").style.display="block":document.getElementById("identitycontainer").style.display="none"}
function search_matches(a,b){var c=getBG(),c=c.g_prompts.edit_sn_prompt?!1:c.get_searchNotesPref(),f=getBG().g_sites[a];if("undefined"==typeof f&&(f=getBG().g_securenotes[a],"undefined"==typeof f&&(0==a.indexOf("app")&&(a=a.substring(3)),f=getBG().g_applications[a],"undefined"==typeof f&&(f=getBG().g_pendings[a],"undefined"==typeof f)))){var g=getgroupnamefromid(a);if(g)for(var j in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(j)&&"undefined"!=typeof getBG().g_sites[j]&&"http://group"==getBG().g_sites[j].url&&
getBG().g_sites[j].group==g){f=getBG().g_sites[j];break}if("undefined"==typeof f)return!1}return matches(f,b,c)}var g_all_li=[],g_search_array={};function init_vault_search(){g_all_li=$("#thetree").find("li");g_CNTinit_vault++;var a=getBG(),a=a.g_prompts.edit_sn_prompt?!1:a.get_searchNotesPref();g_search_array=sites_tokenize(g_all_li,a)}function finish_vault_search(){lastqstr=g_search_array=g_all_li=null}
function sites_tokenize(a,b){for(var c={},f=0;f<a.length;f++){var g=a[f].id,j="id"+g,k="",h=getBG().g_sites[g];if("undefined"==typeof h&&(h=getBG().g_securenotes[g],"undefined"==typeof h&&(0==g.indexOf("app")&&(g=g.substring(3)),h=getBG().g_applications[g],"undefined"==typeof h&&(h=getBG().g_pendings[g],"undefined"==typeof h))))if(g=getgroupnamefromid(g))k=g;else if("undefined"==typeof h)continue;if(k)h=k.toLowerCase(),c[j]=h;else if("undefined"!=typeof h){k=[];k.push(h.name);k.push(h.group);"http://group"!=
h.url&&"http://sn"!=h.url&&k.push(h.url);h.unencryptedUsername&&k.push(h.unencryptedUsername);is_application(h)&&(k.push(h.appname),k.push(getusernamefromacct(h)));if(b&&"undefined"!=typeof h.extra&&0<h.extra.length&&("undefined"==typeof h.url||"http://group"!=h.url)&&!h.pwprotect)g=getBG().lpmdec_acct(h.extra,!0,h,getBG().g_shares),(!g||0==g.length)&&console.log("searchinnotes: site aid="+h.aid+" FAILED TO DECRYPT"),k.push(g);h=k.join(" ");h=h.toLowerCase();c[j]=h}}return c}
function search_string_tokenize(a){var b=[];g_CNTsearch_string_tokenize++;if(!a)return b;if(-1==a.indexOf('"'))b=a.split(/\s+/);else{var c=[],c=a.split('"');for(a=0;a<c.length;a++)if(a%2)b.push(c[a]);else for(var f=[],f=c[a].split(/\s+/),g=0;g<f.length;g++)f[g]=f[g].replace(/^\s+/,""),f[g]=f[g].replace(/\s+$/,""),0<f[g].length&&b.push(f[g])}return b}
function search_it(a,b){g_CNTsearch_it++;var c="id"+a;"string"==typeof b&&(b=[b]);for(var f=1,g=0;g<b.length;g++)if(!(g_search_array[c]&&-1!=g_search_array[c].indexOf(b[g]))){f=0;break}return f}var populate_done=!1;
function populate(a,b){try{var c=getBG();g_CNTpopulate++;c.g_prompts.edit_sn_prompt||c.get_searchNotesPref();var f=$("#q").val(),g=0;a!=f&&($("#q").val(a),f=a,g=0);gLastSearch=a;gIconsLength=c.g_icons_length;gIdentity=c.g_identity;var j=[],k=""!=a;g_view==VIEWS.GRID&&k&&(j=search_string_tokenize(a));var f=[],h=[],p=[],q=[],x=[],l=[c.g_sites,c.g_securenotes],z;for(z in l)if(l.hasOwnProperty(z)){var r=l[z],m;for(m in r)if(r.hasOwnProperty(m)&&c.check_ident_aid(m)){var v=r[m];if(!(g_view==VIEWS.GRID&&
k)||!(0<j.length)||search_it(m,j)){for(var n=""!=v.group?v.group:"http://sn"==v.url?gs("Secure Notes"):g_xlat_none,n="_"+n;"\\"==n[0];)n=n.substr(1);"undefined"==typeof f[n]&&(f[n]=[],h[h.length]=n,p[n]="undefined"==typeof v.aid?null:v.aid);f[n][f[n].length]=v;x[x.length]=v;"1"==v.fav&&(q[q.length]=v)}}}for(m in c.g_applications)if(c.g_applications.hasOwnProperty(m)&&c.check_ident_appaid(m)&&(v=c.g_applications[m],!(g_view==VIEWS.GRID&&k)||!(0<j.length)||search_it(m,j)))n=""!=v.group?v.group:g_xlat_none,
n="_"+n,"undefined"==typeof f[n]&&(f[n]=[],h[h.length]=n,p[n]="undefined"==typeof v.aid?null:v.aid),f[n][f[n].length]=v,x[x.length]=v,"1"==v.fav&&(q[q.length]=v);var l=0,u;for(u in c.g_pendings)c.g_pendings.hasOwnProperty(u)&&(++l,v=c.g_pendings[u],""==a&&("undefined"==typeof f[g_xlat_pendingname]&&(f[g_xlat_pendingname]=[],h[h.length]=g_xlat_pendingname,p[g_xlat_pendingname]=null),f[g_xlat_pendingname][f[g_xlat_pendingname].length]=v));var H=h.length;h.sort(function(a,b){return"_Apps assigned to me"==
a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});x.sort(function(a,b){return a.last_touch>b.last_touch?1:-1});var v=[],B=c.getClearRecentTime(),C=c.getRecentCount();if(""==a)for(u=0;v.length<C&&u<x.length;u++)"http://group"!=x[x.length-u-1].url&&(x[x.length-u-1].last_touch<B||(v[v.length]=x[x.length-u-1]));v.length&&(h.unshift(g_xlat_runame),f[g_xlat_runame]=v);q.length&&(h.unshift(g_xlat_favorites),f[g_xlat_favorites]=q);B=[];""==a&&(B=getOpenedGroups());if(g_view==VIEWS.GRID)$("#thegrid").scrollTop(),
$("#thegrid").empty(),createTile(h,f,B,a),setupTileEvents();else{var E=[],C=[];resetgroupnames();event_handlers={};event_handlers_onmouseover={};event_handlers_onmouseout={};event_handlers_onclick={};styles={};for(u=0;u<h.length;u++){q=!1;if(""!=a||"undefined"!=typeof B[h[u]]||1==H&&u==h.length-1)q=!0;var A="undefined"==typeof p[h[u]]?null:p[h[u]];"undefined"!=typeof h[u]&&addGroup(c,f,E,C,h[u],q,!1,B,A)}g_tree&&"undefined"!=typeof g_tree?($.tree.focused().settings.data.opts["static"]=E,$.tree.focused().refresh()):
$(function(){var a={};a["static"]=E;var b={beforedelete:lpbeforedelete,beforemove:lpbeforemove,onmove:lponmove,check_move:lpcheck_move,onselect:lponselect};populate_done||(b.onrgtclk=lponrgtclk,populate_done=!0);$("#thetree").tree({callback:b,data:{type:"json",opts:a},rules:{multiple:"ctrl",drag_copy:!1,use_max_children:!1,use_max_depth:!1},plugins:{hotkeys:{functions:{"return":function(){var a=$.tree.focused().selected;a&&(1==a.length&&(isNumber(a[0].id)||is_application(a[0].id)))&&ls(a[0].id)}}}}})});
$(".shareimggroup").click(function(){var a=$(this).closest("li").get();a.length&&(a=getgroupnamefromid(a[0].id),0==a.indexOf("_")&&(a=a.substring(1)),0==a.indexOf("Shared-")?manageSharedFolder(a):shareFolder(a))});$(".toolsimg").click(function(){var a=$(this).closest("li").get();if(a.length){var a=a[0],b=getgroupnamefromid(a.id);0==b.indexOf("_")&&(b=b.substring(1));openGroupMenu(a,b,t,event)}});$(".folder").mouseover(function(){sv(null,this)});$(".folder").mouseout(function(){hv(null,this)})}}catch(w){if("undefined"==
typeof LPFromWebsite||"function"!=typeof LPFromWebsite.ipad){if(0<=w.message.indexOf("atob")&&-1==document.location.href.indexOf("retry")){document.location.href+="?retry=1";return}alert("populate_error:"+w)}}update_identity_popup();g_view!=VIEWS.GRID&&init_vault_search();a&&""!=a&&SearchTree(g,b);for(u in event_handlers)document.getElementById(u)&&(document.getElementById(u).onclick=event_handlers[u]);for(u in event_handlers_onmouseover)for(var c=document.getElementsByName(u),y=0;y<c.length;y++)c[y].onmouseover=
event_handlers_onmouseover[u];for(u in event_handlers_onmouseout){c=document.getElementsByName(u);for(y=0;y<c.length;y++)c[y].onmouseout=event_handlers_onmouseout[u]}for(u in event_handlers_onclick){c=document.getElementsByName(u);for(y=0;y<c.length;y++)c[y].onclick=event_handlers_onclick[u]}for(u in styles)if(c=document.getElementById(u))for(y in styles[u])c.style[y]=styles[u][y]}
function getSubfolders(a,b,c){var f="_"+gs("(none)"),g=""==a?a:a+"\\",j;for(j in b)0==j.indexOf(g)&&(-1==j.substring(g.length).indexOf("\\")&&!(""==a&&j==f))&&(b=j.substring(g.length),-1!=b.indexOf("\\")&&(b=b.substring(0,b.indexOf("\\"))),0==b.indexOf("_")&&(b=b.substring(1)),-1==jQuery.inArray(b,c)&&c.push(b));return c}
function lpbeforedelete(a){var b=getBG();if(1<($.tree.focused().selected_arr&&$.tree.focused().selected_arr.length)){for(var c="",f=[],g=0;g<$.tree.focused().selected_arr.length;g++){var j=getmoveid($.tree.focused().selected_arr[g]);j&&""!=j&&(c+=(""!=c?",":"")+j,f[f.length]=$.tree.focused().selected_arr[g])}b.deleteAid(c,window,!1,!1,function(){for(var a=0;a<f.length;a++)$.tree.focused().cut(f[a])});return!1}c=!1;is_application(a.id)||isNumber(a.id)?c=b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)}):
(c=getgroupnamefromid(a.id),c=b.deleteGroup(fix_group(c),window,function(){$.tree.focused().cut(a)}));return c}
function lpbeforemove(a,b){getBG().lpevent("v_dnd");for(var c="",f=b,c=0;f&&""==f.attr("id")&&100>c;)f=f.parent(),c++;if(99<c||!f)return!1;var g=f.attr("id");g.match(/launch_(nor|fav|rec)_\d+/)&&(g=g.substr(11));g.match(/accept2_(nor|fav|rec)_\d+/)&&(g=g.substr(12));var c="",j=getBG();if(is_application(g)||isNumber(g)){is_application(g)?(j=[j.g_applications],g=get_appaid(g)):j=[j.g_sites,j.g_securenotes];for(var k in j)if(j.hasOwnProperty(k)){var h=j[k],p;for(p in h)if(h.hasOwnProperty(p)){var q=
h[p];if(q.aid==g){if("1"==q.fav){h=f.parent();for(c=0;h&&""==h.attr("id")&&100>c;)h=h.parent(),c++;if(99>c&&h&&h.attr("id")==g_xlat_favorites){c=g_xlat_favorites;break}}c=q.group;break}}}}else c=getgroupnamefromid(g);if(!(""==c||c==g_xlat_runame||c==g_xlat_pendingname)){f=$.tree.focused().selected_arr;k="";for(p=0;p<f.length;p++)if(is_application(getmoveid(f[p]))||isNumber(getmoveid(f[p])))k+=(""==k?"":",")+getmoveid(f[p]);0==k.length&&(k=a.attr("id"));0!=k.length&&getBG().moveSelectedToGroup(c,k);
return!1}}function lponmove(){}function lpcheck_move(a){return 1<$.tree.focused().selected_arr.length?!0:a&&""!=a.attr("id")&&!is_application(a.attr("id"))&&!isNumber(a.attr("id"))?!1:!0}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}var g_groups={},g_groupindex=2E5,g_groupid={},g_groupnames={};function getgroupnamefromid(a,b){var c=g_view==VIEWS.GRID?g_idgroupmap:g_groups;if("undefined"==typeof c[a])return a;c=c[a];!b&&0==c.indexOf("_")&&(c=c.substring(1));return c}
function getrawgroupid(a){return"undefined"==typeof g_groupid[a]||null==g_groupid[a]?null:g_groupid[a]}function resetgroupnames(){g_groups={};g_groupindex=2E5;g_groupid={};g_groupnames={}}function getgroupid(a,b){var c="LpGrOuP"+g_groupindex;g_groups[c]=a;g_groupnames[a]=c;g_groupid[c]=b;++g_groupindex;return"LpGrOuP"+(g_groupindex-1)}function getgroupidfromname(a){return"undefined"==typeof g_groupnames[a]||null==g_groupnames[a]?null:g_groupnames[a]}var div_ids={};
function get_div_id(){for(;;){var a="div"+Math.floor(1E9*Math.random()+1);if("undefined"==typeof div_ids[a])return div_ids[a]=!0,a}}var g_rootnodeid=null,g_lastnodeid=null;
function addGroup(a,b,c,f,g,j,k,h,p){var q="",x=g.indexOf("Shared-");if(g===g_xlat_favorites)q=" favorite";else if(g===g_xlat_runame)q=" recent";else if(0===x||1===x)q=" shared";for(;"\\"==g[0];)g=g.substr(1);for(var l=g.match(/^([^\\]*)\\(.*)$/),z=null!=l,r="",x=0;l&&!k;){var m=l[1],v=l[2],r=r+((""!=r?"\\":"")+m);"undefined"==typeof f[r]&&addGroup(a,b,c,f,r,j||"undefined"!=typeof h[r],!0,h,p);x++;l=v.match(/^([^\\]*)\\(.*)$/)}r=(""==r?"":"\\")+g;k=[];j=j?"open":"closed";h=b[g];"undefined"==typeof h&&
(h=[]);var n="nor_";g!=g_xlat_runame&&g!=g_xlat_pendingname?(h.sort(a.lp_sort_case_insensitive_name),g==g_xlat_favorites&&(n="fav_")):(h.sort(function(a,b){return a.last_touch>b.last_touch?-1:1}),g==g_xlat_runame&&(n="rec_"));for(var u=getcolvisibility("usernamecol"),H=getcolvisibility("ltnamecol"),B=navigator.userAgent.match("Gecko/"),C=1==g_showrows?"":"none",E=0;E<h.length;E++){var A=62+15*x;if(B||"undefined"!=typeof g_isopera&&g_isopera)A+=20;var w=h[E];if("http://group"!=w.url){l=m="";if("undefined"!=
typeof w.sharerusername)"undefined"!=typeof g_isopera&&g_isopera&&(m+="</a>"),b=get_div_id(),m+="<div class='actionmenu' id='"+b+"'><a href='#' id='accept_"+n+w.id+"' class='vaultlink'><img src='"+gLocalBaseUrl+"images/vaultaccept.png'/></a> | <a href='#' id='reject_"+n+w.id+"' class='vaultlink'><img src='"+gLocalBaseUrl+"images/vaultreject.png'/></a></div>",styles[b]={paddingRight:A+"px",display:C},event_handlers["accept_"+n+w.id]=function(){return accept(this.id.substring(11))},event_handlers["reject_"+
n+w.id]=function(){return reject(this.id.substring(11))},m+="<span class='clearboth'></span>",m+="<span><a href='#' id='accept2_"+n+w.id+"'>"+gs("Share offer from")+" "+of(a.hex2bin(w.sharerusername))+"</a></span>",event_handlers["accept2_"+n+w.id]=function(){return accept(this.id.substring(12))};else{var y=safclassdel=safclassshare="";if(g_issafari||g_isopera)y=" editsaf",safclassdel=" delsaf",safclassshare=" sharesaf";var l=get_record_id(w),F,D="<a href='#' id='share_"+n+l+"' class='vaultlink' title='"+
g_xlat_share+"'><span class='shareimg"+safclassshare+"'></span></a> ";event_handlers["share_"+n+l]=function(){return s(this.id.substring(10))};!a.LPISLOC&&!w.genpw&&("undefined"==typeof w.sharedfromaid||null==w.sharedfromaid||""==w.sharedfromaid||"0"==w.sharedfromaid||"null"==w.sharedfromaid)&&"undefined"==typeof w.sharefolderid&&!is_application(w)&&!1==a.g_hidesharing&&a.g_sharing_enabled?F="":(F='<font class="hiddenfont">'+D+"</font>",D="");var G="";b="undefined"!=typeof w.sharedfromaid&&"0"!=w.sharedfromaid?
w.sharedfromaid:"";"undefined"!=typeof w.hasbeenshared&&1==w.hasbeenshared?(G="<p class='sharesubtext'><subtext id='sharesub_"+n+l+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+n+l]=function(){return s(this.id.substring(13))}):w.individualshare&&(""==b?(G="<p class='sharesubtext'><subtext id='sharesub_"+n+l+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+n+l]=function(){return s(this.id.substring(13))}):G="<p class='sharesubtext'>"+gs("shared with you")+"</p>");"undefined"!=
typeof g_isopera&&g_isopera&&(m+="</a>");b=get_div_id();m+="<div class='actionmenu' id='"+b+"'>"+F;styles[b]={paddingRight:A+"px",display:C};m+="<a href='#' id='chpw_"+n+l+"' class='vaultlink colhidden' title='"+g_xlat_chpw+"'><span class='chpwimg'></span></a> ";g_cpwbot&&w.pwch&&(event_handlers["chpw_"+n+l]=function(){e(this.id.substring(9),!0)});m+="<a href='#' id='edit_"+n+l+"' class='vaultlink' title='"+g_xlat_edit+"'><span class='editimg"+y+"'></span></a> ";event_handlers["edit_"+n+l]=function(){return e(this.id.substring(9))};
m+=D;m+="<a href='#' id='delete_"+n+l+"' class='vaultlink' title='"+g_xlat_delete+"'><span class='delimg"+safclassdel+"'></span></a></div>";event_handlers["delete_"+n+l]=function(){return d(this.id.substring(11))};m+="<span class='clearboth'></span>";m+="<span><a href='#' id='launch_"+n+l+"'>"+of(w.name)+"</a>"+G+"</span>";event_handlers["launch_"+n+l]=function(){return ls(this.id.substring(11))}}A="calc(5% + 10px)";y=u?"usercolvisible":"usercolhidden";F=H?"ltcolvisible":"ltcolhidden";D=of(a.getusernamefromacct(w));
""==D&&(D="&nbsp;");b=get_div_id();m+="<div id='"+b+"' class='"+y+"' name='usercol'>"+D+"</div>";styles[b]={cssFloat:"right",paddingRight:A,display:C};b=get_div_id();m+="<div id='"+b+"' class='"+F+"' name='ltcol'>"+("undefined"!=typeof w.last_touch?of(elapsedTime(w.last_touch)):"")+"</div>";styles[b]={cssFloat:"right",paddingRight:A,display:C};k[k.length]={data:{title:m,icon:a.geticonurlfromrecord(w)},attributes:{id:l,name:l}};event_handlers_onmouseover[l]=function(a){sv(a,this);return!1};event_handlers_onmouseout[l]=
function(a){hv(a,this);return!1};event_handlers_onclick[l]=function(a){lc(a,this);return!1}}}h=g;0==h.indexOf("_")&&(h=h.substring(1));n=30+15*x;m=g===g_xlat_favorites||g==g_xlat_runame||g==g_xlat_pendingname;b=get_div_id();m=m?"":"<div class='actionmenu' id='"+b+"'>"+("1"==a.g_enterpriseuser&&!is_personal_linked(h)&&a.g_folder_sharing_enabled?"<a href='#' title='"+g_xlat_share+"'><span class='shareimggroup'></span></a> ":"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";
styles[b]={paddingRight:n+"px"};is_personal_linked(h)&&!z?(m+="<span class='boldspan' isgroup='1' >"+of(h)+" - "+of("Linked Personal Account")+"</span>",q=" linked"):m+="<span class='boldspan' isgroup='1' >"+of(h)+"</span>";f[g]=c.length;if(z){l=g.match(/^([^\\]*)\\(.*)$/);f=null;for(q=z=0;l;){m=l[1];v=l[2];if(0==z){for(r=c.length-1;0<=r;r--)if(c[r].group==m){f=c[r].children;break}q=0;z=1;if(!v.match(/^([^\\]*)\\(.*)$/))for(r=0;r<f.length;r++)if("undefined"==typeof f[r].group||f[r].group==m){q=r;
break}}else{for(r=l=0;r<f.length;r++)if("undefined"==typeof f[r].group){l=r-1;break}else if(f[r].group==m){l=r;break}f=f[l].children}l=v.match(/^([^\\]*)\\(.*)$/);if(!l)for(r=0;r<f.length;r++)if("undefined"==typeof f[r].group||f[r].group==m){q=r;break}else if(r==f.length-1){q=r+1;break}}l=getgroupid(g,p);n=30+15*x;b=get_div_id();m="<div class='actionmenu' id='"+b+"'>"+("1"==a.g_enterpriseuser&&!is_personal_linked(h)&&a.g_folder_sharing_enabled?"<a href='#' title='"+g_xlat_share+"'><span class='shareimggroup'></span></a> ":
"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";styles[b]={paddingRight:n+"px"};m+="<span class='boldspan' isgroup='1'>"+of(v)+"</span>";f.splice(q,0,{data:m,children:k,state:j,group:v,attributes:{"class":"folder",id:l}})}else 0==c.length&&(g_rootnodeid=g),g_lastnodeid=g,l=getgroupid(r,p),c[c.length]={data:m,children:k,state:j,group:g,attributes:{"class":"folder"+q,id:l}}}function getcolvisibility(a){return 0==localStorage_getItem(a)?!1:!0}
function setcolvisibility(a,b){localStorage_setItem(a,b)}
function matches(a,b,c){var f=b.toLowerCase();return-1!=a.name.toLowerCase().indexOf(f)||(a.url&&-1!=a.url.toLowerCase().indexOf(f)||-1!=a.group.toLowerCase().indexOf(f)||a.unencryptedUsername&&-1!=a.unencryptedUsername.toLowerCase().indexOf(f))||is_application(a)&&(a.appname&&-1!=a.appname.toLowerCase().indexOf(f)||-1!=getusernamefromacct(a).toLowerCase().indexOf(f))||c&&("undefined"!=typeof a.extra&&0<a.extra.length&&("undefined"==typeof a.url||"http://group"!=a.url))&&-1!=getBG().lpmdec_acct(a.extra,
!0,a,getBG().g_shares).toLowerCase().indexOf(f)||"has:attachment"==b&&"undefined"!=typeof a.attachid&&null!=a.attachid&&0!=a.attachid?!0:!1}var g_cachedOpenGroups=null;
function getOpenedGroups(){var a=getBG(),b=[],c="";if("undefined"==typeof LPFromWebsite){if("undefined"==typeof localStorage)return b;g_cachedOpenGroups&&g_cachedOpenGroups.length?c=g_cachedOpenGroups:(c=localStorage_getItem(a.db_prepend(a.g_username_hash+".savedtree")),g_cachedOpenGroups=c=a.dec(c))}else c=LPFromWebsite.readopengroups();if(!c||""==c)return b;a=c.split(",");for(c=0;c<a.length;c++)b[a[c].replace("%2C",",")]=1;return b}
function saveGroupState(){var a=getBG();if(!massoperation&&a.lploggedin){var b="";if(g_view==VIEWS.GRID)$(".cont:visible").each(function(a,c){var j=getgroupnamefromid(c.id.substr(2),!0);j.replace(",","%2C");b+=j+","});else{var c=$("#thetree").find(".open");$.each(c,function(a,c){var j=getgroupnamefromid(c.id,!0);j.replace(",","%2C");b+=j+","})}"undefined"==typeof LPFromWebsite?"undefined"!=typeof localStorage&&g_cachedOpenGroups!=b&&(g_cachedOpenGroups=b,c=a.enc(b),localStorage_setItem(a.db_prepend(a.g_username_hash+
".savedtree"),c)):LPFromWebsite.saveopengroups(b)}}function lc(a,b){$.tree.focused().select_branch(b,a.ctrlKey|a.metaKey,a.shiftKey)}function sv(a,b){$(b).children(".actionmenu").find("span").each(function(){$(this).css("opacity","1.0")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="inline-block")}
function hv(a,b){$(b).children(".actionmenu").find("span").each(function(){$(this).css("opacity","0.2")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="none")}function lponopen(){saveGroupState()}function lponclose(){saveGroupState()}function lponselect(){document.getElementById("q").blur()}var g_lastpop=0;
function lponrgtclk(a,b,c){var f=$.tree.focused().selected_arr&&$.tree.focused().selected_arr.length;1==f&&a!==b.selected&&b.select_branch(a);getBG().lpevent("v_rgt");var g=(new Date).getTime();if(!(g_lastpop>g-500)){g_lastpop=g;if(1<f){for(var j="",k=[],h=!1,p=!1,f=0;f<$.tree.focused().selected_arr.length;f++)if((g=getmoveid($.tree.focused().selected_arr[f]))&&""!=g)is_application(g)&&(h=!0),get_record(g)&&"undefined"!=typeof get_record(g).sharefolderid&&(p=!0),j+=(""!=j?",":"")+g,k[k.length]=$.tree.focused().selected_arr[f];
setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};c[gs("Move Selected to Group")]=function(){b.lpevent("v_multmov");openMoveGroup(a)};!h&&!p&&(c[gs("Share Selected")]=function(){b.lpevent("v_mults");s(j)});c[gs("Delete Selected")]=function(){b.lpevent("v_multd");b.deleteAid(j,window,!1,!1,function(){for(var a=0;a<k.length;a++)$.tree.focused().cut(k[a])})};return[c]},{theme:"vista"}).show(b,c)},100)}else if("undefined"!=typeof a)if(""!=a.id&&!is_application(a.id)&&!isNumber(a.id)){f=
getgroupnamefromid(a.id);0==f.indexOf("_")&&(f=f.substring(1));for(var g=!1,q=a;q.parentNode&&q.parentNode!=q;)if(q=q.parentNode,"thetree"==q.id){g=!0;break}if(!g)return;openGroupMenu(a,f,b,c);c.preventDefault()}else""!=a.id&&(is_application(a.id)||isNumber(a.id))&&setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};if("undefined"!=typeof getBG().g_sites[a.id]||is_application(a.id)){if("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&"undefined"==typeof g_ismaxthon&&
"undefined"==typeof g_isfirefoxsdk||"function"==typeof b.can_copy_to_clipboard&&b.can_copy_to_clipboard()||"undefined"!=typeof g_is_safari)c[gs("Copy Username")]=function(){b.copyusername(a.id)},c[gs("Copy Password")]=function(){b.copypassword(a.id)},c[gs("Copy URL")]=function(){b.copyurl(a.id)}}else if("undefined"!=typeof getBG().g_securenotes[a.id]){var f=getBG().g_securenotes[a.id],g="undefined"!=typeof f.notetype?f.notetype:"";"undefined"!=typeof sntemplates[g]&&"undefined"!=typeof sntemplates[g].Username&&
(c[gs("Copy Username")]=function(){b.copyusername(a.id)});var f=getBG().lpmdec_acct(f.extra,!0,f,getBG().g_shares),j;j=0|-1<f.indexOf("Wi-Fi Password");j|=-1<f.indexOf("Email Account");j=(j|=-1<f.indexOf("Server"))&&-1<f.indexOf("Password");if("undefined"!=typeof sntemplates[g]&&"undefined"!=typeof sntemplates[g].Password||j)c[gs("Copy Password")]=function(){b.copypassword(a.id)}}c[gs("Move to Group")]=function(){b.lpevent("v_mov");openMoveGroup(a)};c[gs("Move to Sub-Group")]=function(){b.lpevent("v_msub");
openMoveGroup(a,!0)};g=get_record(a.id);if(!is_application(a.id)&&g&&"undefined"==typeof g.sharefolderid&&("undefined"==typeof g.sharedfromaid||null==g.sharedfromaid||""==g.sharedfromaid||"0"==g.sharedfromaid||"null"==g.sharedfromaid)&&b.g_sharing_enabled)c[gs("Share")]=function(){s(a.id)};c[gs("Delete")]=function(){b.lpevent("v_rgtd");b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)})};c[gs("Edit")]=function(){b.lpevent("v_rgte");b.editAid(a.id,window)};"undefined"!=typeof getBG().g_sites[a.id]&&
(c[gs("Go to URL")]=function(){b.lpevent("v_g2");b.gotourl(a.id,null)});return[c]},{theme:"vista"}).show(b,c)},100);c.preventDefault()}}var lastqstr="";
function SearchTree(a,b,c){g_CNTsearch_tree++;var f=!1;0<document.location.href.indexOf("cmd=viewcreditmon")&&1!=g_autoselectcredmontab?(ontabchange(document.getElementById("credmon")),g_autoselectcredmontab=1):"sites"!=g_activetab.id&&(f=!0);var g=$("#q").val(),j=!1;if(a||g!=lastqstr)f&&!b&&(ontabchange(document.getElementById("sites")),j=!0),gLastSearch=lastqstr=g,g_view==VIEWS.GRID?populate(g,!0):(massoperation=!0,""==g?c||clearTree():$.tree.focused().search(g),massoperation=!1);f&&!j&&setTimeout(function(){ontabchange(g_activetab)},
0);document.getElementById("searchx").src=""==g?gLocalBaseUrl+"images/search.png":gLocalBaseUrl+"images/cancel.png"}function ls(a){var b=getBG();b.lpevent("v_ls");b.launch(a);return!1}function cu(a){var b=getBG();b.lpevent("v_cu");b.copyusername(a);return!1}function cp(a){var b=getBG();b.lpevent("v_cp");b.copypassword(a);return!1}function curl(a){var b=getBG();b.lpevent("v_curl");b.copyurl(a);return!1}function e(a,b){var c=getBG();c.lpevent("v_e");c.editAid(a,window,null,b);return!1}
function d(a){var b=getBG();b.lpevent("v_d");b.deleteAid(a,window);return!1}function is_protected(a){"string"==typeof a&&(a=a.split(","));for(var b=0;b<a.length;b++){var c=get_record(a[b]);if(c&&1==c.pwprotect)return!0}return!1}function s(a){getBG().lpevent("v_s");callServerFunction("share",a);return!1}
function MoveFocus(a){if(40==a.keyCode||34==a.keyCode||38==a.keyCode||33==a.keyCode)a=38==a.keyCode||33==a.keyCode?getgroupidfromname(g_lastnodeid):getgroupidfromname(g_rootnodeid),$.tree.focused().select_branch("#"+a),document.getElementById("q").blur()}function clearTree(){g_CNTclear_tree++;populate("");document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png";document.getElementById("q").value=""}var massoperation=!1;
function expandall(){if(!getBG().lploggedin)return!1;massoperation=!0;g_view==VIEWS.GRID?($(".cont").each(function(a,b){$(b).show()}),$(".grpclose").removeClass("grpclose").addClass("grpopen")):$.tree.focused().open_all();massoperation=!1;saveGroupState()}
function collapseall(){if(!getBG().lploggedin)return!1;massoperation=!0;g_view==VIEWS.GRID?($(".cont").each(function(a,b){$(b).hide()}),$(".grpopen").removeClass("grpopen").addClass("grpclose")):$.tree.focused().close_all();massoperation=!1;saveGroupState()}function creategroup(){var a=getBG();a.lploggedin&&(a.lpevent("v_cg"),openCreateGroup(null))}
function showformfill(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),b={},c;for(c in a.g_formfills)a.g_formfills.hasOwnProperty(c)&&a.check_ident_ffid(a.g_formfills[c].ffid)&&(b[of(a.g_formfills[c].decprofilename)]=function(a){editff(get_innerText(a))});a={};a[gs("Add Profile")]=function(){getBG().addprofile()};a[gs("Add Credit Card")]=function(){getBG().addcreditcard()};return[b,"context-menu-separator",a]},{theme:"vista"}).show(a,
b)},0);return!1}function editff(a){var b=getBG();a=$.trim(a);for(var c in b.g_formfills)if(b.g_formfills.hasOwnProperty(c)&&a==$.trim(b.g_formfills[c].decprofilename)){b.editprofile(b.g_formfills[c].ffid);break}}
function showmoremenu(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a={};gHidePreferences||(a[gs("Preferences")]=function(){getBG().openprefs()});getBG().LPISLOC||(a[gs("History")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&openhistory=1")},a[gs("Show Deleted Sites")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&showdeleted=1")});if(!getBG().LPISLOC||!getBG().LPISUPEK)a[gs("Change Password")]=
function(){getBG().unlock_plug2web();getBG().changemasterpassword()};a[gs("Forums")]=function(){getBG().openURL("http://forums.lastpass.com")};a[gs("Blog")]=function(){getBG().openURL("http://blog.lastpass.com")};getBG().g_isadmin&&(a[gs("Admin Tools")]=function(){getBG().openURL("https://rodan-internal.lastpass.com/admintools/")});return[a]},{theme:"vista"}).show(a,b)},0);return!1}function addsecurenote(){getBG().lpevent("v_addn");getBG().openaddsecurenote();return!1}
function logoff(){if(!getBG().lploggedin)return!1;finish_vault_search();getBG().lpevent("v_off");saveGroupState();getBG().loggedOut(!1,"homelocal2");return!1}function accept(a){getBG().lpevent("v_apt");callServerFunction("acceptshare",a)}function reject(a){getBG().lpevent("v_rjt");callServerFunction("rejectshare",a)}function login(){getBG().lpevent("v_lgn");getBG().open_login(!0);return!1}
function changeidentity(a,b){("undefined"==typeof b||!0==b)&&closepopup();getBG();getBG().lpevent("v_cid");getBG().switch_identity(a);document.getElementById("identity").value=getBG().g_identity;setusernametext(getBG().g_username);closepopup()}var gMoveSelected=null;
function openMoveGroup(a,b,c){if(addedjqueryui){gMoveSelected=$.tree.focused().selected_arr;if("undefined"==typeof gMoveSelected||0==gMoveSelected.length)gMoveSelected=Array(a);var f=getBG(),g=[],j=[],k=[f.g_sites,f.g_securenotes,f.g_applications],h="",p;for(p in k)if(k.hasOwnProperty(p)){var q=k[p],x;for(x in q)if(q.hasOwnProperty(x)){var l=q[x];if(gMoveSelected&&(1==gMoveSelected.length&&getmoveid(gMoveSelected[0])==get_record_id(l))&&(h=l.group,b)){""!=l.group&&(g[g.length]=l.group);break}l=""!=
l.group?l.group:gs("(none)");"undefined"!=typeof l&&"undefined"==typeof j[l]&&(j[l]="1",g[g.length]=l)}}g.sort(function(a,b){return"_Apps assigned to me"==a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});j=!1;""==h&&(1==gMoveSelected.length&&!isNumber(getmoveid(gMoveSelected[0])))&&(h=getmoveid(gMoveSelected[0]),j=!0);k=-1!=h.indexOf("\\")&&0<h.substring(h.indexOf("\\")+1).length;if(j&&0===h.indexOf("Shared-")&&!k){if(g=void 0,c){for(i in f.g_sites)if(f.g_sites[i].group==h){g=
f.g_sites[i].aid;break}callServerFunction("renamesharedfolder",g)}}else document.getElementById("grpsel").value="",repopulate_combo("grpsel",g),document.getElementById("dialog").title=gs("Change Group Name"),set_innertext(document.getElementById("dialogtext"),gs("Select or enter a new group name")),document.getElementById("dialoggrpinp").style.display="none",document.getElementById("dialoggrpsel").style.display="block",document.getElementById("dosubgroup").value="undefined"!=typeof b&&b?"1":"0",1==
gMoveSelected.length&&(b?(document.getElementById("dialogtext").appendChild(document.createElement("br")),document.getElementById("dialogtext").appendChild(document.createElement("br")),document.getElementById("dialogtext").appendChild(document.createTextNode(gs("Group will be created or currently exists under")+": ")),document.getElementById("dialogtext").appendChild(document.createElement("br")),document.getElementById("dialogtext").appendChild(document.createTextNode(h))):document.getElementById("grpsel").value=
h),$("#dialog").dialog("destroy"),$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,dragStop:function(){var a=document.getElementById("grpsel_combo");a&&"block"==a.style.display&&realShowCombo()},close:function(){var a=document.getElementById("grpsel_combo");a&&"block"==a.style.display&&close_combo("grpsel")},buttons:{Change:function(){var a=1==gMoveSelected.length?getmoveid(gMoveSelected[0]):"";if(1==gMoveSelected.length&&""!=a&&!is_application(a)&&!isNumber(a)){var b=
fix_group(document.getElementById("grpsel").value),c=fix_group(a);0==b.indexOf("Shared-")?-1!=b.indexOf("\\")&&0==c.indexOf(b.substr(0,b.indexOf("\\")))?getBG().renameGroup(fix_group(a),b):shareFolder(b.replace("Shared-","")):getBG().renameGroup(c,b)}else{b="";for(c=0;c<gMoveSelected.length;c++)if(a=getmoveid(gMoveSelected[c]),is_application(a)||isNumber(a))b+=(""==b?"":",")+a;if(0==b.length)return;a=document.getElementById("grpsel").value;1==gMoveSelected.length&&"1"==document.getElementById("dosubgroup").value&&
a!=h&&0!=a.indexOf(h+"\\")&&(a=h+"\\"+a);getBG().moveSelectedToGroup(a,b)}populate(gLastSearch);$(this).dialog("close")},Close:function(){$(this).dialog("close")}}}),$("#dialog").dialog("open"),$("#grpsel").click()}else addJqueryUI(),setTimeout(function(){openMoveGroup(a,b,c)},250)}var selected_global;
function openCreateGroup(a){addedjqueryui||(addJqueryUI(),setTimeout(function(){openCreateGroup(a)},250));selected_global=a;getBG().lpevent("v_cg");document.getElementById("dialog").title=gs("Group Name");set_innertext(document.getElementById("dialogtext"),gs("Group Name"));document.getElementById("dialoggrpinp").style.display="block";document.getElementById("grpinp").value="";document.getElementById("dialoggrpsel").style.display="none";"function"==typeof $("#dialog").dialog&&($("#dialog").dialog("destroy"),
$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,buttons:{OK:function(){var a=document.getElementById("grpinp").value;for(null!=selected_global&&(a=fix_group(getmoveid(selected_global))+"\\"+a);"\\"==a[0];)a=a.substr(1);if(a==gs("favorites")||a==g_xlat_runame||a==g_xlat_pendingname)alert(gs("That group already exists."));else if(null==selected_global&&0==a.indexOf("Shared-"))alert(gs("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name."));
else{var c=getBG(),f=[c.g_sites,c.g_securenotes,c.g_applications],g;for(g in f)if(f.hasOwnProperty(g)){var j=f[g],k;for(k in j)if(j.hasOwnProperty(k)&&j[k].group==a){alert(gs("That group already exists."));return}}c.addEmptyGroup(a);populate(gLastSearch);$(this).dialog("close")}},Close:function(){$(this).dialog("close")}}}),"function"==typeof $("#dialog").dialog&&$("#dialog").dialog("open"));$("#grpinp").click()}
function getmoveid(a){var b="",b="undefined"!=typeof a.id?getgroupnamefromid(a.id,!0):getgroupnamefromid(a.attr("id"),!0);0==b.indexOf("_")&&(b=b.substring(1));return b}function getacct(a){return get_record(a)}function getDragHTMLForNode(a){var b=a;for(a=0;b&&""==b.attr("id")&&100>a;)b=b.parent(),a++;a=getBG();b=b.attr("id");return(b=getacct(b))?"<div><img src='"+a.geticonurlfromrecord(b)+"' />&nbsp;<span>"+of(b.name)+"</span></div>":""}
function getDragHTML(a){var b="<div id='jstree-dragged' class='tree default'>";if(null==a){a=$.tree.focused().selected_arr;for(var c=0;c<a.length;c++)b+=getDragHTMLForNode(a[c])}else b+=getDragHTMLForNode(a);return b+"</div>"}var togglestate=0;
function toggleUserCol(){var a=getcolvisibility("usernamecol"),b=getcolvisibility("ltnamecol"),c="usercol",f="usernamecol",g="usercolhidden",j="usercolvisible",k=a;1==togglestate%2?(c="ltcol",f="ltnamecol",g="ltcolhidden",j="ltcolvisible",k=b):document.getElementById("ltcol").style.paddingRight=!a?"5%":"calc(5% + 20px)";togglestate++;a=document.getElementsByName(c);for(b=0;b<a.length;b++)a[b].className=k?g:j,0==b&&setcolvisibility(f,k?"0":"1")}
function openinparent(a,b){0!=a.indexOf("http")&&(a=g_urlprefix+a);a+="?";for(var c in b)b.hasOwnProperty(c)&&(a+="&"+en(c)+"="+en(b[c]));window.open(a)}function showpopup(){getBG().lploggedin?document.getElementById("lppopup").style.display="block":login()}document.addEventListener("click",closepopup,!0);
function closepopup(a){if("block"==document.getElementById("lppopup").style.display&&(!a||!a.target||"person"!=a.target.id&&"identity"!=a.target.id&&"lpusername"!=a.target.id))document.getElementById("lppopup").style.display="none";$("#tilepopup").hide()}var translations=[];translations.DeleteSiteConfirm=gs("Are you sure you want to delete this site?");translations.DeleteSite=gs("Delete Site?");translations.DeleteIdentityConfirm=gs("Are you sure you want to delete this identity?");
translations.DeleteIdentity=gs("Delete Identity?");translations["Invalid Password."]=gs("Invalid Password.");translations["Add Site"]=gs("Add Site");translations["Add Profile"]=gs("Add Profile");translations["Add Identity"]=gs("Add Identity");this.updated_enc=function(){return!0};var g_waitbox=null;
this.show_waitbox=function(a,b){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy());var c=gs("Submitting...");"undefined"!=typeof a&&null!=a&&!0==a?c=gs("LastPass must reencrypt all of your data because of a key change.")+"<br/><br/>"+gs("This may take a while...")+"<br/><br/>"+gs("Please keep this page open until the operation completes.")+'<br/><br/><div id="changepw_progress" class="width300div"></div>':"undefined"!=typeof b&&(b&&""!=b)&&(c=b);b=gs("Please Wait...");var f=Math.min(750,200+4*c.length);
g_waitbox=new Ext.Window({closable:!1,width:f,autoHeight:!0,layout:"fit",modal:!0,title:b,bodyStyle:"padding: 20px",id:"waitbox",html:"<br/><br/><b>"+c+"</b><br/><br/>"});g_waitbox.show()};this.hide_waitbox=function(){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy(),g_waitbox=null)};this.populateff=function(a,b){for(var c=getBG(),f=convert_object_to_array(c.g_formfills),g=[],j=0;j<f.length;j++){var k=f[j];c.check_ident_ffid(k.ffid)&&g.push(k)}populateffcommon(g,a,b)};
this.openff=function(a){getBG().lpevent("v_off");getBG().editprofile(a)};this.delff=function(a){confirm(gs("Are you sure you would like to delete this form fill profile?"))&&(getBG().lpevent("v_dff"),getBG().deleteformfill(a))};
this.populateident=function(a){var b=convert_object_to_array(getBG().g_identities);if(b.length){if(document.getElementById("identiframe")){var c=document.getElementById("identpane");c.removeChild(document.getElementById("identiframe"))}populateidentcommon(b,a)}else if(!document.getElementById("identiframe")){for(c=document.getElementById("identpane");c.children.length;)c.removeChild(c.children[0]);a=document.createElement("iframe");a.id="identiframe";a.className="overviewiframe";a.src=getpartnerurl("ident_overview.php");
c.appendChild(a)}};this.openident=function(a){getBG().lpevent("v_oid");callServerFunction("identity",a);return!1};this.delident=function(a){getBG().lpevent("v_did");confirm(gs("Are you sure you want to delete this identity?"))&&callServerFunction("deleteidentity",a,getBG().g_token);return!1};
this.populateshares_remote=function(){cleartab("sharepane");var a=document.getElementById("sharepane");if(!document.getElementById("shareiframe")){getBG().unlock_plug2web();var b=document.createElement("iframe");b.id="shareiframe";b.className="overviewiframe";b.src=getpartnerurl("share_overview.php?extension=1");a.appendChild(b)}};
this.populatealerts=function(){cleartab("credmonpane");var a=document.getElementById("credmonpane");if(!document.getElementById("credmoniframe")){var b=document.createElement("iframe");b.id="credmoniframe";b.className="overviewiframe";b.src=getpartnerurl("credmon_overview.php");a.appendChild(b)}};this.cleartab=function(a){for(a=document.getElementById(a);a&&a.children.length;)a.removeChild(a.children[0])};this.refreshsites=function(){getBG().refreshsites()};var g_loaded=g_haspluginrsa=!1,g_func=null;
this.doneloadingexternaljs=function(){g_loaded=!0;g_func&&g_func();g_func=null};this.openaddbytab=function(){if(getBG().lploggedin)return"ident"==g_activetab.id?callServerFunction("identity",""):"ff"==g_activetab.id||"credmon"==g_activetab.id?getBG().addprofile():getBG().openaddsite(),!1};this.opencreditmondash=function(a,b){if(getBG().lploggedin)return a?callServerFunction("opencreditmondash",b):callServerFunction("opencreditmondashnoalert",b),!1};function togglerows(){}
window.addEventListener("message",function(a){if(!("undefined"==typeof getBG().base_url||0!=getBG().base_url.indexOf(a.origin))){var b=a.data+"";if("addprofile"==b||"addidentity"==b)openaddbytab();else if(0<=b.indexOf("showcredmondash_"))a=b.substr(16),opencreditmondash(!0,a);else if(0<=b.indexOf("showcredmondashnoalert_"))a=b.substr(23),opencreditmondash(!1,a);else if("object"==typeof a.data)if("getdata"==a.data.msg)0==a.data.url.indexOf(getBG().base_url)&&(g_ipctarget=a,getBG().processCS(null,{cmd:"ipcgetdata",
url:a.data.url,callback:website_event_callback},null));else if("refreshsites"==a.data.msg)getBG().refreshsites();else if("closeiframe"==a.data.msg)a=document.body,b=document.getElementById("__serveriframe"),a&&b&&a.removeChild(b);else if("websiteevent"==a.data.msg)g_websiteeventtarget=a,document.getElementById("eventtype").value=a.data.eventtype,document.getElementById("eventdata1").value=a.data.eventdata1,document.getElementById("eventdata2").value=a.data.eventdata2,document.getElementById("eventdata3").value=
a.data.eventdata3,document.getElementById("eventdata4").value=a.data.eventdata4,document.getElementById("eventdata5").value=a.data.eventdata5,website_event();else if(0==a.data.msg.indexOf("sharefolder_")&&(b=a.data.msg.match(/^sharefolder_([^_]+)_(.*)$/)))a=b[1],b=b[2],"undefined"!=typeof share_folder_group&&share_folder_group==b&&(share_folder_id=a,getBG().set_share_folder_id(a))}},!1);
function callServerFunction(a,b,c,f){var g=getBG();if(g.lploggedin){g.unlock_plug2web();var j=document,k=!1;if("share"==a||"acceptshare"==a||"rejectshare"==a){if(k=g.g_prompts.edit_site_prompt||g.g_prompts.edit_sn_prompt,!k&&"share"==a)for(var h=b.split(","),p=0;p<h.length;p++){var q=get_record(h[p]);if(q&&q.pwprotect){k=!0;break}}}else if("identity"==a||"deleteidentity"==a){if(k=g.g_prompts.switch_identity_prompt,!k&&""!=b){h=convert_object_to_array(g.g_identities);for(p=0;p<h.length;++p)if(h[p].iid==
b&&h[p].pw_prompt){k=!0;break}}}else if("opencreditmondash"==a||"opencreditmondashnoalert"==a)k=!1;if(k&&!f)g.security_prompt(function(){callServerFunction(a,b,c,!0)});else{f=j.body;j=j.createElement("iframe");j.type="content";g=1E3*Math.random();g=g_urlprefix+"acctsiframe.php?rand="+g+"&command="+encodeURIComponent(a);b&&(g+="&commandid="+encodeURIComponent(b));c&&(g+="&commandtoken="+encodeURIComponent(c));g+="&version="+encodeURIComponent(lpversion);j.setAttribute("src",getpartnerurl(g));j.id=
"__serveriframe";j.style.position="absolute";j.style.top=j.style.left="0px";try{var x=f.ownerDocument.defaultView.getComputedStyle(f,"");j.style.width=x.width;j.style.height=x.height}catch(l){}f.appendChild(j)}}}function manageSharedFolder(a){var b=getBG(),c=a.indexOf("\\");-1!=c&&(a=a.substring(0,c));for(var f in b.g_shares)if(b.g_shares[f].decsharename==a){callServerFunction("sharedfolders",b.g_shares[f].id);break}}
function shareFolder(a){share_folder_id="";getBG().set_share_folder_id("");share_folder_group=a;getBG().set_share_folder_group(a);callServerFunction("sharefolder",a)}function sendToManageSharedFolders(){alert("Please delete Shared Folders using the Manage Shared Folders link")}
function openGroupMenu(a,b,c,f){var g=getrawgroupid(a.id);setTimeout(function(){$.contextMenu.create(function(){var c=getBG(),f={};b!=g_xlat_favorites&&(b!=g_xlat_runame&&b!=g_xlat_pendingname&&b!=g_xlat_none)&&(0==b.indexOf("Shared-")&&c.g_folder_sharing_enabled?f[gs("Manage Shared Folder")]=function(){manageSharedFolder(b)}:"1"==c.g_enterpriseuser&&(!is_personal_linked(b)&&c.g_folder_sharing_enabled)&&(f[gs("Share Folder")]=function(){shareFolder(b)}),f[gs("Rename Group")]=function(){c.lpevent("v_ren");
openMoveGroup(a,void 0,!0)},f[gs("Delete Group")]=function(){0==b.indexOf("Shared-")&&-1==b.indexOf("\\")?(callServerFunction("sharedfolders"),sendToManageSharedFolders()):(c.lpevent("v_dg"),c.deleteGroup(fix_group(b),window,function(){$.tree.focused().cut(a)},"homelocal2.html B",0,g))},f[gs("Create Sub-Group")]=function(){c.lpevent("v_csub");openCreateGroup(a)});f[gs("Open All")]=function(){c.openall(b)};return[f]},{theme:"vista"}).show(c,f)},0)}
function contains(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return!0;return!1}var I_SHOW=!0,I_HIDE=!1;function refresh_ident_actions(){var a=getBG();a&&convert_object_to_array(a.g_identities).length&&showhide_ident_actions(I_SHOW)}
function showhide_ident_actions(a){getBG();a==I_SHOW?(document.getElementById("ident").style.display="table-cell",document.getElementById("lpidentities").style.display="block"):(document.getElementById("ident").style.display="none",document.getElementById("lpidentities").style.display="none")}
function grid_sites_tokenize(a){var b=getBG(),c,f={},b=[b.g_sites,b.g_securenotes,b.g_applications,b.g_pendings];for(c in b)if(b.hasOwnProperty(c)){var g=b[c],j;for(j in g)if(g.hasOwnProperty(j)){var k=g[j],h="id"+k.aid,p=[];k.name&&p.push(k.name);k.group&&p.push(k.group);"http://group"!=k.url&&"http://sn"!=k.url&&p.push(k.url);k.unencryptedUsername&&p.push(k.unencryptedUsername);is_application(k)&&(p.push(k.appname),p.push(getusernamefromacct(k)));if(a&&"undefined"!=typeof k.extra&&0<k.extra.length&&
("undefined"==typeof k.url||"http://group"!=k.url)&&!k.pwprotect){var q=getBG().lpmdec_acct(k.extra,!0,k,getBG().g_shares);(!q||0==q.length)&&console.log("searchinnotes: site aid="+k.aid+" FAILED TO DECRYPT");p.push(q)}k=p.join(" ");k=k.toLowerCase();f[h]=k}}return f}function grid_init_vault_search(){var a=getBG(),a=a.g_prompts.edit_sn_prompt?!1:a.get_searchNotesPref();g_search_array=grid_sites_tokenize(a);return!0}
function refresh_legacy_link(a){var b=getBG();if(!b)return!1;g_dolegacy=is_user_premium();if(b.g_legacy_enabled&&b.lploggedin&&g_dolegacy)return a?(a=a.getElementById("legacy_li"))?(a.style.display="block",a=!0):a=!1:a=!1,a;a?(a=a.getElementById("legacy_li"))?(a.style.display="none",a=!0):a=!1:a=!1;return a}$(document).bind("DOMContentLoaded",function(){$("#vaultToggle").bind("click",function(a){a.preventDefault();a.stopPropagation();getBG().VaultToggle.toggleVault4_0(window)})});
