var NoteDialog=function(j){DialogWithGroupInput.call(this,j,{closeButtonEnabled:!0,maximizeButtonEnabled:!0});this.addedAttachments=this.removedAttachments=null;this.showAttachmentContainer=function(j){j?$("#noteDialogExistingAttachments").hide():$("#noteDialogExistingAttachments").show()};this.noteForms={};this.noteTypeIcon=this.noteFormElement=null};NoteDialog.prototype=Object.create(DialogWithGroupInput.prototype);NoteDialog.prototype.constructor=NoteDialog;
(function(j){var l=function(a){var b=new Note;b._noteType=a;return(new NoteDisplay(b)).buildItemIconElement()};NoteDialog.prototype.open=function(a){a=a||{};a.title=a.vaultItem?Strings.translateString("Edit Note"):Strings.translateString("Add Note");a.sourceFunction=LPProxy.getNoteModel;DialogWithGroupInput.prototype.open.call(this,a)};NoteDialog.prototype.defaultFields=function(a){a.defaultData=$.extend({notetype:a.vaultItem?a.vaultItem.getNoteType():Note.prototype.NOTE_TYPES.GENERIC},a.defaultData);
DialogWithGroupInput.prototype.defaultFields.apply(this,arguments)};NoteDialog.prototype.clearFields=function(a){DialogWithGroupInput.prototype.clearFields.apply(this,arguments);for(var b in this.noteForms)this.noteForms[b].inputs.clear()};NoteDialog.prototype.clearErrors=function(){DialogWithGroupInput.prototype.clearErrors.apply(this,arguments);for(var a in this.noteForms)this.noteForms[a].inputs.clearErrors()};NoteDialog.prototype.validate=function(a){var b=DialogWithGroupInput.prototype.validate.apply(this,
arguments);""===a.name&&(this.addError("name","Name is required."),b=!1);if(45E3<a.extra.Notes.length){var d=this;dialogs.confirmation.open({title:Strings.translateString("Error"),text:Strings.translateString("The notes field contains too much data. You may store a maximum of 45,000 characters per note. Would you like us to truncate the note for you? You will lose some of your data."),handler:function(){d.inputFields.extra.Notes.setValue(a.extra.Notes.substring(0,45E3))}});b=!1}return b};NoteDialog.prototype.initializeAttachmentContainer=
function(a){this.containers.attachments=new Container(a,{stateChangeCallback:this.showAttachmentContainer});this.containers.attachments.initialize(document.getElementById("attachmentContainer"));this.showAttachmentContainer(this.containers.attachments.isEmpty())};NoteDialog.prototype.setup=function(a,b){DialogWithGroupInput.prototype.setup.apply(this,arguments);var d=b.vaultItem;d?this.inputFields.notetype.disable():this.inputFields.notetype.enable();if(d&&d.hasAttachments()){for(var d=d.getAttachments(),
c=[],e=0,g=d.length;e<g;++e)c.push(d[e].newDisplayObject());this.initializeAttachmentContainer(c)}else this.showAttachmentContainer(!0);this.removedAttachments=[];this.addedAttachments=[];this.vaultItem?(a.find(".history").show(),bg.loglogin(this.vaultItem.getID())):a.find(".history").hide()};NoteDialog.prototype.initialize=function(a){DialogWithGroupInput.prototype.initialize.apply(this,arguments);this.noteFormElement=j.getElementById("noteForm");var b=this.inputFields.notetype,d=j.getElementById("noteDialogType");
this.noteTypeIcon=l(Note.prototype.NOTE_TYPES.GENERIC);this.noteTypeIcon.setAttribute("id","noteDialogTypeIcon");this.noteTypeIcon.addEventListener("mousedown",function(a){b.toggle(a);a.preventDefault();b.focus()});d.parentElement.insertBefore(this.noteTypeIcon,d);for(var h=d.parentElement.nextElementSibling.children[0],e=0,g=h.children.length;e<g;++e){var k=h.children[e],m=l(k.getAttribute(DropdownInput.prototype.ATTR_DROPDOWN_VALUE));k.insertBefore(m,k.firstChild)}var f=this;d.addEventListener("focus",
function(){$(f.noteTypeIcon.parentElement).addClass("focus")});d.addEventListener("blur",function(){$(f.noteTypeIcon.parentElement).removeClass("focus")});d=f.addFavButton();h=LPTools.createElement("a",{"class":"itemButton history",title:Strings.translateString("Note History")});$(h).bind("click",function(){LPRequest.makeRequest(LPProxy.getNoteHistory,{parameters:[f.vaultItem.getID(),f.vaultItem.getShareID()],success:function(a){dialogs.fieldHistory.open({history:a,vaultItem:f.vaultItem,type:Constants.HISTORY_TYPES.NOTE})},
requestSuccessOptions:{closeDialog:!1}})});d.appendChild(h);b.onChange(function(a){f.setNoteFields(a)});Topics.get(Topics.ATTACHMENT_REMOVED).subscribe(function(a){for(var b=0,d=f.addedAttachments.length;b<d;++b)if(f.addedAttachments[b]===a){f.addedAttachments.splice(b,1);return}f.removedAttachments.push(a)});$("#addAttachmentButton").bind("click",function(){LPProxy.addAttachment(function(a){f.addAttachment(a)})});this.noteForms[Note.prototype.NOTE_TYPES.AMEX]=new c;this.noteForms[Note.prototype.NOTE_TYPES.BANK]=
new c([new DialogInput.TextInput("Bank Name"),new DialogInput.TextInput("Account Type"),new DialogInput.TextInput("Routing Number"),new DialogInput.TextInput("Account Number"),new DialogInput.TextInput("SWIFT Code"),new DialogInput.TextInput("IBAN Number"),new DialogInput.TextInput("Pin"),new DialogInput.TextInput("Branch Address"),new DialogInput.TextInput("Branch Phone"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.DATABASE]=new c([new DialogInput.TextInput("Type"),
new DialogInput.TextInput("Hostname"),new DialogInput.TextInput("Port"),new DialogInput.TextInput("Database"),new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),new DialogInput.TextInput("SID"),new DialogInput.TextInput("Alias"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.DRIVERS_LICENSE]=new c([new DialogInput.TextInput("Number"),new DialogInput.AlphaDateInput("Expiration Date"),new DialogInput.TextInput("License Class"),new DialogInput.TextInput("Name"),
new DialogInput.TextInput("Address"),new DialogInput.TextInput("City / Town"),new DialogInput.TextInput("State"),new DialogInput.TextInput("ZIP / Postal Code"),new DialogInput.TextInput("Country"),new DialogInput.AlphaDateInput("Date of Birth"),new DialogInput.TextInput("Sex"),new DialogInput.TextInput("Height"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.EMAIL]=new c([new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),new DialogInput.TextInput("Server"),
new DialogInput.TextInput("Port"),new DialogInput.TextInput("Type"),new DialogInput.TextInput("SMTP Server"),new DialogInput.TextInput("SMTP Port"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.HEALTH_INSURANCE]=new c([new DialogInput.TextInput("Company"),new DialogInput.TextInput("Company Phone"),new DialogInput.TextInput("Policy Type"),new DialogInput.TextInput("Policy Number"),new DialogInput.TextInput("Group ID"),new DialogInput.TextInput("Member Name"),new DialogInput.TextInput("Member ID"),
new DialogInput.TextInput("Physician Name"),new DialogInput.TextInput("Physician Phone"),new DialogInput.TextInput("Physician Address"),new DialogInput.TextInput("Co-pay"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.IM]=new c([new DialogInput.TextInput("Type"),new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),new DialogInput.TextInput("Server"),new DialogInput.TextInput("Port"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.INSURANCE]=
new c([new DialogInput.TextInput("Company"),new DialogInput.TextInput("Policy Type"),new DialogInput.TextInput("Policy Number"),new DialogInput.AlphaDateInput("Expiration"),new DialogInput.TextInput("Agent Name"),new DialogInput.TextInput("Agent Phone"),new DialogInput.TextInput("URL"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.MASTERCARD]=new c;this.noteForms[Note.prototype.NOTE_TYPES.MEMBERSHIP]=new c([new DialogInput.TextInput("Organization"),new DialogInput.TextInput("Membership Number"),
new DialogInput.TextInput("Member Name"),new DialogInput.AlphaDateInput("Start Date"),new DialogInput.AlphaDateInput("Expiration Date"),new DialogInput.TextInput("Website"),new DialogInput.TextInput("Telephone"),new DialogInput.PasswordInput("Password"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.CREDIT]=new c([new DialogInput.TextInput("Name on Card"),new DialogInput.TextInput("Type"),new DialogInput.TextInput("Number"),new DialogInput.TextInput("Security Code"),
new DialogInput.AlphaDateInput("Start Date",{includeDay:!1}),new DialogInput.AlphaDateInput("Expiration Date",{includeDay:!1}),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SSN]=new c([new DialogInput.TextInput("Name"),new DialogInput.TextInput("Number"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SOFTWARE_LICENSE]=new c([new DialogInput.TextInput("License Key"),new DialogInput.TextInput("Licensee"),new DialogInput.TextInput("Version"),
new DialogInput.TextInput("Publisher"),new DialogInput.TextInput("Support Email"),new DialogInput.TextInput("Website"),new DialogInput.TextInput("Price"),new DialogInput.AlphaDateInput("Purchase Date"),new DialogInput.TextInput("Order Number"),new DialogInput.TextInput("Number of Licenses"),new DialogInput.TextInput("Order Total"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SSH_KEY]=new c([new DialogInput.TextInput("Bit Strength"),new DialogInput.TextInput("Format"),
new DialogInput.TextInput("Passphrase"),new DialogInput.TextInput("Private Key",void 0,{inputButton:Strings.translateString("Copy"),inputButtonHandler:function(){this.dialog.vaultItem.copyPrivateKey()}}),new DialogInput.TextInput("Public Key"),new DialogInput.TextInput("Hostname"),new DialogInput.AlphaDateInput("Date"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.VISA]=new c;this.noteForms[Note.prototype.NOTE_TYPES.WIFI]=new c([new DialogInput.TextInput("SSID"),new DialogInput.PasswordInput("Password"),
new DialogInput.TextInput("Connection Type"),new DialogInput.TextInput("Connection Mode"),new DialogInput.TextInput("Authentication"),new DialogInput.TextInput("Encryption"),new DialogInput.TextInput("Use 802.1X"),new DialogInput.TextInput("FIPS Mode"),new DialogInput.TextInput("Key Type"),new DialogInput.TextInput("Protected"),new DialogInput.TextInput("Key Index"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SERVER]=new c([new DialogInput.TextInput("Hostname"),new DialogInput.TextInput("Username"),
new DialogInput.PasswordInput("Password"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.PASSPORT]=new c([new DialogInput.TextInput("Type"),new DialogInput.TextInput("Name"),new DialogInput.TextInput("Country"),new DialogInput.TextInput("Number"),new DialogInput.TextInput("Sex"),new DialogInput.TextInput("Nationality"),new DialogInput.TextInput("Issuing Authority"),new DialogInput.AlphaDateInput("Date of Birth"),new DialogInput.AlphaDateInput("Issued Date"),new DialogInput.AlphaDateInput("Expiration Date"),
new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.GENERIC]=new c([new DialogInput.TextArea("Notes",null)],["noteContent"])};NoteDialog.prototype.addAttachment=function(a){a&&(this.addedAttachments.push(a),a=a.newDisplayObject(),this.containers.attachments?this.containers.attachments.addChild(a):this.initializeAttachmentContainer([a]))};NoteDialog.prototype.setNoteFields=function(a){a=a||Note.prototype.NOTE_TYPES.GENERIC;LPTools.removeDOMChildren(this.noteFormElement);var b=
this.noteForms[a];null===b.element&&b.initialize(this);this.noteFormElement.appendChild(b.element);this.noteFormElement.scrollTop=0;this.inputFields.extra=b.inputs;b=this.noteTypeIcon;a=NoteDisplay.prototype.NOTE_TYPES[a];b.children[0].children[0].setAttribute("src",a.path);b.children[0].setAttribute("class","noteFormFillIcon "+a.css)};NoteDialog.prototype.populateFields=function(a){a.notetype&&this.inputFields.notetype.setValue(a.notetype);Dialog.prototype.populateFields.apply(this,arguments)};NoteDialog.prototype.add=
function(a){(new Note).addFromDialog(a,this.getGroup(a))};NoteDialog.prototype.getData=function(){var a=DialogWithGroupInput.prototype.getData.apply(this,arguments);if(this.removedAttachments&&0<this.removedAttachments.length||this.addedAttachments&&0<this.addedAttachments.length){a.attacharraychanges={};var b=this.addedAttachments,d=a.attacharraychanges;if(b){for(var c=[],e=0,g=b.length;e<g;++e)c.push(b[e]._data);0<c.length&&(d.add=c)}b=this.removedAttachments;d=a.attacharraychanges;if(b){c=[];e=
0;for(g=b.length;e<g;++e)c.push(b[e].getID());0<c.length&&(d.remove=c)}}return a};var c=function(a,b){this.inputs=new DialogInput.NestedFields;this.inputsArray=[];if(a instanceof Array){this.inputsArray=a;for(var c=0,h=a.length;c<h;++c){var e=a[c];this.inputs[e.field]=e}}this.$_element=this.element=null;this.additionalClasses=b};c.prototype.initialize=function(a){var b=["settings"];this.additionalClasses&&(b=b.concat(this.additionalClasses));this.element=LPTools.createElement("table",b);this.$_element=
$(this.element);for(var b=LPTools.createElement("tbody"),c=0,h=this.inputsArray.length;c<h;++c){var e=this.inputsArray[c],g=e.build();g.setAttribute("class","settingsRow");b.appendChild(g);e.dialog=a}LPTools.addZebraStriping(b);this.element.appendChild(b);Strings.translate(this.element)}})(document);
