var do_bgiconinput=!0,g_CSPCHECKER=0;
function popupfill_create_iframe(a,e,d,f,b,g,h,j,k,l){if(do_experimental_popupfill&&a){var c=a.getElementsByTagName("input");for(j=0;j<c.length&&j<MAX_INPUTS_HARD;j++){var p=c[j];"undefined"!==typeof p.maxLength&&"password"==p.type&&(g_isie||sendBG({cmd:"set_possiblemax",max:p.maxLength}))}g_isie&&init_LPfn()&&LPfn&&LPfn.resetSafeCloseIframe();g_iframeclose_starttime=null;e=parseInt(e)+"px";d=parseInt(d)+"px";if((p=a.body)&&!a.getElementById(LPMAGICIFRAME+f)){c=a.createElement("iframe");c.id=LPMAGICIFRAME+
f;c.name=LPMAGICIFRAME+f;g_iframe_docked=!0;if(g_isie)c.src="https://lastpass.com/fake/fake.php#framesrc=LPMAGIC",init_LPfn()&&LPfn&&9>LPfn.getDocumentMode(a)&&(c.setAttribute("allowTransparency",!0),c.setAttribute("frameBorder",0),c.allowTransparency=!0,c.frameBorder=0);else if("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk){g_popup_iframe=c;add_event_listener_if();var m=a.location.href,m=lpParseUri(m),t=Math.floor(1E8*Math.random());c.setAttribute("lpsrc",m.protocol+"://"+t+"."+m.host+"/lpblankiframe.local")}else m=
urlprefix+"popupfilltab.html","undefined"===typeof chrome&&"undefined"!=typeof lplanguage&&(m+="?lplanguage="+lplanguage),c.src=m;0>parseInt(e)&&(e="0px");0>parseInt(d)&&(d="0px");dotrans?(g_frame_css_str="display:block !important; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:none !important; opacity: 1.0 !important; margin:0 !important; padding:0 !important;","undefined"!=typeof g_isie&&g_isie&&(g_frame_css_str+="background-color:transparent !important;background-image:none !important;filter:alpha(opacity=100) !important ; ")):
g_frame_css_str="display:block; position:absolute !important; visibility:visible !important; opacity: 1.0 !important ; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); filter:alpha(opacity=100) !important; ";
c.style.cssText=g_frame_css_str;try{if(framesetarr=document.getElementsByTagName("frameset"),0==framesetarr.length)p.appendChild(c);else if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&k&&1==framesetarr.length){var n=LPJSON.stringify(g_frame_css_str+" border: none;");k.body.setAttribute("data-lp-gcss",n);var q=k.getElementsByTagName("FRAMESET");if(q&&q[0]){var r=q[0].getElementsByTagName("FRAME");if(r){var s=r[0].contentWindow.document;s.body.setAttribute("data-lp-gcss",n);s.body.appendChild(c)}else k.body.appendChild(c)}}else{k=
!1;for(j=0;j<framesetarr.length;j++){for(n=0;n<framesetarr[j].children.length;n++)if("FRAME"==framesetarr[j].children[n].tagName)if(cf=framesetarr[j].children[n].contentWindow.document,null!=cf.getElementById(f)){if(k=!0,toappendTo=cf.getElementById(f),l&&l.framesrc&&l.framesrc==get_doc_location_href(cf))break}else if(null!=cf.getElementsByName(f)&&0!=cf.getElementsByName(f).length&&(k=!0,toappendTo=cf.getElementsByName(f)[0],l&&l.framesrc&&l.framesrc==get_doc_location_href(cf)))break;if(k){try{toappendTo.ownerDocument.body.setAttribute("data-lp-gcss",
LPJSON.stringify(g_frame_css_str)),toappendTo.parentNode.appendChild(c)}catch(v){framesetarr[j].children[n].contentWindow.document.body.appendChild(c)}break}}}}catch(u){verbose_log("append failed! "+u);return}g_isie&&!LP_getloggedin()&&c.parentNode.removeChild(c);c.width=parseInt(g)+"px";g_isie?(c.height="38px",c.height="173px"):c.height="26px";"undefined"!=typeof b&&0<b&&(c.height=24*b+23+"px");c.height=0<parseInt(h)?parseInt(h)+"px":parseInt(c.height)+"px";f=parseInt(c.width)+"px";b=parseInt(c.height)+
"px";c.style.cssText=g_frame_css_str+("width: "+f+" !important; height: "+b+" !important; top:"+d+" !important; left:"+e+" !important; ");setTimeout(function(){0==g_CSPCHECKER&&("undefined"===typeof chrome&&"object"===typeof safari)&&do_iframe_sad_msg(a)},5E3)}}}
function weasel(a){LPCTR("weasel");if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;if(g_isdebug){var e=(new Date).getTime(),d=e-g_last_weasel;d>2*a&&verbose_log("last weasel cycle took too long"+d+" ms")}popupfill_resize();g_isdebug&&(e=(new Date).getTime()-e,e>a&&verbose_log("last resize took too long "+e+" ms"),g_last_weasel=(new Date).getTime());g_weasel_id=setTimeout(function(){weasel(a)},a)}}var g_last_weasel=0;
function issaveall(a){a=a.elements;for(var e=0,d=0,f=0,b=0;b<a.length;b++){var g=a[b].type;"password"==g?d++:"text"==g||"tel"==g||"email"==g?e++:"textarea"==g&&f++}return 1==e&&1==d&&0==f?!1:!0}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,e,d,f){if(!do_experimental_popupfill)return null;"undefined"==typeof f&&(f=!1);if(!a||null==e)return null;var b=e.style.left,g=e.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(b)||0>parseInt(g)){var h=a.getElementById(LPMAGICIFRAME+LP_pickFieldName(a,e));if(null!=h&&(h=LP_getAbsolutePos(a,h,null,f)))return g=parseInt(h.top),b=parseInt(h.left),isNaN(g)||isNaN(b)?null:{posx:b+"px",posy:g+"px"}}LP_pickFieldName(a,e);if(null!=e){h=LP_getAbsolutePos(a,
e,null,f);null!=h&&(b=parseInt(h.left)+POPUP_FIELD_OFFSET+"px",g=parseInt(h.top)+parseInt(h.height)+"px",g_do_icon_number_hint&&(g=parseInt(h.top)+parseInt(h.height)+4+"px"));if(null==d||0==d||""==d)h=LP_getElementByIdOrName(a,LPMAGICIFRAME+LP_pickFieldName(a,e)),d=null!=h?(d=LP_getAbsolutePos(a,h,null,!0))?d.width:0:0;if(!f){f=LP_getWindowWidth(window,!0);if(!f)return{posx:0,posy:0};parseInt(d)+parseInt(b)>f&&(b=f-parseInt(d)-20+"px")}}if(""==b||"auto"==b||""==g||"auto"==g)return null;b=parseInt(b);
g=parseInt(g);return"NaN"==b||"NaN"==g?null:{posx:b+"px",posy:g+"px"}}function verbose_log(a){verbose&&("undefined"!=typeof Date?console_log("["+g_docnum+"] "+((new Date).getTime()-g_tsstart)+" : "+a):console_log("["+g_docnum+"] "+a))}function is_watermark(){return!1}function checkAskGenerate(){}function sendKey(a,e){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(e,0,KeyEvent[keyName],!1)}catch(d){lpdbg("error",d)}return null}
function send_simulated_key(a,e,d,f){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;var b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keydown",!0,!0,null,!1,!1,f,!1,d,e):b.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,f,!1,d,d);var g=a.dispatchEvent(b);g&&("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk)&&(b=a.ownerDocument.createEvent("KeyboardEvent"),b.initKeyEvent("keypress",
!0,!0,null,!1,!1,f,!1,d,e),g=a.dispatchEvent(b));b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keyup",!0,!0,null,!1,!1,f,!1,d,e):b.initKeyboardEvent("keyup",!0,!0,null,!1,!1,f,!1,d,d);a.dispatchEvent(b);return g}var g_formmutations=0;
function checkShouldRecheck(a){function e(a){a||(a=LP_derive_doc());return!a?!1:LP_isSinglePageApp(a)||isASPpage()?!0:g_did_muto?(g_did_muto=!1,!0):!1}var d=20,f=!1,b=document,g=window;if(!a||"object"!=typeof a)a={};var h=!1,j=!1,k=!1;"undefined"!=typeof a.fromclick&&(h=a.fromclick);"undefined"!=typeof a.frommuto&&(j=a.frommuto);"undefined"!=typeof a.skipfill&&(k=a.skipfill);g_pending_recheck=!1;debug_checkpoint("entered checkShouldRecheck, clear pending state");LP_isSinglePageApp(b)&&(d=100);if(g_formmutations>
d)return verbose_log("Abort"),!1;if(LP_should_ignore_this_doc(b,h))return!1;if(do_experimental_popupfill&&0<=g_input_cnt&&0<=g_form_cnt){var d=countInputs(document),h=countFormEquivalents(document),l=computeFingerprint(document);verbose_log("checkShouldRecheck() : # inputs was "+g_input_cnt+", now "+d+" #forms was "+g_form_cnt+" now "+h+", fingerprint was "+g_input_fingerprint+" now "+l);if(g_input_cnt!=d||g_form_cnt!=h||g_input_fingerprint!=l)g_formmutations++,formcachereset(document),fieldcachereset(document),
g_isie?setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3):(get_doc_location_href(b),setTimeout(function(){LPCTR("recheck");var c=LP_get_last_url_history(b);c||(LP_put_last_url_history(b),c=LP_get_last_url_history(b));var d=c.href,c=c.href_hash,f=get_doc_location_href(b);!j&&(f!==d||a.href!==f||c!==a.href_hash)?(formcachereset(b),fieldcachereset(b),g_form_cnt=g_input_cnt=0,delete b.body._lpcrdone,LP_put_last_url_history(b),c=LP_get_last_url_history(b),a.href=c.href,a.href_hash=
c.href_hash,g_pending_recheck||checkShouldRecheck(a)):g_pending_eval||evalScriptsInFrame(g,b,!0,{skipfill:k||!e(b),href:d,href_hash:c,frommuto:j})},200)),g_input_cnt=d,g_form_cnt=h,g_input_fingerprint=l,f=!0}return f}function is_watermark_password(){return!1}
function createpopuptoplevel_handler(a){if(!a)return!1;var e=LP_derive_doc();g_iscasper&&a.override_doc&&(e=a.override_doc);var d=parseInt(a.from_iframe.posx),f=parseInt(a.from_iframe.posy),b=a.from_iframe.id,g=a.from_iframe.rows,h=a.from_iframe.width,j=a.from_iframe.framename,k=a.from_iframe.framesrc,l=null;if(is_your_popup_showing(e))return!1;var c=find_iframe_pos(e,j,k,!1);c||(c=find_iframe_pos(e,j,k,!0),null!==c&&"undefined"!=typeof c.cframedoc?l=c.cframedoc:pass);k=j=0;c?(j=parseInt(c.left)+
d+"px",k=parseInt(c.top)+f+"px",g_toplevel_initial_abs_x=j,g_toplevel_initial_abs_y=k):k=j="10px";popupfill_create_iframe(e,j,k,b,g,h,"90px",!1,l,a.from_iframe);g_popupfill_iframe_width_save=h;return!0}var g_toplevel_initial_abs_x=null,g_toplevel_initial_abs_y=null;
function popupfillresize_handler(a){0<a.width&&(g_minwidth_override=parseInt(a.width));0<a.height&&(g_minheight_override=parseInt(a.height));g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&!LP_inIframe(window)&&toplevel_iframe_state_get()&&relocate_popupfill_iframes(document)}
function find_iframe_pos(a,e,d,f){if(!a)return null;var b,g;try{var h=a.getElementsByTagName("IFRAME");f&&(h=a.getElementsByTagName("FRAME"));if(!e&&1==h.length)return LP_getAbsolutePos(a,h[0],!0,!0);var j=[];for(b=0;b<h.length&&50>b;b++)j[b]=h[b];for(b=0;b<j.length;b++)if(j[b].name&&""!=e&&j[b].name==e||j[b].src&&""!=d&&compare_puny_urls(j[b].src,d))return LP_getAbsolutePos(a,j[b],!0,!0);if(f)for(b=0;b<j.length;b++){var k=j[b].contentWindow.document,l=k.getElementsByTagName("FRAME");for(g=0;g<l.length&&
50>g;g++)if(l[g].name&&""!=e&&l[g].name==e||l[g].src&&""!=d&&l[g].src==d){var c=LP_getAbsolutePos(k,l[g],!0,!0);c.cframedoc=k;return c}}}catch(p){}return null};
