var g_ischrome="undefined"!=typeof chrome&&("undefined"!=typeof chrome.runtime||"undefined"!=typeof chrome.extension),g_issafari="undefined"!=typeof safari&&"undefined"!=typeof safari.self,g_isopera="undefined"!=typeof opera&&"undefined"!=typeof opera.extension,close_img_src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABYklEQVR42qXTvWrCUBQHcKe+QqfundPFxT0OnTJ0MtChmw/g4NgH6FtkEwoBv8BEA8EYFGswBIIEhFCrU4V26cfp+Qe5RLlKwcAPknty/7mHe1NoNBoy9+yZJWzBcN3J3j0cuGJJt9ul0WhEYRjSfD4nz/Oo0+kQ10J2eSygyL4xcb1eyyAUIV/sWhawHY/HtFqtTvJ9HyGbw4B6r9ejNE3/ZdfOQz4gnkwmtFwuM7VajRRFIcMwyLIs3GNM1HetePmA9yAIKEkSoVqtUrlcBtzv1abTKQJe9wIwGMexgGd8GQ5rvFoEvOUDFtiqKIoEXddJVdWMpml7Ndd1EfCSD3jC3mPPoVKpUKlUItM0AavAmKi3220E1PMBF+zTcRyazWYn9ft9Qsuyc3DLfm3bRs8y2BFM/mFFWQDcsE2r1SKsZjgcZgaDATWbTUxOxSmUBwiPLGEfOzGrH/uZzlIgorP8ASYfyJK1fcokAAAAAElFTkSuQmCC",
x3_img_src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABX0lEQVR42qXTsWrCUBTGcaFroZNTwQfo1KnQN3CQblLIkD2CFIqbaEBQsGAIJBAaCIoQI4JKoeADFDpVmuCsUyE4FJyznJ4vSEjkKgWFH4R7cv/RS8zNZjORO/bMXDZkT+xWdO/hwtV+E02n0wxeg1d2eSxQYD+TyYRc1xXiGSIblhcFPnGT4zgnjUYjRBaHgaLneWSa5r+Mx2NE7tOBvmVZ1O12Y8vlkqIoovl8ToPBANdYS+a2bSPwkg58YNBsNhNBENB2uwVcZ2a9Xg+Bt0yg1WpRrVZLNBoNPBlwnZm1220E3tOBIQKKoiRWqxWFYRhbr9eZWafTQcBIBx4NwyBZlmO+79Nut8OTAd8Ca8kc54WDTwcu2He9XqdyuXySqqqEnyx6D27YLyKlUkkEB4jNISuIAnDNFpqmUaVSIUmSYtVqlXRdx2Z88uJXOeuBuexrr8+Kx/5MZ8kR0Vn+AGczfuZVuZDxAAAAAElFTkSuQmCC",
g_searchfillbox=null,g_searchloginbox=null,pass=!0,g_40notify=!1,showintro=!1,showinterstitial=!1,showadddialog=!1,showtryagain=!1,preventhideoverlay=!1;addStyle(!0);
function totp_enable(){var b=document.createElement("div");b.id="totp_step2";var a=document.createElement("center"),c=document.createElement("img");c.setAttribute("src","images/vault_4.0/Loading.gif");a.appendChild(c);a.appendChild(document.createElement("br"));a.appendChild(document.createElement("br"));c=document.createElement("b");c.appendChild(document.createTextNode(gs("Great. One moment, please.")));a.appendChild(c);b.appendChild(a);a=document.getElementById("totp_step1");a.parentNode.replaceChild(b,
a);sendRequest({cmd:"enabletotp",tld:getQueryVariable("tld")},enabletotp_response)}
function enabletotp_response(b){var a=document.createElement("div"),c=document.createElement("b");c.appendChild(document.createTextNode(b.ok?gs("You did it!"):gs("Great! Here's what you do.")));a.appendChild(c);a.appendChild(document.createElement("br"));a.appendChild(document.createElement("br"));a.appendChild(document.createTextNode(b.ok?gs("Your preferences have been updated, so next time you need multifactor authentication on this page, you'll get a push notification."):gs("Setting up push notifications with LastPass Authenticator is simple. Open the LastPass Authenticator app, and either scan or manually add this website's information in the multifactor authenticator settings.")));
b=document.getElementById("totp_step2");b.parentNode.replaceChild(a,b)}
function totp_sendlink(){var b=document.createElement("div"),a=document.createElement("b");a.appendChild(document.createTextNode(gs("Send me a link")));b.appendChild(a);b.appendChild(document.createElement("br"));b.appendChild(document.createElement("br"));b.appendChild(document.createTextNode(gs("Simply choose if you'd like the link emailed to you or sent via SMS message.")));b.appendChild(document.createElement("br"));b.appendChild(document.createElement("br"));b.appendChild(document.createTextNode(gs("Email")));
b.appendChild(document.createElement("br"));a=document.createElement("input");a.id="email";a.style.width="100%";a.style.height="50px";a.value=getQueryVariable("username");b.appendChild(a);a=document.createElement("center");a.appendChild(document.createTextNode(gs("- or -")));b.appendChild(a);b.appendChild(document.createTextNode(gs("Phone Number")));b.appendChild(document.createElement("br"));a=document.createElement("input");a.id="phone";a.style.width="100%";a.style.height="50px";b.appendChild(a);
b.appendChild(document.createElement("br"));b.appendChild(document.createElement("br"));a=document.createElement("input");a.setAttribute("type","button");a.setAttribute("value",gs("Cancel"));a.addEventListener("click",function(){sendRequest({cmd:"hidetotp"})});a.style.width="48%";a.style.height="50px";a.style.backgroundColor="#3C4A54";a.style.color="white";a.style.fontWeight="bold";b.appendChild(a);a=document.createElement("input");a.setAttribute("type","button");a.setAttribute("value",gs("Send"));
a.addEventListener("click",function(){sendRequest({cmd:"invitetotp",email:document.getElementById("email").value,phone:document.getElementById("phone").value});sendRequest({cmd:"hidetotp"})});a.style.width="48%";a.style.height="50px";a.style.backgroundColor="#D32D27";a.style.color="white";a.style.fontWeight="bold";a.style.float="right";b.appendChild(a);a=document.getElementById("totp_step1");a.parentNode.replaceChild(b,a)}
function load(){"undefined"!=typeof safari?(safari.self.removeEventListener("message",handleMessage,!1),safari.self.addEventListener("message",handleMessage,!1)):g_isfirefoxsdk&&window.addEventListener("message",handleMessage,!1);0<document.location.href.indexOf("&do40=1")&&(g_40notify=!0);0<document.location.href.indexOf("&doInterstitial=1")&&(showinterstitial=!0);0<document.location.href.indexOf("&doIntro=1")&&(showintro=!0);0<document.location.href.indexOf("&showadddialog=1")&&(showadddialog=!0);
0<document.location.href.indexOf("&showtryagain=1")&&(showtryagain=!0,showadddialog=!1);0<document.location.href.indexOf("&hideoverlay=1")&&(preventhideoverlay=!0);if(0<document.location.href.indexOf("&add=1"))document.body.style.background=get_notification_add_bg();else if(0<document.location.href.indexOf("&error=1"))document.body.style.background=get_notification_error_bg();else if(0<document.location.href.indexOf("&context="))document.body.style.backgroundColor="#E8EDF9",document.body.style.margin=
"0px";else{if(0<document.location.href.indexOf("&cpwbot")){var b=getQueryVariable("symbolic"),a=getQueryVariable("cpwbot");display_cpw_message_loop(document,a,b);return}if(0<document.location.href.indexOf("&totp")){var c=-1!=document.location.href.indexOf("&multifactorenabled=1"),a=-1!=document.location.href.indexOf("&lastpassauthenabled=1"),b=document.createElement("div");b.style.border="1px solid #000";b.style.marginRight="10px";b.style.padding="20px";b.style.backgroundColor="#fff";b.style.fontFamily=
'"Open Sans",Arial,sans-serif';b.style.fontSize="14px";var d=document.createElement("img");d.setAttribute("src","images/authenticator.png");b.appendChild(d);var e=document.createElement("a");e.setAttribute("href","#");e.onclick=function(){lpshowmenudiv("totp");return!1};d=document.createElement("img");d.id="lptotp";d.setAttribute("src","images/dropdown.png");d.style.float="right";e.appendChild(d);b.appendChild(e);b.appendChild(document.createElement("br"));b.appendChild(document.createElement("br"));
d=document.createElement("div");d.id="totp_step1";e=document.createElement("b");e.appendChild(document.createTextNode(gs("Tired of typing those 6 numbers?")));d.appendChild(e);d.appendChild(document.createElement("br"));d.appendChild(document.createElement("br"));c=a?gs("LastPass Authenticator can send you a push notification instead, and decrease your authentication annoyance with a single tap."):c?gs("LastPass Authenticator can send you a push notification instead, and decrease your authentication annoyance with a single tap.  Switch to LastPass Authenticator today."):
gs("LastPass Authenticator can send you a push notification instead, and decrease your authentication annoyance with a single tap.  Download LastPass Authenticator today.");d.appendChild(document.createTextNode(c));d.appendChild(document.createElement("br"));d.appendChild(document.createElement("br"));a&&(e=document.createElement("a"),e.setAttribute("target","_blank"),e.setAttribute("href","https://helpdesk.lastpass.com/"),e.appendChild(document.createTextNode(gs("Learn more"))),d.appendChild(e),
d.appendChild(document.createElement("br")),d.appendChild(document.createElement("br")));c=document.createElement("input");c.setAttribute("type","button");c.setAttribute("value",a?gs("Enable"):gs("Send me a link"));c.addEventListener("click",a?totp_enable:totp_sendlink);c.style.width="100%";c.style.height="50px";c.style.backgroundColor="#D32D27";c.style.color="white";c.style.fontWeight="bold";d.appendChild(c);b.appendChild(d);document.body.appendChild(b);b=document.createElement("div");b.id="lppopuptotp";
b.className="lppopup";a=document.createElement("table");a.setAttribute("width","100%");d=document.createElement("tr");c=document.createElement("td");c.style.height="45px";c.appendChild(document.createTextNode(gs("Dismiss this notification")));c.addEventListener("click",function(){sendRequest({cmd:"hidetotp"})});d.appendChild(c);a.appendChild(d);d=document.createElement("tr");c=document.createElement("td");c.style.height="45px";var f=getQueryVariable("tld");c.appendChild(document.createTextNode(sprintf(gs("Don't show this for %s"),
f)));c.addEventListener("click",function(){sendRequest({cmd:"disabletotp",tld:f});sendRequest({cmd:"hidetotp"})});d.appendChild(c);a.appendChild(d);d=document.createElement("tr");c=document.createElement("td");c.style.height="45px";c.appendChild(document.createTextNode(gs("Don't show this option for any site")));c.addEventListener("click",function(){sendRequest({cmd:"disabletotp",tld:"all"});sendRequest({cmd:"hidetotp"})});d.appendChild(c);a.appendChild(d);b.appendChild(a);document.body.appendChild(b);
return}document.body.style.background=get_notification_bg()}document.body.style.backgroundRepeat="repeat-x";g_ischrome?chrome_runtime_sendMessage({cmd:"getnotificationdata"},function(a){document.body.innerHTML=a.html;stylize_tags();setup_extra(a.extra);setup_event_handlers();initialize_sorttable();g_40notify&&diddle_40(document);showtryagain?(document.body.innerHTML="",a=new IntroTutorialHelpDialog,a.initialize(document,{makeShade:!1,alignBottom:!1,addHide:!0,transparentBG:!0,textChoice:"tryAgain",
arrow:{orientation:"right",position:"middle"}})):showintro&&(document.body.innerHTML="",a=new IntroTutorialHelpDialog,a.initialize(document,{makeShade:!1,alignBottom:!1,addHide:!0,transparentBG:!0,textChoice:"siteLanding",arrow:{orientation:"right",position:"middle"}}));showinterstitial&&(document.body.innerHTML="",a=new IntroTutorialHelpDialog,a.initialize(document,{makeShade:!0,alignBottom:!1,addHide:!1,transparentBG:!0,textChoice:"interstitial"}));showadddialog&&(a=new IntroTutorialHelpDialog,
a.initialize(document,{makeShade:!0,alignBottom:!1,addHide:!0,transparentBG:!1,appendElementId:"main",position:{positionFn:function(){return{top:document.getElementById("lpaddsite").offsetTop,left:document.getElementById("lpaddsite").offsetLeft}},offset:{top:37,left:-217}},textChoice:"saveSite",arrow:{orientation:"top",position:"right"}}))}):"undefined"!=typeof safari?safari.self.tab.dispatchMessage("getnotificationdata",{}):g_isfirefoxsdk&&window.parent.postMessage({messagetype:"getnotificationdata"},
"*")}
function handleMessage(b){if(g_isopera||g_isfirefoxsdk)b.message=b.data,b.name=b.data.messagetype;if(("gotnotificationdata"==b.name||"gotnotificationdata"==b.message.cmd)&&setup_extra(b.message.extra)){if(g_isfirefoxsdk){LP_decimate_children(document.body);for(var a=(new DOMParser).parseFromString(b.message.html,"text/html");a.body.firstChild;)document.body.appendChild(a.body.removeChild(a.body.firstChild))}else document.body.innerHTML=b.message.html;stylize_tags();setup_event_handlers();initialize_sorttable();g_40notify&&
diddle_40(document)}if("gotcpwmsg"==b.name||"gotcpwmsg"==b.message.cmd)b.message.msg&&display_cpw_message(document,b.message.msg),1===b.message.minimize_state&&minimize_cpw_dialog(document);"enabletotp_response"==b.name|"enabletotp_response"==b.message.cmd&&enabletotp_response(b.message)}
function setup_extra(b){b=LPJSON.parse(b);return-1!=document.location.href.indexOf("&"+b.type+"=")?(document_location_href=b.document_location_href,g_fillaid=b.g_fillaid,from=b.from,data={},"undefined"!=typeof b.notificationdata&&(data.notificationdata=b.notificationdata),!0):!1}
function setup_event_handlers(){for(var b=1;3>=b;b++)for(var a=document.getElementsByTagName(1==b?"img":2==b?"button":"tr"),c=0;c<a.length;c++)if(a[c].id)if("lpaddcreditcard"==a[c].id)a[c].addEventListener("click",function(){addcc()});else if("lpaddprofile"==a[c].id)a[c].addEventListener("click",function(){addprofile()});else if("lpaddsite"==a[c].id)a[c].addEventListener("click",function(){savethesite(utf8_to_b64(data.notificationdata))});else if("lpautofill"==a[c].id){var d=a[c].getAttribute("lptype");
d&&"autofillsingle"==d?a[c].addEventListener("click",function(){autofill(this.getAttribute("aid"));hideoverlay()}):a[c].addEventListener("click",function(){clear_searchbox("autofill");showmenu("autofill")})}else 0==a[c].id.indexOf("lpautofill")?a[c].addEventListener("click",function(){autofill(this.id.substring(10))}):"lpautologin"==a[c].id?(d=a[c].getAttribute("lptype"))&&"autologinsingle"==d?a[c].addEventListener("click",function(){autologin(this.getAttribute("aid"))}):a[c].addEventListener("click",
function(){clear_searchbox("autologin");showmenu("autologin")}):0==a[c].id.indexOf("lpautologin")?a[c].addEventListener("click",function(){autologin(this.id.substring(11))}):"lpbasicauthmoreinfobtn"==a[c].id?a[c].addEventListener("click",function(){genericaction("basicauthmoreinfobtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpbasicauthneverbtn"==a[c].id?a[c].addEventListener("click",function(){genericaction("basicauthneverbtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):
"lpchooseprofilecc"==a[c].id?a[c].addEventListener("click",function(){chooseprofilecc()}):"lpclearforms"==a[c].id?a[c].addEventListener("click",function(){clearforms()}):"lpconfirm"==a[c].id?a[c].addEventListener("click",function(){changepw(utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpcreateaccountbtn"==a[c].id?a[c].addEventListener("click",function(){genericaction("createaccountbtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpdisablebtn"==a[c].id?a[c].addEventListener("click",
function(){genericaction("disablebtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpfeedbackbtn"==a[c].id?a[c].addEventListener("click",function(){genericaction("feedbackbtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpstarttrialbtn"==a[c].id?a[c].addEventListener("click",function(){genericaction("starttrialbtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpfillcurrent"==a[c].id?a[c].addEventListener("click",function(){showmenu("fillcurrent")}):0==a[c].id.indexOf("lpfillcurrent")?
a[c].addEventListener("click",function(){fillcurrent(this.id.substring(13))}):"lpfillform"==a[c].id?a[c].addEventListener("click",function(){showmenu("fillform")}):0==a[c].id.indexOf("lpfillform")?a[c].addEventListener("click",function(){fillform(this.id.substring(10))}):"lpgenerate"==a[c].id?a[c].addEventListener("click",function(){generate()}):"lphideoverlay"==a[c].id?(g_40notify||(a[c].addEventListener("mouseover",function(){this.src=x3_img_src}),a[c].addEventListener("mouseout",function(){this.src=
close_img_src})),a[c].addEventListener("click",function(){hideoverlay();sendRequest({cmd:"stoptutorial"})})):"lpnever"==a[c].id?a[c].addEventListener("click",function(){showmenu("never");sendRequest({cmd:"stoptutorial"})}):"lpneverautofill"==a[c].id?a[c].addEventListener("click",function(){never("neverautofill",btoa(document_location_href),g_fillaid,from)}):"lpneverdomain"==a[c].id?a[c].addEventListener("click",function(){never("neverdomain",btoa(document_location_href),g_fillaid,from);sendRequest({cmd:"stoptutorial"})}):
"lpneverpage"==a[c].id?a[c].addEventListener("click",function(){never("neverpage",btoa(document_location_href),g_fillaid,from);sendRequest({cmd:"stoptutorial"})}):"lpnotnow"==a[c].id?a[c].addEventListener("click",function(){notnow(utf8_to_b64(data.notificationdata),btoa(lp_gettld_url(document_location_href)))}):"lpsavenewsite"==a[c].id?a[c].addEventListener("click",function(){savethesite(utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lptryagainbtn"==a[c].id?a[c].addEventListener("click",
function(){genericaction("tryagainbtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"lpcustombtn"==a[c].id?a[c].addEventListener("click",function(){genericaction("custombtn",utf8_to_b64(LPJSON.stringify(data.notificationdata)))}):"autofilltabsearchboxreset"==a[c].id?(a[c].addEventListener("click",function(){clear_searchbox("autofill")}),a[c].src=x3_img_src):"autologintabsearchboxreset"==a[c].id&&(a[c].addEventListener("click",function(){clear_searchbox("autologin")}),a[c].src=x3_img_src);
g_searchfillbox=document.getElementById("autofilltabsearchbox");null!=g_searchfillbox&&g_searchfillbox.addEventListener("keyup",function(){dofilter("autofill")},!1);g_searchloginbox=document.getElementById("autologintabsearchbox");null!=g_searchloginbox&&g_searchloginbox.addEventListener("keyup",function(){dofilter("autologin")},!1)}
function clear_searchbox(b){var a;if("autofill"==b)a=g_searchfillbox;else if("autologin"==b)a=g_searchloginbox;else return;if(null!=a){a.value="";for(var c=document.getElementsByTagName("tr"),d=0;d<c.length;d++){var e=c[d].id;0==e.indexOf("lp"+b)&&(e=document.getElementById(e),"table-row"!=e.style.display&&(e.style.display="table-row"))}b=document.getElementById(b+"footer");null!=b&&(b.className="lppopupsearchbox");a.focus()}}
function sendRequest(b,a){g_ischrome?chrome_runtime_sendMessage(b,a?a:function(){}):g_issafari?safari.self.tab.dispatchMessage(b.cmd,b):g_isfirefoxsdk&&(b.messagetype=b.cmd,window.parent.postMessage(b,"*"))}function hideoverlay(){sendRequest({cmd:"hideoverlay"})}var g_firstmenu=!0;
function showmenu(b){!g_firstmenu&&document.getElementById("lppopup"+b)&&"none"!=document.getElementById("lppopup"+b).style.display?(hideMenus(),sendRequest({cmd:"slideupoverlay"})):(g_firstmenu=!0,hideMenus(),sendRequest({cmd:"slidedownoverlay"}),lpshowmenudiv(b))}function autofill(b){sendRequest({cmd:"autofillaid",aid:b});hideMenus();slideup()}function autologin(b){sendRequest({cmd:"autologinaid",aid:b});hideMenus();slideup()}
function fillcurrent(b){sendRequest({cmd:"fillcurrentaid",aid:b});hideMenus();slideup()}function fillform(b){sendRequest({cmd:"fillformffid",ffid:b});hideMenus();slideup()}function addprofile(){sendRequest({cmd:"addprofile"});hideMenus();hidecontext()}function addcc(){sendRequest({cmd:"addcreditcard"});hideMenus();hidecontext()}function clearforms(){sendRequest({cmd:"clearforms"});hideMenus();hidecontext()}
function never(b,a,c,d){var e=1==d?1:0,f=2==d?1:0;d=3==d?1:0;sendRequest({action:"never",cmd:b,url:atob(a),aid:c,fromsave:e,fromgenerate:f,fromformfill:d});sendRequest({cmd:"hideoverlay"})}function notnow(b,a){sendRequest({cmd:"notnow",notificationdata:b64_to_utf8(b),tld:atob(a)});sendRequest({cmd:"hideoverlay"})}function savethesite(b){sendRequest({cmd:"savethesite",notificationdata:b64_to_utf8(b)});sendRequest({cmd:"hideoverlay"})}
function changepw(b){sendRequest({cmd:"changepw",notificationdata:b64_to_utf8(b)});sendRequest({cmd:"hideoverlay"})}function genericaction(b,a){sendRequest({cmd:b,notificationdata:b64_to_utf8(a)});sendRequest({cmd:"hideoverlay"})}
function generate(){sendRequest({cmd:"generate"});document.getElementById("lastpass-notification")&&(!document.getElementById("lppopupfillform")&&!document.getElementById("lppopupfillcurrent"))&&(document.getElementById("lastpass-notification").style.display="none");hidecontext()}function chooseprofilecc(){sendRequest({cmd:"chooseprofilecc"});sendRequest({cmd:"hideoverlay"});hidecontext()}function slideup(){sendRequest({cmd:"slideupoverlay"})}
function hideMenus(){document.getElementById("lppopupautofill")&&(document.getElementById("lppopupautofill").style.display="none");document.getElementById("lppopupautologin")&&(document.getElementById("lppopupautologin").style.display="none");document.getElementById("lppopupnever")&&(document.getElementById("lppopupnever").style.display="none");document.getElementById("lppopupfillform")&&(document.getElementById("lppopupfillform").style.display="none");document.getElementById("lppopupfillcurrent")&&
(document.getElementById("lppopupfillcurrent").style.display="none");-1!=document.location.href.indexOf("&bottom=1")&&(document.body.style.marginTop="",document.body.style.backgroundPosition="")}function copyusername(b){sendRequest({cmd:"copyusername",aid:b});hidecontext()}function copypassword(b){sendRequest({cmd:"copypassword",aid:b});hidecontext()}function copyurl(b){sendRequest({cmd:"copyurl",aid:b});hidecontext()}
function recheckpage(b){sendRequest({cmd:"recheckpagecontext",aid:b});hidecontext()}var g_context=null,g_ffid=null;function showcontext(b,a){g_context=b;document.getElementById("contextmain").style.display="none";3>b?document.getElementById("contextsub").style.display="block":3==b?document.getElementById("contextff").style.display="block":5==b?document.getElementById("contextsub").style.display="block":4==b&&(document.getElementById("contextffsub").style.display="block",g_ffid=a)}
function docontextaction(b){0==g_context?autofill(b):1==g_context?copyusername(b):2==g_context?copypassword(b):5==g_context&&copyurl(b);hidecontext()}function ffsub(b){0==b?sendRequest({cmd:"fillformffid",ffid:g_ffid}):1==b&&sendRequest({cmd:"editprofile",ffid:g_ffid});hidecontext()}function hidecontext(){sendRequest({cmd:"hidecontext"})}
document.addEventListener("click",function(b){if(!preventhideoverlay){var a="autologintab autologintabfooter autologintabheader autologintabsearchlabel autofilltab autofilltabfooter autofilltabheader autofilltabsearchlabel sorttable_sortrevind sorttable_sortfwdind".split(" "),c=null,d=null;"undefined"!=typeof b.target&&(c=b.target.id,"undefined"!=typeof b.target.parentElement&&null!=b.target.parentElement&&(d=b.target.parentElement.id));var e=!1,f;for(f in a){if(null!=c&&c==a[f]){e=!0;break}if(null!=
d&&d==a[f]){e=!0;break}}e||(showintro?sendRequest({cmd:"hideoverlay"}):"BUTTON"!=b.target.nodeName&&(hideMenus(),sendRequest({cmd:"slideupoverlay"})))}},!1);var g_lastsize=-1;window.onresize=function(){document&&document.body&&(g_lastsize>document.body.clientHeight&&hideMenus(),g_lastsize=document.body.clientHeight)};document.addEventListener("DOMContentLoaded",function(){g_isfirefoxsdk?load():window.addEventListener("load",function(){load()})});
function dofilter(b){var a;if("autofill"==b)a=g_searchfillbox;else if("autologin"==b)a=g_searchloginbox;else return;null!=a&&(b=document.getElementById(b+"tab"),a=a.value.toLowerCase(),sorttable.filter(b,a))}
function initialize_sorttable(){sorttable.init();var b=document.getElementById("autofilltab");null!=b&&sorttable.initial_sort(b.tHead.rows[0].cells[2]);b=document.getElementById("autologintab");null!=b&&sorttable.initial_sort(b.tHead.rows[0].cells[2]);g_searchfillbox=document.getElementById("autofilltabsearchbox");g_searchloginbox=document.getElementById("autologintabsearchbox")}function utf8_to_b64(b){return window.btoa(unescape(encodeURIComponent(b)))}
function b64_to_utf8(b){return decodeURIComponent(escape(window.atob(b)))}function stylize_tags(){if(g_ischrome)for(var b=["img","div","th","tr","td"],a=0;a<b.length;a++)for(var c=document.getElementsByTagName(b[a]),d=0;d<c.length;d++)c[d].getAttribute("data-lpstyle")&&(c[d].style.cssText=c[d].getAttribute("data-lpstyle"))}
function diddle_40(b){b||(b=document);var a=b.getElementsByTagName("button"),c;if(a)for(c=0;c<a.length;c++)a[c].className+=" lpbutton40 lptext40";if(a=b.getElementById("lastpass-content"))a.className+=" lptext40";a=null;c=b.getElementsByTagName("MAIN");0<c.length&&(a=c[0]);a&&(a.style.backgroundColor=b.body.style.backgroundColor,a.style.borderColor=a.style.backgroundColor,a.style.borderWidth="8px",a.style.borderStyle="solid");b.body&&(b.body.style.backgroundColor="transparent",b.body.style.margin=
"0");return!0};
