var SHOULD_DO_LOGIN_ONLY=!0,SHOULD_DO_ALWAYS=!1;
function popupfill_shoulddofield(a,b,c){var d=["lpcurrpasselt","lpcurruserelt"];if(do_experimental_popupfill&&!(null==b||"undefined"==typeof b.type||"hidden"==b.type)&&("text"==b.type||"password"==b.type||"email"==b.type||!c&&"tel"==b.type||!c&&"url"==b.type||!c&&"textarea"==b.type)){var e=LP_pickFieldName(a,b);if(lp_in_array(e,d))return decision_log(a,"DE28",{param1:e}),!1;if(is_search_field(a,b,!c)||is_date_field(b)||LP_looksLikeOTPField(a,b)||LP_explicit_ignored(a,b)||LP_implicit_ignored(a,b)||
LP_isCaptchaField(b))return!1;if(c){if(!chk_form_has_password(a,b.form)&&!checkDocumentForLoginOrphans(a))return verbose&&(b=LP_pickFormName(a,b.form),decision_log(a,"DE29",{param1:b})),!1;if(b.form&&is_shopping_form(a,b.form)&&g_aspx_hack&&(isASPpage()&&2<a.getElementsByTagName("form").length||!isASPpage()))return!1}return!0}return!1}
function chk_form_ask_generate(a,b,c){var d=null;if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;var e=LP_pickFormName(a,b),f;if(!c&&(f=formcacheget(a,e,"ask_generate"),null!=f))return f;var g="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(g.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(g.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_login",!1),!1;try{var h=gettldcached(a.location.href)}catch(n){return!1}var m=
f=0,l=3;c&&(l=2);g_aspx_hack&&isASPpage()&&(l=7);if("tumblr.com"==h&&(tumblr_action_btn=a.getElementById("signup_forms_submit"),null!=tumblr_action_btn)){c=tumblr_action_btn.getElementsByTagName("SPAN");var r;for(r=0;r<c.length;r++)if(0<=c[r].className.indexOf("login_btn")&&checkIsDisplayed(a,c[r],0,h))return!1}if(!checkIsDisplayed(a,b,0,h))return decision_log(a,"DE30"),!1;c=LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=c&&(0<=c.toLowerCase().indexOf("signup")||0<=c.toLowerCase().indexOf("register"))&&
-1==c.toLowerCase().indexOf("login"))return decision_log(a,"DE31",{param1:e}),formcacheset(a,e,"ask_generate",!0),!0;var j=!1;if("undefined"!=typeof Math){c=Math.floor(1E4*Math.random());var j=g=r=0,p=null,q=b.elements.length;Checkpoint.assert(q<MAX_FORM_ELEMENTS_SOFT,"form "+e+" too big 1");q>MAX_FORM_ELEMENTS_SOFT&&(q=MAX_FORM_ELEMENTS_SOFT);for(var s=0;s<q;s++){var k=b.elements[s];"INPUT"==k.tagName&&("password"==k.type?r++:("text"==k.type||"email"==k.type)&&g++);if("INPUT"==k.tagName&&"submit"==
k.type||"BUTTON"==k.tagName)if(j++,p=k,10<j&&b.elements.length>MAX_FORM_ELEMENTS_SOFT)return!1}if(1==j&&2>=g&&0<r&&checkButtonHint(p))return decision_log(a,"DE32"),!1;g=b.elements;for(s=0;s<MAX_FORM_ELEMENTS_SOFT&&s<g.length;s++)if(k=g[s],j=!1,"FIELDSET"!=k.tagName&&valid_by_role(a,k)&&!LP_fieldIsDisabled(k)&&!LP_treat_as_hidden(k)&&("expedia.com"==h||checkIsDisplayed(a,k,0,h,c)))if(!g_use_wacky_disp||is_wacky_disp(a,k)){if("text"==k.type&&is_watermark(k.className)&&is_watermark_password(k))try{k.type=
"password"}catch(t){j=!0}p=LP_elt_get_text(k);if("BUTTON"==k.tagName&&"submit"==k.type&&null!=p&&0<=p.indexOf("Create")||"BUTTON"==k.tagName&&"submit"==k.type&&null!=p&&0<=p.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Create")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Sign me up")||"INPUT"==k.tagName&&"image"==k.type&&null!=k.value&&
"create"==k.value)l=2,decision_log(a,"DE33",{param1:e});if(1<r&&LP_passwordAlt(a,k))m++;else if(p=fieldIsDoublePassword(a,k),!b||!("form1"==b.id&&b.action&&"string"==typeof b.action&&b.action.indexOf(".aspx")&&"text"==k.type&&(p===DOUBLE_PW_VISIBLE||p===DOUBLE_SECRET_PW_VISIBLE)))if(!do_bgiconinput||!("text"==k.type&&(p===DOUBLE_TEXT_VISIBLE||p===DOUBLE_SECRET_TEXT_VISIBLE))){if("password"==k.type||j||"text"==k.type&&p===DOUBLE_TEXT_VISIBLE||"text"==k.type&&p===DOUBLE_SECRET_TEXT_VISIBLE){j=k.getAttribute("placeholder");
null!=j&&0<=j.indexOf("Create your")&&(l=2);if("facebook.com"==h&&"string"==typeof k.id&&k.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/))continue;else if("tdbank.com"==h&&"string"==typeof k.name&&"user"==k.name){m++;continue}if(0==f&&1<r&&passwordIsFake(k)){m++;continue}if(0<f&&1<r&&LP_looksLikeOTPField(a,k)){m++;continue}LP_get_input_pattern(a,k)&&!d&&(d=k);f++}else if("email"==k.type||"text"==k.type||"textarea"==k.type||"tel"==k.type||"url"==k.type)if(treat_text_as_password(k))f++;else{if(LP_isForgetField(k))continue;
lpIsVisible(k,!0)&&(j=LP_pickFieldName(a,k),LP_looksLikeOTPField(a,k)?decision_log(a,"DE35",{param1:j}):m++)}if(4<=f||100<=m)return 4<=f&&decision_log(a,"DE37",{param1:e,param2:f,param3:m}),100<=m&&decision_log(a,"DE38",{param1:e,param2:f,param3:m}),formcacheset(a,e,"ask_generate",!1),!1;if(2<=f||1<=f&&m>=l)return 2<=f&&decision_log(a,"DE39",{param1:e,param2:f,param3:m}),1<=f&&m>=l&&decision_log(a,"DE40",{param1:e,param2:f,param3:m}),formcacheset(a,e,"ask_generate",!0),d&&!g_isie&&!g_isfirefox&&sendBG_generate_pattern(a,
d),!0}}decision_log(a,"DE41",{param1:e,param2:f,param3:m});formcacheset(a,e,"ask_generate",!1);return!1}}function passwordIsFake(a){var b=/(?:Account)|(?:Member)|(?:IUO_NAME)/i,c=a.name;return b.exec(a.id)||b.exec(c)?!0:!1}function checkButtonHint(a){if(!a)return!1;var b="INPUT"==a.tagName?a.value:a.innerHTML,c=/(?:Login)|(?:Log.In)|(?:Logon)|(?:Log.on)/i;return c.exec(a.id)||c.exec(b)?!0:!1}
function LP_isForgetField(a){if(!a)return!1;var b=a.id;a=a.name;var c=RegExp(lpgs("ff_forgot_regexp"),"i");return c.exec(b)||c.exec(a)?!0:!1}function LP_isCaptchaField(a){if(!a)return!1;var b=a.id;a=a.name;var c=RegExp(lpgs("ff_captcha_regexp"),"i");return c.exec(b)||c.exec(a)?!0:!1}
function element_is_detached(a,b,c){if(!b||!a&&(a=b.ownerDocument,!a))return!1;"undefined"==typeof c&&(c=0);var d=null;try{if(15<c&&(d=!1),null==b.parentNode&&(d=!0),b.parentNode===a.documentElement||b.parentNode===b.ownerDocument.documentElement)d=!1}catch(e){d=!0}return null==d?element_is_detached(a,b.parentNode,c+1):d}
function get_javaservlet_fields(a,b){if(!a)return[];if("undefined"==typeof b||null===b)b=!1;var c=[],d=a.getElementsByName("j_username"),e=a.getElementsByName("j_password");if(1===d.length&&1===e.length)Checkpoint.assert(d[0].form===e[0].form,"javaservlet form mismatch"),c=[d[0],e[0]];else if(b&&(1===d.length||1===e.length)){var f=null,g=null;1===d.length&&(f=d[0]);1===e.length&&(g=e[0]);c=[f,g]}else{d=a.getElementsByTagName("FORM");f=LP_getFormsThreshold(a);Checkpoint.assert(d.length<f,"too many forms on page");
for(e=0;e<f&&e<d.length;e++)if(d[e].action&&"undefined"!=typeof d[e].action.indexOf&&0<=d[e].action.indexOf("j_security_check")){f=form_get_username(a,d[e]);g=form_get_password(a,d[e]);f&&g&&(c=[f,g]);break}}return c}
function is_random_hashstr(a){return!a?!1:(16==a.length||32==a.length)&&a.match(/^[a-zA-Z0-9]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||32==a.length&&a.match(/^[a-f0-9]+$/)||a.match(/_\d{18}[A-Z]{4}_/)||17==a.length&&"a"==a.charAt(0)&&a.match(/^[a-zA-Z0-9_]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||(20==a.length&&a.match(/^[A-Z]0[A-F]\d{16}[A-Z]$/)||21==a.length&&a.match(/^[A-Z]0[A-F]\d{17}[A-Z]$/))||18==a.length&&a.match(/^el[0-9a-f]{16}$/)||24<a.length&&
a.match(/^yui_[0-9_a-z]+$/)||14<=a.length&&a.match(/^[a-zA-Z_]{8}[a-zA-Z_]+\[[0-9]{2}[0-9]+\]$/)?!0:!1}function chk_form_changepw_new(){return!0}
function shouldOfferGenerate(a,b){if(null==a||null==b)return null;var c=!1,d=b.form,e=!1;d||(e=checkDocumentForCPWOrphans(a));var f=!0,g=!0,h=check_nevers(a,g_nevers,a.location.href);null!=h&&(f=h.show_for_generate,g=h.show_for_clickable_icon);if(f&&chk_form_ask_generate(a,d)&&isInputFieldPassword(a,b)&&g){if(chk_form_has_password(a,d)&&(c=LP_pickFormName(a,d),RegExp(lpgs("ff_loginform_regexp"),"i").exec(c)))return!1;(currentpw=lpCheckCurrentPWField(d))||(currentpw=lpCheckCurrentPWField(d,!0));chk_form_changepw(a,
d)&&b==lpCheckCurrentPWField(d)?(c=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE42",{param1:g_docnum,param2:LP_pickFormName(a,d),param3:LP_pickFieldName(a,b)})):chk_form_changepw_new(a,d)&&b==currentpw?(c=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE43",{param1:g_docnum,param2:LP_pickFormName(a,d),param3:LP_pickFieldName(a,b)})):(c=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE44",{param1:g_docnum,param2:LP_pickFormName(a,d),param3:LP_pickFieldName(a,b)}))}else!d&&(f&&e)&&(isInputFieldPassword(a,
elt)&&!lpIsFieldCurrentPWField(b))&&(c=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE45",{param1:g_docnum,param2:LP_pickFieldName(a,b)}));return c}function popupfill_shoulddoform(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=b.name,d=b.id,e=["lpmanualform","lpwebsiteeventform"];return c&&lp_in_array(c,e)||d&&lp_in_array(d,e)?!1:!0}
function LP_isRememberCheckbox(a){if(!a||"checkbox"!=a.type)return!1;var b=a.id;a=a.name;var c=RegExp(lpgs("ff_remember_regexp"),"i");return c.exec(b)||c.exec(a)?!0:!1}
function chk_form_is_nonlogin_form(a,b){if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;try{var c=gettldcached(a.location.href)}catch(d){return!1}var e=LP_pickFormName(a,b),f=formcacheget(a,e,"is_nonlogin");if(null!=f)return f;f="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(f.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(f.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_nonlogin",!0),!0;if(is_search_form(a,
b))return decision_log(a,"DE46",{param1:e}),formcacheset(a,e,"is_nonlogin",!1),!1;if(!checkIsDisplayed(a,b,0,c))return decision_log(a,"DE47",{param1:e}),!1;var g=c=0,f=b.elements,h=f.length;Checkpoint.assert(h<MAX_INPUTS_HARD,"form "+e+" too big 2");h>MAX_INPUTS_HARD&&(h=MAX_INPUTS_HARD);for(var n=0;n<h;n++){var m=f[n];if("FIELDSET"!=m.tagName&&("email"==m.type||"text"==m.type||"password"==m.type)&&!LP_fieldIsDisabled(m)){if(100<++g)return formcacheset(a,e,"is_nonlogin",!1),!1;if(!0!=m.disabled&&
valid_by_role(a,m)&&lpIsVisible(m)&&!LP_treat_as_hidden(m)){if(is_search_field(a,m,!0)&&8>f.length)return decision_log(a,"DE48",{param1:e}),formcacheset(a,e,"is_nonlogin",!1),!1;c++;if(3<=c)return decision_log(a,"DE49",{param1:e}),formcacheset(a,e,"is_nonlogin",!0),!0}}}formcacheset(a,e,"is_nonlogin",!1);return!1}
function treat_text_as_password(a){return!a||"TEXTAREA"==a.tagName?!1:"text"==a.type&&(0==a.name.indexOf("pass")||0<=a.name.toLowerCase().indexOf(lpgs("Password").toLowerCase()))&&-1==a.name.toLowerCase().indexOf("hint")&&-1==a.name.toLowerCase().indexOf("placeholder")?RegExp(lpgs("ff_username_regexp"),"i").exec(a.name)&&a.form&&a.form.action&&0<=a.form.action.indexOf("login")?!1:!0:!1}function ASP_treat_text_as_password(a){return treat_text_as_password(a)}
function valid_by_role(a,b){if(!b)return!1;a||(a=b.ownerDocument);if(!a)return!1;var c=b.getAttribute("role");!c&&"INPUT"!=b.tagName&&(c=b.parentNode.getAttribute("role"));if(!c)return!0;switch(c){case "navigation":case "banner":case "contentinfo":case "note":case "search":case "seealso":return!1;case "columnheader":case "presentation":case "toolbar":case "directory":return!1;default:return!0}}
function should_do_lastpass_here(a){var b=null;if(!a)return!1;if(null!=a.g_content_check_result)return a.g_content_check_result;try{var c=a.location.href;if(0<c.indexOf(".xul")||0<c.indexOf("libsyn.com/embed")||0<c.indexOf("platform.twitter.com/tweet_button")||0<=c.indexOf("facebook.com/plugins/"))b=a.g_content_check_result=!1;null===b&&("complete"!=a.readyState&&"interactive"!=a.readyState)&&(verbose_log("answer hazy, try again later"),b=!0);if(null===b){var d=a.body,e=LP_elt_get_text(d).length;
null===b&&(2<e&&is_page_JSON(a))&&(b=a.g_content_check_result=!1)}if(null===b&&d){var f=d.getAttribute("contentEditable"),g=d.getAttribute("preview"),h=null!==d.getAttribute("data-silex-id")||null!==d.getAttribute("data-silex-type");if("edit"==g||f||h)b=!1}}catch(n){return a.g_content_check_result=!1}null===b&&(b=a.g_content_check_result=!0);return b}
function is_shopping_form(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=LP_createXPathFromElement(a,b);c||(c=LP_pickFormName(a,b));var d=formcacheget(a,c,"is-shopping");if(null!=d)return d;var d=!1,e=0,f=0,g=0,h=0,n=0,m=0,l=/qty|quantity/i,r=/[Ss]hipping/,j=/[Ss]hopping|[CcK]art/,p=/gift|Gift|GIFT/,q=/[Cc]heck[Oo]ut/,s=b.getElementsByTagName("input");Checkpoint.assert(s.length<MAX_INPUTS_SOFT,"form "+LP_getname(b)+" has too many inputs");var k=s.length;k>MAX_INPUTS_SOFT&&(k=MAX_INPUTS_SOFT);
for(m=0;m<k;m++){var t=s[m].id,u=s[m].name,v=s[m].className;if(l.exec(t)||l.exec(u)||l.exec(v))e++;else if(r.exec(t)||r.exec(u)||r.exec(v))g++;else if(j.exec(t)||j.exec(u)||j.exec(v))f++;else if(p.exec(t)||p.exec(u)||p.exec(v))h++;else if(q.exec(t)||q.exec(u)||q.exec(v))n++;else{t=void 0;u=0;v=[e,f,g,h,n];for(t=0;t<v.length;t++)0<v[t]&&u++;if(2<=u){d=!0;break}}}formcacheset(a,c,"is-shopping",d);return d}
function is_wacky_disp(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;if(b==a.body)return!0;var c=!0;try{var d=LP_get_live_style(b);if(d){if("none"==d.display||"hidden"==d.visibility)c=!1;if(!0==c&&(!b.offsetHeight||!b.offsetHeight))c=!1;if(!0==c&&(0==d.height||0==d.width))c=!1;if(!0==c&&(2>parseInt(d.height)||2>parseInt(d.width)))c=!1;if(!0==c&&(0>parseInt(d.left)&&"auto"!=d.left||0>parseInt(d.top)&&"auto"!=d.top))c=!1;!0==c&&("-1px"==d.marginTop&&1==b.offsetHeight)&&(c=!1);if(!0==c&&(3>b.offsetHeight||
3>b.offsetWidth))c=!1;if(!0==c&&("transparent"==d.backgroundColor&&"transparent"==d.color||g_isie&&"transparent"==d.backgroundColor&&""==d.color||"rgba(0, 0, 0, 0)"==d.backgroundColor&&"rgba(0, 0, 0, 0)"==d.color))c=!1;!0==c&&(d.opacity&&0.02>parseFloat(d.opacity))&&(c=!1);if(!0==c&&g_isie&&d.filter){var e=/alpha\(opacity=(\d+)\)/.exec(d.filter);e&&(e[1]&&2>parseInt(e[1]))&&(c=!1)}}}catch(f){c=!0}if(c)try{var g=b.parentNode;g||(c=!1);var h=LP_get_live_style(g);if(h){if(!0==c&&("none"==h.display||
"hidden"==h.visibility))c=!1;if(!0==c&&(0>parseInt(h.left)&&"auto"!=h.left||0>parseInt(h.top)&&"auto"!=h.top))c=!1;if(!0==c&&(3>parseInt(h.height)&&"auto"!=h.height||3>parseInt(h.width)&&"auto"!=h.width)&&("hidden"==h.overflowY||"hidden"==h.overflow))c=!1}}catch(n){c=!0}return c}
function LP_treat_as_hidden(a){return!a||"hidden"==a.type||!a.parentNode||0==a.id.indexOf("hidden")&&("none"==a.style.display||"none"==a.parentNode.style.display)||"true"===a.getAttribute("aria-hidden")?!0:(a=a.getAttribute("hidden"))&&"false"!==a?!0:!1}
function LP_has_textlike_type(a){if(!a)return!1;var b=a.tagName.toUpperCase();if("INPUT"!=b&&"TEXTAREA"!=b)return!1;if("TEXTAREA"==b)return!0;var b="text number email tel url textarea".split(" "),c;for(c in b)if(b.hasOwnProperty(c)&&a.type==b[c])return True;return False}function computeFingerprint(a){if(!a)return"";var b="";a=a.getElementsByTagName("INPUT");var c;for(c=0;c<a.length&&20>c;c++)b+=a[c].id?a[c].id:a[c].name;try{"undefined"!=typeof crc32&&(b=crc32(b).toString())}catch(d){}return b}
function LP_firstVisibleOrphan(a){if(!a)return null;a=a.getElementsByTagName("INPUT");var b,c=null;for(b=0;b<a.length&&50>b;b++)if(c=a[b],!c.form&&("text"==c.type||"password"==c.type||"url"==c.type||"email"==c.type)&&lpIsVisible(c))return c;return null}
function checkFormForLoginFirstStage(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var c=LP_pickFormName(a,b);verbose_log("checking "+c+" for first stage of multi-stage login");var d=formcacheget(a,c,"multi-first");if(null!=d)return d;if("undefined"==typeof Math)return False;for(var d=0,e=!1,f,g=Math.floor(1E4*Math.random()),h=0,n=0;20>n&&n<b.elements.length;n++)if(f=b.elements[n],"INPUT"==f.tagName&&checkIsDisplayed(a,f,0,null,g)){looksLikeUsername(f)&&d++;if("text"==f.type||"tel"==f.type||
"url"==f.type||"email"==f.type||"textarea"==f.type){if("string"==typeof f.id&&"identifier-captcha-input"==f.id)try{if("google.com"==gettldcached(a.location.href))continue}catch(m){}h++}if(isInputFieldPassword(a,f)){e=!0;break}if(2<=d)break;if(2<=h)break}if(0<d&&3>=d&&!1==e&&2>h)return verbose_log("isolated login field/initial stage of multi-stage found"),formcacheset(a,c,"multi-first",!0),!0;formcacheset(a,c,"multi-first",!1);return!1}
function checkDocumentForLoginFirstStageForm(a){if(!a)return!1;var b=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<b,"too many forms on page");for(var d=!1,e=0;e<c.length&&e<b;e++)if(d=checkFormForLoginFirstStage(a,c[e]))return d;return!1}
function checkDocumentForNonLoginOrphans(a){if(null==a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup"),c=formcacheget(a,"fakedoc","orphan-registration"),d=formcacheget(a,"fakedoc","orphan-cc"),b=b||c||d;if(null!=b)return b;b=RegExp(lpgs("ff_firstname_regexp"),"i");c=RegExp(lpgs("ff_lastname_regexp"),"i");d=RegExp(lpgs("ff_cctype_regexp"),"i");lpgs("ff_address1_regexp");lpgs("ff_forgot_regexp");lpgs("ff_remember_regexp");var e=!1,f=!1,g=!1,h=!1,n=!1;try{gettldcached(a.location.href)}catch(m){return!1}for(var l=
0,r=a.getElementsByTagName("INPUT"),j=0;j<r.length&&20>j;j++){var p=r[j];if("INPUT"==p.tagName){LP_isRememberCheckbox(p)&&(lpIsVisible(p)&&!LP_fieldIsDisabled(p))&&l++;if("email"==p.type||"text"==p.type||"password"==p.type){if(LP_fieldIsDisabled(p))continue;if(LP_fieldIsDisabled(p))continue;if(!valid_by_role(a,p))continue;if(!lpIsVisible(p))continue;if(is_search_field(a,p,!0))continue;var q=p.name,s=p.id?p.id:"",k=lpGetTextBeforeFormField(p);looksLikeUsername(p)?e=!0:isInputFieldPassword(a,p)?f=!0:
b.exec(s)||b.exec(q)||b.exec(k)?g=!0:c.exec(s)||c.exec(q)||c.exec(k)?h=!0:d.exec(s)||d.exec(q)||d.exec(k)?n=!0:regexp_address1.exec(s)||regexp_address1.exec(q)||regexp_address1.exec(k);l++}if(3<=l){if(e&&f&&!n)return verbose_log("document appears to be have orphan signup fields"),formcacheset(a,"fakedoc","orphan-signup",!0),formcacheset(a,"fakedoc","orphan-cc",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if(n&&!e&&!f)return verbose_log("document appears to be have orphan credit card fields"),
formcacheset(a,"fakedoc","orphan-cc",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if((g||h)&&e)return verbose_log("document appears to be have orphan registration fields"),formcacheset(a,"fakedoc","orphan-registration",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-cc",!1),!0}}}formcacheset(a,"fakedoc","orphan-signup",!1);formcacheset(a,"fakedoc","orphan-cc",!1);formcacheset(a,"fakedoc","orphan-registration",
!1);return!1}function checkDocumentHasOrphanSignup(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-signup")}function checkDocumentHasOrphanCC(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-cc");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-cc")}
function checkDocumentHasOrphanRegistration(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-registration");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-registration")}function LP_should_ignore_this_doc(a,b){if(!a||!a.location)return!0;var c=a.location.href;return LP_is_browser_url(c)||0==c.indexOf("javascript:")||0<c.indexOf(".xul")||b&&"www.irccloud.com"==a.location.hostname?!0:!1}
function countInputs(a,b,c){var d=0,e=0,f=a.getElementsByTagName("INPUT");if("undefined"!=typeof Math){for(var g=0;g<f.length;g++){if(100<g){b||(d+=f.length-g);break}var h="password"==f[g].type;if(!b||h)"checkbox"==f[g].type||"hidden"==f[g].type||(h&&e++,d++)}c&&(a.g_password_cnt=e);return d}}
function checkForLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(b){return!1}var c=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<c,"too many forms on page");for(var e=!1,f=0;f<d.length&&f<c;f++){e=chk_form_has_password(a,d[f],!0);if(null==e)break;if(e)return e}return!1}
function checkForNonLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(b){return!1}var c=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<c,"too many forms on page");for(var e=!1,f=0;f<d.length&&f<c;f++)if(e=chk_form_is_nonlogin_form(a,d[f]))return e;return!1}
function checkForSignupForm(a){a||(a=LP_derive_doc());if(!a)return!1;var b=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<b,"too many forms on page");for(var d=!1,e=0;e<c.length&&e<b;e++)if(d=chk_form_ask_generate(a,c[e]))return d;return!1}
function usercacheset(a,b){if(null==a||null==b||0===b.length)return!1;var c=gettldcached(a.location.href);"function"==typeof sendBG&&sendBG({cmd:"usercacheset",tld:c,username:b});verbose_log("USERCACHE-SAVED  domain: "+c+" user: "+b);return!0}
function checkForTotpForm(a,b){if(!g_do_totp||g_totp_elt)return!1;a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(c){return!1}verbose_log("checkForTotpForm called from "+b);var d=LP_getFormsThreshold(a),e=a.getElementsByTagName("form");Checkpoint.assert(e.length<d,"too many forms on page");for(var f=!1,g=0;g<e.length&&g<d;g++){f=chk_form_has_totp(a,e[g],!0);if(null==f)break;if(f)return verbose_log("checkForTotpForm FOUND totp form - called from "+b),f}return!1}
function chk_form_has_totp(a,b){if(!g_do_totp||g_totp_elt||null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;LP_pickFormName(a,b);var c="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");if(c.length>=MAX_FORM_ELEMENTS_HARD)return!1;var d=0;verbose_log("checking form: id-> "+b.id+"  class-> "+b.className+" name-> "+b.name);d+=textFieldScore(b,"totp");d+=textFieldScore(b,"2fa");d+=textFieldScore(b,"twofactor");d+=textFieldScore(b,"tfa");verbose_log("form score: ( id-> "+
b.id+"  class-> "+b.className+" name-> "+b.name+" )   "+d);for(var e=0,f=0,g=0;g<MAX_FORM_ELEMENTS_SOFT&&g<b.elements.length;g++){var h=b.elements[g];"INPUT"==h.tagName&&("text"==h.type||"tel"==h.type||"number"==h.type)&&e++;("INPUT"==h.tagName&&"submit"==h.type||"BUTTON"==h.tagName)&&f++}verbose_log("check for totp form: txtfieldcount="+e+" submitcnt="+f);if(0==f||0==e)return!1;for(g=0;g<MAX_FORM_ELEMENTS_SOFT&&g<c.length;g++)if(h=c[g],isInputFieldTotpCode(a,h))if(d+=2,null===h.offsetParent){verbose_log("HIDDEN totp element found: id-> "+
h.id+"  class-> "+h.className+"  name-> "+h.name);var n,m=h;n=setInterval(function(){var b=m;verbose_log("checking visibility for: id-> "+b.id+"  class-> "+b.className+"  name-> "+b.name);null===b.offsetParent?verbose_log("element is STILL HIDDEN: id-> "+b.id+"  class-> "+b.className+"  name-> "+b.name):(clearInterval(n),verbose_log("element become VISIBLE - totp code field revealed!!!!!: id-> "+b.id+"  class-> "+b.className+"  name-> "+b.name),found_totp_elt(b,a))},5E3)}else found_totp_elt(h,a),
verbose_log("VISIBLE totp element found!!!!!: id-> "+h.id+"  class-> "+h.className+"  name-> "+h.name);verbose_log("form totp score: "+d+"+id-> "+b.id+"  class-> "+b.className+" name-> "+b.name);return 2<=d}var g_totp_elt=null,g_totp_form=null;
function found_totp_elt(a,b){verbose_log("found totp elt");g_totp_elt?verbose_log("already found totp elt, returning"):(g_totp_elt=a,"undefined"==typeof g_can_get_totp||!g_can_get_totp?(verbose_log("set totp form"),g_totp_form=a.form):"function"==typeof sendBG&&(verbose_log("attempting to get totp from server"),sendBG({cmd:"get_totp",tld:gettldcached(b.location.href),name:a.name,id:a.id,className:a.className})))}
function chk_form_has_password(a,b,c){if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;var d=LP_pickFormName(a,b),e=formcacheget(a,d,"is_login");if(null!=e)return e;e="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(e.length<MAX_FORM_ELEMENTS_HARD,"form "+d+" has too many inputs");if(e.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,d,"is_login",!1),!1;try{var f=gettldcached(a.location.href);if("bankofamerica.com"==f){var g=
a.getElementById("tlpvt-passcode-input");null!==g&&g.removeAttr("disabled")}}catch(h){return!1}for(var n=!1,m=g=0,l=0,e=null,r=0;r<MAX_FORM_ELEMENTS_SOFT&&r<b.elements.length;r++){var j=b.elements[r];"INPUT"==j.tagName&&("password"==j.type?g++:("text"==j.type||"email"==j.type)&&m++);if("INPUT"==j.tagName&&"submit"==j.type||"BUTTON"==j.tagName)l++,e=j}verbose_log("check for login form: prelimtxt="+m+" prelimpw="+g);if(1==l&&2>=m&&0<g&&checkButtonHint(e))return!0;for(var p=0,q=0,s=!lpIsVisible(b),k=
!1,e=b.elements,r=0;r<MAX_FORM_ELEMENTS_SOFT&&r<e.length;r++)if(j=e[r],n=!1,"FIELDSET"!=j.tagName&&(check_for_ASP(a,j),valid_by_role(a,j)&&!LP_fieldIsDisabled(j)&&!LP_treat_as_hidden(j))){if("text"==j.type&&is_watermark(j.className)&&is_watermark_password(j))try{j.type="password",decision_log(a,"DE11")}catch(t){n=!0}ASP_treat_text_as_password(j)&&(n=!0);(n||"password"==j.type)&&LP_get_input_pattern(a,j);if(1<g&&LP_passwordAlt(a,j))q++;else if(b=fieldIsDoublePassword(a,j),!("text"==j.type&&(b===DOUBLE_PW_VISIBLE||
b===DOUBLE_SECRET_PW_VISIBLE)))if("password"==j.type||n||"text"==j.type&&b===DOUBLE_TEXT_VISIBLE||"text"==j.type&&b===DOUBLE_SECRET_TEXT_VISIBLE){if(!("facebook.com"==f&&"string"==typeof j.id&&j.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)))if("tdbank.com"==f&&"string"==typeof j.name&&"user"==j.name)q++;else{if(g_fillaid&&c)return!0;if(g_aspx_hack&&isASPpage()&&do_bgiconinput)decision_log(a,"DE12");else if(!lpIsVisible(j)||g_use_wacky_disp&&!is_wacky_disp(a,j))if(k=!0,s)decision_log(a,"DE13",{param1:LP_pickFormName(a,
j)});else continue;if(0==p&&1<g&&passwordIsFake(j))q++;else if(0<p&&1<g&&LP_looksLikeOTPField(a,j))q++;else if(b=2,j="",g_aspx_hack&&(isASPpage()&&do_bgiconinput)&&(b=4,j=" [ASP]"),++p>=b){if(2==g&&(0===m&&1===l)&&RegExp(lpgs("ff_loginform_regexp"),"i").exec(d))return formcacheset(a,d,"is_login",!0),!0;formcacheset(a,d,"is_login",!1);verbose_log("Password Form detection: "+d+j+" has too many password fields; do not treat as login form [PW:"+p+"/NON:"+q+"]");return null}}}else if("email"==j.type||
"text"==j.type||"textarea"==j.type||"tel"==j.type||"url"==j.type){if(!lpIsVisible(j)||g_use_wacky_disp&&!is_wacky_disp(a,j))if(s)verbose_log("EVALUATING HIDDEN FORM, NOT IGNORING HIDDEN FIELD ANYMORE "+LP_pickFormName(a,j));else continue;q++;if(g_aspx_hack&&5<q||!g_aspx_hack&&2<q)return formcacheset(a,d,"is_login",!1),verbose_log("Password Form detection: "+d+" has too many non-password fields; do not treat as login form [PW:"+p+"/NON:"+q+"]"),null}}if(1==p)return verbose_log("Password Form detection: "+
d+" is a login form, has only one passwd field"),formcacheset(a,d,"is_login",!0),!0;if(g_aspx_hack&&(isASPpage()&&do_bgiconinput)&&1<p)return verbose_log("Password Form detection: "+d+" is an ASP form, treat as login form"),formcacheset(a,d,"is_login",!0),!0;k||formcacheset(a,d,"is_login",!1);return!1}function looksLikePassword(a,b){return isInputFieldPassword(a,b)}
function isInputFieldPassword(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;try{var c=gettldcached(a.location.href)}catch(d){return!1}if(!valid_by_role(a,b))return!1;var e=!1;if("text"==b.type&&is_watermark(b.className)&&is_watermark_password(b))try{b.type="password"}catch(f){e=!0}if("text"==b.type&&(0==b.name.indexOf("pass")||0==b.name.toLowerCase().indexOf(lpgs("Password").toLowerCase())))return RegExp(lpgs("ff_username_regexp"),"i").exec(b.name)&&b.form&&b.form.action&&
0<=b.form.action.indexOf("login")?!1:!0;g_aspx_hack&&isASPpage()&&do_bgiconinput&&"text"==b.type&&0<=b.value.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&(e=!0);return"password"==b.type||e?"facebook.com"==c&&"string"==typeof b.id&&b.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)||"tdbank.com"==c&&"string"==typeof b.name&&"user"==b.name||"google.com"==c&&"string"==typeof b.id&&"Passwd-hidden"==b.id?!1:!0:!1}
function checkDocumentForLoginOrphans(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan");if(null!=b)return b;var b=[],c=[],d=[],e=0,f,g=0;if("undefined"!=typeof Math){for(var h=Math.floor(1E4*Math.random()),n=["input"],m=0;m<n.length;m++){var l=a.getElementsByTagName(n[m]),r=l.length;Checkpoint.assert(r<MAX_INPUTS_SOFT,"page has too many inputs");r>MAX_INPUTS_SOFT&&(r=MAX_INPUTS_SOFT);for(var j=0;j<r;j++)if(checkIsDisplayed(a,l[j],0,null,h)){f=l[j];if(null!=f.id&&""!=
f.id){var p=d[f.id];if(null==p)d[f.id]=!0;else continue}if(null!=f.name&&""!=f.name)if(p=c[f.name],null==p)c[f.name]=!0;else continue;if(lp_in_array(LP_pickFieldName(a,f),b))verbose_log("fieldname "+b[p]+" is blacklisted, skipping");else{var q=fieldIsDoublePassword(a,f);if(null==f.form&&("password"==f.type||"text"==f.type&&q===DOUBLE_TEXT_VISIBLE||"text"==f.type&&q===DOUBLE_SECRET_TEXT_VISIBLE)){e++;var q=[],s;s=LP_pickFieldName(a,f);f=LP_getname(f);s&&q.push(s);f&&s!=f&&q.push(f);for(f=0;f<q.length;f++)if((s=
q[f])&&0<=s.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&0<j){var k=l[j-1];s=LP_pickFieldName(a,k);var k=LP_getname(k),t=RegExp(lpgs("ff_username_regexp"),"i");if(t.exec(s)||t.exec(k)){g++;break}}}if(2<=e&&2<=g)break}}}if(1<=e||1==g)return formcacheset(a,"fakedoc","orphan",!0),!0;formcacheset(a,"fakedoc","orphan",!1);return!1}}
function chk_form_changepw(a,b){if(null==a||null==b)return!1;for(var c=lpCheckCurrentPWField(b),d=!1,e=null,f=null,g=1;2>=g;g++){var d=!1,e=f=null,h=-1;if(1==g){if(c)for(var n=0;n<b.elements.length;n++)if(b.elements[n]==c){h=n+1;break}}else h=0;if(-1!=h){for(n=h;n<b.elements.length;n++)if(h=b.elements[n],"FIELDSET"!=h.tagName)if(isInputFieldPassword(a,h)){if(d||!e||!f)if(f=e,e=h,d&&e&&f)break;d=!0}else d=!1;if(e&&f)break}}return null!=e&&null!=f&&null!=c?!0:!1}
function containsSubString(a,b){return a&&-1<a.replace(/\s/g,"").toLowerCase().indexOf(b.toLowerCase())}function textFieldScore(a,b){var c=0;containsSubString(a.name,b)&&c++;containsSubString(a.id,b)&&c++;containsSubString(a.className,b)&&c++;return c}
function isInputFieldTotpCode(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;try{var c=gettldcached(a.location.href)}catch(d){return!1}if(!valid_by_role(a,b)||"text"!=b.type&&"tel"!=b.type&&"number"!=b.type)return!1;if(0<textFieldScore(b,"totp")||"salesforce.com"==c&&"tc"==b.id&&6==b.maxLength&&"tc"==b.name&&-1!=b.form.action.indexOf("Totp")||"github.com"==c&&"otp"==b.id&&"otp"==b.name&&-1!=b.form.action.indexOf("two-factor")||"live.com"==c&&"idTxtBx_SAOTCC_OTC"==b.id&&"otc"==
b.name&&8==b.maxLength)return!0;c=0+textFieldScore(b,"code");c+=textFieldScore(b,"pin");c+=textFieldScore(b,"verification");c+=textFieldScore(b,"2fa");c+=textFieldScore(b,"twofactor");c+=textFieldScore(b,"tfa");b.pattern&&containsSubString(b.pattern,"0-9")&&c++;b.placeholder&&(containsSubString(b.placeholder,"6")||containsSubString(b.placeholder,"six")||containsSubString(b.placeholder,"hat"))&&c++;return 0<c}
function form_get_password(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var c=LP_pickFormName(a,b),d=formcacheget(a,c,"password_field");if(null!==d)return d;if(!0===formcacheget(a,c,"nopasswords"))return null;var d=null,e,f=[],f="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==f&&0<f.length,"empty form?");if("undefined"==typeof Math)return null;var g=f.length;Checkpoint.assert(g<MAX_FORM_ELEMENTS_HARD,"form "+c+" too big 3");g>MAX_FORM_ELEMENTS_HARD&&
(g=MAX_FORM_ELEMENTS_HARD);var h=0;for(e=0;e<g;e++)isInputFieldPassword(a,f[e])&&h++;e=Math.floor(1E4*Math.random());for(var n=0;n<g;n++){var m=f[n];if("FIELDSET"!=m.tagName&&(checkIsDisplayed(a,m,0,null,e)&&isInputFieldPassword(a,m))&&!(1<h&&(passwordIsFake(m)||LP_looksLikeOTPField(a,m)||!valid_by_role(a,m)||LP_fieldIsDisabled(m)||LP_treat_as_hidden(m)||is_search_field(a,m,!0)))){d=m;break}}null===d&&0===h&&formcacheset(a,c,"nopasswords",!0);formcacheset(a,c,"password_field",d);return d}
function form_get_username(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var c=[],c="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==c);var d=null,e=LP_pickFormName(a,b),f=formcacheget(a,e,"username_field");if(null!==f)return f;if("undefined"==typeof Math)return null;f=c.length;Checkpoint.assert(f<MAX_FORM_ELEMENTS_HARD,"form "+e+" too big 4 ");f>MAX_FORM_ELEMENTS_HARD&&(f=MAX_FORM_ELEMENTS_HARD);for(var g=Math.floor(1E4*Math.random()),h=0;h<
f;h++){var n=c[h];if(!("FIELDSET"==n.tagName||"hidden"==n.type))if(valid_by_role(a,n)&&!LP_fieldIsDisabled(n)&&!is_search_field(a,n,!0)&&checkIsDisplayed(a,n,0,null,g)&&("text"==n.type||"email"==n.type||looksLikeUsername(n))){if(isFirstFieldNonLoginSubForm(a,n))return null;d=n;break}}formcacheset(a,e,"username_field",d);return d}
function doc_get_orphan_username(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b;if("undefined"!=typeof Math){b=formcacheget(a,"orphans","username_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[0])return formcacheset(a,"orphans","username_field",b[0]),b[0];if(LP_has_youama(a)&&(b=LP_get_youama_fields(a))&&b.login_username)return formcacheset(a,"orphans","username_field",b.login_username),b.login_username;var c=doc_get_form_equivalents(a);
if(c&&0<c.length)for(b=0;b<c.length;b++)if("FORM"!=c[b].tagName.toUpperCase()){var d=form_get_username(a,c[b]);if(d)return formcacheset(a,"orphans","username_field",d),d}formcacheset(a,"orphans","username_field","none");return null}}
function doc_get_orphan_password(a){if(null==a)return null;if("undefined"!=typeof Math){var b=formcacheget(a,"orphans","password_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[1])return formcacheset(a,"orphans","password_field",b[1]),b[1];if(LP_has_youama(a)&&(b=LP_get_youama_fields(a))&&b.login_password)return formcacheset(a,"orphans","password_field",b.login_password),b.login_password;if((b=doc_get_form_equivalents(a))&&0<
b.length)for(x=0;x<b.length;x++)if("FORM"!=b[x].tagName.toUpperCase()){var c=form_get_password(a,b[x]);if(c)return formcacheset(a,"orphans","password_field",c),c}formcacheset(a,"orphans","password_field","none");return null}}
function set_active_username_password(a,b){if(null==a)g_popup_active_password=g_popup_active_username=null;else{var c=null,d=null;null==b?checkDocumentForLoginOrphans(a)&&(c=doc_get_orphan_username(a),d=doc_get_orphan_password(a)):(c=form_get_username(a,b),d=form_get_password(a,b));g_popup_active_username=c;g_popup_active_password=d}}function looksLikeEmail(a,b){return null==a||null==b||!("text"==b.type||"email"==b.type)?!1:"email"==b.type||RegExp(lpgs("ff_email_regexp"),"i").exec(b.name)?!0:!1}
function is_search_field(a,b,c){if(null==a||null==b||"INPUT"!=b.tagName.toUpperCase()&&!b.getAttribute("contentEditable"))return!1;var d=null;switch(b.type){case "search":d=!0;break;case "text":break;default:"INPUT"==b.tagName.toUpperCase()&&(d=!1)}if(null!==d)return d;null===c&&(c=!1);var d=LP_pickFieldName(a,b),e=fieldcacheget(a,d,"search");if(null!=e)return e;var e=b.form,f=[];null!=e&&(f=e.elements);if(b.parentNode&&"FORM"!=b.parentNode.tagName&&b.parentNode.className&&0<=b.parentNode.className.toLowerCase().indexOf("login")&&
b.className&&0<=b.className.toLowerCase().indexOf("search"))return!1;if((null!=b.className&&0<=b.className.toLowerCase().indexOf("search")||0<=b.className.toLowerCase().indexOf("srch")||0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch")||0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch"))&&0>b.name.toLowerCase().indexOf("user")&&0>b.name.toLowerCase().indexOf("login")&&0>b.id.toLowerCase().indexOf("user")&&0>b.id.toLowerCase().indexOf("login")&&
(c||5>f.length))return fieldcacheset(a,d,"search",!0),!0;c=RegExp(lpgs("ff_search_regexp"),"i");if(c.exec(b.name)||c.exec(b.id))if(c=b.name&&b.name.match(/[qQ]/)||b.id&&b.id.match(/[qQ]/),e=RegExp(lpgs("ff_email_regexp"),"i"),f=RegExp(lpgs("ff_username_regexp"),"i"),c&&b.name&&!b.name.match(/^[qQ]/)&&(!b.id||b.id&&!b.id.match(/^[qQ]/)))pass;else if(c&&b.id&&!b.id.match(/^[qQ]/)&&(!b.name||b.name&&!b.name.match(/^[qQ]/)))pass;else if(c&&(f.exec(b.name)||f.exec(b.id)||e.exec(b.name)||e.exec(b.id)))pass;
else return verbose_log("field "+d+" appears to be a search field based on regexp"),fieldcacheset(a,d,"search",!0),!0;c=b.getAttribute("placeholder");if(null!=c&&0<=c.toLowerCase().indexOf("search"))return verbose_log("field "+d+" appears to be a search field based on placeholder text"),fieldcacheset(a,d,"search",!0),True;if("rds-instances-filter-txtbx"==b.id)return verbose_log("field "+d+" appears to be a search field based on manually added searchtext"),fieldcacheset(a,d,"search",!0),!0;if(b.parentNode&&
"FORM"!=b.parentNode.tagName&&b.parentNode.className&&(0<=b.parentNode.className.toLowerCase().indexOf("search")||0<=b.parentNode.className.toLowerCase().indexOf("srch"))||"search"==b.getAttribute("role"))return fieldcacheset(a,d,"search",!0),!0;c=b.getAttribute("spellcheck");if(b.className&&0<=b.className.indexOf("tt-input")&&c&&"false"===c)return fieldcacheset(a,d,"search",!0),!0;fieldcacheset(a,d,"search",!1);return!1}
function is_date_field(a){if(!a)return!1;var b=a.name,c=/(?:date)|(?:calendar)/i,d=/(?:validate)/i,b=a.name,e=a.id,f=a.className;if(c.exec(b)||c.exec(e)||c.exec(f))return d.exec(b)||d.exec(e)||d.exec(f)?!1:!0;if(a=a.getAttribute("placeholder"))if(a=a.toLowerCase(),-1!=a.indexOf("yyyy")||-1!=a.indexOf("/yy")||-1!=a.indexOf("mm/"))return!0;return!1}
function is_search_form(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var c=LP_pickFormName(a,b),d=formcacheget(a,c,"search");if(null!=d)return d;if(null!=b.id&&0<b.id.length&&"undefined"!=typeof b.id.toLowerCase&&(0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch"))||null!=b.name&&0<b.name.length&&"undefined"!=typeof b.name.toLowerCase&&(0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch")))return verbose_log("form "+c+" appears to be a search form based on name/id "),
formcacheset(a,c,"search",!0),!0;if("search"==b.getAttribute("role"))return formcacheset(a,c,"search",!0),!0;formcacheset(a,c,"search",!1);return!1}
function looksLikeUsername(a,b){if(!a)return!1;var c=LP_hasAngular(a.ownerDocument);if("undefined"==typeof b||null===b)b=!1;if(!b&&"text"!=a.type&&"email"!=a.type&&"url"!=a.type)return!1;var d=RegExp(lpgs("ff_username_regexp"),"i");if(d.exec(a.name)||a.id&&d.exec(a.id))return!0;var e=a.getAttribute("placeholder");if(null!=e&&0<=e.indexOf("Login")||c&&(c=LP_getAngularAttributes(a))&&c["ng-model"]&&d.exec(c["ng-model"]))return!0;c=RegExp(lpgs("ff_loginform_regexp"),"i");if(a.form)for(var e=a.form.elements,
f=0;f<e.length;f++)if("submit"==e[f].type&&(e[f].name&&d.exec(e[f].name)||c.exec(e[f].name)))return!0;d=/^id$|.*-id|online.*id$|.*Id$|onlineId\d?$/i;if(d.exec(a.name))return!0;if(g_is_specialsite){d=RegExp(lpgs("ff_bankacctnum_regexp"),"i");if(d.exec(a.name))return!0;d=RegExp(lpgs("ff_company_regexp"),"i");if(d.exec(a.name))return!0;d=RegExp(lpgs("ff_email_regexp"),"i");if(d.exec(a.name))return!0}return!1}
function formHasUsernameField(a){if(a=a.form){a=a.elements;for(var b=0;b<a.length;b++){var c=a[b];if("text"==c.type||"email"==c.type)return!0}}return!1}var DOUBLE_TEXT_VISIBLE=1,DOUBLE_PW_VISIBLE=2,DOUBLE_SECRET_TEXT_VISIBLE=3,DOUBLE_SECRET_PW_VISIBLE=4,NOT_DOUBLE_PW=0;
function fieldIsDoublePassword(a,b){"document"==a&&(a=document,b=LP_getElementByIdOrName(a,b));if(null==a&&(a=document,!a))return!1;if(null==b||"checkbox"==b.type||"button"==b.type||"submit"==b.type||"select-one"==b.type)return NOT_DOUBLE_PW;var c=null,d=null,e=null,f=null;if("undefined"!=typeof b.previousElementSibling)c=b.previousElementSibling;else if((c=b.previousSibling)&&null!=c.nodeType&&3==c.nodeType)c=c.previousSibling;if("undefined"!=typeof b.nextElementSibling)d=b.nextElementSibling;else if((d=
b.nextSibling)&&null!=d.nodeType&&3==d.nodeType)d=d.nextSibling;c&&"INPUT"!=c.tagName&&(c=null);d&&"INPUT"!=d.tagName&&(d=null);if(c){if("undefined"!=typeof c.previousElementSibling)e=c.previousElementSibling;else if((e=c.previousSibling)&&null!=e.nodeType&&3==e.nodeType)e=e.previousSibling;e&&"INPUT"!=e.tagName&&(e=null)}if(d){if("undefined"!=typeof d.nextElementSibling)f=d.nextElementSibling;else if((f=d.nextSibling)&&null!=f.nodeType&&3==f.nodeType)f=f.nextSibling;f&&"INPUT"!=f.tagName&&(f=null)}if("undefined"!=
typeof Math){var g=Math.floor(1E4*Math.random());if("password"==b.type&&!checkIsDisplayed(a,b,-1,null,g)&&c&&"text"==c.type&&!checkIsDisplayed(a,c,-1,null,g)&&d&&"text"==d.type&&checkIsDisplayed(a,d,-1,null,g)&&f&&"text"==f.type&&checkIsDisplayed(a,f,-1,null,g)||"text"==b.type&&checkIsDisplayed(a,b,-1,null,g)&&c&&"text"==c.type&&checkIsDisplayed(a,c,-1,null,g)&&e&&"password"==e.type&&!checkIsDisplayed(a,e,-1,null,g))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double secret password hack"),
g_double_secret_password_hack=!0,DOUBLE_SECRET_TEXT_VISIBLE;if("password"==b.type&&checkIsDisplayed(a,b,-1,null,g)&&c&&"text"==c.type&&!checkIsDisplayed(a,c,-1,null,g)||"text"==b.type&&!checkIsDisplayed(a,b,-1,null,g)&&d&&"password"==d.type&&checkIsDisplayed(a,d,-1,null,g))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE;var e=null!=b&&lpIsVisible(b,!0),f=null!=c&&lpIsVisible(c,!0),g=null!=d&&lpIsVisible(d,!0),h=null!=b&&
looksLikeUsername(b),n=null!=c&&looksLikeUsername(c),m=null!=d&&looksLikeUsername(d);return"password"==b.type&&!e&&c&&"text"==c.type&&f&&!n||"text"==b.type&&e&&!h&&d&&"password"==d.type&&!g||"password"==b.type&&!e&&d&&"text"==d.type&&g&&!m||"text"==b.type&&e&&!h&&c&&"password"==c.type&&!f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_TEXT_VISIBLE):"password"==b.type&&e&&c&&"text"==c.type&&!f&&!n||"text"==b.type&&!e&&d&&"password"==d.type&&
g||"password"==b.type&&e&&d&&"text"==d.type&&!g&&!m||"text"==b.type&&!e&&c&&"password"==c.type&&f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE):NOT_DOUBLE_PW}}
function ContigPWHack(a,b,c){null===a&&(a=document);if(null===a||"undefined"==typeof a.getElementsByTagName)return!1;var d=lpCountInputFields(b);if("undefined"!=typeof Math){b=Math.floor(1E4*Math.random());if((3==d.passwordvisible||4==d.passwordvisible)&&!0===d.passwordsContiguous)for(var e=a.getElementsByTagName("input"),d=0;d<e.length&&!(100<d);d++)if(e[d]==c){if("undefined"!=typeof e[d+1]&&"password"==e[d+1].type&&"undefined"!=typeof e[d+2]&&"password"==e[d+2].type&&checkIsDisplayed(a,e[d],-1,
null,b)&&checkIsDisplayed(a,e[d+1],-1,null,b)&&checkIsDisplayed(a,e[d+2],-1,null,b))return!0;break}return!1}}
function isContigPW(a,b,c){null==b&&(b=a);var d=b.getElementsByTagName("input");if("undefined"!=typeof Math){var e=Math.floor(1E4*Math.random());for(b=0;b<d.length;b++)if(d[b]==c&&"password"==d[b].type){if("undefined"!=typeof d[b+1]&&"password"==d[b+1].type&&checkIsDisplayed(a,d[b],-1,null,e)&&checkIsDisplayed(a,d[b+1],-1,null,e)||"undefined"!=typeof d[b-1]&&"password"==d[b-1].type&&checkIsDisplayed(a,d[b],-1,null,e)&&checkIsDisplayed(a,d[b-1],-1,null,e))return!0;break}return!1}}
function get_prev_field(a,b){if("undefined"!=typeof b.previousElementSibling)prev_field=b.previousElementSibling;else if((prev_field=b.previousSibling)&&null!=prev_field.nodeType&&prev_field.nodeType==TEXT_NODE)prev_field=prev_field.previousSibling}function get_next_field(a,b){if("undefined"!=typeof b.nextElementSibling)next_field=b.nextElementSibling;else if((next_field=b.nextSibling)&&null!=next_field.nodeType&&next_field.nodeType==TEXT_NODE)next_field=next_field.nextSibling}
function isFirstFieldNonLoginSubForm(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type)return!1;if("text"==b.type){var c=RegExp(lpgs("ff_firstname_regexp"),"i");if(c.exec(b.name)||c.exec(b.id))return!0;c=/register|signup|enroll|create/i;if(b.parentNode&&c.exec(b.parentNode.name)||c.exec(b.parentNode.id)||b.parentNode&&b.parentNode.parentNode&&(c.exec(b.parentNode.parentNode.name)||c.exec(b.parentNode.parentNode.id)))return!0}return!1}
function isUsernameFieldLoginSubForm(a,b){return null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type?!1:FoundNonLoginSubForm(a)?False:looksLikeUsername(b)?!0:!1}function FoundNonLoginSubForm(a){if(null==a)return!1;if(isASPpage()){a=getAllIconStates();var b;for(b=0;b<a.length;b++)if("formfills"==a[b].fillhint)return True}return False}
function isPasswordFieldLoginSubForm(a,b){if(null==a||(null==b||"INPUT"!=b.tagName)||"hidden"==b.type)return!1;if(FoundNonLoginSubForm(a))return False;if("password"==b.type){var c=a.getElementsByTagName("INPUT"),d;for(d=0;d<c.length&&d<MAX_INPUTS_HARD&&b!=c[d];d++);if(b==c[d]&&0<d){var e=LP_pickFieldName(a,b);if(e&&e.toLowerCase().indexOf(0<=lpgs("Password"))&&(c=LP_pickFieldName(a,c[d-1]),RegExp(lpgs("ff_username_regexp"),"i").exec(c)))return!0}}return!1}
function isASPpage(){var a=!1;if(g_isfirefox){var b;(b="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?a=b.g_found_aspx:verbose_log("unable to get g_found_aspx in isASPpage() for "+b?b.location.href:"null")}else a=g_found_aspx;a||(a=!1);return a}
function setASPpage(a){var b=!1;null==a&&(a=!0);if(g_isfirefox){var c;(c="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?b=c.g_found_aspx=a:verbose_log("unable to set g_found_aspx in isASPpage() for "+c?c.location.href:"null")}else g_found_aspx=a,b=!0;b||(b=!1);return b}
function checkDocumentForLoginOrphansFirstStage(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-first");if(null!=b)return b;if("undefined"!=typeof Math){for(var b=[],c=[],d=0,e=!1,f=Math.floor(1E4*Math.random()),g=["input"],h=0;h<g.length;h++)for(var n=a.getElementsByTagName(g[h]),m=0;m<n.length;m++){var l=n[m];if(20<m)break;if(!n[m].form&&checkIsDisplayed(a,n[m],0,null,f)){verbose_log("checking "+LP_pickFieldName(a,l));if(null!=l.id&&""!=l.id){var r=c[l.id];if(null==r)c[l.id]=!0;else continue}if(null!=
l.name&&""!=l.name)if(r=b[l.name],null==r)b[l.name]=!0;else continue;looksLikeUsername(l)&&d++;if(isInputFieldPassword(a,l)){e=!0;break}if(2<d)break}}if(0<d&&4>=d&&!1==e)return decision_log(a,"DE27"),formcacheset(a,"fakedoc","orphan-first",!0),!0;formcacheset(a,"fakedoc","orphan-first",!1);return!1}}
function LP_looksLikeOTPField(a,b){if(!a||!b||"INPUT"!=b.tagName)return!1;var c=/^(otp|token|tokencode|mfacode)[_\W]|[_\W](otp|token|tokencode|mfacode)$|^(otp|token|tokencode|totpPin|mfacode):?$|[_\W](otp|token|tokencode|mfacode)[_\W]|(validation|verification|challenge).*code:?$/i,d=get_doc_location_href(a);gettldcached(d);var e=LP_pickFieldName(a,b);if(c.exec(e)||(e=b.getAttribute("aria-label"))&&0<e.indexOf("O-Key"))return!0;e=lpGetTextBeforeFormField(b,!1).toLowerCase();return c.exec(e)||d&&0<
d.toLowerCase().indexOf("challenge")&&e&&e.match(/([_\W]code:?$|^code[_\W])/)?!0:!1}function LP_fieldIsDisabled(a){return!a?!1:"undefined"!=typeof a.disabled&&a.disabled||"true"===a.getAttribute("aria-disabled")?!0:!1}function LP_fieldIsReadOnly(a){return!a?!1:"undefined"!=typeof a.readOnly&&a.readOnly||"true"===a.getAttribute("aria-readonly")?!0:!1}function LP_fieldIsDecorative(a){return!a?!1:"presentation"===a.getAttribute("role")?!0:!1}
function checkDocumentForCPWOrphans(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b=formcacheget(a,"fakedoc","cpw");if(null!=b)return b;var b=null,c=0,d=a.getElementsByTagName("INPUT");Checkpoint.assert(d.length<=MAX_INPUTS_HARD,"page has too many inputs");for(var e=0;e<d.length;e++){var f=d[e];if(e>MAX_INPUTS_HARD)break;if(null==f.form){if(isInputFieldPassword(a,f)&&lpIsVisible(f)&&(c++,f=lpIsFieldCurrentPWField(f))){if(b)return!1;b=f}if(4<=c)return formcacheset(a,"fakedoc","cpw",!1),!1}}if(2<=
c&&b)return formcacheset(a,"fakedoc","cpw",!0),!0;formcacheset(a,"fakedoc","cpw",!1);return!1}
function ForceFillFieldClicked(a,b,c,d){if(!b||!d)return!1;c=b.form&&!c?LP_getname(b.form):"";var e=b.type?b.type:"";return"password"==e?LP_getname(b)?LP_setval(a,LP_getname(b),d.p,0,d.a,c,e,d.sharedsite,null,d.automaticallyFill,d.reqinfo,null,!0,d.humanize,d.reqinfo,d.realurl):LP_fill_given_field(a,b,d.p,e,d.sharedsite,d.automaticallyFill,d.a,!0,!0,d.humanize,d.reqinfo,d.realurl):""==d.u?!0:LP_getname(b)?LP_setval(a,LP_getname(b),d.u,0,d.a,c,e,d.sharedsite,null,d.automaticallyFill,d.reqinfo,null,
!0,d.humanize,d.reqinfo,d.realurl):LP_fill_given_field(a,b,d.u,e,d.sharedsite,d.automaticallyFill,d.a,!0,!0,d.humanize,d.reqinfo,d.realurl)}function ForceFillFormClicked(a,b,c,d){if(!b)return!1;c=null;if(b=b.getElementsByTagName("INPUT")){if(c=GuessUserPassFields(b,!0,!0,!0))c.text&&ForceFillFieldClicked(a,c.text,!1,d),c.password&&ForceFillFieldClicked(a,c.password,!1,d);return!0}return!1}
function GuessUserPassFields(a,b,c,d){if(!a||0>=a.length)return null;var e=document,f,g=a.length,h=null,n=null,m=!1;for(f=0;f<g;f++){var l=a[f];if(l)if(c&&(LP_fieldIsReadOnly(l)||LP_fieldIsDisabled(l)))decision_log(e,"DE24");else if(d&&!lpIsVisible(l,!0))decision_log(e,"DE25");else{if(b){var r=RegExp(lpgs("ff_search_regexp"),"i");if(r.exec(l.name)||r.exec(l.id)){var r=l.name&&l.name.match(/[qQ]/)||l.id&&l.id.match(/[qQ]/),j=RegExp(lpgs("ff_username_regexp"),"i"),p=RegExp(lpgs("ff_email_regexp"),"i");
if(r&&l.name&&!l.name.match(/^[qQ]/)&&(!l.id||l.id&&!l.id.match(/^[qQ]/)))pass;else if(r&&l.id&&!l.id.match(/^[qQ]/)&&(!l.name||l.name&&!l.name.match(/^[qQ]/)))pass;else if(r&&(j.exec(l.name)||j.exec(l.id)||p.exec(l.name)||p.exec(l.id)))pass;else{decision_log(e,"DE23");continue}}}if(!popupfill_shoulddofield(e,l,!1)){if(("text"==l.type||"tel"==l.type||"email"==l.type)&&!n)b?(r=RegExp(lpgs("ff_username_regexp"),"i"),r.exec(l.name)||r.exec(l.id)?(h=l,m=!0):m||(h=l)):h=l;"password"==l.type&&!n&&(b?(r=
RegExp(lpgs("ff_username_regexp"),"i"),!m&&(r.exec(l.name)||r.exec(l.id))?h=l:n=l):n=l)}}}a={};h&&(a.text=h);n&&(a.password=n);return isEmptyObject(a)?null:a}
function ForceFillClicked(a,b,c){var d=g_popupfill_parent;d||(d=g_popupfill_parent_last);if(!d){if(g_force_fill_active_element){var e=LP_getActiveElement(a);e&&("INPUT"==e.tagName&&LP_docHasFocus(a)&&hasIconState(a,LP_pickFieldName(a,e)))&&(d=e,info_log("CV21"))}if(!d)return!1}if(!a&&(a=d.ownerDocument,!a))return!1;var e=chk_form_has_password(a,d.form),f=chk_form_ask_generate(a,d.form);return d.form&&e&&!f?!ForceFillFormClicked(a,d.form,b,c)||""===d.value?ForceFillFieldClicked(a,d,b,c):!0:null==d.form?
ForceFillOrphanFieldClicked(a,d,c):ForceFillFieldClicked(a,d,b,c)}function isMultiStageLoginForm(){}function LP_passwordAlt(a,b){return!a||!b||"INPUT"!=b.tagName?!1:"nyckel"==LP_pickFieldName(a,b).toLowerCase()&&"password"==b.type?!0:!1}
function LP_explicit_ignored(a,b){if(!a||!b||"undefined"==typeof b.getAttribute)return!0;var c=b.getAttribute("data-lpignore");if("true"===c)return!0;c=b.dataset?b.dataset.lpignore:!1;if("true"===c)return!0;c=b.getAttribute("lpignore");return"true"===c||"true"===b.lpignore?!0:!1}function countFormEquivalents(a){var b=0,c=a.getElementsByTagName("FORM");a=LP_getFormsThreshold(a);for(var d=0;d<c.length&&d<a;d++)(lpIsVisible(c[d]),!0)&&b++;return b}
function LP_implicit_ignored(a,b){if(!b||!a&&(a=LP_derive_doc(),!a))return!1;var c=b.id,d=b.name,e=a.body,f=b.form;if(d&&"post_title"==d&&e&&e.className&&0<=e.className.indexOf("wp-admin")||d&&("symbols"==d||"symbol"==d)||"text"==b.type&&c&&(0<c.indexOf("_note")||0<c.indexOf("-note")))return!0;var e=RegExp(lpgs("ff_combineddummy_regexp"),"i"),g=/member.*number/i;return(e.exec(c)||e.exec(d))&&!g.exec(c)&&!g.exec(d)?(decision_log(a,"DE22",{param1:c,param2:d}),!0):LP_field_is_xsrf(a,b)||f&&!popupfill_shoulddoform(a,
f)?!0:!1}function LP_read_website_hint(){}
function should_ignore_body_relative(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","ignore-relative-style");if(!0===b||!1===b)return b;b=0;b=null;LP_get_cached_body_rect(a);var b=LP_get_body_reference(a),c=LP_get_cached_body_style(a);if(c&&"relative"!=c.position)return formcacheset(a,"fakedoc","ignore-relative-style",!0),!0;c=[];b&&(c=b.children);if(c&&0<c.length){Checkpoint.assert(100>c.length,"too many body.children");for(b=0;b<c.length&&100>b;b++)if(!lp_in_array(c[b].tagName.toUpperCase(),
["SCRIPT"])&&lp_in_array(c[b].tagName.toUpperCase(),["DIV","SECTION","FORM"])){if((b=LP_get_live_style(c[b]))&&"relative"==b.position)return formcacheset(a,"fakedoc","ignore-relative-style",!1),!1;break}}formcacheset(a,"fakedoc","ignore-relative-style",!0);return!0}
function LP_iconFieldWidthOK(a,b,c){if(!a||null===b)return!1;var d=a.ownerDocument;if(!d)return verbose_log("iconFieldWidthOK: no doc???"),!1;if("undefined"==typeof c||null===c)if(isInputFieldPassword(d,a))c=!0;else{var e=a.form;e&&chk_form_has_password(d,e)&&(c=!0)}c?0<b&&40>b?a=!1:(a?(b=a.getAttribute("size"),c=a.getAttribute("maxlength"),null==b&&(b=a.size),null==c&&(c=a.maxLength),a=""==a.style.width&&b&&2>b&&0<=b||c&&3>c&&0<=c?!1:!0):a=!1,a=!a?!1:!0):a=0<b&&100>b?!1:!0;return a}
function create_icons_on_ASP(a,b){if(do_experimental_popupfill){a||(a=LP_derive_doc());if(!a)return!1;decision_log(a,"DE21",{param1:a.location.href});var c=[];if(g_do_icon_number_hint)if(g_isfirefox){var d=LP.getMatchingSites(a.location.href,SKIP_GENPWS);c.sites=d&&d.length?d.length:0}else c=g_icon_numbers;var d=a.getElementsByTagName("FORM"),e,f,g=SHOULD_DO_ALWAYS,h=LP_getFormsThreshold(a),n=0;for(f=0;f<d.length&&f<h;f++){var m=d[f].elements;chk_form_has_password(a,d[f]);chk_form_is_nonlogin_form(a,
d[f]);chk_form_ask_generate(a,d[f]);var l=form_get_username(a,d[f]),r=form_get_password(a,d[f]),j=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(j=MAX_INPUTS_HARD);for(e=0;e<m.length&&e<j;e++){var p=!1,q=m[e],s="sites";if("INPUT"==q.tagName){var k=!1;if(popupfill_shoulddofield(a,q,g)){var t=LP_fieldGetWidth(q),u=!0;if(b){if(looksLikeUsername(q)||isInputFieldPassword(a,q))s="sites",p=!0}else if(l==q)s="sites",p=!0;else if(isInputFieldPassword(a,q))q==lpCheckCurrentPWField(d[f],!0)?(s="sites",k=p=!0):
r==q?(s="sites",k=p=!0):isContigPW(a,q.form,q)?(s="generate",p=!0):(s="sites",k=p=!0);else if(isFirstFieldNonLoginSubForm(a,q))s="formfills",p=!0,u=!1;else if(isUsernameFieldLoginSubForm(a,q)||isPasswordFieldLoginSubForm(a,q))s="sites",k=p=!0;if(p&&LP_iconFieldWidthOK(q,t,u)&&(n++,setup_input_icon(a,q,s,c,k),g_clickable_input&&(!("password"==q.type&&formHasUsernameField(q))||g_clickable_input_on_password)&&!LP_didFieldClickEvent(a,q)&&s&&"sites"==s))LP_setFieldClickEvent(a,q),LP_addEventHandler(q,
"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,q.form),popuptoggle(a,null,LP_getname_or_idx(a,q,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},!1)}}}}decision_log(a,
"DE1",{param1:n})}}
function check_for_ASP(a,b){if(b&&!isASPpage()&&g_aspx_hack){if((0===b.name.indexOf("ctl00$")||null!=b.form&&("ctl00"==b.form.name||"landingform"==b.form.name||"landingForm"==b.form.name||"aspnetForm"==b.form.name||"aspnetForm"==b.form.id)||0===b.name.indexOf("ctl00_"))&&!isASPpage())setASPpage(!0),decision_log("DE20");try{a.location&&(a.location.href&&0<a.location.href.indexOf(".aspx"))&&(b.form&&(b.form.elements&&b.form.elements.length&&6<b.form.elements.length)&&!isASPpage())&&(setASPpage(!0),
decision_log("DE19"))}catch(c){write_error_to_history(a,"check_for_ASP",c)}}}
function create_icons_generic(a,b){if(do_experimental_popupfill){if(!a&&(a=LP_derive_doc(),!a))return null;decision_log(a,"DE16",{param1:a.location.href});var c=[];if(g_do_icon_number_hint)if(g_isfirefox){var d=LP.getMatchingSites(a.location.href,SKIP_GENPWS);c.sites=d&&d.length?d.length:0}else c=g_icon_numbers;var d=a.getElementsByTagName("INPUT"),e,f=d.length;e=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(e=MAX_INPUTS_HARD);Checkpoint.assert(f<=e,"page has too many inputs");f>e&&(f=e);var g=SHOULD_DO_ALWAYS,
h=checkDocumentForLoginOrphans(a);LP_firstVisibleOrphan(a);var n=0;for(e=0;e<f;e++){var m=d[e].form,l=null,r=null;m?(l=form_get_username(a,m),r=form_get_password(a,m)):(l=doc_get_orphan_username(a),r=doc_get_orphan_password(a));var j=d[e],p=!1,q="sites",s=!1;if(popupfill_shoulddofield(a,j,g)){var k=LP_fieldGetWidth(j),t=!0;if(b){if(looksLikeUsername(j)||isInputFieldPassword(a,j))q="sites",p=!0}else if(l==j)q="sites",p=!0;else if(isInputFieldPassword(a,j))m&&j==lpCheckCurrentPWField(m,!0)?(q="sites",
s=p=!0):lpIsFieldCurrentPWField(j)?(q="sites",s=p=!0):r==j?(q="sites",s=p=!0):isContigPW(a,j.form,j)?(q="generate",p=!0):(q="sites",s=p=!0);else if(isFirstFieldNonLoginSubForm(a,j))q="formfills",p=!0,t=!1;else if(isUsernameFieldLoginSubForm(a,j)||isPasswordFieldLoginSubForm(a,j))q="sites",s=p=!0;else if(null==j.form&&h&&(looksLikeUsername(j)||isInputFieldPassword(a,j)))q="sites",p=!0;if(p&&LP_iconFieldWidthOK(j,k,t)&&(n++,setup_input_icon(a,j,q,c,s),g_clickable_input&&(!("password"==j.type&&formHasUsernameField(j))||
g_clickable_input_on_password)&&!LP_didFieldClickEvent(a,j)&&q&&"sites"==q))LP_setFieldClickEvent(a,j),LP_addEventHandler(j,"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,j.form),popuptoggle(a,null,LP_getname_or_idx(a,j,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));
else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},!1)}}decision_log(a,"DE2",{param1:n});return!0}}
function LP_getAngularAttributes(a,b){a||(a=LP_derive_doc());if(!b||!a)return null;for(var c={},d="ng-model ng-controller ng-repeat ng-include ng-switch ng-view ng-minlength ng-maxlength ng-pattern ng-click ng-submit ng-required".split(" "),e=0;e<d.length;e++){var f=b.getAttribute(d[e]);null!==f&&(c[d[e]]=f)}d="ng-valid ng-invalid ng-pristine ng-dirty ng-touched ng-untouched ng-pending ng-empty ng-not-empty".split(" ");for(e=0;e<d.length;e++)f=sprintf("[\\w]*%s[\\w]*",d[e]),b.className.match(f)&&
(c[d[e]]=!0);return c}function LP_hasAngular(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-angular");if(null!=c)return c;var c=a.documentElement,d=a.body;d&&d.getAttribute("ng-app")||c&&c.getAttribute("ng-app")||d&&null!==d.getAttribute("ng-strict-di")||c&&null!==c.getAttribute("ng-strict-di")?b=!0:LP_getElementByXPath(a,"//*[@ng-app!='']")&&(b=!0);formcacheset(a,"fakedoc","has-angular",b);return b}
function LP_hasKnockout(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-knockout");if(null!=c)return c;if(g_isie)for(var c=a.getElementsByTagName("input"),d=0;d<c.length&&d<MAX_INPUTS_HARD;d++){if(c[d].getAttribute("data-bind")){b=!0;break}}else(c=LP_getElementsByXPath(a,"//*[@data-bind != '']"))&&0<c.length&&(b=!0);formcacheset(a,"fakedoc","has-knockout",b);return b}
function LP_has_yui(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","has-yui");if(null!=b)return b;if(a.documentElement&&0<=a.documentElement.className.indexOf("yui3-js-enabled")||a.documentElement&&0==a.documentElement.id.indexOf("yui_3")||a.getElementById("yui3-css-stamp"))return formcacheset(a,"fakedoc","has-yui",!0),!0;formcacheset(a,"fakedoc","has-yui",!1);return!1}
function LP_field_is_xsrf(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=!1;if(b.tagName&&"INPUT"==b.tagName.toUpperCase()&&"string"==typeof b.name&&(0<=b.name.toUpperCase().indexOf("CSRF")||0<=b.name.toUpperCase().indexOf("XSRF")||0<=b.id.toUpperCase().indexOf("CSRF")||0<=b.id.toUpperCase().indexOf("XSRF")))c=!0;return c}
function LP_get_youama_fields(a){a||(a=LP_derive_doc());if(!a)return null;var b={},b=formcacheget(a,"orphans","youama-fields");if(null!=b)return b;var b=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//input[@id='youama-email']"),c=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//input[@id='youama-password']"),d=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//button[contains(@class,'youama-ajaxlogin-button')]"),e=LP_getElementByXPath(a,
"//div[contains(@class,'youama-login-window')]"),f=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//input[@id='youama-email']"),g=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//input[@id='youama-password']"),h=LP_getElementByIdOrName(a,"youama-firstname"),n=LP_getElementByIdOrName(a,"youama-lastname"),m=LP_getElementByIdOrName(a,"youama-passwordsecond"),l=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//button[contains(@class,'youama-ajaxlogin-button')]"),
r=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]"),b={login_username:b,login_password:c,login_button:d,login_form_container:e,regis_username:f,regis_password:g,regis_password_confirm:m,regis_firstname:h,regis_lastname:n,regis_button:l,regis_form_container:r};formcacheset(a,"orphans","youama-fields",b);return b}
function LP_has_youama(a){a||(a=LP_derive_doc());if(!a)return[];var b=formcacheget(a,"fakedoc","has-youama");if(null!=b)return b;if(0<a.getElementsByClassName("youama-login-window").length||0<a.getElementsByClassName("youama-register-window").length)return formcacheset(a,"fakedoc","has-youama",!0),!0;formcacheset(a,"fakedoc","has-youama",!1);return!1}
function LP_has_dijit(a){a||(a=LP_derive_doc());if(!a||!a.documentElement)return[];var b=0,c=a.getElementsByClassName("dijitContentPane");if(c&&0<c.length||a.documentElement.className.match(/^dj_[a-z]+|\sdj_[a-z]+/))return!0;c=a.getElementsByTagName("SCRIPT");for(b=0;b<c.length;b++)if("dojo/connect"==c[b].getAttribute("type")||"dojo/method"==c[b].getAttribute("type"))return!0;c=a.getElementsByTagName("FORM");for(b=0;b<c.length;b++)if(c[b].getAttribute("data-dojo-attach-point"))return!0;return!1}
var LP_milestone_flags=0;function LP_parser_milestone(a){if("undefined"==typeof a)return!1;LP_milestone_flags|=a;return!0}
function page_is_nemid(a){a||(a=LP_derive_doc());if(!a)return!1;var b=lp_gettld_url(punycode.URLToASCII(get_doc_location_href(document))),c="",d="",e=!1,f=formcacheget(a,"fakedoc","is-nemid");if(null!=f)return f;try{if(!get_can_xref(a,"top"))throw"xref";c=window.name;d=window.top.name}catch(g){set_can_xref(a,"top",!1)}if(("danid.dk"==b||"nemid.nu"==b)&&(a.getElementById("appArea")||"nemid_iframe"==c||"loginWindow"==d))e=!0;formcacheset(a,"fakedoc","is-nemid",e);return e}
function LP_element_is_honeypot(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=gettldcached(get_doc_location_href(a)),d=[],e=[],f=0,g,h=["lpcurrpasselt","lpcurruserelt"];if(lp_in_array(b.id,h))return!1;if(has_same_tld(c,"citi.com")){if(a.getElementById("loginForm")||a.getElementById("logon")||a.getElementById("password")||a.getElementById("PASSWORD")){e=a.getElementsByTagName("input");f=e.length;for(g=0;g<MAX_INPUTS_SOFT&&g<f;g++)e[g]&&"password"==e[g].type&&!lp_in_array(e[g].id,h)&&d.push(e[g]);
if(5==d.length&&"a"==d[0].defaultValue&&"b"==d[1].defaultValue&&"c"==d[2].defaultValue&&"d"==d[3].defaultValue&&lp_in_array(b,[d[0],d[1],d[2],d[3]]))return!0}}else if(compare_equiv_domains(c,"ebay.com")&&1===a.getElementsByName("runId2").length&&("userid"==b.id||"userid"==b.name||"pass"==b.id||"pass"==b.name||"runId2"==b.name))return!0;return compare_equiv_domains(c,"nordnet.no")&&"fake_password"==b.name?!0:!1}
function LP_page_is_lazyloader(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","is-lazyloader");if(null!=c)return c;if(LP_hasAngular(a)||LP_hasKnockout(a)||LP_has_emberjs(a))return formcacheset(a,"fakedoc","is-lazyloader",!0),!0;if(a.body&&(c=a.body.getAttribute("onload"),"string"==typeof c&&0<=c.toLowerCase().indexOf("lazyload")))return!0;var d="",e="",d="",f=/requirejs|lazyload|LAB\.?js|LAB\.min\.js/i,g=/dojo/;if(!f||!g)return!1;for(var h=a.getElementsByTagName("script"),
c=0;c<h.length;c++)if(d=h[c].getAttribute("src")){id=h[c].id;if(f.exec(d)||f.exec(id)){b=!0;break}e=h[c].getAttribute("type");if("module"==e){b=!0;break}if(g.exec(d)&&(d=h[c].getAttribute("data-dojo-config"),"async: true"==d)){b=!0;break}if("microloader"==id&&h[c].getAttribute("data-app")){b=!0;break}d=h[c].getAttribute("data-requirecontext");e=h[c].getAttribute("data-requiremodule");if(d&&e){b=!0;break}}else if((d=h[c].innerHTML)&&512>d.length&&0<d.indexOf("function SRSRetry"))return!0;if(!b){f=
a.getElementsByTagName("meta");g="";for(c=0;c<f.length;c++)if(g=f[c].name,"string"==typeof g&&g.match(/config\/environment$/)){b=!0;break}}formcacheset(a,"fakedoc","is-lazyloader",b);return b}function LP_isSinglePageApp(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","SPA");return null!=b?b:LP_hasAngular(a)||(LP_hasKnockout(a)||LP_has_emberjs(a))||0<g_probablySinglePageApp||LP_url_is_single_page_app(get_doc_location_href(a))?(formcacheset(a,"fakedoc","SPA",!0),!0):!1}
var g_probablySinglePageApp=0;function LP_has_jquery(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-jquery");if(null!=c)return c;for(var c="",d=/jquery/i,e=a.getElementsByTagName("script"),f=0;f<e.length;f++)if(c=e[f].getAttribute("src"),d.exec(c)){b=!0;break}formcacheset(a,"fakedoc","has-jquery",b);return b}
function LP_init_url_history(a){a||(a=LP_derive_doc());if(!a)return!1;if("undefined"==typeof LPUH||null===LPUH||null===LPUH.url_history){LPUH={};if(null===LPUH)return!1;LPUH.url_history=[]}return!0}function LP_get_last_url_history(a){a||(a=LP_derive_doc());if(!a)return!1;LP_init_url_history(a);return LPUH&&(a=LPUH.url_history.length,0<a)?LPUH.url_history[a-1]:{}}function LP_reset_url_history(a){LP_init_url_history(a);return LPUH?(LPUH.url_history=[],!0):!1}
function LP_put_last_url_history(a){a||(a=LP_derive_doc());if(!a)return!1;LP_init_url_history(a);a=get_doc_location_href(a);var b=crc32(LP_gettime()+"%"+a);LPUH.url_history.push({href:a,href_hash:b});verbose_log("computed new hash "+b+" for "+a);return!0}function LP_has_extjs(){}function LP_is_buttonlike(a,b){a||(a=LP_derive_doc());return!a||!b?!1:"BUTTON"==b.tagName||"INPUT"==b.tagName&&("submit"==b.type||"image"==b.type||"button"==b.type)?!0:!1}var BEEPID="_lpbeep";
function LP_putBeeper(a,b,c){a||(a=LP_derive_doc());if(!a)return!1;if(a.getElementById(BEEPID))return!0;if(!c&&!a.body)return!1;var d=a.createElement("div");d.setAttribute("aria-hidden","true");d.style.display="none";d.style.left="-1000px";d.style.height="0";d.setAttribute("data-lpbeep",b);d.id=BEEPID;c?c.appendChild(d):a.body.appendChild(d);return!0}function LP_pickBeeper(a){a||(a=LP_derive_doc());if(!a)return!1;(a=a.getElementById(BEEPID))&&a.parentNode.removeChild(a);return!0}
function LP_readBeeper(a){a||(a=LP_derive_doc());if(!a)return null;if(a=a.getElementById(BEEPID)){var b=getComputedStyle(a);return{display:b.display,visibility:b.visibility,val:a.getAttribute("data-lpbeep")}}return null}
function should_fill_on_click(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=!1,d=b.tagName.toUpperCase(),e=b.form,f=!1,g=b.getAttribute("role");if(LP_is_buttonlike(a,b)&&e){var h=e.action,e=e.method;h&&(0==h.toLowerCase().indexOf("https://")&&e&&"POST"==e.toUpperCase())&&(f=c=!0)}if(!f&&("A"==d||"NAV"==d||"navigation"==g||"INPUT"==d&&"submit"==b.type))c=!1,f=!0;f||lp_in_array(d,"INPUT LABEL SELECT FIELDSET OPTION TEXTAREA TBODY THEAD ADDRESS BLOCKQUOTE Q PRE ABBR CITE BODY HEAD META SCRIPT STYLE MAIN ARTICLE HEADER FOOTER ASIDE DETAILS FIGURE FIGCAPTION MARK SECTION SUMMARY TIME IFRAME FRAME FRAMESET".split(" "))&&
(c=!0);return!c}function should_simulate_submit_on_click(a){a||LP_derive_doc();return!1}function LP_url_is_single_page_app(a){return!a||"string"!=typeof a?!1:/https?:\/\/.*#\/[a-z]/i.exec(a)?!0:!1}
function LP_has_bootstrapJS(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-bootstrap");if(null!=c)return c;for(var c="",d=/bootstrap.min.js$/i,e=a.getElementsByTagName("script"),f=0;f<e.length;f++)if(c=e[f].getAttribute("src"),d.exec(c)){b=!0;break}formcacheset(a,"fakedoc","has-bootstrap",b);return b}
function LP_has_joomla(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-joomla");if(null!=c)return c;for(var c="",d=/(\/media\/jui\/js|\/templates\/joomla)/i,e=a.getElementsByTagName("script"),f=0;f<e.length;f++)if(c=e[f].getAttribute("src"),d.exec(c)){b=!0;break}formcacheset(a,"fakedoc","has-joomla",b);return b}
function LP_has_emberjs(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-emberjs");if(null!=c)return c;if((c=a.body)&&(0<=c.className.indexOf("ember-application")||"1"==c.getAttribute("data-ember-extension")))b=!0;!b&&a.documentElement&&"1"==a.documentElement.getAttribute("data-ember-extension")&&(b=!0);if(!b)for(var c=a.getElementsByTagName("meta"),d="",e=0;e<c.length;e++)if(d=c[e].name,"string"==typeof d&&d.match(/config\/environment$/)){b=!0;break}formcacheset(a,
"fakedoc","has-emberjs",b);return b}var SPA_INDETERMINATE=0,SPA_LOADED=1,SPA_LOGIN=2,SPA_LOGINFAILED=4,SPA_ACCTMGMT=8,SPA_REGISTER=16,SPA_APP=32,SPA_INDETERMINATE_STATE="A",SPA_LOGIN_STATE="B",SPA_IN_APP_STATE="C",SPA_LOGIN_WITHIN_APP_STATE="D";
