LPPlatform={};
(function(){LPPlatform.openURL=function(a){bg.openURL(a)};LPPlatform.getBaseURL=function(){return bg.base_url};LPPlatform.doAjax=function(a){$.ajax(a)};LPPlatform.ajax=function(a){bg.isOffline()?a.error&&a.error(null,null,"offline"):LPPlatform.doAjax(a)};LPPlatform.getOpenGroups=function(){var a=bg.localStorage_getItem(bg.db_prepend(bg.g_username_hash+".savedtree"));if(null!==a){for(var b={},a=LPProxy.decrypt(a).split(","),c=0,e=a.length;c<e;++c){var d=a[c];0===d.indexOf("_")&&(d=d.substring(1));b[d]=
!0}return b}return null};LPPlatform.setOpenGroups=function(a){for(var b=0,c=a.length;b<c;++b)a[b]="_"+a[b];a=LPProxy.encrypt(a.join(","));bg.localStorage_setItem(bg.db_prepend(bg.g_username_hash+".savedtree"),a)};LPPlatform.initialized=function(){return!0};LPPlatform.getHTML=function(a,b){$.ajax({url:a,success:b,dataType:"text"})};LPPlatform.loadedPreferences=function(){return LPTools.hasProperties(bg.g_userprefs)};LPPlatform.openAttachment=function(a){bg.openAttach(a._parentNote.getID(),a.getID())};
LPPlatform.saveAttachment=function(a){bg.exportAttachment(a._parentNote.getID(),a.getID())};LPPlatform.logException=function(a){var b="string"===typeof a?a:a.message;a.stack&&(b+="\n"+a.stack);LPPlatform.logError(b)};LPPlatform.logError=function(a){a="Page: "+window.location.href+" Error: "+a;try{console.error(a),bg.lpReportError("VAULT_4_0: "+a)}catch(b){}};LPPlatform.addEventListener=function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.addEventListener.apply(a,b)};LPPlatform.removeEventListener=
function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.removeEventListener.apply(a,b)};LPPlatform.handleAcctsIFrameLoaded=function(){};LPPlatform.canBackgroundOpenPopover=function(){return!0};LPPlatform.generateSharingKeys=function(a){bg.generateSharingKeys(a)};LPPlatform.getResourcePath=function(a){return a};LPPlatform.getResourceName=function(a){return a};LPPlatform.canPreventBlur=function(){return!0};LPPlatform.getBackgroundData=function(a){return a};LPPlatform.showIntroTutorial=
function(){return!1};LPPlatform.supportsBinary=function(){return!0};LPPlatform.openKeyboard=function(){LPPlatform.openTabDialog("login",{virtualKeyboard:!0})}})();
(function(a){var b=$(document.body),c=$(document.getElementsByTagName("html")),e,d=function(a,f){b.css({height:a,width:f});c.css({height:a,width:f})};e=function(a,b){bg.LPPlatform.isMac()?(d(a+1,b),setTimeout(function(){d(a,b)},50)):d(a,b)};a.setLoginPopoverSize=function(a,b){e(a,b)};a.setDropdownPopoverSize=function(a,b){e(a,b)};a.openTabDialog=function(){bg.openTabDialog?bg.openTabDialog.apply(bg,arguments):bg.LPPlatform.openTabDialog.apply(bg.LPPlatform,arguments)};a.closePopup=function(b){(b||
0===Dialog.prototype.getDialogCount()&&0===LPDialog.getPendingCount())&&a.doClosePopup()};a.doClosePopup=function(){window.close()};a.closeTab=function(){window.close()};a.getLoginDialog=function(){return dialogs.login};a.openLoginPopover=function(){!bg.lploggedin&&bg.g_badgedata&&"notification"===bg.g_badgedata.cmd?(dialogs.notification.open({notification:bg.g_notification_data,onResize:function(b,c){a.setLoginPopoverSize(b,c)}}),bg.clear_badge()):a.getLoginDialog().open({isPopup:!0,onResize:function(b,
c){a.setLoginPopoverSize(b,c)},onClose:function(){a.closePopup()}})};a.requiresData=function(a){switch(a){case "chooseProfile":return!0}return!1};a.openDropdownPopoverDialog=function(b,c){$("#container").LP_hide();LPTools.removeKeyBoardNavigation();a.requiresData(b)&&LPProxy.initializeModel();c=$.extend(c,{onResize:function(b,c){a.setDropdownPopoverSize(b,c)},onClose:function(){a.closePopup()}});dialogs[b].open(c)};a.openDropdownPopover=function(){if(bg.g_badgedata&&"notification"===bg.g_badgedata.cmd){switch(bg.g_badgedata.alerttype){case "duplicate":a.openDropdownPopoverDialog("duplicatePassword",
{notification:bg.g_badgedata});break;case "weak":a.openDropdownPopoverDialog("weakPassword",{notification:bg.g_badgedata})}switch(bg.g_badgedata.type){case "error":a.openDropdownPopoverDialog("notification",{notification:bg.g_notification_data})}bg.clear_badge()}else $("#container").LP_show(),ExtensionDropdown.setup()};a.checkBrowserPasswordManager=function(){};a.setupDropdownImportMenu=function(a){a.addClass("singleImportOption");a=$("#importMenuItemMain");a.unbind("click");a.bind("click",function(){bg.lpevent("m_i");
bg.openimport()})};a.getUnavailablePreferences=function(){return{clearClipboardSecsVal:!bg.can_clear_clipboard(),openpopoverHk:!a.canBackgroundOpenPopover(),pollServerVal:bg.g_nopoll,storeLostOTP:"0"===bg.g_prefoverrides.account_recovery,showvault:bg.g_hidevault||bg.g_hideshowvault,homeHk:bg.g_hidevault||bg.g_hideshowvault,saveallHk:bg.g_hidesaedhotkey,searchHk:bg.g_hidesearch,usepopupfill:!bg.g_offer_popupfill,recentUsedCount:bg.g_hiderecentlyusedlistsize,searchNotes:bg.g_hidenotes,idleLogoffVal:!(bg.g_is_win||
bg.g_is_mac||bg.g_is_linux),enablenamedpipes:bg.lppassusernamehash||!(bg.g_is_win||bg.g_is_mac||bg.g_is_linux)||bg.LPISLOC||bg.is_chrome_portable(),enablenewlogin:!0}};a.getPreferencesRequiringBinary=function(){return{enablenamedpipes:!0}};a.handlePreferenceChanges=function(a){!1===a.storeLostOTP&&bg.DeleteOTP()};a.resizeTo=function(a,b){window.resizeTo(a,b)};a.openCreateAccount=function(){a.openTabDialog("createAccount")}})(LPPlatform);
