var g_new_superbar=!0;"undefined"!=typeof g_isfirefox&&g_isfirefox&&(g_new_superbar=!1);
var SB_icons={savesite:{id:"SB_addico",alt:gs("Save Site"),src:g_40_icons.Add,dock:"left",tooltiptext:gs("Save Password to Vault"),clickfn:function(b){savesite_popupaction_iframe(LP_derive_doc(),b,null)}},sites:{id:"SB_siteico",alt:gs("Sites"),src:g_40_icons.Sites,dock:"left",tooltiptext:gs("Saved Passwords"),clickfn:function(b){sites_popupaction(b,LP_derive_doc())}},formfill:{id:"SB_ffico",alt:gs("Form Fills"),src:g_40_icons.FormFill,dock:"left",tooltiptext:gs("Form Fill Profiles"),clickfn:function(b){formfillprofile_popupaction(b,
LP_derive_doc())}},generate:{id:"SB_genico",alt:gs("Generate"),src:g_40_icons.Generate,dock:"left",tooltiptext:gs("Generate"),clickfn:function(b){generate_popupaction(b)}},never:{id:"SB_nevico",alt:gs("Never"),src:g_40_icons.Disable,dock:"left",tooltiptext:gs("Disable"),clickfn:function(b){never_popupaction(b,LP_derive_doc())}},close:{id:"SB_closeico",alt:gs("Close"),src:g_40_icons.Close,dock:"right",tooltiptext:gs("Close"),clickfn:function(){close_popupaction(LP_derive_doc())}}};
function set_new_superbox_40(b,h){if(!b)return null;var e="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"",a=null;verbose&&times&&(times.createbox=LP_gettime());!b||!h?a=null:(a=b.createElement(e+"div"),a.id="headerdiv",a.className="bg40dialog",h.appendChild(a),verbose&&times&&(times.createheader=LP_gettime()),LP_addEventHandler(a,"selectstart",function(){return!1}));if(!a)return null;var g=a;verbose&&times&&(times.doiconsstart=LP_gettime());var k,c=b.createElement(e+"div");c.id="SB_iconbox";
c.className="super40height bg40header";c.setAttribute("role","navigation");g.appendChild(c);for(k in SB_icons)if(SB_icons.hasOwnProperty(k)){var j=b,f=c,g=SB_icons[k];if(j&&f){var d="",l=j.createElement(e+"a");l.id=g.id+"_a";d="super40icon";"right"==g.dock?(d+=" floatright",g.tooltiptext&&(d+=" tooltip40super")):(d+=" floatleft",g.tooltiptext&&(d+=" tooltip40superlong"));l.setAttribute("draggable","false");l.className=d;f.appendChild(l);f=g;!j||!f?f=null:(d=j.createElement(e+"input"))?(d.id=f.id+
"_img",d.type="button",f.tooltiptext||d.setAttribute("title",f.alt),d.setAttribute("aria-label",f.alt),d.className=sprintf("bg40header super40icon_icon %s",d.id),f=d):f=null;l.appendChild(f);g_isie&&(f.style.display="none",f=g,!j||!f?f=null:(d=j.createElement("INPUT"),d.id=f.id+"_img_ie",d.type="image",g_isie?d.src=f.src:d.setAttribute("src",f.src),d.setAttribute("alt",f.alt),f.tooltiptext||d.setAttribute("title",f.alt),d.width=16,d.height=16,d.className="super40icon_icon_ie",f=d),l.appendChild(f));
g.tooltiptext&&(j=j.createElement(e+"span"),LP_elt_set_text(j,g.tooltiptext),l.appendChild(j))}}verbose&&times&&(times.doiconsdone=LP_gettime());k=a;b&&k&&(a=b.createElement(e+"div"),a.id="SB_titlebox",a.className="super40height bg40title super40title unselectable",g_isie&&10>LP_getDocumentMode(b)&&a.setAttribute("unselectable","on"),c=b.createElement(e+"span"),c.id="SB_titlebox_txt",c.setAttribute("draggable","false"),c.className="super40title",LP_elt_set_text(c,gs("What would you like to do?")),
a.appendChild(c),verbose&&(c=b.createElement(e+"span"),c.id="debug_txt",c.style.display="inline",c.style.fontSize="10px",c.style.marginLeft="5px",a.appendChild(c)),k.appendChild(a),verbose&&times&&(times.createtitle=LP_gettime()));if(b)for(var m in SB_icons)SB_icons.hasOwnProperty(m)&&(e=b.getElementById(SB_icons[m].id+"_img"))&&LP_addEventHandler(e,"click",SB_icons[m].clickfn)}
function update_title40(b,h){if(!b)return!1;var e=b.getElementById("SB_titlebox_txt"),a="";switch(h){case "sites":case "never":case "formfill":case "generate":case "savesite":a=SB_icons[h].alt;break;case "zerostate":a=gs("What would you like to do?");break;case "delete":a=gs("Delete Site");break;case "deleteff":a=gs("Delete Formfill Profile");break;case "more":a=gs("More")}a&&LP_elt_set_text(e,a);return!0}
function set_active_img40(b,h){if(!b)return!1;var e,a,g,k=SB_icons[h];switch(h){case "sites":case "never":case "formfill":case "generate":case "savesite":for(e in SB_icons)if(SB_icons.hasOwnProperty(e))if(a=SB_icons[e].id+"_img",g=SB_icons[e].id+"_active",e==h){var c=b.getElementById(k.id+"_img");c&&0<=c.className.indexOf(a)&&(c.className=c.className.replace(a,g))}else if((c=b.getElementById(SB_icons[e].id+"_img"))&&0<=c.className.indexOf(g))c.className=c.className.replace(g,a);break;default:for(e in SB_icons)if(SB_icons.hasOwnProperty(e)&&
(a=SB_icons[e].id+"_img",g=SB_icons[e].id+"_active",c=b.getElementById(a)))c.className=c.className.replace(g,a)}return!0}function reveal_real_icons(b){for(var h in SB_icons){var e=b.getElementById(SB_icons[h].id+"_img_ie"),a=b.getElementById(SB_icons[h].id+"_img");e&&a&&(e.style.display="none",a.style.display="block")}return!0}"undefined"!=typeof g_isie&&g_isie&&LP_addEventHandler(window,"load",function(){reveal_real_icons(document)});
