document.title=gs("Preferences");document.getElementById("lp_docwrite_prefs1")&&set_innertext(document.getElementById("lp_docwrite_prefs1"),gs("Preferences"));document.getElementById("lp_docwrite_prefs2")&&set_innertext(document.getElementById("lp_docwrite_prefs2"),gs("Security"));document.getElementById("lp_docwrite_prefs3")&&set_innertext(document.getElementById("lp_docwrite_prefs3"),gs("Disable Chrome Password Manager"));
document.getElementById("lp_docwrite_prefs4")&&set_innertext(document.getElementById("lp_docwrite_prefs4"),gs("Automatically Log out when all browsers are closed and Chrome has been closed for (mins)"));document.getElementById("lp_docwrite_prefs5")&&set_innertext(document.getElementById("lp_docwrite_prefs5"),gs("Automatically Log out after idle (mins)"));document.getElementById("lp_docwrite_prefs6")&&set_innertext(document.getElementById("lp_docwrite_prefs6"),gs("Install the binary version of LastPass for Chrome to enable automatic log out after idle"));
document.getElementById("lp_docwrite_prefs7")&&set_innertext(document.getElementById("lp_docwrite_prefs7"),gs("Install the LastPass Library for Chrome to enable automatic log out after idle"));document.getElementById("lp_docwrite_prefs8")&&set_innertext(document.getElementById("lp_docwrite_prefs8"),gs("General"));document.getElementById("lp_docwrite_prefs9")&&set_innertext(document.getElementById("lp_docwrite_prefs9"),gs("Open New Pages in"));
document.getElementById("lp_docwrite_prefs10")&&set_innertext(document.getElementById("lp_docwrite_prefs10"),gs("the current tab"));document.getElementById("lp_docwrite_prefs11")&&set_innertext(document.getElementById("lp_docwrite_prefs11"),gs("Tabs"));document.getElementById("lp_docwrite_prefs12")&&set_innertext(document.getElementById("lp_docwrite_prefs12"),gs("Windows"));document.getElementById("lp_docwrite_prefs13")&&set_innertext(document.getElementById("lp_docwrite_prefs13"),gs("Highlight input boxes"));
document.getElementById("lp_docwrite_prefs14")&&set_innertext(document.getElementById("lp_docwrite_prefs14"),gs("Automatically Fill Login Information"));document.getElementById("lp_docwrite_prefs15")&&set_innertext(document.getElementById("lp_docwrite_prefs15"),gs("Show My LastPass Vault After Login"));document.getElementById("lp_docwrite_prefs16")&&set_innertext(document.getElementById("lp_docwrite_prefs16"),gs("Appearance"));
document.getElementById("lp_docwrite_prefs17")&&set_innertext(document.getElementById("lp_docwrite_prefs17"),gs("Show Sites in Groups"));document.getElementById("lp_docwrite_prefs18")&&set_innertext(document.getElementById("lp_docwrite_prefs18"),gs("Hide Context Menu Options"));document.getElementById("lp_docwrite_prefs19")&&set_innertext(document.getElementById("lp_docwrite_prefs19"),gs("Form Fill"));
document.getElementById("lp_docwrite_prefs20")&&set_innertext(document.getElementById("lp_docwrite_prefs20"),gs("Default Form Fill Profile"));document.getElementById("lp_docwrite_prefs21")&&set_innertext(document.getElementById("lp_docwrite_prefs21"),gs("Do not overwrite fields that are already filled"));document.getElementById("lp_docwrite_prefs22")&&set_innertext(document.getElementById("lp_docwrite_prefs22"),gs("Notifications"));
document.getElementById("lp_docwrite_prefs23")&&set_innertext(document.getElementById("lp_docwrite_prefs23"),gs("Show Notifications")+"\u00a0"+gs("_Chrome_Only_Toolstrip_"));document.getElementById("lp_docwrite_prefs24")&&set_innertext(document.getElementById("lp_docwrite_prefs24"),gs("Offer to Generate Secure Passwords"));document.getElementById("lp_docwrite_prefs25")&&set_innertext(document.getElementById("lp_docwrite_prefs25"),gs("Show Form Fill Notifications"));
document.getElementById("lp_docwrite_prefs26")&&set_innertext(document.getElementById("lp_docwrite_prefs26"),gs("Show Save Site Notifications")+"\u00a0"+gs("_Chrome_Only_Toolstrip_"));document.getElementById("lp_docwrite_prefs27")&&set_innertext(document.getElementById("lp_docwrite_prefs27"),gs("Show certain notifications only after click"));document.getElementById("lp_docwrite_prefs28")&&set_innertext(document.getElementById("lp_docwrite_prefs28"),gs("Show Fill Notification Bar"));
document.getElementById("lp_docwrite_prefs29")&&set_innertext(document.getElementById("lp_docwrite_prefs29"),gs("Show Save Site Notification Bar"));document.getElementById("lp_docwrite_prefs30")&&set_innertext(document.getElementById("lp_docwrite_prefs30"),gs("Show Change Password Notification Bar"));document.getElementById("lp_docwrite_prefs31")&&set_innertext(document.getElementById("lp_docwrite_prefs31"),gs("Feedback"));
document.getElementById("lp_docwrite_prefs32")&&set_innertext(document.getElementById("lp_docwrite_prefs32"),gs("Click here to launch feedback"));document.getElementById("lp_docwrite_prefs33")&&set_innertext(document.getElementById("lp_docwrite_prefs33"),gs("HotKeys"));document.getElementById("lp_docwrite_prefs34")&&set_innertext(document.getElementById("lp_docwrite_prefs34"),gs("Generate Secure Password"));
document.getElementById("lp_docwrite_prefs35")&&set_innertext(document.getElementById("lp_docwrite_prefs35"),gs("Recheck Page"));document.getElementById("lp_docwrite_prefs36")&&set_innertext(document.getElementById("lp_docwrite_prefs36"),gs("Site Search"));document.getElementById("lp_docwrite_prefs37")&&set_innertext(document.getElementById("lp_docwrite_prefs37"),gs("Fill In Next Login (When Multiple)"));
document.getElementById("lp_docwrite_prefs38")&&set_innertext(document.getElementById("lp_docwrite_prefs38"),gs("Fill In Previous Login (When Multiple)"));document.getElementById("lp_docwrite_prefs39")&&set_innertext(document.getElementById("lp_docwrite_prefs39"),gs("Submit Form"));document.getElementById("lp_docwrite_prefs40")&&set_innertext(document.getElementById("lp_docwrite_prefs40"),gs("Open My LastPass Vault"));
document.getElementById("lp_docwrite_prefs41")&&set_innertext(document.getElementById("lp_docwrite_prefs41"),gs("Save All Entered Data"));document.getElementById("lp_docwrite_prefs42")&&set_innertext(document.getElementById("lp_docwrite_prefs42"),gs("Log Out"));document.getElementById("lp_docwrite_prefs43")&&set_innertext(document.getElementById("lp_docwrite_prefs43"),gs("Fill In Default Form Fill Profile"));
document.getElementById("lp_docwrite_prefs44")&&set_innertext(document.getElementById("lp_docwrite_prefs44"),gs("Open Popover"));document.getElementById("lp_docwrite_prefs45")&&set_innertext(document.getElementById("lp_docwrite_prefs45"),gs("Account Settings"));document.getElementById("lp_docwrite_prefs46")&&set_innertext(document.getElementById("lp_docwrite_prefs46"),gs("Click here to launch account settings"));
document.getElementById("lp_docwrite_prefs47")&&set_innertext(document.getElementById("lp_docwrite_prefs47"),gs("Require security reprompt when:"));document.getElementById("lp_docwrite_prefs48")&&set_innertext(document.getElementById("lp_docwrite_prefs48"),gs("Log into a Site"));document.getElementById("lp_docwrite_prefs49")&&set_innertext(document.getElementById("lp_docwrite_prefs49"),gs("Edit Site"));
document.getElementById("lp_docwrite_prefs50")&&set_innertext(document.getElementById("lp_docwrite_prefs50"),gs("Edit Secure Notes"));document.getElementById("lp_docwrite_prefs51")&&set_innertext(document.getElementById("lp_docwrite_prefs51"),gs("View Passwords"));document.getElementById("lp_docwrite_prefs52")&&set_innertext(document.getElementById("lp_docwrite_prefs52"),gs("Fill or Edit Form Fill Data"));
document.getElementById("lp_docwrite_prefs53")&&set_innertext(document.getElementById("lp_docwrite_prefs53"),gs("Advanced"));document.getElementById("lp_docwrite_prefs54")&&set_innertext(document.getElementById("lp_docwrite_prefs54"),gs("Automatically login to sites if time since last login > (seconds)"));document.getElementById("lp_docwrite_prefs55")&&set_innertext(document.getElementById("lp_docwrite_prefs55"),gs("Warn before filling insecure forms"));
document.getElementById("lp_docwrite_prefs56")&&set_innertext(document.getElementById("lp_docwrite_prefs56"),gs("Respect AutoComplete=off: allow websites to disable AutoFill"));document.getElementById("lp_docwrite_prefs57")&&set_innertext(document.getElementById("lp_docwrite_prefs57"),gs("Poll Server for account changes (mins)"));document.getElementById("lp_docwrite_prefs58")&&set_innertext(document.getElementById("lp_docwrite_prefs58"),gs("Clear Clipboard after use (seconds)"));
document.getElementById("lp_docwrite_prefs59")&&set_innertext(document.getElementById("lp_docwrite_prefs59"),gs("Recently Used list size"));document.getElementById("lp_docwrite_prefs60")&&set_innertext(document.getElementById("lp_docwrite_prefs60"),gs("Search within secure notes"));document.getElementById("lp_docwrite_prefs61")&&set_innertext(document.getElementById("lp_docwrite_prefs61"),gs("Open login dialog when browser starts"));
document.getElementById("lp_docwrite_prefs62")&&set_innertext(document.getElementById("lp_docwrite_prefs62"),gs("Save a disabled One Time Password locally for Account Recovery"));document.getElementById("lp_docwrite_prefs63")&&set_innertext(document.getElementById("lp_docwrite_prefs63"),gs("Share login state between other browsers"));document.getElementById("lp_docwrite_prefs64")&&set_innertext(document.getElementById("lp_docwrite_prefs64"),gs("Install the binary version of LastPass for Chrome to enable sharing login state between other browsers"));
document.getElementById("lp_docwrite_prefs65")&&set_innertext(document.getElementById("lp_docwrite_prefs65"),gs("Language"));document.getElementById("lp_docwrite_prefs66")&&set_innertext(document.getElementById("lp_docwrite_prefs66"),gs("Enable new login screen"));document.getElementById("lp_docwrite_prefs67")&&set_innertext(document.getElementById("lp_docwrite_prefs67"),gs("This can only be handled from a webpage"));
document.getElementById("lp_docwrite_prefs68")&&set_innertext(document.getElementById("lp_docwrite_prefs68"),gs("Clear filled fields on log out"));document.getElementById("lp_docwrite_prefs168")&&set_innertext(document.getElementById("lp_docwrite_prefs168"),gs("Show Matching Sites in top level menu"));document.getElementById("lp_docwrite_prefs170")&&set_innertext(document.getElementById("lp_docwrite_prefs170"),gs("Open extension pages in dialogs"));
document.getElementById("lp_docwrite_prefs69")&&set_innertext(document.getElementById("lp_docwrite_prefs69"),gs("Click Icons in Fields"));document.getElementById("lp_docwrite_prefs169")&&set_innertext(document.getElementById("lp_docwrite_prefs169"),gs("Show Matching Sites Count in Toolbar"));document.getElementById("lp_docwrite_prefs70")&&set_innertext(document.getElementById("lp_docwrite_prefs70"),gs("Icons"));
document.getElementById("lp_docwrite_prefs71")&&set_innertext(document.getElementById("lp_docwrite_prefs71"),gs("Show notifications below browser"));
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){onLoad()});document.getElementById("prefs").onsubmit=function(){return!1};document.getElementById("getbinary1").onclick=function(){getbinary();return!1};document.getElementById("getbinary2").onclick=function(){getbinary();return!1};document.getElementById("generateHk").onkeypress=function(){return!1};document.getElementById("generateHk").addEventListener("keyup",function(a){fixhk("generateHk",a)});document.getElementById("generateHk").addEventListener("blur",
function(a){fixhk("generateHk",a)});document.getElementById("generateHk").addEventListener("keydown",function(a){capturehk("generateHk",a)});document.getElementById("recheckHk").onkeypress=function(){return!1};document.getElementById("recheckHk").addEventListener("keyup",function(a){fixhk("recheckHk",a)});document.getElementById("recheckHk").addEventListener("blur",function(a){fixhk("recheckHk",a)});document.getElementById("recheckHk").addEventListener("keydown",function(a){capturehk("recheckHk",
a)});document.getElementById("searchHk").onkeypress=function(){return!1};document.getElementById("searchHk").addEventListener("keyup",function(a){fixhk("searchHk",a)});document.getElementById("searchHk").addEventListener("blur",function(a){fixhk("searchHk",a)});document.getElementById("searchHk").addEventListener("keydown",function(a){capturehk("searchHk",a)});document.getElementById("nextHk").onkeypress=function(){return!1};document.getElementById("nextHk").addEventListener("keyup",function(a){fixhk("nextHk",
a)});document.getElementById("nextHk").addEventListener("blur",function(a){fixhk("nextHk",a)});document.getElementById("nextHk").addEventListener("keydown",function(a){capturehk("nextHk",a)});document.getElementById("prevHk").onkeypress=function(){return!1};document.getElementById("prevHk").addEventListener("keyup",function(a){fixhk("prevHk",a)});document.getElementById("prevHk").addEventListener("blur",function(a){fixhk("prevHk",a)});document.getElementById("prevHk").addEventListener("keydown",function(a){capturehk("prevHk",
a)});document.getElementById("submitHk").onkeypress=function(){return!1};document.getElementById("submitHk").addEventListener("keyup",function(a){fixhk("submitHk",a)});document.getElementById("submitHk").addEventListener("blur",function(a){fixhk("submitHk",a)});document.getElementById("submitHk").addEventListener("keydown",function(a){capturehk("submitHk",a)});document.getElementById("homeHk").onkeypress=function(){return!1};document.getElementById("homeHk").addEventListener("keyup",function(a){fixhk("homeHk",
a)});document.getElementById("homeHk").addEventListener("blur",function(a){fixhk("homeHk",a)});document.getElementById("homeHk").addEventListener("keydown",function(a){capturehk("homeHk",a)});document.getElementById("saveallHk").onkeypress=function(){return!1};document.getElementById("saveallHk").addEventListener("keyup",function(a){fixhk("saveallHk",a)});document.getElementById("saveallHk").addEventListener("blur",function(a){fixhk("saveallHk",a)});document.getElementById("saveallHk").addEventListener("keydown",
function(a){capturehk("saveallHk",a)});document.getElementById("logoffHk").onkeypress=function(){return!1};document.getElementById("logoffHk").addEventListener("keyup",function(a){fixhk("logoffHk",a)});document.getElementById("logoffHk").addEventListener("blur",function(a){fixhk("logoffHk",a)});document.getElementById("logoffHk").addEventListener("keydown",function(a){capturehk("logoffHk",a)});document.getElementById("defaultffidHk").onkeypress=function(){return!1};document.getElementById("defaultffidHk").addEventListener("keyup",
function(a){fixhk("defaultffidHk",a)});document.getElementById("defaultffidHk").addEventListener("blur",function(a){fixhk("defaultffidHk",a)});document.getElementById("defaultffidHk").addEventListener("keydown",function(a){capturehk("defaultffidHk",a)});document.getElementById("openpopoverHk").onkeypress=function(){return!1};document.getElementById("openpopoverHk").addEventListener("keyup",function(a){fixhk("openpopoverHk",a)});document.getElementById("openpopoverHk").addEventListener("blur",function(a){fixhk("openpopoverHk",
a)});document.getElementById("openpopoverHk").addEventListener("keydown",function(a){capturehk("openpopoverHk",a)});document.getElementById("launchaccountsettings").onclick=function(){openaccountsettings();return!1};document.getElementById("getbinary3").onclick=function(){getbinary();return!1};document.getElementById("language").onclick=function(){return g_ischrome?(showChromeLanguageError(),!1):!0};document.getElementById("helptranslate").addEventListener("click",function(){openhelptranslate();return!1});
document.getElementById("save").addEventListener("click",function(){dosave();return!1});document.getElementById("default").addEventListener("click",function(){dodefault();return!1});document.getElementById("cancel").addEventListener("click",function(){docancel();return!1});document.getElementById("notifications_help").addEventListener("click",function(){openhelp("notifications");return!1});document.getElementById("hotkeys_help").addEventListener("click",function(){openhelp("hotkeys");return!1});document.getElementById("general_help").addEventListener("click",
function(){openhelp("security");return!1});document.getElementById("general2_help").addEventListener("click",function(){openhelp("general");return!1});document.getElementById("general3_help").addEventListener("click",function(){openhelp("appearance");return!1});document.getElementById("general4_help").addEventListener("click",function(){openhelp("formfill");return!1});document.getElementById("advanced_help").addEventListener("click",function(){openhelp("advanced");return!1})});
g_ismaxthon&&(document.getElementById("openpref").options[2]=null);is_in_dialog()&&(document.getElementById("body").style.padding="10px 0px");
