var PreferencesDialog=function(h){Dialog.call(this,h,{additionalHeaderClasses:"icon",title:Strings.translateString("Preferences"),closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.hotkeyFields={}};PreferencesDialog.prototype=Object.create(Dialog.prototype);PreferencesDialog.prototype.constructor=PreferencesDialog;
(function(){var h={usepopupfill:!0,enablenamedpipes:!0,language:!0},n=function(a){var b=[];a.ctrlKey&&b.push("control");a.metaKey&&b.push("meta");a.altKey&&b.push("alt");a.shiftKey&&b.push("shift");if(b.length>a.shiftKey)switch(a.which){case 16:case 17:case 18:case 91:case 92:break;default:this.setValue(a.which,b.join(" "))}switch(a.which){case 8:case 46:this.clear();break;case 9:break;default:a.preventDefault(),a.stopPropagation()}},j=function(a,b){DialogInput.Input.apply(this,arguments);this.keyCode=
0;this.mods="";var c=this;c.input.bind("keydown",function(a){n.call(c,a)})};j.prototype=Object.create(DialogInput.Input.prototype);j.prototype.constructor=j;var k=null,l=null;j.prototype.setValue=function(a,b){var c="";if(b&&a){var c=b.split(" "),d;null===l&&(l={control:Strings.translateString("Ctrl"),meta:Strings.translateString("Meta"),alt:Strings.translateString("Alt"),shift:Strings.translateString("Shift")});d=l;for(var g=0,e=c.length;g<e;++g)c[g]=d[c[g]];null===k&&(k={33:Strings.translateString("Page Up"),
34:Strings.translateString("Page Down"),35:Strings.translateString("End"),36:Strings.translateString("Home"),37:Strings.translateString("Left"),38:Strings.translateString("Up"),39:Strings.translateString("Right"),40:Strings.translateString("Down"),189:"-",219:"[",220:"\\",221:"]",186:";",222:"'",188:",",187:"+",190:".",191:"/",106:"*",192:"~",124:Strings.translateString("Print Screen")});d=k;void 0!==d[a]?c.push(d[a]):c.push(String.fromCharCode(a).toUpperCase());c=c.join("+");this.keyCode=a;this.mods=
b}else this.keyCode=0,this.mods="";DialogInput.Input.prototype.setValue.call(this,c)};var e=function(a,b){DialogInput.Input.apply(this,arguments);this.checkboxField=$("#"+this.input.attr("checkboxField"));var c=this,d=null;void 0===c.checkboxField.attr(Dialog.prototype.DIALOG_FIELD)&&(c.checkboxField.bind("change",function(){c.checkboxField.prop("checked")?null!==d&&(c.setValue(d),d=null):(d=c.getValue(),c.setValue(""))}),c.onChange(function(a){c.checkboxField.prop("checked",0<a?!0:!1)}))};e.prototype=
Object.create(DialogInput.Input.prototype);e.prototype.constructor=e;e.prototype.enable=function(){DialogInput.Input.prototype.enable.apply(this,arguments);this.checkboxField.prop("disabled",!1)};e.prototype.disable=function(){DialogInput.Input.prototype.disable.apply(this,arguments);this.checkboxField.prop("disabled",!0)};e.prototype.addError=function(a,b){this._errors.push(b);if(!this._errorElement){var c={collection:this.input.parent().children(),dialog:a};this._errorElement=LPTools.buildErrorElement(c)}LPTools.buildErrorMessage(this._errorElement,
this._errors)};e.prototype.setValue=function(a){("number"!==typeof a||0<a)&&DialogInput.Input.prototype.setValue.apply(this,arguments)};e.prototype.validate=function(a,b,c){return c&&(c=parseInt(c),isNaN(c)||0>c)?(a.addError(b,Strings.translateString("Value must be greater than or equal to %1.",0)),!1):!0};var p=function(){for(var a=LPProxy.getFormFillModels(),b=[{value:0,label:""}],c=0,d=a.length;c<d;++c){var e=a[c];b.push({value:e.getID(),label:e.getName()})}return b},q=function(){var a=[],b;for(b in bg.g_langs)a.push({value:b,
label:bg.g_langs[b]});return a};PreferencesDialog.prototype.setupButtons=function(a){Dialog.prototype.setupButtons.apply(this,arguments);this.resetDefaultsButton=$(LPTools.createElement("button","nbtn btn_midi wbtn dynamicWidth leftButton"));this.resetDefaultsButton.bind("click",this.createHandler(this.resetDefaults));this.buttonContainer.prepend(this.resetDefaultsButton)};PreferencesDialog.prototype.resetDefaults=function(){for(var a=this.currentViewElement.find("["+this.DIALOG_FIELD+"]"),b={},c=
0,d=a.length;c<d;++c)b[a[c].getAttribute(this.DIALOG_FIELD)]=!0;this.populateFields(bg.Preferences.getDefault(b))};PreferencesDialog.prototype.leftMenuChange=function(a){this.resetDefaultsButton.text(Strings.translateString("Restore '%1' Defaults",a.text()))};PreferencesDialog.prototype.getHotKeyPreferenceNames=function(){var a={},b;for(b in this.hotkeyFields)a[b+"KeyCode"]=!0,a[b+"Mods"]=!0;return a};PreferencesDialog.prototype.getData=function(){var a=Dialog.prototype.getData.apply(this,arguments),
b;for(b in this.hotkeyFields){var c=this.hotkeyFields[b];a[b+"KeyCode"]=c.keyCode;a[b+"Mods"]=c.mods}return a};PreferencesDialog.prototype.defaultFields=function(a){a.defaultData=$.extend(a.defaultData,bg.Preferences.get(DialogInput.getProperties(this.inputFields)));this.inputFields.defaultffid.setOptions(p());this.inputFields.language.setOptions(q());Dialog.prototype.defaultFields.apply(this,arguments);var b=bg.Preferences.get(this.getHotKeyPreferenceNames()),c;for(c in this.hotkeyFields)this.hotkeyFields[c].setValue(b[c+
"KeyCode"],b[c+"Mods"]);-1<bg.g_prefoverrides.logoffclosebrowser?(this.inputFields.logoffWhenCloseBrowserVal.setValue(bg.g_prefoverrides.logoffclosebrowser),this.inputFields.logoffWhenCloseBrowserVal.disable()):this.inputFields.logoffWhenCloseBrowserVal.enable();-1<bg.g_prefoverrides.logoffidle?(this.inputFields.idleLogoffVal.setValue(bg.g_prefoverrides.logoffidle),this.inputFields.idleLogoffVal.disable()):this.inputFields.idleLogoffVal.enable();bg.g_flags.pollIntervalSetByPolicy?this.inputFields.pollServerVal.disable():
this.inputFields.pollServerVal.enable()};PreferencesDialog.prototype.clearFields=function(){Dialog.prototype.clearFields.apply(this,arguments);for(var a in this.hotkeyFields)this.hotkeyFields[a].clear()};var r=function(a){return function(){var b=a.getValue();b&&(a.clear(),LPTools.requireBinary(function(){a.setValue(b)}))}};PreferencesDialog.prototype.initialize=function(a){this.initializeInputFields(a.find("input[checkboxField]"),function(a,b){return new e(a,b)});Dialog.prototype.initialize.apply(this,
arguments);for(var b=a.find("input[hotkeyField]"),c=0,d=b.length;c<d;++c){var g=b[c],h=g.getAttribute("hotkeyField");this.hotkeyFields[h]=new j(g,this)}var b=LPPlatform.getUnavailablePreferences(),f;for(f in b)b[f]&&(a.find("input["+this.DIALOG_FIELD+"="+f+"]").closest("tr").detach(),a.find("select["+this.DIALOG_FIELD+"="+f+"]").closest("tr").detach(),a.find("input[hotkeyField="+f+"]").closest("tr").detach());b=LPPlatform.getPreferencesRequiringBinary();for(f in b)b[f]&&(c=this.inputFields[f])&&c.input.bind("change",
r(c));bg.g_hidelogoffprefs&&$("#securityPrefs").remove();bg.g_hideappearancebox&&$("#appearancePrefs").remove();bg.g_hidehelptranslate&&$("#helpTranslateButton").remove();bg.g_issafari?$("#iconMenuItem").LP_hide():$("#helpTranslateButton").bind("click",function(){bg.openURL(bg.base_url+"translate.php")})};PreferencesDialog.prototype.validate=function(a){var b=Dialog.prototype.validate.apply(this,arguments);a.autoautoVal&&10>a.autoautoVal&&(this.addError("autoautoVal",Strings.translateString("Value must be greater than or equal to %1.",
10)),b=!1);a.pollServerVal&&5>a.pollServerVal&&(this.addError("pollServerVal",Strings.translateString("Value must be greater than or equal to %1.",5)),b=!1);return b};PreferencesDialog.prototype.checkForRestartOrLogoff=function(a,b){for(var c in h)if(a[c]!==this.originalData[c]){dialogs.alert.open({title:Strings.translateString("Restart Required"),text:Strings.translateString("You must restart your browser before all of the changes will take effect."),handler:b,closeHandler:b});return}(this.originalData.logoffWhenCloseBrowser&&
0===this.originalData.logoffWhenCloseBrowserVal)!==(a.logoffWhenCloseBrowser&&0===a.logoffWhenCloseBrowserVal)?dialogs.alert.open({title:Strings.translateString("Logoff Required"),text:Strings.translateString("You must restart Chrome or logoff and back in to get 'Logoff on Browser Close' changes to take effect."),handler:b,closeHandler:b}):b()};var m=function(a){var b=this.getChanges(a);this.checkForRestartOrLogoff(a,this.createHandler(function(){bg.Preferences.set(b);LPPlatform.handlePreferenceChanges(b);
this.close(!0)}))};PreferencesDialog.prototype.handleSubmit=function(a){(a.logoffWhenCloseBrowser||a.idleLogoffEnabled)&&(bg.Preferences.get("rememberpassword")||bg.g_master_password_saved)?dialogs.confirmation.open({title:Strings.translateString("Remember Password"),text:Strings.translateString("You currently have LastPass set to remember your password.  Doing so essentially makes the automatically log out options you've chosen useless.  Would you like LastPass to stop remembering your password?"),
handler:this.createHandler(function(){bg.Preferences.set("rememberpassword",!1);bg.deletesavedpw(bg.g_username);m.call(this,a)}),closeHandler:this.createHandler(m,a)}):m.call(this,a)}})();
