LPServer.sharing=LPServer.sharing||{};
LPServer.sharing.individual=function(){var w={noemailspecified:function(a,b){b.error(LPServer.ext.translate("Please enter at least one email and try again."))},usernameisnotvalidemail:function(a,b){var c=LPServer.getRecordsFromResponse(a,"email",LPServer.getAttrInt(a,"numinvalid",0));b.error(LPServer.ext.translate("The following emails are invalid: %1",c.join(", ")))},toomanyemails:function(a,b){var c=LPServer.getAttrInt(a,"numexcess");"1"===c?b.error(LPServer.ext.translate("You are trying to share with too many people.  Please remove at least %1 email and try again.",c)):
b.error(LPServer.ext.translate("You are trying to share with too many people.  Please remove at least %1 emails and try again.",c))},cantsharewithself:function(a,b){b.error(LPServer.ext.translate("You can not share with yourself."))}},x=function(a,b,c){this.email=a;this.pubkey=b;this.encpass=c},t=function(a,b){this.aid=a.getAttribute("aid");this.username=LPServer.ext.decrypt(a.getAttribute("username"),b);this.password=LPServer.ext.decrypt(a.getAttribute("password"),b);this.name=LPServer.ext.decrypt(a.getAttribute("name"),
b);this.grouping=LPServer.ext.decrypt(a.getAttribute("grouping"),b);this.extra=LPServer.ext.decrypt(a.getAttribute("extra"),b);this.attachkey=LPServer.ext.decrypt(a.getAttribute("attachkey"),b);this.afids=this.parseFields(a.getAttribute("afids"),b);this.otherafids=this.parseFields(a.getAttribute("otherafids"),b);this.accts_notes=this.parseFields(a.getAttribute("accts_notes"),b);this.accts_usernames=this.parseFields(a.getAttribute("accts_usernames"),b);this.accts_passwords=this.parseFields(a.getAttribute("accts_passwords"),
b)};t.prototype.parseFields=function(a,b){var c=[];if(a){a=a.split("^");for(var d=0,f=a.length;d<f;++d){var e=a[d];""!==e&&(e=a[d].split("&"),c.push({name:e[0],value:LPServer.ext.decrypt(e[1],b)}))}}return c};var j=function(a,b){return a?LPServer.ext.encryptCBC(a,b):""},q=function(a,b){for(var c=JSON.parse(JSON.stringify(a)),d=0,f=c.length;d<f;++d)c[d].value=j(c[d].value,b);return c};t.prototype.encrypt=function(a){return{username:j(this.username,a),password:j(this.password,a),name:j(this.name,a),
grouping:j(this.grouping,a),extra:j(this.extra,a),attachkey:j(this.attachkey,a),afids:q(this.afids,a),otherafids:q(this.otherafids,a),accts_notes:q(this.accts_notes,a),accts_usernames:q(this.accts_usernames,a),accts_passwords:q(this.accts_passwords,a)}};var r=function(a,b,c,d){for(var f=0,e=c.length;f<e;++f)a[b+d+f+"name"]=c[f].name,a[b+d+f+"value"]=c[f].value;a[b+"num"+d]=c.length},y=function(a,b){var c=LPServer.getAttrInt(a,"numemails",0);1===c?b.success(LPServer.ext.translate("Share sent to %1.",
LPServer.getAttr(a,"email0",""))):b.success(LPServer.ext.translate("Share sent to %1 recipients.",c))},s=function(a,b){for(var c=[],d=0,f=a.length;d<f;++d){var e=a[d];e&&c.push({email:e,reason:b})}return c},z=function(a,b){var c=LPServer.getAttrInt(a,"numsharesok",0);if(0<c){for(var d=[],f=0;f<c;++f){var e=LPServer.getAttr(a,"emailok"+f,""),h=LPServer.getAttr(a,"emailokpubkeyhex"+f,""),g=LPServer.getAttr(a,"emailencp"+f,"");d.push(new x(e,h,g))}for(var e=b.params.key,f=[],h=LPServer.getNodes(a,"encdata"),
g=0,j=h.length;g<j;++g)f.push(new t(h[g],e));e={cmd:"share",sharemessage:"",giveshare:b.params.giveshare?1:0,numemails:d.length,numaids:f.length,fromrole:0,sharesyncpush:0,shareautopull:0,reportname:[]};h=0;for(g=d.length;h<g;++h){var n=d[h],j=LPServer.ext.createRandomHexString(64),j=LPServer.ext.hex2bin(j),k=new LPServer.ext.RSAKey;LPServer.ext.parsePublicKey(k,n.pubkey);var p=k.encrypt(j),k="email"+h;e[k]=n.email;e["sharekeyenchex"+h]=p;e["sharekeyenchexsig"+h]="";n.encpass&&(e["encpass"+h]=n.encpass);
for(n=0;n<f.length;++n){var p=f[n],m=p.encrypt(j);1==b.params.logname&&e.reportname.push({aid:p.aid,name:p.name});var l=k+"aid"+n;e[l]=p.aid;e[l+"username"]=m.username;e[l+"password"]=m.password;e[l+"name"]=m.name;e[l+"grouping"]=m.grouping;e[l+"extra"]=m.extra;e[l+"attachkey"]=m.attachkey;r(e,l,m.afids,"afid");r(e,l,m.otherafids,"otherafid");r(e,l,m.accts_notes,"accts_notes");r(e,l,m.accts_usernames,"accts_usernames");r(e,l,m.accts_passwords,"accts_passwords")}}LPServer.xmlRequest({url:"showshare.php",
data:e,callbacks:{shareok:y},userSupplied:b})}d=LPServer.getAttrInt(a,"numsharesdne",0);0<d&&b.callbacks&&b.callbacks.invite&&b.callbacks.invite({emails:LPServer.getRecordsFromResponse(a,"emaildne",d)});g=LPServer.getAttr(a,"sharingwithself","");d=LPServer.getAttrInt(a,"numsharesinv",0);f=LPServer.getAttrInt(a,"numsharesuns",0);e=LPServer.getAttrInt(a,"numsharesspa",0);h=LPServer.getAttrInt(a,"numsharesres",0);if((g||0<d||0<f||0<e||0<h)&&b.callbacks&&b.callbacks.problems)g=s([g],LPServer.ext.translate("You can not share with yourself.")),
g=g.concat(s(LPServer.getRecordsFromResponse(a,"emailinv",d),LPServer.ext.translate("Invalid email address."))),g=g.concat(s(LPServer.getRecordsFromResponse(a,"emailuns",f),LPServer.ext.translate("The user must login to LastPass at least once to permit sharing."))),g=g.concat(s(LPServer.getRecordsFromResponse(a,"emailspa",e),LPServer.ext.translate("The user does not want to receive emails from LastPass."))),g=g.concat(s(LPServer.getRecordsFromResponse(a,"emailres",h),LPServer.ext.translate("Sharing is restricted by a LastPass Enterprise policy."))),
b.callbacks.problems(g);0===c&&b.error()},A=function(a,b){b.success(LPServer.ext.translate("Share revoked from %1",b.params.email))},B=function(a,b){b.success(LPServer.ext.translate("Share accepted."))},k=function(a,b,c){return(a=LPServer.ext.decrypt(a,b))?LPServer.ext.encryptCBC(a,c):""},u=function(a){var b=a.params.key,c=a.params.pendingShareKey,d=a.params.pendingShare,f={cmd:"acceptshare",msgtosharer:"",aid:d.id,newgroup:LPServer.ext.encryptCBC(a.params.group,b),name:k(d.sharename,c,b),grouping:k(d.sharegroup,
c,b),username:k(d.username,c,b),password:k(d.password,c,b),extra:k(d.extra,c,b),attachkey:k(d.attachkey,c,b)};f.newname=a.params.name?LPServer.ext.encryptCBC(a.params.name,b):f.name;var e=d.save_all?"otherafid":"afid",h;for(h in d.shareafids){var g=d.shareafids[h];g&&(g=k(g,c,b));f[e+h]=g}LPServer.xmlRequest({url:"showacceptshare.php",data:f,callbacks:{acceptshareok:B},userSupplied:a})},C=function(a,b){b.success(LPServer.ext.translate("Share rejected."))},D=function(a,b){if(b.callbacks&&b.callbacks.problems){var c=
[],d=LPServer.getAttrInt(a,"numalready",0);0<d&&(d=LPServer.getRecordsFromResponse(a,"emailalready",d).join(", "),c.push(LPServer.ext.translate("You have already invited the following friends: %1. Please send them a reminder using your personal email as the email invitation sent by LastPass might not have reached them.",d)));d=LPServer.getAttrInt(a,"numspam",0);0<d&&(d=LPServer.getRecordsFromResponse(a,"emailspam",d).join(", "),c.push(LPServer.ext.translate("The following friends have marked your invitations as spam: %1.",
d)));0<c.length&&b.callbacks.problems(c)}c=LPServer.getAttrInt(a,"numsent",0);1===c?b.success(LPServer.ext.translate("%1 was invited. We will send you a notification email when they join LastPass so you can retry sharing your data with them.",LPServer.getAttr(a,"emailsent0",""))):1<c?b.success(LPServer.ext.translate("%1 friends were invited. We will send you a notification email when any of them join LastPass so you can retry sharing your data with them.",c)):b.error()},v=function(a){LPServer.jsonRequest({url:"getReceivedShareInfo.php",
data:a.params&&a.params.id?{aid:a.params.id}:null,userSupplied:a})};return{shareItems:function(a){a.callbacks=LPServer.extend(a.callbacks,w);for(var b={cmd:"getclientdata",shareeusername:a.params.emails,numaids:a.params.aids.length},c=0,d=a.params.aids.length;c<d;++c)b["aid"+c]=a.params.aids[c];LPServer.xmlRequest({url:"showshare.php",data:b,callbacks:{getclientdataack:z},userSupplied:a})},unshareItem:function(a){LPServer.xmlRequest({url:"showshare.php",data:{cmd:"unshare",aid:a.params.id,username:a.params.email},
callbacks:{unshareok:A},userSupplied:a})},acceptShare:function(a){a.params.pendingShare?u(a):a.params.id&&v(LPServer.extend({},a,{params:{id:a.params.id},success:function(b){a.params.pendingShare=b.pendingShare;var c=new LPServer.ext.RSAKey;LPServer.ext.parsePrivateKey(c,LPServer.ext.extractPrivateKey(b.privateKey,a.params.key));a.params.pendingShareKey=c.decrypt(a.params.pendingShare.sharekeyenchex);u(a)}}))},rejectShare:function(a){LPServer.xmlRequest({url:"showacceptshare.php",data:{cmd:"rejectshare",
aid:a.params.id},callbacks:{rejectshareok:C},userSupplied:a})},inviteFriends:function(a){for(var b={cmd:"invite",numemails:a.params.emails.length},c=0,d=a.params.emails.length;c<d;++c)b["email"+c]=a.params.emails[c];LPServer.xmlRequest({url:"showshare.php",data:b,callbacks:{inviteack:D},userSupplied:a})},getSentShareData:function(a){LPServer.jsonRequest({url:"getSentShareInfo.php",data:a.params&&a.params.id?{aid:a.params.id}:null,userSupplied:a})},getReceivedShareData:v}}();
