var SettingsDialog=function(e,c){c=void 0===c?{}:c;c.closeButtonEnabled=!0;c.additionalHeaderClasses=void 0===c.additionalHeaderClasses?[]:c.additionalHeaderClasses;c.additionalHeaderClasses.push("leftIcon");Dialog.call(this,e,c)};SettingsDialog.prototype=Object.create(Dialog.prototype);SettingsDialog.prototype.constructor=SettingsDialog;
(function(e){var c={},d={},b=null,a=null,l=function(d){return function(e){a!==e.target&&(b.menu.hide(),b.content.hide(),a.removeAttribute("class"),b=c[d],a=e.target,b.menu.show(),b.content.show(),a.setAttribute("class","selected"))}},r=function(a){return function(c){b.content!==a&&(b.content.hide(),b.menuItem.removeAttribute("class"),b.content=a,b.menuItem=c.target,b.content.show(),b.menuItem.setAttribute("class","selected"))}};SettingsDialog.prototype.setup=function(a,b,c){Dialog.prototype.setup.apply(this,
arguments);for(var e=d.paymentHistory.children[0].children[0],f=e.children[0].nextElementSibling;f;){var h=f.nextElementSibling;e.removeChild(f);f=h}b.addPaymentHistoryRows(e)};SettingsDialog.prototype.initialize=function(p){Dialog.prototype.initialize.apply(this,arguments);$("table").each(function(){for(var a=$(this).find("tr"),b=0,c=a.length;b<c;++b)0!==b%2&&a[b].setAttribute("class","odd")});p.children[0].appendChild(p.children[1].children[0]);for(var j=e.getElementById("settingsContent"),g=0,
m=j.children.length;g<m;++g){var f=j.children[g];d[f.getAttribute("settingGroup")]=f}j=e.getElementById("settingsLeftMenu");g=0;for(m=j.children.length;g<m;++g){var f=j.children[g],h={};h.menu=$(f);for(var k=0;k<f.children.length;++k){var n=f.children[k],q=$(d[n.getAttribute("settingGroup")]);0===k&&(n.setAttribute("class","selected"),h.menuItem=n,h.content=q);LPPlatform.addEventListener(n,"click",r(q))}c[f.getAttribute("settingGroup")]=h}j=p.children[0].children[1];g=0;for(m=j.children.length;g<
m;++g)f=j.children[g],h=f.getAttribute("settingGroup"),0===g&&(b=c[h],b.menu.show(),b.content.show(),a=f,a.setAttribute("class","selected")),LPPlatform.addEventListener(f,"click",l(h))};SettingsDialog.prototype.initializeDataBindings=function(){for(var a=e.getElementById("settingsContent"),b=0,c=a.children.length;b<c;++b){var d=$(a.children[b]),f=d.attr("settingGroup"),d=d.find("["+this.DIALOG_FIELD+"]"),h=new DialogInput.NestedFields;this._inputFields[f]=h;for(f=0;f<d.length;++f){var k=d[f];h[k.getAttribute(this.DIALOG_FIELD)]=
new DialogInput.Input(k)}}}})(document);var PaymentHistory=function(e){this.data=e};
PaymentHistory.prototype.template=function(){var e=[],c;for(c in this.data){var d=this.data[c],b=document.createElement("tr"),a=document.createElement("td");a.textContent=d.timecreated;b.appendChild(a);a=document.createElement("td");a.textContent=d.product;b.appendChild(a);a=document.createElement("td");a.textContent=d.paymentprovider;b.appendChild(a);a=document.createElement("td");a.textContent=d.orderid;b.appendChild(a);a=document.createElement("td");a.textContent=d.unitcost;b.appendChild(a);a=
document.createElement("td");a.textContent=d.quantity;b.appendChild(a);a=document.createElement("td");a.textContent=d.duration;b.appendChild(a);a=document.createElement("td");a.textContent="$"+d.unitcost*d.quantity+" "+d.currency;b.appendChild(a);a=document.createElement("td");a.textContent="Refund";b.appendChild(a);e.push(b)}return e};var AccountSettings=function(e){this.data=e;void 0!==this.data.paymentHistory&&(this.data.paymentHistory=new PaymentHistory(this.data.paymentHistory))};
AccountSettings.prototype.getFormData=function(){var e={},c;for(c in this.data){var d=this.data[c],b={},a;for(a in d){var l=d[a];b[a]=null!==l&&"object"===typeof l?l.value:l}e[c]=b}return e};var appendChildren=function(e,c){for(var d=0,b=c.length;d<b;++d)e.appendChild(c[d])};AccountSettings.prototype.addPaymentHistoryRows=function(e){var c=document.createElement("tbody");appendChildren(c,this.data.paymentHistory.template());appendChildren(e,c.children)};
AccountSettingsService=function(e){var c=LPProxy.getBaseURL()+"getAccountSettings.php";return{call:function(d,b){e.ajax({url:c,success:function(a){a=new AccountSettings(JSON.parse(a));d(a)},error:b})}}}($);
