var SharedFolderAccessDialog=function(c){ContainerSelectionDialog.call(this,c);this.rightHeaderText=this.rightHeader=this.leftHeaderText=this.leftHeader=this.selectedAids=this.member=null};SharedFolderAccessDialog.prototype=Object.create(ContainerSelectionDialog.prototype);SharedFolderAccessDialog.prototype.constructor=SharedFolderAccessDialog;
(function(){SharedFolderAccessDialog.prototype.initialize=function(b){ContainerSelectionDialog.prototype.initialize.apply(this,arguments);this.leftHeader=b.find(".identityLeft .header");this.leftHeaderText=this.leftHeader.text();this.leftPlaceHolder=b.find(".availableSearch");this.leftPlaceHolderText=this.leftPlaceHolder.attr("placeholder");this.rightHeader=b.find(".identityRight .header");this.rightHeaderText=this.rightHeader.text();this.rightPlaceHolder=b.find(".selectedSearch");this.rightPlaceHolderText=
this.rightPlaceHolder.attr("placeholder");this.otherMembersElement=$("#sharedFolderAccessOtherUsers");var a=this;a.inputFields.hidebydefault.onChange(function(b){b?(a.leftHeader.text(a.rightHeaderText),a.leftPlaceHolder.attr("placeholder",a.rightPlaceHolderText),a.rightHeader.text(a.leftHeaderText),a.rightPlaceHolder.attr("placeholder",a.leftPlaceHolderText)):(a.leftHeader.text(a.leftHeaderText),a.leftPlaceHolder.attr("placeholder",a.leftPlaceHolderText),a.rightHeader.text(a.rightHeaderText),a.rightPlaceHolder.attr("placeholder",
a.rightPlaceHolderText))});a.inputFields.applyToOthers.onChange(function(b){b?a.otherMembersElement.show():a.otherMembersElement.hide()})};SharedFolderAccessDialog.prototype.setup=function(){ContainerSelectionDialog.prototype.setup.apply(this,arguments);for(var b=[],a=dialogs.sharedFolder.getDialog().containers.existingMembers.getItemChildren(),f=0,d=a.length;f<d;++f){var e=a[f];e!==this.member&&b.push(new SharedFolderAccessCheckbox(e))}0<b.length&&(this.containers.otherMembers=new Container(b,{allowDrag:!1,
searchInput:"sharedFolderAccessOtherUsersSearch",publishSelect:!1}),this.containers.otherMembers.initialize(document.getElementById("sharedFolderAccessOtherUsersContainer")))};SharedFolderAccessDialog.prototype.open=function(b,a){if(void 0===a){var f=this;LPRequest.makeDataRequest(LPProxy.getSharedFolderRestrictions,{parameters:b,success:function(a){f.open(b,a)}})}else{var d=a.aids;this.member=b;for(var e={},g=0,c=d.length;g<c;++g)e[d[g]]=!0;this.selectedAids=e;if(this.member._sharedGroup.isDownloaded())if(this.availableAids=
{},d=LPProxy.getItemsByShareID(this.member._sharedGroup.getID()),0===d.length)dialogs.alert.open({title:Strings.translateString("Edit Access"),text:Strings.translateString("Please add items to this folder before editing a member's access.")});else{e=0;for(g=d.length;e<g;++e)c=d[e].getID(),void 0===this.selectedAids[c]&&(this.availableAids[c]=!0);ContainerSelectionDialog.prototype.open.apply(this,[{title:"Edit Access: "+b.toString(),defaultData:{hidebydefault:"1"===a.hidebydefault}}])}else{var h=this.member._sharedGroup;
dialogs.confirmation.open({title:Strings.translateString("Error"),text:Strings.translateString("Folder must be downloaded in order to edit a member's access. Would you like to download now?"),handler:function(){h._sharedFolderItem.startDownloading();Dialog.prototype.closeAllDialogs()}})}}};var c=function(b){b={filter:b};b=LPProxy.getSites(b).concat(LPProxy.getNotes(b));return LPProxy.assignItemsToGroups(b,!1)};SharedFolderAccessDialog.prototype.getAvailableItems=function(){return c(this.availableAids)};
SharedFolderAccessDialog.prototype.getSelectedItems=function(){return c(this.selectedAids)};var h=function(b){for(var a=[],c=0,d=b.length;c<d;++c)a.push(b[c].getID());return a.join(",")};SharedFolderAccessDialog.prototype.getData=function(b){var a=ContainerSelectionDialog.prototype.getData.apply(this,arguments);a.aids="";this.containers.selected&&(a.aids=h(this.containers.selected.getItemModelChildren()));a.additionaluids="";a.applyToOthers&&this.containers.otherMembers&&(a.additionaluids=h(this.containers.otherMembers.getSelectedModelItems()));
return a};SharedFolderAccessDialog.prototype.handleSubmit=function(b){LPRequest.makeRequest(LPProxy.updateSharedFolderRestrictions,{parameters:[this.member,b],success:function(){Topics.get(Topics.SUCCESS).publish("Access restrictions updated.")}})}})();
