var ShareDialog=function(e){Dialog.call(this,e,{nextButtonText:"Share",buttonAlign:this.RIGHT_ALIGN});this.dataContainer=this.recipients=this.friends=this.existingShares=this.items=null;this.existingItems={};var a=this;a.shareItemOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE)]},getItemButtonActions:function(){return[Constants.ACTION_EDIT,Constants.ACTION_REMOVE]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){delete a.existingItems[this._model.getID()];
this.destruct()}}};ShareDialog.prototype=Object.create(Dialog.prototype);ShareDialog.prototype.constructor=ShareDialog;
(function(e){ShareDialog.prototype.open=function(a,b,f){this.existingShares=b;this.friends=f;this.items=a;this.recipients=null;Dialog.prototype.open.call(this,{title:1===this.getItemCount()?"Share "+a[0].toString():"Share an Item"})};ShareDialog.prototype.getItemCount=function(){return this.items?this.items.length:0};ShareDialog.prototype.initialize=function(){Dialog.prototype.initialize.apply(this,arguments);var a=this;Topics.get(Topics.REMOVED_SHARED_FOLDER_USER).subscribe(function(b){a.recipients&&
delete a.recipients[b.getID()]});a.inputFields.itemSearch=new VaultItemTypeahead(document.getElementById("shareDialogItems"),{sourceFunction:function(){var a=LPProxy.getSites().concat(LPProxy.getNotes()).concat(LPProxy.getApplications());return LPProxy.assignItemsToGroups(a)},filter:function(b){return!a.existingItems[b._model.getID()]&&!b.isExcludedAction(Constants.ACTION_SHARE)}});a.inputFields.itemSearch.onChange(function(b){a.addItem(b)})};ShareDialog.prototype.addItem=function(a){if(a){var b=
LPProxy.getSite(a);null===b&&(b=LPProxy.getNote(a));this.containers.shareItem.addChild(b);this.existingItems[a]=!0;this.inputFields.itemSearch.clear();this.inputFields.itemSearch.focus()}};ShareDialog.prototype.setup=function(a,b){this.existingShares&&0<this.existingShares.length?(this.containers.share=new IndividualShareContainer(this.existingShares,{minimized:!0,additionalGroupClasses:"dialogItemGroup",excludeActions:[Constants.ACTION_EDIT,Constants.ACTION_SHARE]}),this.containers.share.initialize(e.getElementById("shareDialogExistingShares")),
this.$element.removeClass("noShares")):this.$element.addClass("noShares");1===this.getItemCount()&&this.items[0]instanceof Note?$("#shareDialogPermissionContainer").hide():$("#shareDialogPermissionContainer").show();(function(a){LPProxy.isEnterpriseUser()?(a.recipients={},a.inputFields.inviteInput=new BloodhoundDropdown(document.getElementById("shareDialogEmails"),{local:this.friends,identify:function(a){return a.email},remote:{url:LPProxy.getBaseURL()+"typeahead_remote.php?q=%QUERY",wildcard:"%QUERY"}},
{optionLabel:function(a){return(new ShareRecipient(a)).getLabel()},ignore:function(b){return a.recipients[b]}},{autoCompleteBlurs:!1}),a.inputFields.inviteInput.onChange(function(b){b=new ShareRecipient(b);a.recipients[b.getID()]=!0;a.addRecipient(b)})):(a.inputFields.inviteInput=new TypeaheadDropdown(document.getElementById("shareDialogEmails"),null,{autoCompleteBlurs:!1}),a.inputFields.inviteInput.setValues(a.friends),a.inputFields.inviteInput.onChange(function(b){b&&a.addRecipient(new ShareRecipient({email:b}))}));
a.inputFields.inviteInput.autocomplete=function(b){var c=b.target.value;if(null===this.hint&&c){for(var c=a.parseRecipientInput(c),d=0,e=c.length;d<e;++d)a.addRecipient(c[d]);b.preventDefault()}TypeaheadDropdown.prototype.autocomplete.apply(this,arguments)};if(1===a.getItemCount())a.$element.addClass("site");else if(a.$element.removeClass("site"),a.containers.shareItem=new Container([],{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem",allowDrag:!1,override:function(){return a.shareItemOverrides},
publishSelect:!1}),a.containers.shareItem.initialize(e.getElementById("shareItemsContainer")),0<a.getItemCount())for(var b=0,c=a.items.length;b<c;++b)a.addItem(a.items[b].getID())})(this);Dialog.prototype.setup.apply(this,arguments)};ShareDialog.prototype.close=function(){Dialog.prototype.close.apply(this,arguments)&&(this.existingItems={})};ShareDialog.prototype.parseRecipientInput=function(a){if(null===a)throw Error("Argument can not be null.");return(a=a.match(Constants.EmailAddressRegularExpression))?
a.map(function(a){a=new ShareRecipient({email:a});a.setEditable(!0);return a}):[]};ShareDialog.prototype.addRecipient=function(a){this.containers.recipients||(this.containers.recipients=new Container([],{additionalItemClasses:"dialogItem"}),this.containers.recipients.initialize(document.getElementById("shareDialogRecipients")));this.containers.recipients.addChild(a);this.inputFields.inviteInput.clear();this.inputFields.inviteInput.focus()};ShareDialog.prototype.getData=function(){var a=Dialog.prototype.getData.apply(this,
arguments),b=[];this.containers.recipients&&(b=this.containers.recipients.getItemChildren());a.inviteInput&&(b=b.concat(this.parseRecipientInput(a.inviteInput)));for(var f=[],d=0,c=b.length;d<c;++d)f.push(b[d].getEmail());a.emails=f.join(",");if(1===this.getItemCount())a.aids=[this.items[0].getID()];else{for(var b=a,f=this.containers.shareItem.getItemModelChildren(),d=[],c=0,e=f.length;c<e;++c)d.push(f[c].getID());b.aids=d}return a};ShareDialog.prototype.validate=function(a){var b=Dialog.prototype.validate.apply(this,
arguments);""===a.emails&&(this.addError("inviteInput","You must enter at least one recipient email address."),b=!1);if(!a.aids||0===a.aids.length)this.addError("itemSearch","You must select at least one item to share."),b=!1;return b};ShareDialog.prototype.handleSubmit=function(a){LPRequest.makeUpdateRequest(LPProxy.shareItems,{params:a})}})(document);
