var SharedFolderDialog=function(g){Dialog.call(this,g,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.folder=this.existingUsers=null};SharedFolderDialog.prototype=Object.create(Dialog.prototype);SharedFolderDialog.prototype.constructor=SharedFolderDialog;
(function(g){SharedFolderDialog.prototype.initialize=function(a){Dialog.prototype.initialize.apply(this,arguments);var b=this,d=document.getElementById("sharedFolderDialogUserTypeahead");LPProxy.isEnterpriseUser()?(d=new BloodhoundDropdown(d,{identify:function(b){return"group"===b.type?b.cgid:b.uid},remote:{url:LPProxy.getBaseURL()+"typeahead_remote.php?grp=1&q=%QUERY",wildcard:"%QUERY"}},{optionLabel:function(b){var c=b.name;"companyuser"===b.type?""===c?c=b.email:""!==b.email&&(c+=" ("+b.email+
")"):c+=" ("+Strings.Vault.USER_GROUP+")";return c},ignore:function(a,c){return b.existingUsers[a]||void 0===c.type&&!LPFeatures.allowShareOutsideEnterprise()}}),d.onChange(function(a,c){a=$.extend({},a);var d=SharedFolderUser;"group"===a.type&&(a.uid=a.cgid,delete a.cgid,d=SharedFolderUserGroup);a.username=a.email;delete a.email;d=new d(a,b.folder);d._pending=!0;b.addNewUser(d);b.existingUsers[c]=!0}),b.inputFields.friends=d.inputObject):b.inputFields.friends=new TypeaheadDropdown(d);b.inputFields.friends.autocomplete=
function(a){var c=a.target.value;if(null===this.hint&&c){for(var c=b.parseFriendsInput(c),d=0,g=c.length;d<g;++d)b.addNewUser(c[d]);a.preventDefault()}TypeaheadDropdown.prototype.autocomplete.apply(this,arguments)};Topics.get(Topics.REMOVED_SHARED_FOLDER_USER).subscribe(function(a){delete b.existingUsers[a.getID()];b.showHideInviteInput()});$("#sharedFolderDialogInviteButton").bind("click",function(){b.submit()})};SharedFolderDialog.prototype.parseFriendsInput=function(a){var b=[];a=a.split(",");
for(var d=0,e=a.length;d<e;++d){var c=a[d].trim(),f;-1<c.indexOf("@")?(c=c.match(Constants.EmailAddressRegularExpression))&&1===c.length&&(f=new SharedFolderUser({username:c[0]},this.folder)):c&&(f=new SharedFolderUserGroup({name:c},this.folder));f&&(f._pending=!0,f.setEditable(!0),b.push(f))}return b};SharedFolderDialog.prototype.validate=function(a){var b=Dialog.prototype.validate.apply(this,arguments);a.friends&&0===this.parseFriendsInput(a.friends).length&&(this.addError("friends","You must enter a valid email or group name."),
b=!1);return b};SharedFolderDialog.prototype.defaultFields=function(a){a.defaultData=$.extend({readonly:!0,hidePasswords:!0},a.defaultData);Dialog.prototype.defaultFields.call(this,a)};SharedFolderDialog.prototype.addNewUser=function(a){this.containers.newMembers||(this.containers.newMembers=new Container([],{additionalItemClasses:"dialogItem"}),this.containers.newMembers.initialize(document.getElementById("sharedFolderDialogNewUsersContainer")));this.containers.newMembers.addChild(a);this.inputFields.friends.clear();
this.inputFields.friends.focus()};SharedFolderDialog.prototype.setup=function(a,b){Dialog.prototype.setup.apply(this,arguments);this.containers.existingMembers&&(this.containers.existingMembers.initialize(g.getElementById("folderMembers")),this.showHideInviteInput())};SharedFolderDialog.prototype.showHideInviteInput=function(){LPProxy.isEnterpriseUser()||(5<this.containers.existingMembers.getItemChildren().length?($("#sharedFolderMaxMembers").show(),$("#sharedFolderDialogInvites").hide()):($("#sharedFolderMaxMembers").hide(),
$("#sharedFolderDialogInvites").show()))};SharedFolderDialog.prototype.open=function(a){this.folder=a;var b=this;LPRequest.makeDataRequest(LPProxy.getSharedFolderMembers,{parameters:a,success:function(a){if(a instanceof Array){b.containers.existingMembers=new Container(a);b.existingUsers={};for(var e=0,c=a.length;e<c;++e)b.existingUsers[a[e].getID()]=!0}Dialog.prototype.open.call(b,{title:Strings.translateString("Manage Shared Folder")+": "+b.folder.getShareGroupName()})},error:function(){Topics.get(Topics.DIALOG_LOADED).publish()}})};
SharedFolderDialog.prototype.isModified=function(){if(""!==this.inputFields.friends.getValue()||this.containers.newMembers&&!this.containers.newMembers.isEmpty())return!0;for(var a=this.containers.existingMembers.getItemChildren(),b=0,d=a.length;b<d;++b)if(a[b].isModified())return!0;return!1};SharedFolderDialog.prototype.handleSubmit=function(a){if(""!==a.friends||this.containers.newMembers&&!this.containers.newMembers.isEmpty()){var b=this.containers.newMembers?this.containers.newMembers.getItems().slice():
[],b=b.concat(this.parseFriendsInput(a.friends));LPRequest.makeRequest(LPProxy.addSharedFolderMembers,{parameters:[this.folder,b,a],requestSuccessOptions:{closeDialog:!1},success:function(c){return function(){for(var d=0,f=b.length;d<f;++d){var e=b[d];e._pending=!1;e._data.readonly=a.readonly?"1":"0";e._data.give=!a.hidePasswords?"1":"0";e._data.can_administer=a.can_administer?"1":"0";e.rebuild()&&e._parent.removeChild(e)}c.containers.existingMembers.addChild(b);c.showHideInviteInput();c.inputFields.friends.clear();
Topics.get(Topics.SUCCESS).publish(b.length+" users/groups were invited.")}}(this)})}else{for(var d=[],e=this.containers.existingMembers.getItemChildren(),c={},f=0,g=e.length;f<g;++f){var h=e[f];if(h.isModified()){var j=h.getID(!0);c[j]=h;d.push({uid:j,give:h.getCheckboxValue("give"),readonly:h.getCheckboxValue("readonly"),canadminister:LPProxy.isEnterpriseUser()?h.getCheckboxValue("can_administer"):"0"})}}0<d.length?LPRequest.makeRequest(LPProxy.updateSharedFolderMemberPermissions,{parameters:[this.folder.getID(),
d],success:function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("Permissions saved."));for(var a=0,b=d.length;a<b;++a){var e=d[a];c[e.uid].updatePermissions(e)}}}):Topics.get(Topics.SUCCESS).publish(Strings.translateString("Permissions saved."))}}})(document);
