var data=null,existing=null,origusername=null,origpassword=null,attachnum=0,attaches=[],removedattach=[],g_eye_show=!0,g_eyeimgid=null,g_start_time=null,POLL_MAXTIME=3E5,g_pwlen=0,pass=!0,g_sharedfromaid=!1,g_pw_field_ids=[],ENABLE_ONLY=!0,g_do_keyaccel=!0,KEY_S=83,event_handlers={};
function fix_event_handlers(){lpdbg("site","fixing event handlers");for(var a in event_handlers){lpdbg("site","setting event handler for "+a);var c=document.getElementById("fields").contentWindow.document.getElementById(a);c?(c.onclick=event_handlers[a],lpdbg("site","set event handler for "+a)):lpdbg("site","could not find "+a)}}
function onLoad(a){clearData();if(a){var c=getBG(),f;c.g_site_data&&(f=c.g_site_data.aid);if("undefined"==typeof f)data=c.g_site_data;else{data=c.g_site_data;var b=!1;"undefined"!==typeof c.g_site_data.save_all&&!0==c.g_site_data.save_all&&(b=!0);a=get_record(f);for(var j in a)data[j]=a[j]}c.g_generatedpw&&(document.getElementById("pwprotect").style.visibility="hidden",document.getElementById("pwprotectlabel").style.visibility="hidden");if((existing=data&&"undefined"!=typeof get_record_id(data)&&
get_record_id(data)&&""!=get_record_id(data)&&"0"!=get_record_id(data))&&!c.LPISLOC&&c.g_showhistorylinks)document.getElementById("usernamehistory").style.display="inline",document.getElementById("passwordhistory").style.display="inline";if(data){a=issharedfolder(c.g_shares,data.group);var e=!1==a?c.g_local_key:a.sharekey;"http://sn"==data.url&&c.loglogin(get_record_id(data));a=!1;if(is_application(data)){document.getElementById("usernamehistory").style.display="none";document.getElementById("passwordhistory").style.display=
"none";set_innertext(document.getElementById("urltext"),gs("Application:"));document.getElementById("url").value=data.appname;var d=0,h=0,g;for(g in data.fields)if(data.fields.hasOwnProperty(g))if(""==data.fields[g].type){if(1<++d)break}else if("password"==data.fields[g].type&&1<++h)break;if(1!=d||1!=h)a=!0}else if(d=AES._utf8_decode(data.url),existing||!(0<=d.indexOf("homelocal")))document.getElementById("url").value=d;event_handlers={};data.editfields?(document.title=is_application(data)?gs("Edit Application Fields"):
gs("Edit Site Fields"),document.getElementById("siteactions").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("namegrouprow").style.display="none",document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("notesrow1").style.display="none",document.getElementById("notesrow2").style.display="none",document.getElementById("advsettingswrap").style.display="none",document.getElementById("cpwfieldbtn").style.display="none",
document.getElementById("fieldsrow2").style.display="block",document.getElementById("fields").contentWindow.document.body.appendChild(getFieldsHTMLNodes(e))):data.save_all||a?(document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("fieldsrow1").style.display="block",document.getElementById("fieldsrow2").style.display="block",existing?(document.title=is_application(data)?gs("Edit Application"):gs("Edit Site"),document.getElementById("fields").contentWindow.document.body.appendChild(getFieldsHTMLNodes(e))):
(document.title=gs("Add Site"),document.getElementById("fields").contentWindow.document.body.appendChild(getDataHTML()))):data.sn?(document.title=existing?gs("Edit Secure Note"):gs("Add Secure Note"),document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("addrow").style.display="block",showadvpane()):existing?(is_application(data)?(document.title=gs("Edit Application"),document.getElementById("username").value=
getusernamefromacct(data),document.getElementById("password").value=getpasswordfromacct(data),origusername=c.lpmenc(document.getElementById("username").value,!0,e),origpassword=c.lpmenc(document.getElementById("password").value,!0,e)):(document.title=gs("Edit Site"),document.getElementById("username").value=data.unencryptedUsername,g_pwlen=(a=c.lpmdec(data.password,!0,e))?a.length:-1,g_pwlen=""==data.password?0:g_pwlen,document.getElementById("password").value=a,origusername=data.username,origpassword=
data.password),document.getElementById("editfields").style.display="inline"):(document.title=gs("Add Site"),document.getElementById("username").value=data.username,document.getElementById("password").value=data.password,disable_CPWButton());fix_event_handlers();document.getElementById("exnotehist").style.display=existing?"block":"none";!existing&&("undefined"!=typeof data.addsite&&-1==AES._utf8_decode(data.url).indexOf("homelocal"))&&(document.getElementById("group").value=get_default_group(data.url),
document.getElementById("name").value=c.getname_url(data.url));existing?(document.getElementById("name").value=data.name,document.getElementById("group").value=data.group,a=c.lpmdec(data.extra,!0,e),document.getElementById("notes").value=a,document.getElementById("fav").checked="1"==data.fav,document.getElementById("pwprotect").checked=data.pwprotect,document.getElementById("autologin").checked=data.autologin&&"0"!=data.autologin,is_application(data)?document.getElementById("never_autofill_td").style.visibility=
"hidden":document.getElementById("never_autofill").checked=data.never_autofill):data.sn&&(document.getElementById("group").value=gs("Secure Notes"));1==data.sn&&(document.getElementById("favcheck").style.display="none",document.getElementById("never_autofill_td").style.display="none",document.getElementById("autologingrp").style.visibility="hidden")}existing&&!data.editfields?(document.getElementById("del").style.display="inline-block",a=get_record(get_record_id(data)),document.getElementById("share").style.display=
!c.LPISLOC&&!a.genpw&&("undefined"==typeof a.sharedfromaid||null==a.sharedfromaid||""==a.sharedfromaid||"0"==a.sharedfromaid||"null"==a.sharedfromaid)&&"undefined"==typeof a.sharefolderid&&!is_application(a)&&c.g_sharing_enabled?"inline-block":"none"):(document.getElementById("del").style.display="none",document.getElementById("share").style.display="none");a=[];for(f in c.g_sites)c.check_ident_aid(f)&&(d=c.g_sites[f].group,""!=d&&!lp_in_array(d,a)&&(a[a.length]=d));for(f in c.g_securenotes)c.check_ident_aid(f)&&
(d=c.g_securenotes[f].group,""!=d&&!lp_in_array(d,a)&&(a[a.length]=d));for(f in c.g_applications)c.check_ident_appaid(f)&&(d=c.g_applications[f].group,""!=d&&!lp_in_array(d,a)&&(a[a.length]=d));a.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});existing||(""==document.getElementById("url").value?document.getElementById("url").focus():document.getElementById("name").focus());if(!existing&&data&&!data.save_all&&!data.noreplace){d=c.getsites(lp_gettld_url(data.url),!0);f=[];for(g in d)f[f.length]=
g;f.sort(function(a,b){return c.g_sites[a].name.toLowerCase()<c.g_sites[b].name.toLowerCase()?-1:1});d=document.getElementById("replaceexistingsiteaid");for(g=0;g<f.length;g++)h=c.g_sites[f[g]].name,typeof c.g_sites[f[g]].useusername&&""!=c.g_sites[f[g]].useusername&&(h+=" ("+c.g_sites[f[g]].useusername+")"),d.options[d.options.length]=new Option(h,f[g]);if(1<d.options.length)for(g=1;4>=g;g++)document.getElementById("addreplacerow"+g).style.display="block"}LP_decimate_children(document.getElementById("metercontainer"));
document.getElementById("metercontainer").appendChild(ghetto_meter(280,!0,document));stylize_ghetto_meter(document,280);update_password_meter("",document.getElementById("password").value);data&&data.last_pwchange_gmt&&pw_age_update(data.last_pwchange_gmt);show_cpw_button(data);my_aid=get_record_id(data);buildSecureNotes(existing);onResize();create_combo("group",a,!0,document,"","group",-22,5);setup_eye_events(document);(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)&&setTimeout(function(){decryptThumbnails(e)},
0);document.getElementById("advsettings").addEventListener("click",showadvpane);document.getElementById("lp_docwrite_site14a").addEventListener("click",showadvpane);document.getElementById("fav").addEventListener("change",echoFavorite);echoFavorite();null!==document.getElementById("name")&&null!==document.getElementById("notestype")&&(document.getElementById("name").addEventListener("keyup",function(){setTimeout(updateFormHeading,100)}),updateFormHeading());data&&data.openchpw&&show_cpw_dialog("new");
data=c.g_site_data;for(j in c.g_site_data)data[j]=c.g_site_data[j];b&&(data.save_all=!0);c.g_site_data=null}else get_data("site",function(){onLoad(!0)})}
function updateFormHeading(){""!=document.getElementById("notestype").value?set_innertext(document.getElementById("dynheader"),document.getElementById("name").value+" - "+document.getElementById("notestype").value+(1==data.sn?" "+gs("Secure Note"):"")):(document.getElementById("dynheader").style.display="none",document.getElementById("dynbody").style.backgroundColor="transparent")}
function showadvpane(){var a=document.getElementById("advsettings"),c=document.getElementById("checkboxrow1");a.classList.toggle("turn90");c.classList.toggle("displaynone")}
function echoFavorite(){document.getElementById("fav").checked?(document.getElementById("echo_favorite").src="images/favorite.png",set_innertext(document.getElementById("lp_docwrite_site15"),gs("Remove Favorite")),set_innertext(document.getElementById("lp_docwrite_site34"),gs("Remove Site from Favorites"))):(document.getElementById("echo_favorite").src="images/not_favorite.png",set_innertext(document.getElementById("lp_docwrite_site15"),gs("Make Favorite")),set_innertext(document.getElementById("lp_docwrite_site34"),
gs("Add Site to Favorites")))}function decryptThumbnails(a){if("undefined"!=typeof data&&(null!==data&&1==data.sn)&&(document.getElementById("lpaddattach").style.display="block","undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)){getBG();num_attachments=data.attaches.length;for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&(addThumbnail(data.attaches[c].id,data.attaches[c].mimetype,data.attaches[c].bytes,data.attaches[c].filename,data.attachkey,a),num_attachments--)}}
function buildSecureNotes(a){0==issharedfolder(getBG().g_shares,data.group).give&&(g_sharedfromaid=1);if("undefined"!=typeof data&&null!==data&&"undefined"!=typeof data.sn&&1==data.sn){document.getElementById("notesrow0").style.display="block";document.getElementById("notesrow1").style.display="none";document.getElementById("notehistory").style.display=a?"inline-block":"none";document.getElementById("group").style.width="auto";document.getElementById("group").spellcheck=!1;var c=document.getElementById("notestype").val,
f=[],b;for(b in sntemplates){var j="undefined"!=typeof sntemplateicons[b]?sntemplateicons[b]:geticonurl("sn");f[f.length]={label:gs(b),image:j,value:b}}a||(create_combo("notestype",f,!0,document,"","notestype",-22,5),document.getElementById("notestype").addEventListener("click",function(){openCombo(null,"notestype","notestype_combo",document)}));a&&(c=getNoteValue("NoteType",document.getElementById("notes").value));if(!c||"undefined"==typeof sntemplates[c])c="Generic";init_attachment_action_menu();
document.getElementById("autologingrp").setAttribute("colspan","0");a=document.getElementById("pwaginggrp");null!=a&&a.setAttribute("colspan","2");buildForm(c);onResize()}else document.getElementById("attachtabletr").style.width="0px"}function disable_CPWButton(){document.getElementById("cpwbtnmini").classList.add("btn_disabled");document.getElementById("cpwfieldbtn")&&document.getElementById("cpwfieldbtn").classList.add("btn_disabled")}
function disable_SaveButton(){document.getElementById("save").classList.add("btn_disabled")}function enable_SaveButton(){document.getElementById("save").classList.remove("btn_disabled")}function update_SaveButton(a){var c=document,f=c.getElementById("save");c&&f&&(check_for_changes()?0<=f.className.indexOf("btn_disabled")&&enable_SaveButton():a!=ENABLE_ONLY&&-1==f.className.indexOf("btn_disabled")&&disable_SaveButton())}
function buildForm(a){var c=document.getElementById("notestype");c.value=gs(a);c.val=a;var f="undefined"!=typeof sntemplateicons[a]?sntemplateicons[a]:geticonurl("sn");c.style.background="url("+f+") no-repeat 2px 2px"+(existing?" rgb(238,238,238)":" rgb(249,249,249)");document.getElementById("notesrow2").style.display="Generic"==a?"block":"none";document.getElementById("notesrow3").style.display="Generic"==a?"none":"block";document.getElementById("notestype").disabled=existing?!0:!1;if("Generic"!=
a){for(c=document.getElementById("dynamicnotes");c.hasChildNodes()&&0<c.childNodes.length;)c.removeChild(c.firstChild);f=sntemplates[a];a=document.createElement("table");a.style.width="100%";a.style.borderSpacing="0px";for(var b in f){var j=document.createElement("tr"),e=document.createElement("td");e.style.whiteSpace="nowrap";var d=document.createElement("td");d.style.width="100%";var h=document.createTextNode(gsproper(b)+":");e.appendChild(h);var g=h=null;if("text"==f[b])h=document.createElement("input"),
h.type="text",h.spellcheck=!1,h.id="note_"+b,h.style.width="100%",h.style.fontFamily="Courier",existing&&(h.value=getNoteValue(b,document.getElementById("notes").value),"Private Key"==b&&(g=document.createElement("a"),set_innertext(g," Copy Key"),g.style.textDecoration="none",g.style.cursor="pointer",g.style.height="15px",g.style.align="right",g.onclick=-1==h.value.indexOf("-----BEGIN")&&-1==h.value.indexOf("END-----")?function(){var a=document.getElementById("note_Private Key").value;getBG().copytoclipboard(a)}:
function(){var a=document.getElementById("note_Private Key");pkelparse=a.value.split(/-----BEGIN.*KEY----- | -----END.*KEY-----/);pkelarmor=a.value.split(/-----/);var a="",b;for(b in pkelparse[1])a=":"!=pkelparse[1].charAt(b-1)?a+pkelparse[1][b].replace(/\u0020/g,"\n"):a+pkelparse[1][b];pktotal="-----"+pkelarmor[1]+"-----\n"+a+"\n-----"+pkelarmor[3]+"-----";getBG().copytoclipboard(pktotal);return!1})),"Password"==b&&(h.type="password",g=document.createElement("img"),g.id="note_eye_img",g.src="images/eye-shown.png",
g.style.textDecoration="none",g.style.position="relative",g.style.top="6px",g.style.left="-22px",g.onclick=function(){if(g_sharedfromaid)return alert(gs("This is a shared site. You are not permitted to view the password.")),!1;var a=document.getElementById("note_Password");-1!==document.getElementById("note_eye_img").src.indexOf("images/eye-shown.png")?document.getElementById("note_eye_img").src="images/eye-hidden.png":document.getElementById("note_eye_img").src="images/eye-shown.png";a.type="password"==
a.type?"text":"password"});else if("date"==f[b]||"datemoyr"==f[b]){h=document.createElement("span");h.style.width="100%";var m=document.createElement("select");m.id="note_"+b+"_mo";m.style.width="auto";var k="January February March April May June July August September October November December".split(" "),l;for(l in k)m.options[m.options.length]=new Option(gs(k[l]),k[l]);var q=null;if(existing&&((q=getNoteValue(b,document.getElementById("notes").value))&&(q=q.split(",")),q&&0<q.length))for(var p in k)if(k[p]==
q[0]||gs(k[p])==q[0]){m.value=k[p];break}h.appendChild(m);if("date"==f[b]){m=document.createElement("select");m.id="note_"+b+"_day";for(l=1;31>=l;l++)m.options[m.options.length]=new Option(l,l);q&&1<q.length&&(m.value=q[1]);h.appendChild(m)}m=document.createElement("input");m.type="text";m.maxLength=4;m.size=4;m.spellcheck=!1;m.id="note_"+b+"_yr";k="date"==f[b]?2:1;q&&q.length>k&&(m.value=q[k]);h.appendChild(m)}else if("textarea"==f[b])e.style.verticalAlign="top",h=document.createElement("textarea"),
h.cols=30,h.spellcheck=!1,h.rows=7,h.id="note_"+b,h.style.width="100%",h.style.fontFamily="Courier",existing&&(h.value=getNoteValue(b,document.getElementById("notes").value,!0));else continue;d.appendChild(h);null!==g&&d.appendChild(g);j.appendChild(e);j.appendChild(d);a.appendChild(j)}b=document.createElement("fieldset");b.appendChild(a);c.appendChild(b);updateFormHeading()}}function onResize(){}
function fix_addreplace(){document.getElementById("addnewsite").checked?(document.getElementById("url").disabled=!1,document.getElementById("name").disabled=!1,document.getElementById("group").disabled=!1,document.getElementById("username").disabled=!1,document.getElementById("password").disabled=!1,document.getElementById("notes").disabled=!1,document.getElementById("fav").disabled=!1,document.getElementById("never_autofill").disabled=!1,document.getElementById("pwprotect").disabled=!1,document.getElementById("autologin").disabled=
!1,document.getElementById("replaceexistingsiteaid").disabled=!0):document.getElementById("replaceexistingsite").checked&&(document.getElementById("url").disabled=!0,document.getElementById("name").disabled=!0,document.getElementById("group").disabled=!0,document.getElementById("username").disabled=!0,document.getElementById("password").disabled=!0,document.getElementById("notes").disabled=!0,document.getElementById("fav").disabled=!0,document.getElementById("never_autofill").disabled=!0,document.getElementById("pwprotect").disabled=
!0,document.getElementById("autologin").disabled=!0,document.getElementById("replaceexistingsiteaid").disabled=!1)}
function getSecureNoteFromFields(){if("undefined"!=typeof data&&1==data.sn){var a=document.getElementById("notestype").val;if("Generic"==a||"none"==document.getElementById("notesrow0").style.display)return document.getElementById("notes").value;var c="NoteType:"+a+"\n",f;for(f in sntemplates[a])"text"==sntemplates[a][f]?c+=f+":"+document.getElementById("note_"+f).value+"\n":"date"==sntemplates[a][f]||"datemoyr"==sntemplates[a][f]?(c+=f+":"+document.getElementById("note_"+f+"_mo").value,"date"==sntemplates[a][f]&&
(c+=","+document.getElementById("note_"+f+"_day").value),c+=","+document.getElementById("note_"+f+"_yr").value+"\n"):"textarea"==sntemplates[a][f]&&(c+=f+":"+document.getElementById("note_"+f).value+"\n");return c}return document.getElementById("notes").value}function get_decrypted_attachdata(a){for(var c in g_encatt)if("undefined"!=typeof g_encatt[c].id&&g_encatt[c].id==a)return g_encatt[c].data;return""}
function dosave(a,c){var f=document.getElementById("replaceexistingsite").checked;if(f&&0==document.getElementById("replaceexistingsiteaid").selectedIndex)alert(gs("Please Make a Selection"));else{var b=getBG();if(b.lploggedin)if(data.editfields){var j=issharedfolder(b.g_shares,data.group);if(checkreadonly(j)){var e=!1==j?b.g_local_key:j.sharekey;if(is_application(data)){var d=get_record(get_record_id(data));d.last_touch=lp_get_gmt_timestamp();for(var h in d.fields){var g=d.fields[h],m=document.getElementById("fields").contentWindow.document.getElementById(g.htmlid);
m&&(g.value=b.lpmenc(m.value,!0,e))}var k="appaid="+b.en(d.appaid);for(h in d.fields)g=d.fields[h],k+="&fieldid"+h+"="+b.en(g.id)+"&fieldtype"+h+"="+b.en(g.type)+"&fieldvalue"+h+"="+b.en(crypto_btoa(g.value));k+=!1==j?"":"&sharedfolderid="+b.en(j.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(k,d)}else checkFieldsForUpdates(e);getBG().close_editfieldsopener();setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}}else{var l=punycode.URLToASCII(trim(document.getElementById("url").value)),m=document.getElementById("name").value,k=document.getElementById("group").value,q=document.getElementById("username").value,d=document.getElementById("password").value,p=getSecureNoteFromFields(),s=document.getElementById("fav").checked,x=document.getElementById("never_autofill").checked,r=document.getElementById("pwprotect").checked,z=document.getElementById("autologin").checked;if(0<g_pwlen&&0==d.length||-1==g_pwlen&&
0==d.length)if(e=gs("Are you sure you want to save an empty password?"),!confirm(e))return;j=issharedfolder(b.g_shares,k);if(!1===j&&0==k.toLowerCase().indexOf("shared-"))alert(gs("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name."));else if(checkreadonly(j)){var y=!1;if(existing&&k!=data.group){if(y=issharedfolder(b.g_shares,data.group),!checkmove(j,y))return}else existing&&(y=j);e=existing?!1==y?b.g_local_key:
y.sharekey:!1==j?b.g_local_key:j.sharekey;f&&(z=b.g_sites[document.getElementById("replaceexistingsiteaid").value],m=z.name,k=z.group,j=issharedfolder(b.g_shares,k),e=!1==j?b.g_local_key:j.sharekey,p=b.lpmdec(z.extra,!0,e),s="1"==z.fav,x=z.never_autofill,r=z.pwprotect,z=z.autologin);if(""==m)alert(gs("You must enter a name."));else{if(45E3<p.length)if(confirm(gs("The notes field contains too much data.  You may store a maximum of 45,000 characters per note.\n\nWould you like us to truncate the note for you?  You will lose some of your data.")))p=
p.substring(0,45E3);else return;var u=!1;if(existing&&k!=data.group&&(j||y)){var n=[get_record_id(data)],t=[];t[get_record_id(data)]=k;u=!0;if(!b.moveIntoSharedFolder(j,y,n,t,!1,!0))return}if(existing&&is_application(data)){d=get_record(get_record_id(data));d.last_touch=lp_get_gmt_timestamp();l=getusernamefromacct(d);f=getpasswordfromacct(d);for(h in d.fields)if(g=d.fields[h],m=document.getElementById("fieldsrow2"),"none"!=window.getComputedStyle(m).display){if(m=document.getElementById("fields").contentWindow.document.getElementById(g.htmlid))g.value=
b.lpmenc(m.value,!0,e)}else""==g.type&&b.lpmdec_acct(g.value,!0,d,b.g_shares)==l?g.value=b.lpmenc(document.getElementById("username").value,!0,e):"password"==g.type&&b.lpmdec_acct(g.value,!0,d,b.g_shares)==f&&(g.value=b.lpmenc(document.getElementById("password").value,!0,e));d.name=document.getElementById("name").value;d.group=document.getElementById("group").value;d.appname=document.getElementById("url").value;g=getSecureNoteFromFields();g!=b.lpmdec(d.extra,!0,e)&&(d.extra=lpmenc(g,!0,e));d.fav=
document.getElementById("fav").checked?"1":"0";d.pwprotect=document.getElementById("pwprotect").checked;d.autologin=document.getElementById("autologin").checked?"1":"0";var v=d.group;j&&(d.sharefolderid=j.id,v=v.substr(j.decsharename.length+1));if(k!=data.group&&(j||y))n=[get_record_id(data)],t=[],t[get_record_id(data)]=k,b.moveIntoSharedFolder(j,y,n,t,!1,!1,!0);else{k="ajax=1&extjs=1&cmd=updatelpaa&name="+b.en(b.lpenc(d.name,e))+"&grouping="+b.en(b.lpenc(v,e))+"&appname="+b.en(d.appname)+"&extra="+
b.en(crypto_btoa(d.extra))+"&appaid="+b.en(d.appaid);"1"==d.fav&&(k+="&fav=on");d.pwprotect&&(k+="&pwprotect=on");"1"==d.autologin&&(k+="&autologin=on");for(h in d.fields)g=d.fields[h],k+="&fieldid"+h+"="+b.en(g.id)+"&fieldtype"+h+"="+b.en(g.type)+"&fieldvalue"+h+"="+b.en(crypto_btoa(g.value));k+=!1==j?"":"&sharedfolderid="+b.en(j.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(k,d)}setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}else{n=existing?data.sn?b.g_securenotes[get_record_id(data)]:b.g_sites[get_record_id(data)]:b.createNewAcct();v=!1;for(h in attaches)attaches.hasOwnProperty(h)&&"undefined"!=typeof attaches[h]&&(v=!0);if(v&&!c){"undefined"==typeof n.attachkey||""==n.attachkey?(t=SHA256(lpCreatePass(32,1,1,1,1,1,1,1)),g_attachkey=b.lpenc(t,e)):g_attachkey=n.attachkey;var t=AES.hex2bin(b.lpdec(g_attachkey,e)),w=[];for(h in attaches)attaches.hasOwnProperty(h)&&"undefined"!=typeof attaches[h]&&(attaches[h].filename=
lpenc(attaches[h].filename,t),w[w.length]={id:attaches[h].id,bytes:attaches[h].bytes});if(w.length){b.fastEncryptAttachments(t,w,function(a){g_encatt=a;dosave(null,!0)});return}}t=lp_gettld_url(AES._utf8_encode(l));if(existing&&!data.sn&&n.tld!=t&&!a&&b.g_prompts.view_pw_prompt)b.security_prompt(function(){dosave(1,c)});else{existing&&!n.sn&&b.fix_tlds(n.tld,t,get_record_id(data));n.genpw=!1;n.name=m;u||(n.group=k);"http://sn"==l?(n.url=l,n.sn=1):n.url=AES._utf8_encode(l);n.tld=t;n.unencryptedUsername=
q;q!=b.lpmdec(n.username,!0,e)&&(n.username=b.lpmenc(q,!0,e));d!=b.lpmdec(n.password,!0,e)&&(n.password=b.lpmenc(d,!0,e));p!=b.lpmdec(n.extra,!0,e)&&(n.extra=b.lpmenc(p,!0,e));n.fav=s?"1":"0";n.autologin=z;n.never_autofill=x;n.pwprotect=r;existing||(n.aid="0");!1!=j&&(n.sharefolderid=j.id,0==j.give&&(n.sharedfromaid=1,g_sharedfromaid=!0));u="";w=[];if(v){if("undefined"==typeof n.attachkey||""==n.attachkey)n.attachkey=g_attachkey,u+="&attachkey="+b.en(n.attachkey);n.attachpresent="1";n.retrieveattach=
1;v=0;for(h in attaches)attaches.hasOwnProperty(h)&&"undefined"!=typeof attaches[h]&&(u+="&filename"+v+"="+b.en(attaches[h].filename),u+="&mimetype"+v+"="+b.en(attaches[h].mimetype),u+="&attachid"+v+"="+b.en(attaches[h].id),u+="&attachbytes"+v+"="+b.en(get_decrypted_attachdata(attaches[h].id)),"undefined"==typeof w.add&&(w.add=[]),w.add[w.add.length]=existing?{id:n.aid+"-"+attaches[h].id,mimetype:attaches[h].mimetype,parent:n.aid,filename:attaches[h].filename}:{id:attaches[h].id,mimetype:attaches[h].mimetype,
filename:attaches[h].filename},v++)}if(0<removedattach.length){n.retrieveattach=1;for(h=0;h<removedattach.length;h++)u+="&rmattach"+h+"="+b.en(removedattach[h]),"undefined"==typeof w.remove&&(w.remove=[]),w.remove[w.remove.length]=removedattach[h]}v=k;j&&(v=k.substr(j.decsharename.length+1));if(existing){if(l!=data.url||m!=data.name||k!=data.group||q!=data.unencryptedUsername||d!=b.lpmdec(data.password,!0,e)||p!=b.lpmdec(data.extra,!0,e)||s!=("1"==data.fav)||x!=data.never_autofill||r!=data.pwprotect||
z!=data.autologin||0<attaches.length||0<removedattach.length){n.sn?b.g_securenotes[n.aid]=n:b.g_sites[n.aid]=n;for(h in n.fields)if(n.fields.hasOwnProperty(h)&&(f=n.fields[h],is_encrypted_field(f.type)&&(null!=origpassword&&""!=origpassword&&null!=f.value&&""!=f.value&&b.lpmdec_acct(f.value,!0,n,b.g_shares)==b.lpmdec_acct(origpassword,!0,n,b.g_shares))&&"password"==f.type&&(f.value=n.password),is_encrypted_field(f.type)&&(null!=origusername&&""!=origusername&&null!=f.value&&""!=f.value&&b.lpmdec_acct(f.value,
!0,n,b.g_shares)==b.lpmdec_acct(origusername,!0,n,b.g_shares))&&("text"==f.type||"email"==f.type||"tel"==f.type||"url"==f.type)))f.value=n.username;if(k!=data.group&&(j||y)){n=[get_record_id(data)];t=[];t[get_record_id(data)]=k;b.moveIntoSharedFolder(j,y,n,t,!1,!1,!0);setTimeout(function(){getBG().closecurrenttab("site.html")},0);return}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.applyattacharraychanges(w);b.increment_local_accts_version();b.rewritelocalfile();
k="ajax=1&extjs=1&name="+b.en(b.lpenc(m,e))+"&url="+b.en(AES.url2hex(l))+"&grouping="+b.en(b.lpenc(v,e))+"&username="+b.en(crypto_btoa(n.username))+"&password="+b.en(crypto_btoa(n.password))+"&extra="+b.en(crypto_btoa(n.extra))+"&openid_url=&aid="+b.en(get_record_id(data))+"&basic_auth=0&isbookmark=0&localupdate=1";k=k+(r?"&pwprotect=on":"")+(x?"&never_autofill=on":"");k+=z?"&autologin=on":"";k+=s?"&fav=on":"";k+=!1==j?"":"&sharedfolderid="+b.en(j.id);"http://sn"==l&&("undefined"!==typeof b.g_loglogins&&
b.g_loglogins)&&(k+="&n="+AES.url2hex(m));"http://sn"!=n.url&&"http://group"!=n.url&&8==(b.g_loglogins&8)&&(k+="&un="+en(AES.bin2hex(b.lpmdec_acct(origusername,!0,n,b.g_shares))));k+=u;n.attacharraychanges=w;n.newvalues=[];b.saveSite(k,n);j=b.getsites(t,!0);if(d!=b.lpmdec(data.password,!0,e)&&1<array_length(j)){h=b.lpmdec(data.password,!0,e);k=!1;y=","+get_record_id(data)+",";for(g in j)getpasswordfromacct(b.g_sites[g])==h&&get_record_id(data)!=g?k=!0:y+=","+g+",";k&&b.openLinkedSites(d,t,y)}}data.save_all&&
checkFieldsForUpdates(e)}else n.fields=[],h=[],k=updateAndEncryptData2(b,n.username,n.password,n.fields,n,h,e),k="name="+b.en(b.lpenc(m,e))+"&grouping="+b.en(b.lpenc(v,e))+"&data="+b.en(b.bin2hex(k))+"&extra="+b.en(b.lpenc(p,e))+(r?"&pwprotect=on":"")+(x?"&never_autofill=on":"")+(z?"&autologin=on":"")+(s?"&fav=on":""),k+="&extjs=1&localupdate=1",k+=!1==j?"":"&sharedfolderid="+b.en(j.id),"undefined"!=typeof data.realm&&(n.realm_data=b.lpmenc(data.realm,!0,e),n.basic_auth="1",k+="&basic_auth=1&realm="+
b.en(b.lpenc(data.realm,e))),"http://sn"==l&&(e=getNoteValue("NoteType",p),n.notetype=e,k+=e&&""!=e?"&notetype="+b.en(e):""),f&&(k+="&replacing=1"),k+=u,data.save_all?(n.save_all=!0,k+="&ajax=1&aid=0&save_all=1&url="+b.en(AES.url2hex(l))+"&openid_url=&username=&password=",n.newvalues=h,b.saveAllSite(k,n)):"undefined"!=typeof data.formdata?(k+="&ref="+b.en(AES.url2hex(l)),f&&(k+="&aid="+b.en(document.getElementById("replaceexistingsiteaid").value)),"undefined"!=typeof data.createacct&&(data.createacct&&
"undefined"!=typeof data.username_field)&&(n.fields=[],k+="&createacct=1&username_field="+b.en(data.username_field)),n.newvalues=h,b.saveSiteFromSubmit(k,n)):(k+="&ajax=1&aid=0&url="+b.en(AES.url2hex(l))+"&openid_url=&username="+b.en(crypto_btoa(n.username))+"&password="+b.en(crypto_btoa(n.password)),n.newvalues=h,n.attacharraychanges=w,b.saveSite(k,n));setTimeout(function(){getBG().closecurrenttab("site.html")},0)}}}}}else console_log("Not logged in!")}}
function checkFieldsForUpdates(a){var c=getBG(),f=document.getElementById("fields").contentWindow.document,b=!1,j;for(j in data.fields){var e=data.fields[j];if(is_encrypted_field(e.type)){var d=f.getElementById(e.htmlid);if(d&&"undefined"!=typeof d.value&&c.lpmdec(e.value,!0,a)!=d.value){var b=!0,h=c.lpmenc(d.value,!0,a);""!=e.value&&(""!=c.g_sites[get_record_id(data)].username&&e.value==c.g_sites[get_record_id(data)].username&&""!=d.value)&&(c.g_sites[get_record_id(data)].username=h,c.g_sites[get_record_id(data)].unencryptedUsername=
d.value);""!=e.value&&(""!=c.g_sites[get_record_id(data)].password&&e.value==c.g_sites[get_record_id(data)].password&&""!=d.value)&&(c.g_sites[get_record_id(data)].password=h);e.value=h}}else if("checkbox"==e.type||"radio"==e.type)d=e.checked,h=f.getElementById(e.htmlid)&&f.getElementById(e.htmlid).checked,d!=h&&(b=!0,e.checked=h);else if("select-one"==e.type&&e.faketype&&(d=f.getElementById(e.htmlid))&&"undefined"!=typeof d.value&&e.value!=d.value)b=!0,e.value=d.value}if(b){if(g_issafari||g_isopera||
g_ismaxthon||g_isfirefoxsdk)c.update_site(get_record_id(data)),c.update_fields(get_record_id(data),data.fields);c.increment_local_accts_version();c.rewritelocalfile();a="update=1&aid="+c.en(get_record_id(data))+"&urid=0";b="";d=[];for(j in data.fields)if(e=data.fields[j],e.htmlid&&f.getElementById(e.htmlid))if(h=data.editfields&&""==e.formname?"_"+e.name:"_"+e.formname+"_"+e.name,is_encrypted_field(e.type)){var g=f.getElementById(e.htmlid).value;d.push(g);g=crypto_btoa(e.value);b+=h+"="+c.en(g)+"&"}else"checkbox"==
e.type?f.getElementById(e.htmlid).checked&&(b+=h+"="+c.en(e.value)+"&"):"select-one"==e.type&&e.faketype&&(g=f.getElementById(e.htmlid).value,b+=h+"="+c.en(g)+"&");b+="&auto=1";f=issharedfolder(c.g_shares,data.group);b+=!1==f?"":"&sharedfolderid="+c.en(f.id);c.saveFields(a,b,{aid:data.aid,newvalues:d})}}
function updateAndEncryptData2(a,c,f,b,j,e,d){for(var h="",g="undefined"!=typeof data.formdata?data.formdata.split("\n"):[],m=!1,k=0,l=0,q=0;q<g.length;q++){var p=g[q],p=p.split("\t");4!=p.length&&5!=p.length||("text"==p[3]||"email"==p[3]||"tel"==p[3]||"url"==p[3]?k++:"password"==p[3]&&l++)}0==k&&(2==l&&!data.save_all)&&(m=!0);for(q=0;q<g.length;q++)if(p=g[q],p=p.split("\t"),!(4!=p.length&&5!=p.length)){var k=data.save_all?decodeURIComponent(p[0]):"0",l=decodeURIComponent(p[1]),s=decodeURIComponent(p[2]),
x=getBG().lpmenc(s,!0,d),p=p[3];if("text"==p||"password"==p||"hidden"==p||"textarea"==p||"email"==p||"tel"==p||"url"==p){if("email"==p&&s==data.username&&(x=c),"tel"==p&&s==data.username&&(x=c),"url"==p&&s==data.username&&(x=c),"text"==p&&s==data.username&&(x=c),"password"==p&&m?(x=c,m=!1):"password"==p&&s==data.password&&(x=f),s=lpmdec(x,!0,d),e&&e.push(s),h+=k+"\t"+a.en(l)+"\t"+a.en(crypto_btoa(x))+"\t"+a.en(p)+"\n","hidden"!=p){var r={};r.otherfield=data.save_all;r.name=l;r.type=p;r.value=x;r.checked=
!1;r.formname=data.save_all?k:"";r.urid="0";r.otherlogin="0";r.url="";b[b.length]=r}}else if("action"==p)h+=k+"\taction\t"+a.en(s)+"\taction\n",j.action=AES.url2hex(s);else if("method"==p)h+=k+"\tmethod\t"+a.en(s)+"\tmethod\n",j.method=s;else if(h+=k+"\t"+a.en(l)+"\t"+a.en(s)+"\t"+a.en(p)+"\n","checkbox"==p||"radio"==p||"select-one"==p)r={},r.otherfield=data.save_all,r.name=l,r.type=p,"checkbox"==p||"radio"==p?(r.checked="-1"==s.substring(s.length-2),r.value=s.substring(0,s.length-2)):r.value=s,r.formname=
data.save_all?k:"",r.urid="0",r.otherlogin="0",r.url="",b[b.length]=r}return h}
function getDataHTML(){var a=newelt("div"),c=newelt("link");c.type="text/css";c.href="general.css";a.appendChild(c);for(var c=data.formdata.split("\n"),f=0;f<c.length;f++){var b=c[f].split("\t");if(!(4!=b.length&&5!=b.length)){var j=data.save_all?decodeURIComponent(b[0]):"0",e=decodeURIComponent(b[1]),d=decodeURIComponent(b[2]),b=b[3],j=uniqid(j+"_"+e);if("text"==b||"password"==b||"email"==b||"tel"==b||"url"==b){var h=newelt("label");set_innertext(h,e);var g=newelt("input","",j);g.name=e;g.type=b;
g.value=d;a.appendChild(h);a.appendChild(g);"password"==b&&(event_handlers[j+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},g_eyeimgid=j+"toggleimg",e=newelt("a","eye",j+"toggle"),d=newelt("img","",g_eyeimgid),d.alt=gs("[Show]"),d.src="images/eye-shown.png",e.appendChild(d),a.appendChild(e));a.appendChild(newelt("br"))}else if("textarea"==b)b=newelt("label"),set_innertext(b,
e),j=newelt("textarea"),j.readonly=!0,j.name=e,j.style.verticalAlign="top",set_innertext(j,d),a.appendChild(b),a.appendChild(j),a.appendChild(newelt("br"));else if("select-one"==b)b=newelt("select"),b.name=e,e=newelt("option"),e.value=d,set_innertext(e,d),b.appendChild(e),a.appendChild(b),a.appendChild(newelt("br"));else if("checkbox"==b||"radio"==b)checked="-1"==d.substring(d.length-2)?" checked":"","radio"==b&&""==checked||(d=d.substring(0,d.length-2),j=newelt("input"),j.type=b,j.value=d,j.disabled=
!0,0<checked.length&&(j.checked=!0),d=newelt("label"),set_innertext(d,e),a.appendChild(j),a.appendChild(d),a.appendChild(newelt("br")))}}return a}function showaddfield(){var a=getBG(),a=issharedfolder(a.g_shares,data.group);checkreadonly(a)&&(a=document.getElementById("fields").contentWindow.document,a.getElementById("addfield").style.display="block",a.getElementById("newname").focus())}
function doaddfield(){var a=getBG(),c=issharedfolder(a.g_shares,data.group);if(checkreadonly(c)){var f=document.getElementById("fields").contentWindow.document,b=f.getElementById("newname").value,j=f.getElementById("newtype").value,e=j;"select-one"==e&&(e="text");var d=f.getElementById("newformname")?f.getElementById("newformname").value:"";if(""==b)alert(gs("You must enter a name."));else{for(var h in data.fields)if(data.fields[h].name==b&&(data.editfields||data.fields[h].formname==d)){alert(gs("You must enter a unique name."));
return}var g=uniqid(d+"_"+b),m=newelt("div");if("text"==j||"password"==j||"select-one"==j||"email"==j||"tel"==j||"url"==j){var k=newelt("label");set_innertext(k,b);var l=newelt("input","",ofja(g));l.type=ofja(e);k.appendChild(l);m.appendChild(k);"password"==j&&(g_eyeimgid=g+"toggleimg",l=newelt("a","eye",ofja(g)),l.id=ofja(g)+"toggle",l.href="#",l.className="eye",k=newelt("img","",ofja(g_eyeimgid)),k.id=ofja(g_eyeimgid),k.alt=gs("[Show]"),l.appendChild(k),m.appendChild(l))}else"textarea"==j?(l=newelt("textarea",
"",ofja(g)),m.appendChild(l)):"checkbox"==j&&(l=newelt("input","",ofja(g)),k=newelt("label"),k.for=ofja(g),set_innertext(k,b),m.appendChild(l),m.appendChild(k));l=newelt("a","",ofja(g)+"delete");k=newelt("div","","");set_innertext(l,"[ - ]");l.href="#";set_innertext(k,b);l.appendChild(k);l=f.createElement("div");l.id=g+"_div";l.appendChild(m);f.body.appendChild(l);event_handlers={};"password"==j&&(event_handlers[g+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,
this.id.length-6)),this);return!1});event_handlers[g+"delete"]=function(){var a=this.id.substring(0,this.id.length-6)+"_div";parent.delete_field(a,this.children[0].value,"");return!1};lpdbg("site","1 added event handler for "+g+"delete");fix_event_handlers();l={};l.otherfield=!data.editfields;l.name=b;l.type=j;"select-one"==j&&(l.faketype=e);l.value="";l.formname=d;l.checked=!1;l.urid="0";l.otherlogin="0";l.url="";l.htmlid=g;e=0;for(h in data.fields)data.fields.hasOwnProperty(h)&&h>e&&(e=h);"string"==
typeof e&&(e=parseInt(e));0===data.fields.length?data.fields[0]=l:data.fields[e+1]=l;(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&a.update_fields(get_record_id(data),data.fields);a.increment_local_accts_version();a.rewritelocalfile();b="add=1&aid="+a.en(data.aid)+"&urid=0&name="+a.en(b)+"&type="+j;data.editfields||(b+="&formname="+a.en(d));b+="&auto=1";c=!1==c?"":"sharedfolderid="+a.en(c.id);a.saveFields(b,c,{aid:data.aid});f.getElementById("newname").value="";f.getElementById("newtype").selectedIndex=
0;f.getElementById("newformname")&&(f.getElementById("newformname").value="");f.getElementById("addfield").style.display="none"}}}function newelt(a,c,f){a=document.createElement(a);c&&(a.className=c);f&&(a.id=f);return a}
function getFieldsHTMLNodes(a){var c=getBG(),f=document.createElement("div"),b=newelt("link","","");b.rel="stylesheet";b.src="general.css";b.type="text/css";f.appendChild(b);if(!is_application(data)){event_handlers.addfieldlink=function(){parent.showaddfield();return!1};event_handlers.doaddfield=function(){parent.doaddfield()};b=newelt("a","");b.href="#";b.id="addfieldlink";set_innertext(b,gs("Add Field"));f.appendChild(b);f.appendChild(document.createElement("br"));b=newelt("div","","addfield");
b.style.display="none";var j=newelt("label"),e=newelt("input","","newname");e.type="text";set_innertext(j,gs("Name:"));j.appendChild(e);b.appendChild(j);b.appendChild(newelt("br"));j=newelt("label");set_innertext(j,gs("Type:"));var e=newelt("select","","newtype"),d=newelt("option","","");d.value="text";set_innertext(d,gs("Text"));var h=newelt("option","","");h.value="password";set_innertext(h,gs("Password"));var g=newelt("option","","");g.value="select-one";set_innertext(g,gs("Select"));var m=newelt("option",
"","");m.value="checkbox";set_innertext(m,gs("Checkbox"));e.appendChild(d);e.appendChild(h);e.appendChild(g);e.appendChild(m);j.appendChild(e);b.appendChild(j);b.appendChild(newelt("br"));data.editfields||(d=newelt("label"),set_innertext(d,gs("Form Name:")),d.appendChild(newelt("input","","newformname")),b.appendChild(d));d=newelt("input","","doaddfield");d.type="button";d.value=gs("Add");b.appendChild(d);b.appendChild(newelt("br"));b.appendChild(newelt("br"));f.appendChild(b)}var b=[],k;for(k in data.fields){var l=
data.fields[k],d=l.formname,j=is_application(data)?k:l.name,e=g=l.value?l.value:"",m=l.type,h=j+"_"+m+"_"+g;if("undefined"==typeof b[h]){b[h]=!0;h=uniqid(d+"_"+j);l.htmlid=h;d=newelt("div");if(is_application(data)&&""==m||"text"==m||"password"==m||"email"==m||"tel"==m||"url"==m)e=crypto_btoa(g),g=c.lpmdec(g,!0,a),l=newelt("input","",ofja(h)),l.value=g,g=newelt("label"),set_innertext(g,j),g.appendChild(l),d.appendChild(g),"password"==m&&(event_handlers[h+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,
this.id.length-6)),this);return!1},g=newelt("a","",ofja(h)+"toggle"),g.href="#",m=newelt("span","",""),set_innertext(m,gs("[Show]")),g.appendChild(m),d.appendChild(g),l.type="password",g_pw_field_ids.push(h));else if("textarea"==m)e=crypto_btoa(g),g=c.lpmdec(g,!0,a),m=newelt("label"),set_innertext(m,j),l=document.createElement("textarea","",ofja(h)),set_innertext(l,g),m.appendChild(l),d.appendChild(m);else if("select-one"==m){m=newelt("label");set_innertext(m,j);var l=newelt("select","",ofja(h)),
q=newelt("option");q.value=g;set_innertext(q,g);l.appendChild(q);m.appendChild(l);d.appendChild(m)}else if("checkbox"==m||"radio"==m){g=l.checked?" checked":"";if("radio"==m&&""==g)continue;g=newelt("input","",ofja(h));g.type=ofja(m);g.checked=l.checked;d.appendChild(g);g=newelt("label");g.for=ofja(h);set_innertext(g,j);d.appendChild(g)}else continue;is_application(data)||(event_handlers[h+"delete"]=function(){var a=this.children,b=encodeURIComponent(get_innertext(a[0])),a=AES.hex2bin(get_innertext(a[1])),
c=this.id.substring(0,this.id.length-6)+"_div";parent.delete_field(c,b,a);return!1},lpdbg("site","2 added event handler for "+h+"delete"),g=newelt("a","",ofja(h)+"delete"),set_innertext(g,"[ - ]"),g.href="#",m=newelt("div","",ofja(h)+"value"),l=newelt("div","",ofja(h)+"origval"),m.style.display="none",set_innertext(m,j),l.style.display="none",set_innertext(l,AES.bin2hex(e)),d.appendChild(g),g.appendChild(m),g.appendChild(l));j=newelt("div","",ofja(h)+"_div");j.appendChild(d);f.appendChild(j)}}return f}
function delete_field(a,c,f){try{if(confirm(gs("Are you sure you would like to delete this field?"))){var b=getBG(),j=issharedfolder(b.g_shares,data.group);if(checkreadonly(j)){var e=document.getElementById("fields").contentWindow.document;if(e.getElementById(a)){e.getElementById(a).style.display="none";for(var d in data.fields)if(data.fields.hasOwnProperty(d)&&data.fields[d].name==c){var h=data.fields[d].value;is_encrypted_field(data.fields[d].type)&&(h=crypto_btoa(h));h==f&&("undefined"!=typeof data.fields.splice?
data.fields.splice(d,1):delete data.fields[d])}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_fields(get_record_id(data),data.fields);b.increment_local_accts_version();b.rewritelocalfile();var g="delete=1&aid="+b.en(get_record_id(data))+"&urid=0&name="+b.en(c)+"&value="+b.en(f),g=g+"&auto=1",m=!1==j?"":"sharedfolderid="+b.en(j.id);b.saveFields(g,m,{aid:data.aid})}else alert("Sorry, deletion of the field failed. Please re-save the site.")}}}catch(k){console_log("caught exception in delete_field: "+
k.message)}}function dodel(){getBG().deleteAid(get_record_id(data),window,!1,!1,function(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)})}function doshare(){if(!check_for_changes()||confirm(gs("Are you sure you want to share this item?  Doing so will cause you to lose any changes you have made to this item!"))){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&share="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}
function docancel(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)}var HISTORY={USERNAME:0,PASSWORD:1,EXTRA:2};
function show_history(a){if(!check_for_changes()||confirm(gs("Are you sure you want to view history?  Doing so will cause you to lose any changes you have made to this item!"))){var c="";a==HISTORY.USERNAME?c="username":a==HISTORY.PASSWORD?c="password":a==HISTORY.EXTRA&&(c="note");a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&"+c+"history="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}var logged=!1;
function toggle_password(a,c){if("password"==a.type){if(existing){var f=getBG();if(null!=data.sharedfromaid&&""!=data.sharedfromaid&&"0"!=data.sharedfromaid&&"null"!=data.sharedfromaid){alert(gs("This is a shared site. You are not permitted to view the password."));return}if(f.g_prompts.view_pw_prompt){g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?f.security_prompt(function(){a.type="text";c.children[0].children[0].src=get_eye_src(a.type,"glow");
c.children[0].children[0].setAttribute("alt",gs("[Hide]"));set_innertext(c.children[0].children[1],gs("Hide Password"))}):f.security_prompt(function(){a.type="text";set_innertext(c,gs("[Hide]"))});return}}existing&&!logged&&(f.loglogin(get_record_id(data)),logged=!0);a.type="text";g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type,"glow"),c.children[0].children[0].setAttribute("alt",gs("[Hide]")),
set_innertext(c.children[0].children[1],gs("Hide Password"))):set_innertext(c,gs("[Hide]"))}else a.type="password",g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type),c.children[0].children[0].setAttribute("alt",gs("[Show]")),set_innertext(c.children[0].children[1],gs("Show Password"))):set_innertext(c,gs("[Show]"))}function gsproper(a){return gs(a+"proper")!=a+"proper"?gs(a+"proper"):gs(a)}
function check_for_changes(){var a=getBG(),c=document.getElementById("url").value,f=document.getElementById("name").value,b=document.getElementById("group").value,j=document.getElementById("username").value,e=document.getElementById("password").value,d=getSecureNoteFromFields(),h=document.getElementById("fav").checked,g=document.getElementById("never_autofill").checked,m=document.getElementById("pwprotect").checked,k=document.getElementById("autologin").checked,l=issharedfolder(a.g_shares,b),l=!1==
l?a.g_local_key:l.sharekey;return is_application(data)?c!=data.appname||f!=data.name||b!=data.group||j!=getusernamefromacct(data)||e!=getpasswordfromacct(data)||d!=a.lpmdec(data.extra,!0,l)||h!=("1"==data.fav)||m!=data.pwprotect||k!=("1"==data.autologin):c!=data.url||f!=data.name||b!=data.group||j!=data.unencryptedUsername||e!=a.lpmdec(data.password,!0,l)||d!=a.lpmdec(data.extra,!0,l)||h!=("1"==data.fav)||g!=data.never_autofill||m!=data.pwprotect||k!=data.autologin}
function doeditfields(){var a=getBG();if(!check_for_changes()||confirm(is_application(data)?gs("LoseChangesApp"):gs("LoseChanges"))){a.g_site_data=[];for(var c in data)a.g_site_data[c]=data[c];a.g_site_data.editfields=1;a.set_editfieldsopener(window);a.openURL(getchromeurl("site.html"),null,a.g_site_data)}}function showattach(a){a.getAttribute("src_hidden")&&a.getAttribute("src_hidden").length?getBG().showImageAttach(a.getAttribute("src_hidden")):openattach(a)}
function openattach(a){var c=a.getAttribute("filename")?a.getAttribute("filename"):"";getBG().openAttach(get_record_id(data),a.getAttribute("attachid"),c)}function addattach(){getBG().have_binary()?getBG().addAttach(function(){getBG().g_ischrome&&addattachcb()}):confirm(gs("This feature requires the binary version of this browser extension.  Would you like to install it now?"))&&getBG().install_binary()}
function addThumbnail(a,c,f,b,j,e){var d=get_extension_from_mimetype(c),h=check_filename_badchars(d),g=null,g=h==FILENAME_FRAGMENT_VALID?"."+d:0==h.length||h==FILENAME_FRAGMENT_EMPTY?"":"."+gs(d);if(j&&e)try{var m=AES.hex2bin(lpdec(j,e));b=lpdec(b,m)}catch(k){b=""}if(null===b||""==b)b="attachment"+num_attachments+g;d=document.getElementById("attachtable");h=document.createElement("tr");g=document.createElement("td");g.id=a;g.style.height="28px";g.style.width="80%";g.style.background="url('images/paperclip.png') no-repeat 2px 2px #e6e6e6";
var l=document.createElement("span");l.style.fontWeight="bold";l.style.position="relative";l.style.left="32px";l.style.top="6px";l.style.cursor="pointer";l.appendChild(document.createTextNode(b));f&&""!=f&&0==c.indexOf("data:image")?(l.setAttribute("attachid",a),j?(getBG().fastDecryptAttachment(a,c,f,j,e,function(a){getBG().g_ischrome&&(a&&a.length?l.setAttribute("src_hidden",c+";base64,"+a):l.setAttribute("src_hidden",""))}),l.addEventListener("click",function(){attachment_action_menu(this,showattach)})):
(f&&f.length?l.setAttribute("src_hidden",c+";base64,"+f):l.setAttribute("src_hidden",""),getBG().have_binary()?l.addEventListener("click",function(){attachment_action_menu(this,showattach)}):l.addEventListener("click",function(){showattach(this)}))):(l.setAttribute("attachid",a),getBG().have_binary()?l.addEventListener("click",function(){attachment_action_menu(this,openattach)}):l.addEventListener("click",function(){openattach(this)}));f=document.createElement("span");f.className="attachx";f.setAttribute("attachid",
a);f.addEventListener("click",function(){rmattach(this)});set_innertext(f,"\u00a0\u00a0\u00a0\u00a0\u00a0");g.appendChild(l);g.appendChild(f);h.appendChild(g);d.insertBefore(h,d.firstChild);attachnum++}function createAttachId(){for(;;){var a=Math.floor(99999*Math.random()),c;for(c in data.attaches)if(data.attaches.hasOwnProperty(c)&&data.attaches[c].id==get_record_id(data)+"-"+a)break;for(c=0;c<attaches.length&&!("undefined"!=typeof attaches[c]&&attaches[c].id==a);c++);return a}}
function rmattach(a){a=a.getAttribute("attachid");if(confirm(gs("Are you sure you would like to remove this attachment?"))){if("undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&a==data.attaches[c].id&&(removedattach[removedattach.length]=a);delete attaches[a];delThumbnail(a)}}
function delThumbnail(a){for(var c=document.getElementById("attachtable"),f=0;f<c.children.length;f++){var b=c.children[f];if(b.children&&b.children.length&&b.children[0].id==a){c.removeChild(b);break}}}
function attachment_action_doSave(){if(null!=open_attach_target){var a=open_attach_target.getAttribute("filename")?open_attach_target.getAttribute("filename"):"";getBG().exportAttachment(get_record_id(data),open_attach_target.getAttribute("attachid"),a)}else alarm("error, trying to save an attachment that does not exist");close_attach_list()}
function clearData(){for(var a=document.getElementsByTagName("input"),c=0;c<a.length;c++)"button"!=a[c].type&&(a[c].value="");a=document.getElementsByTagName("textarea");for(c=0;c<a.length;c++)a[c].value=""}function uniqid(a){a||(a="");return"a"+SHA256(a+"_"+(new Date).getTime()+"_"+Math.floor(100*Math.random()))}function setup_eye_events(a){g_eye_show&&(a.getElementById("passwordtoggle"),a.getElementById("passwordtoggleimg").style.verticalAlign="bottom")}
function eye_over(a){if(!(null==a||null==a.target)){var c=document.getElementById("passwordtoggleimg"),f=document.getElementById("password");a.target==c&&(c.src=get_eye_src(f.type,"glow"))}}function eye_out(a){if(!(null==a||null==a.target)){var c=document.getElementById("passwordtoggleimg"),f=document.getElementById("password");a.target==c&&(c.src=get_eye_src(f.type))}}function get_eye_src(a){return"password"==a?"images/eye-shown.png":"images/eye-hidden.png"}var CPW_WAKETIME=97,my_aid=null;
function docpwbtn(){var a=getBG(),c=document;if(!c||!a||!data)return!1;var f=data.aid,b=data.url;g_cpwbot&&b?"undefined"!=typeof a.dopwchange?(g_start_time=(new Date).getTime(),a.cpwbot_preinit(),g_cpw_progress_ctr=20,show_cpw_dialog("progress"),setTimeout(function(){insert_cpw_placeholder_msg(c,gs("LastPass is loading..."))},5003),setTimeout(function(){cpw_status_check()},CPW_WAKETIME),g_ischrome?get_selected_tab(null,function(b){a.dopwchange(f,!1,b)}):a.dopwchange(f,!1)):pass:pass;return!1}
function docpwdebug(){var a=getBG(),c=document;if(!c||!a||!data)return!1;if(g_cpwbot){if(document.getElementById("cpwmsgdiv"))return!1;a=c.createElement("div");a.style.height="200px";a.style.width="100%";a.style.overflow="auto";a.style.backgroundColor="blue";a.style.color="yellow";a.style.padding="3px";a.id="cpwmsgdiv";var f=c.getElementById("sitebody");f?f.appendChild(a):c.body.appendChild(a)}return!1}var g_cpw_progress_ctr=0,g_lastmsg="";
function cpw_status_check(){var a=getBG(),c=document;if(!c||!a||!data)return!1;var f=!1,b=!1,j=!1,e=!1,d=!1,h=!1;(c=c.getElementById("cpwmsgdiv"))&&(g_ischrome?set_innertext(c,a.cpwbot_get_user_debug_messages()):a.cpwbot_get_user_debug_messages());g_ischrome?(a=a.cpwbot_get_dialog_msg(),cpw_progress_update(a)):a.cpwbot_get_dialog_msg();a=get_current_state(!0);lpdbg("site","BG.current_state is "+a);switch(a){case "FAIL":b=f=!0;break;case "CAPTCHA":j=b=f=!0;break;case "DOCAPTCHA":e=!0;break;case "TIMEOUT":h=
b=f=!0;break;case "FAIL_PW_SAVED":d=b=f=!0;break;case "DONE":case "OK":f=!0;break;case 0:case null:f=!1}form_refresh();e?g_start_time=(new Date).getTime():(new Date).getTime()>g_start_time+POLL_MAXTIME&&(b=f=!0,lpdbg("site","max timeout"));f?(b?j?show_cpw_dialog("captcha"):h?show_cpw_dialog("timeout"):d?show_cpw_dialog("fail_pw_saved"):show_cpw_dialog("fail"):show_cpw_dialog("dismiss"),g_ischrome?setTimeout(function(){form_refresh()},3001):setTimeout(function(){get_data("siterefresh",function(){form_refresh()})},
3001)):setTimeout(function(){cpw_status_check()},CPW_WAKETIME)}
function form_refresh(){var a=getBG(),c=document;if(!c||(!a||!data)||!a.lploggedin)return!1;var f=(new Date).getTime(),b=0;if(my_aid){var j=get_record(my_aid,!0);if(j){var e="";"undefined"!=typeof a.g_pending_pw_change&&(e=a.lpdec_acct(a.g_pending_pw_change[my_aid],j,a.g_shares));var d=getpasswordfromacct(j);if(j.save_all){c=document.getElementById("fields").contentWindow.document;for(b=0;b<g_pw_field_ids.length;b++){var h=c.getElementById(g_pw_field_ids[b]);if(h){var g=h.value;if(d&&h&&e&&e!=d&&
(d==g||e==g))lpdbg("site","using pending pw instead of g_sites"),d=e;d&&h&&(g===d?console.warn("REFRESH: no change"):g&&d&&(h.value=d,lpdbg("site","REFRESH: reset password iframe field from "+(a.g_show_pw_in_logs?g:"REDACTED")+" to "+(a.g_show_pw_in_logs?d:"REDACTED"))));update_SaveButton()}}}else{h=c.getElementById("password");g=h.value;if(d&&h&&e&&e!=d&&(d==g||e==g))lpdbg("site","using pending pw instead of g_sites"),d=e,b=f/1E3;d&&h&&(g!==d&&g&&d)&&(h.value=d,lpdbg("site","REFRESH: reset password from "+
(a.g_show_pw_in_logs?g:"REDACTED")+" to "+(a.g_show_pw_in_logs?d:"REDACTED")),e=issharedfolder(a.g_shares,data.group),data.password=a.lpmenc(d,!0,!1==e?a.g_local_key:e.sharekey),0<b?pw_age_update(b):pw_age_update(j.last_pwchange_gmt),update_password_meter("",c.getElementById("password").value),update_SaveButton())}}}return!1}
function show_cpw_button(a){var c=getBG(),f=document;if(!f||!c||!a)return!1;var b=!1;!g_cpwbot&&("undefined"!=typeof c.g_cpwbot&&c.g_cpwbot)&&(g_cpwbot=c.g_cpwbot);c=issharedfolder(c.g_shares,a.group);a&&(c?(checkreadonly(c,!0)?(b=!1,lpdbg("site","in shared folder, writable")):(b=!0,lpdbg("site","in shared folder, readonly")),"1"===c.associative&&lpdbg("site","entry is in linked account")):a.individualshare?null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?
(lpdbg("site","individual share, readonly"),b=!0):(lpdbg("site","individual share, writable"),b=!1):b=!1);if(g_cpwbot&&a&&"1"==a.pwch&&!b)if(a.save_all)enable_cpw_field_btn(document);else{if(a=f.getElementById("cpwbtnmini"))a.addEventListener("click",function(){document.getElementById("cpwbtnmini").classList.contains("btn_disabled")||show_cpw_dialog("new")}),a.style.fontSize="12px",a.style.display="inline-block";if(a=f.getElementById("pwspacer"))a.style.display="inline-block",a.style.width="50px"}else{if(a=
f.getElementById("cpwbtnmini"))a.style.display="none";if(a=f.getElementById("pwspacer"))a.style.display="none";if(f=f.getElementById("cpwfieldbtn"))f.style.display="none"}}
function pw_age_update(a){var c=getBG(),f=document;if(!f||!c||!data)return!1;a=parseInt(a);var b=(new Date).getTime(),c=180,c=0,b=null===b?0:parseInt(b/1E3)-60*c,c="Never";if(!a||"number"!=typeof a||!b||isNaN(a)||isNaN(b)||b<a){c="";if(a=f.getElementById("pwagelabel"))a.style.display="none";pass}else f.getElementById("pwagelabel"),a=b-a,60>a?c=a.toString()+" "+(1==a?gs("second"):gs("seconds")):3600>a?(a=parseInt(a/60),c=a.toString()+" "+(1==a?gs("minute"):gs("minutes"))):86400>a?(a=parseInt(a/3600),
c=a.toString()+" "+(1==a?gs("hour"):gs("hours"))):604800>a?(a=parseInt(a/86400),c=a.toString()+" "+(1==a?gs("day"):gs("days"))):2592E3>a?(a=parseInt(a/604800),c=a.toString()+" "+(1==a?gs("week"):gs("weeks"))):31536E3>a?(a=parseInt(a/2592E3),c=a.toString()+" "+(1==a?gs("month"):gs("months"))):(a=parseInt(a/31536E3),c=a.toString()+" "+(1==a?gs("year"):gs("years")));a=f.getElementById("pwagediv");a.style.fontStyle="italic";a&&(set_innertext(a,c),f.getElementById("pwagelabel").style.display="inline")}
function hide_cpw_dialog(){var a=getBG(),c=document;if(!c||!a||!data)return!1;c.getElementById("pwcontainer");var f=c.getElementById("cpwdialog");f&&(f.style.display="none");if(c=c.getElementById("modalbg"))c.style.display="none";"undefined"!=typeof a.cpwbot_halt&&(c=get_current_state(),"FAIL"!=c&&("CAPTCHA"!=c&&"DONE"!=c&&"OK"!=c&&"TIMEOUT"!=c&&0!=c&&null!==c)&&a.cpwbot_halt());data&&data.openchpw&&a.close_cpw_tabs()}var event_flags=0,EV_CX=1,EV_OK=2,g_cpw_heard_from_bg=!1;
function append_text_with_b(a,c){var f=c.indexOf("<b>"),b=c.indexOf("</b>");a.appendChild(a.ownerDocument.createTextNode(c.substring(0,f)));var j=a.ownerDocument.createElement("b");set_innertext(j,c.substring(f+3,b));a.appendChild(j);a.appendChild(a.ownerDocument.createTextNode(c.substring(b+4)))}
function show_cpw_dialog(a,c,f,b,j){var e=getBG(),d=document;if(!d||!e||!data)return!1;d.getElementById("notesrow1");d.getElementById("pwcontainer");e=d.getElementById("modalbg");e.style.width=d.body.clientWidth;e.style.height=d.body.clientHeight;e.style.display="block";var h=d.getElementById("dlghdg"),e=d.getElementById("dlghtml");e.style.fontSize="12px";var g=d.getElementById("bcnd"),m=d.getElementById("bokd"),k=d.getElementById("bdis"),l=null;g&&0==(event_flags&EV_CX)&&(g.addEventListener("click",
function(){hide_cpw_dialog()}),d.getElementById("dlgclose").addEventListener("click",function(){hide_cpw_dialog()}),k.addEventListener("click",function(){hide_cpw_dialog()}),event_flags|=EV_CX);m&&0==(event_flags&EV_OK)&&(m.addEventListener("click",function(a){docpwbtn(a);return!1}),event_flags|=EV_OK);set_innertext(g,gs("No, Thanks"));set_innertext(m,gs("Change Password Now"));set_innertext(k,gs("Dismiss"));set_innertext(h,sprintf(gs("%s Password One-Click Change"),"LastPass"));switch(a){case "new":g_cpw_heard_from_bg=
!1;LP_decimate_children(e);b=d.createElement("p");set_innertext(b,sprintf(gs("%s will now attempt to change your password to a strong, generated password that will be saved in your vault and known only to you."),"LastPass"));e.appendChild(b);e.appendChild(d.createElement("br"));b=d.createElement("p");append_text_with_b(b,sprintf(gs("In order to complete the process, %s will have to log in to %s and navigate through a number of windows quickly. It is normal to see windows flashing and changing quickly, and may take several moments. We'll let you know when you're all set!"),
"LastPass","<b>"+of(data.name)+"</b>"));e.appendChild(b);g.style.display="block";m.style.display="block";k.style.display="none";break;case "progress":LP_decimate_children(e);j=d.createElement("b");set_innertext(j,gs("Overall Progress:"));e.appendChild(j);e.appendChild(d.createElement("br"));j=d.createElement("div");j.className="progress_container";b=d.createElement("div");b.className="progress_bar";b.id="progress_bar";j.appendChild(b);e.appendChild(j);j=d.createElement("div");j.id="stepbystep";e.appendChild(j);
j=d.createElement("div");j.id="advanced";e.appendChild(j);d.getElementById("progress_bar").style.width="10%";g.style.display="none";m.style.display="none";k.style.display="none";break;case "update":d.getElementById("progress_bar").style.width=c+"%";f&&(e=d.createElement("p"),"DOCAPTCHA"==get_current_state()&&(e.className="boldred"),g=d.createTextNode(f),e.appendChild(g),d.getElementById("stepbystep").appendChild(e),g_cpw_heard_from_bg||(g_cpw_heard_from_bg=!0,(l=d.getElementById("cpw_placeholder_msg"))&&
l.parentNode.removeChild(l)));b&&(e=d.createElement("i"),g=d.createTextNode(gs("Complete!")),e.appendChild(g),(b=d.getElementById("stepbystep").lastChild)&&b.appendChild(e));j&&(e=d.createElement("p"),g=d.createTextNode(j),e.appendChild(g),d.getElementById("advanced").appendChild(e));break;case "dismiss":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");append_text_with_b(b,sprintf(gs("Congratulations! Your password for %s was updated, and is now saved in your LastPass vault. Your change will sync on every device."),
"<b>"+of(data.name)+"</b>"));e.appendChild(b);g.style.display="none";m.style.display="none";k.style.display="block";set_innertext(k,gs("OK"));break;case "fail":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");append_text_with_b(b,sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+"</b>"));e.appendChild(b);g.style.display="none";m.style.display=
"none";k.style.display="block";break;case "captcha":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");set_innertext(b,gs("Unable to proceed, the website does not allow automated password change."));e.appendChild(b);g.style.display="none";m.style.display="none";k.style.display="block";break;case "timeout":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");set_innertext(b,
gs("Timed out waiting for the page to load.  Retry?"));e.appendChild(b);g.style.display="none";m.style.display="none";k.style.display="block";break;case "fail_pw_saved":LP_decimate_children(e),e.appendChild(d.createElement("br")),e.appendChild(d.createElement("br")),b=d.createElement("p"),append_text_with_b(b,sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+"</b>")+gs("The random password that was generated has been saved to your vault.")),
e.appendChild(b),g.style.display="none",m.style.display="none",k.style.display="block"}j=d.getElementById("cpwdialog");j.style.display="block";j.style.height="250px";j.style.width="470px";j.style.left=(parseInt(d.body.clientWidth)-470)/2+"px";j.style.top=(parseInt(d.body.clientHeight)-470)/2+"px";g_ischrome||(g_cpwbot_pwchangestate="init_state_dingbats")}
function notehist(){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&notehistory="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}var g_cpwbot_pwchangestate=null;function cpw_progress_update(a){a&&a!=g_lastmsg&&(g_lastmsg=a,g_cpw_progress_ctr+=20,90<g_cpw_progress_ctr&&(g_cpw_progress_ctr=95),show_cpw_dialog("update",g_cpw_progress_ctr,a,!1,""))}
function get_current_state(a){if(g_ischrome)return getBG().cpwbot_getpwchangestate();var c=g_cpwbot_pwchangestate;a&&getBG().cpwbot_getpwchangestate();return c}
function enable_cpw_field_btn(a){var c=a.getElementById("cpwfieldbtn");c&&(c.addEventListener("click",function(){!a.getElementById("cpwfieldbtn").classList.contains("btn_disabled")&&!a.getElementById("cpwbtnmini").classList.contains("btn_disabled")&&show_cpw_dialog("new")}),c.style.fontSize="12px",c.style.display="inline-block",c.style.marginTop="5px",c.style.marginBottom="5px")}
function accelerator_key_handler(a){if(!g_do_keyaccel)return!0;if(!a||!a.keyCode)return!1;var c=!0,f=!1;try{"undefined"!=typeof navigator&&"undefined"!=typeof navigator.platform&&0==navigator.platform.toLowerCase().indexOf("mac")&&(c=!1,f=!0)}catch(b){}var j=document;if(!j)return!1;switch(a.keyCode){case KEY_S:if(a.ctrlKey&&f||a.altKey&&c)"function"!=typeof a.preventDefault&&a.preventDefault(),is_savebtn_disabled(j)||dosave(),LP_stopEventPropagation(a)}return!0}
function is_savebtn_disabled(a){a||(a=document);a=a.getElementById("save");return!a?!0:0<=a.className.indexOf("btn_disabled")}function insert_cpw_placeholder_msg(a,c){a||(a=document);var f=a.getElementById("cpw_placeholder_msg");if(c&&!g_cpw_heard_from_bg&&null===f){var f=a.createElement("p"),b=a.createTextNode(c);f.id="cpw_placeholder_msg";f.appendChild(b);a.getElementById("stepbystep").appendChild(f)}};
