function addTileBox(a,d){var g=null,b=null,f=null,c=!1;if("undefined"!=typeof a.sharerusername)g=a.id,b=gs("Share offer from")+":",f=of(getBG().hex2bin(a.sharerusername)),c=!0;else{if(typeof a.url&&"http://group"==a.url)return;g="undefined"!=typeof a.aid?a.aid:a.appaid;b=a.name;f=getusernamefromacct(a)}var h=getBG(),j=h.geticonurlfromrecord(a,!0),h=h.getbigiconurlfromrecord(a);null==j&&null==h&&(h=gLocalBaseUrl+"images/logos/lastpass.png");h||"http://sn"==a.url&&ofa("undefined"!=typeof a.notetype&&
""!=a.notetype?a.notetype:"Generic");b&&of(b);f&&of(f);b=document.createElement("div");b.className="tile";b.setAttribute("acctid",g);c?b.setAttribute("pending","1"):b.setAttribute("draggable","true");document.getElementById(d)?document.getElementById(d).appendChild(b):console.error("cannot find parent: "+d)}
function addGroupBox(a,d,g){d||(d="#thegrid");var b=get_div_id();g_groupidmap[a]=b;g_idgroupmap[b]=a;g="undefined"!=typeof g[a]?"grpopen":"grpclose";0==a.indexOf("_")&&(a=a.substring(1));a=of(a);$("<a class='tiletoplink' acctid='_"+b+"'><div class='bigfolder'><div class='"+g+"'></div><p class='name'>"+a+"</p></div></a><div id='c_"+b+"' class='cont'></div>").appendTo($(d))}
function setupTileEvents(){$(".tiletoplink").unbind("click");$(".tile").unbind("mouseover");$(".tile").unbind("contextmenu");$(".tile").unbind("dragstart");$(".tiletoplink").click(function(a){var d=getNodeAcctId(a.target);if(""!=d)if("_"==d[0]){a=getBigFolder(a.target);var g=getOpenedGroups(),b="#c"+d,d=getgroupnamefromid(d.substr(1),!0);"undefined"!=typeof g[d]?(closeTileGroup(b),d=$(a).children(".grpopen"),$(d).addClass("grpclose"),$(d).removeClass("grpopen")):(openTileGroup(b),d=$(a).children(".grpclose"),
$(d).addClass("grpopen"),$(d).removeClass("grpclose"));saveGroupState()}else ls(d)});$(".tile").mouseover(function(a){process_mouseover(a)});$(".tile").bind("contextmenu",function(a){process_rightclk(a);return!1});$(".tile").bind("dragstart",function(a){g_dragid=getNodeAcctId(a.target)})}
function process_rightclk(a){setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),g={};g[gs("Move Selected to Group")]=function(){a.lpevent("v_multmov");openMoveGroup(n)};g[gs("Delete Selected")]=function(){a.lpevent("v_multd");a.deleteAid(ids,window,!1,!1,function(){for(var a=0;a<saved.length;a++)$.tree.focused().cut(saved[a])})};return[g]},{theme:"vista"}).show(t,a)},100)}
function process_mouseover(a){var d=getBG(),g=getTile(a.target);if(g&&!$(g).children(".tileoverlay").length){var b=getNodeAcctId(a.target),f=get_record(b),c=!1;null==f&&"undefined"!=typeof d.g_applications[b]&&(f=d.g_applications[b],c=!0);if(null==f)getTile(a.target).hasAttribute("pending")&&(gs("Accept"),gs("Reject"),c=document.createElement("div"),c.id="hoverlaytop",c.className="tileoverlay",c.acctid=b,g.appendChild(c),$("#hoverlayaccept,#hoverlayreject").unbind("click"),$("#hoverlayaccept").click(function(a){a=
getNodeAcctId(a.target);accept(a)}),$("#hoverlayreject").click(function(a){a=getNodeAcctId(a.target);reject(a)}));else{a=!c&&"http://sn"!=f.url;var h=!c&&f&&"undefined"==typeof f.sharefolderid&&("undefined"==typeof f.sharedfromaid||null==f.sharedfromaid||""==f.sharedfromaid||"0"==f.sharedfromaid||"null"==f.sharedfromaid)&&d.g_sharing_enabled,d=!c&&"http://sn"!=f.url&&("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&"undefined"==typeof g_ismaxthon&&"undefined"==typeof g_isfirefoxsdk||
"function"==typeof d.can_copy_to_clipboard&&d.can_copy_to_clipboard()||"undefined"!=typeof g_is_safari);a?gs("Launch Site"):gs("Edit Note");!d||gs("Copy Password");!h||gs("Share");gs("Edit");c&&(b="app"+b);c=document.createElement("div");c.id="hoverlaytop";c.className="tileoverlay";g.appendChild(c);c.setAttribute("acctid",b);$("#hoverlayedit,#hoverlayshare,#hoverlaylaunch,.vaultcheck,#hoveroverlaycopy").unbind("click");$("#hoverlayedit").click(function(a){a=getNodeAcctId(a.target);e(a)});$("#hoverlayshare").click(function(a){a=
getNodeAcctId(a.target);s(a)});$("#hoverlaylaunch").click(function(a){a=getNodeAcctId(a.target);ls(a)});$("#hoverlaycopy").click(function(a){a=getNodeAcctId(a.target);getBG().copypassword(a)});$(".vaultcheck").click(function(a){var b=a.target.checked;a=getTile(a.target);b?$(a).css("border","1px solid yellow"):$(a).css("border","1px solid transparent")})}$(".tile").unbind("mouseout");$(".tile").mouseout(function(a){a=$(a.toElement);"hoverlaytop"!=a.attr("id")&&0==a.parents("div#hoverlaytop").length&&
$(".tileoverlay").remove()})}}function closeTileGroup(a){$(a).hide()}function openTileGroup(a){$(a).show()}function getNodeAcctId(a){if(a&&a.hasAttribute("acctid"))return a.getAttribute("acctid");for(var d="";""==d&&a.parentNode&&a.parentNode!=a;)if(a=a.parentNode,a.hasAttribute("acctid")){d=a.getAttribute("acctid");break}return d}function getTile(a){for(;a.parentNode&&a.parentNode!=a;)if(a=a.parentNode,"tile"==a.className)return a;return null}
function getBigFolder(a){if(-1!=a.className.indexOf("bigfolder"))return a;for(;a.parentNode&&a.parentNode!=a;)if(a=a.parentNode,-1!=a.className.indexOf("bigfolder"))return a;return null}
function createTileData(a,d){var g=[],b=[],f=""==path?"_"+gs("(none)"):path;if(""==d){if("undefined"!=typeof a[f])for(var c=0;c<a[f].length;c++)"http://group"==a[f][c].url?b.push(a[f][c].group):g.push(a[f][c])}else for(c=0;c<a.length;c++)"http://group"==a[c].url?b.push(a[c].group):g.push(a[c]);c=getBG();g.sort(c.lp_sort_case_insensitive_name);b=getSubfolders(path,a,b);b.sort(function(a,b){return a.toLowerCase().localeCompare(b.toLowerCase())});for(c=b.length-1;0<=c;c--)""==d?g.unshift(b[c]):-1!=b[c].toLowerCase().indexOf(d)&&
g.unshift(b[c]);return g}
function createTile(a,d,g,b){g_groupidmap=[];g_idgroupmap=[];b=""!=b;for(var f=0;f<a.length;f++){var c=a[f],h=checkParentGroups(c,g);addGroupBox(c,h,g)}$(".bigfolder").bind("dragover",function(a){var b=getNodeAcctId(a.target);if(""!=b&&"_"==b[0]){var c=getBigFolder(a.target),b=getgroupnamefromid(b.substr(1),!0);b!=gs("favorites")&&(b!=g_xlat_runame&&b!=g_xlat_pendingname)&&$(c).addClass("bigfolderdroptarget")}a.preventDefault();a.stopPropagation()});$(".bigfolder").bind("dragleave",function(a){var b=
getBigFolder(a.target);$(b).removeClass("bigfolderdroptarget");a.preventDefault();a.stopPropagation()});$(".bigfolder").bind("drop",function(a){var b=getNodeAcctId(a.target);if(""!=b&&"_"==b[0]){var c=getBigFolder(a.target);$(c).removeClass("bigfolderdroptarget");b=getgroupnamefromid(b.substr(1),!0);a.originalEvent.dataTransfer.getData("id");console.error(g_dragid+" DROPPED IN "+b);getBG().moveSelectedToGroup(b.substr(1),g_dragid)}a.preventDefault();a.stopPropagation()});for(f=0;f<a.length;f++){var c=
a[f],h="c_"+g_groupidmap[c],j=d[c];j.sort(getBG().lp_sort_case_insensitive_name);for(var k=0;k<j.length;k++)addTileBox(j[k],h);b||"undefined"!=typeof g[c]||((c=document.getElementById(h))?c.style.display="none":console.error("no parent "+h))}}function checkParentGroups(a,d){var g=a.split("/");if(1==g.length)return null;for(var b="",f=0;f<g.length;f++)b+=(""==b?"":"/")+g[f],0==$("#contents"+b).length&&addGroupBox(a,"#contents"+b,d);return"#"+b};
