var g_toolstripid=get_random(0,999999999),g_moles={},g_curmole=null,g_newmole=null,g_changepwnewpw="",g_changepwtld="",g_changepwexcludeid=0,g_browseraction=-1!=document.location.href.indexOf("?browseraction=1"),g_yubikey=-1!=document.location.href.indexOf("&yubikey=1"),g_googleauth=-1!=document.location.href.indexOf("&googleauth=1"),g_outofband=-1!=document.location.href.indexOf("&outofband=1"),g_securityquestion=-1!=document.location.href.indexOf("&securityquestion=1"),g_sesame=-1!=document.location.href.indexOf("&sesame=1"),
g_grid=-1!=document.location.href.indexOf("&grid=1"),g_generate=-1!=document.location.href.indexOf("&generate=1"),g_chooseprofilecc=-1!=document.location.href.indexOf("&chooseprofilecc=1"),g_changepw=-1!=document.location.href.indexOf("&changepw=1"),g_alert=-1!=document.location.href.indexOf("&alert=1"),g_generate_url="",g_generate_found=!1,g_tabid=null,matches=document.location.href.match(/&tabid=(\d+)/);matches&&(g_tabid=matches[1]);
var g_ismenu=!1,g_issafari="undefined"!=typeof safari&&"undefined"!=typeof safari.self;
function onLoad(a){lpdbg("toolstrip","loading toolstrip");if(!a&&(!g_alert||!g_issafari)&&("undefined"==typeof safari||"undefined"==typeof safari.extension.globalPage))get_data(g_changepw?"toolstripchangepw":"toolstrip",function(){onLoad(!0)});else{g_generate&&(g_generate_url=getBG().g_generate_url,""!=getBG().g_generate_url&&(getBG().g_generate_url_prev=getBG().g_generate_url),getBG().g_generate_url="");g_changepw&&(g_changepwnewpw=getBG().g_changepwnewpw,g_changepwtld=getBG().g_changepwtld,g_changepwexcludeid=
"undefined"!=typeof getBG().g_changepwexcludeid?getBG().g_changepwexcludeid:0);L("TS["+g_toolstripid+"] : loaded");g_ischrome&&sendBG({cmd:"getloginstate"});g_curmole="lpbutton";addmole("lpbutton");"undefined"!=typeof onheightmenu&&addmole("lpmenu",onheightmenu,oninitmenu,onshowmenu,onhidemenu);addmole("lpnotify",80,oninitnotify,onshownotify);addmole("lpgeneratecont",300,oninitgenerate,onshowgenerate,onhidegenerate);addmole("lpchooseprofilecc",300,oninitchooseprofilecc,onshowchooseprofilecc,onhidechooseprofilecc);
addmole("lpchangepw",300,oninitchangepw,onshowchangepw,onhidechangepw);addmole("lpyubikey",350,oninityubikey,onshowyubikey,onhideyubikey);addmole("lpgoogleauth",350,oninitgoogleauth,onshowgoogleauth,onhidegoogleauth);addmole("lpoutofband",350,oninitoutofband,onshowoutofband,onhideoutofband);addmole("lpsecurityquestion",350,oninitsecurityquestion,onshowsecurityquestion,onhidesecurityquestion);addmole("lpsesame",350,oninitsesame,onshowsesame,onhidesesame);addmole("lpgrid",350,oninitgrid,onshowgrid,
onhidegrid);addmole("lpinlinelogin",850,oninitlogin,onshowlogin,onhidelogin);for(var b in g_moles)("lpbutton"!=b||g_browseraction)&&$("#"+b).hide(),"function"==typeof g_moles[b].initfunc&&g_moles[b].initfunc();if(g_browseraction)if(lpdbg("toolstrip","detected browser action"),g_yubikey)document.title=gs("YubiKey Multifactor Authentication"),openmole("lpyubikey");else if(g_googleauth)document.title=gs("Google Authenticator Multifactor Authentication"),openmole("lpgoogleauth");else if(g_outofband)document.title=
gs("Multifactor Authentication"),openmole("lpoutofband");else if(g_securityquestion)document.title=gs("Security Question Multifactor Authentication"),openmole("lpsecurityquestion");else if(g_sesame)document.title=gs("Sesame Multifactor Authentication"),openmole("lpsesame");else if(g_grid)document.title=gs("LastPass Grid Multifactor Authentication"),openmole("lpgrid");else if(g_generate)document.title=gs("Generate Secure Password"),openmole("lpgeneratecont");else if(g_chooseprofilecc)document.title=
gs("Choose Profile and Credit Card"),openmole("lpchooseprofilecc");else if(g_changepw)document.title=gs("Change Password"),openmole("lpchangepw");else if(null!=getBG()&&null!=getBG().g_badgedata)lpdbg("toolstrip","have badge data"),receiveBG(getBG().g_badgedata),setTimeout(function(){getBG().clear_badge()},100);else{g_isfirefoxsdk&&(document.getElementById("body").style.backgroundColor="#fff");if(g_ismaxthon||g_isfirefoxsdk)include_language(getBG().g_language),g_menus=[];g_ismenu=!0;openmenu();g_ismaxthon&&
(window.external.mxGetRuntime().onAppEvent=function(a){"ACTION_HIDE"==a.type&&(document.getElementById("content").style.display="none")})}toolstrip_loaded();g_isfirefoxsdk&&dispatch_message("onload_done",{need_data:-1!=document.location.href.indexOf("delay_data=1")})}}var g_closed=!1;function onUnload(){g_closed=!0;g_curmole&&"function"==typeof g_moles[g_curmole].hidefunc&&g_moles[g_curmole].hidefunc()}
function sendBG(a){try{var b=getBG();if(b)return L("TS -> BG : cmd="+a.cmd),b.receiveTS(g_toolstripid,a);L("TS -> BG : FAILED")}catch(c){L("TS -> BG : FAILED error="+c)}return null}
function receiveBG(a){lpdbg("toolstrip","received from bg");if("undefined"==typeof a.cmd)L("BG -> TS : INVALIDMSG");else switch(L("BG -> TS : "+a.cmd),a.cmd){case "login":$("#lploggedin").show();$("#lplogin").hide();break;case "logout":case "logoff":"lpmenu"==g_curmole&&closemole();$("#lploggedin").hide();$("#lplogin").show();break;case "genpw":document.title=gs("Generate Secure Password");openmole("lpgeneratecont");break;case "chooseprofilecc":document.title=gs("Choose Profile and Credit Card");
openmole("lpchooseprofilecc");break;case "changepw":g_changepwnewpw=a.newpw;g_changepwtld=a.tld;g_changepwexcludeid="undefined"!=typeof a.excludeid?a.excludeid:0;document.title=gs("Change Password");openmole("lpchangepw");break;case "yubikey":document.title=gs("YubiKey Multifactor Authentication");openmole("lpyubikey");break;case "googleauth":document.title=gs("Google Authenticator Multifactor Authentication");openmole("lpgoogleauth");break;case "outofband":document.title=gs("Multifactor Authentication");
openmole("lpoutofband");break;case "securityquestion":document.title=gs("Security Question Multifactor Authentication");openmole("lpsecurityquestion");break;case "sesame":document.title=gs("Sesame Multifactor Authentication");openmole("lpsesame");break;case "notification":lpdbg("toolstrip","got notification");a=a.type;if(0!=getBG().lpGetPref("showNotifications",1)||"error"==a||"upgrade"==a||"alert"==a)lpdbg("toolstrip","opening lpnotify mole"),openmole("lpnotify");break;default:L("BG -> TS : INVALIDMSG")}}
function isloggedin(){return getBG().lploggedin}function openmenu(){!isloggedin()&&!g_isfirefoxsdk?g_ischrome||g_ismaxthon||g_isfirefoxsdk?openmole("lpinlinelogin"):(closemole(),getBG().open_login(!0)):openmole("lpmenu")}function addmole(a,b,c,d,e){g_moles[a]={height:b,initfunc:c,showfunc:d,hidefunc:e}}function hidemenu(){$("#menucontainer").hide()}function hidemoles(){for(var a in g_moles)("lpbutton"!=a||g_browseraction)&&$("#"+a).hide()}
function closemole(){if(g_browseraction){if(g_ismaxthon)setTimeout(function(){window.external.mxGetRuntime().getActionByName("lppanel").hide()},0);else{if(g_issafari){g_changepw||"function"!=typeof getBG().closePop?window.close():getBG().closePop();return}if(g_isfirefoxsdk){getBG().closecurrenttab("lp_toolstrip.html");dispatch_message("closepop",{});return}}g_ismenu||"lpnotify"==g_curmole||"lpchangepw"==g_curmole?(setTimeout(function(){window.close()},0),setTimeout(function(){window.close()},1E3),
setTimeout(function(){window.close()},1E4)):g_yubikey||g_googleauth||g_outofband||g_securityquestion?setTimeout(function(){getBG().closecurrenttab("lp_toolstrip.html")},0):g_closed||(g_closed=!0,setTimeout(function(){getBG().closecurrenttab(-1!=document.location.href.indexOf("mpwchange.html")?"mpwchange.html":"")},0))}else $("#body").css("background",""),g_newmole=null}
function openmole(a){lpdbg("toolstrip","opening mole "+a);g_browseraction?hidemoles():closemole();$("#content").show();g_newmole=a;if("lpbutton"==a)$("#lpbutton").show(),"function"==typeof g_moles.lpbutton.showfunc&&g_moles.lpbutton.showfunc();else if("lpinlinelogin"==a)g_ismaxthon||is_opera_chromium()||g_isfirefoxsdk?(a=(new Date).getTime(),a>g_login_logoff_time+100&&(g_login_logoff_time=a,g_ismaxthon?getBG().open_login(!0):getBG().openURL(getchromeurl("login.html"))),closemole()):g_issafari&&"undefined"!=
typeof SafariExtensionPopover&&parent&&parent.document&&"undefined"!=typeof parent.showwin?getBG().open_login():document.location.href=getchromeurl("login.html?inline=1");else{if("lpgeneratecont"==a){LP_decimate_children(document.getElementById("lpgeneratecont"));var b=document.createElement("div");b.id="genheader";var c=document.createElement("div");c.id="gentitle";set_innertext(c,gs("Generate"));b.appendChild(c);document.getElementById("lpgeneratecont").appendChild(b);g_generate||(b=document.createElement("div"),
b.id="backrow",b.className="backgen",b.appendChild(document.createElement("span")),b.appendChild(document.createTextNode(gs("BACKUPPER"))),document.getElementById("lpgeneratecont").appendChild(b));document.getElementById("lpgeneratecont").appendChild(createGenerateHtml(document,!0,!0,!0));stylize_generate_html(document);stylize_ghetto_meter(document,METER_WIDTH);g_issafari&&$(".tooltipgen1").click(function(a){a.preventDefault()});b=document.createElement("link");b.rel="stylesheet";b.type="text/css";
b.href="popupfilltab.css";b.id="popupfilltab_css";document.body.appendChild(b);setup_generate_handlers();populate_usernames();g_pointer_stack.push(g_pointer);g_ids.push(a);g_pointer=null;$("#backrow").click(function(){$("#popupfilltab_css").remove();$("#lpgeneratecont").hide();$("#menucontainer").show();document.getElementById("lpgenerate").style.margin="8px";goback()});setTimeout(function(){create_combo("password",[],!0,document);repopulate_combo("password",getBG().g_genpws);document.getElementById("password_button").style.left=
"200px";document.getElementById("password_button").style.padding="0px";document.getElementById("password_button").style.top="75px"},100);resize_generate()}lpdbg("toolstrip","not lpbutton");"lpbutton"==g_curmole?($("#lpbutton").hide(),"function"==typeof g_moles.lpbutton.hidefunc&&g_moles.lpbutton.hidefunc(),g_ischrome?getBG().get_selected_tab(null,function(a){getBG().setcurrenttabid(a.id);getBG().setcurrenturl(getBG().gettaburl(a));g_browseraction&&toolstrip_expanded()}):(g_issafari||g_isopera||g_ismaxthon||
g_isfirefoxsdk)&&toolstrip_expanded()):(lpdbg("toolstrip","curr is not not lpbutton"),g_browseraction&&(lpdbg("toolstrip","is browser action"),toolstrip_expanded()))}}function toolstrip_expanded(){lpdbg("toolstrip","toolstrip expanded");g_curmole=g_newmole;g_newmole=null;"function"==typeof g_moles[g_curmole].showfunc&&(lpdbg("toolstrip","calling showfunc"),g_moles[g_curmole].showfunc());$("#"+g_curmole).show()}
function toolstrip_loaded(){getBG().allowmultifactortrust||(document.getElementById("lptrustyubi").style.display="none",document.getElementById("lp_docwrite_lp_toolstrip30").style.display="none",document.getElementById("lptrustgoogleauth").style.display="none",document.getElementById("lp_docwrite_lp_toolstrip37").style.display="none",document.getElementById("lptrustoutofband").style.display="none",document.getElementById("lp_docwrite_lp_toolstrip62").style.display="none",document.getElementById("lptrustsecurityquestion").style.display=
"none",document.getElementById("lp_docwrite_lp_toolstrip56").style.display="none",document.getElementById("lptrustsesame").style.display="none",document.getElementById("lp_docwrite_lp_toolstrip43").style.display="none",document.getElementById("lptrustgrid").style.display="none",document.getElementById("lp_docwrite_lp_toolstrip49").style.display="none");getBG().hidemultifactordisable&&(document.getElementById("lostkey").style.display="none",document.getElementById("googleauthlostkey").style.display=
"none",document.getElementById("outofbandlostkey").style.display="none",document.getElementById("sesamelostkey").style.display="none",document.getElementById("lostgrid").style.display="none")};
