Strings={};
(function(g){g.Vault={EDIT:"Edit",SHARE:"Share",DELETE:"Delete",LAUNCH:"Launch",ADMIN_CONSOLE:"Admin Console",HELP_CENTER:"Help Center",ACCOUNT_SETTINGS:"Account Settings",LOGOUT:"Logout",ACCEPT:"Accept",REJECT:"Reject",ENABLE:"Enable",COPY_USERNAME:"Copy Username",COPY_PASSWORD:"Copy Password",COPY_URL:"Copy URL",MOVE_TO_FOLDER:"Move to Group",MOVE_TO_SUB_FOLDER:"Move to Sub-Group",DELETE_FOLDER:"Delete Group",RENAME_FOLDER:"Rename Group",SHARE_FOLDER:"Share Folder",RENAME:"Rename",CREATE_SUB_FOLDER:"Create Sub-Group",OPEN_ALL:"Open All Sites",
COPY_NOTE:"Copy Note",COPY_KEY:"Copy Key",FILL:"Fill",OPEN:"Open",SAVE:"Save",CANCEL:"Cancel",REVOKE:"Revoke Access",RESEND:"Resend Invitation",CANCEL_INVITE:"Cancel Invitation",REMOVE:"Remove",PURGE:"Purge",RESTORE:"Restore",CLOSE:"Close",MAXIMIZE:"Maximize",MINIMIZE:"Minimize",EDIT_ACCESS:"Edit Access",UNLINK_PERSONAL:"Unlink Personal Account",STOP_DOWNLOADING:"Stop Downloading Folder",START_DOWNLOADING:"Start Downloading Folder",CONFIRM_REQUEST_ACCESS:"Confirm Request Access",VAULT_TOGGLE:"Toggle LastPass 3.0",
AUTO_FILL:"Auto Fill",DELETED:"deleted",ADDED:"added",RENAMED:"renamed",SAVED:"saved",REMOVED:"removed",ACCEPTED:"accepted",DECLINED:"declined",PURGED:"purged",RESTORED:"restored",FOLDER_PURGE:"this folder's items",SELECTED_PURGE:"the selected items",CLONE:"Clone",MORE_OPTIONS:"More Options",MANAGE:"Manage",MANAGE_FOLDER:"Manage Folder",REQUEST_ACCESS:"Request Access",SHARED_WITH:"Shared with",SHARED_BY:"Shared by",PENDING_SHARE:"Pending share",LAST_USED:"Last used",WAITING_PERIOD:"Waiting period",
ACCESS_PENDING:"Access pending until",ACCESS_GRANTED:"Access granted",ACCOUNT_LINKED:"Account linked",GO_TO_URL:"Go to URL",UNEXPECTED_ERROR:"An unexpected error has occurred",READ_ONLY:"Read-Only",EMERGENCY_ACCESS_RECIPIENT:"Emergency Access Recipient",UNLINK:"Unlink",GENERATED:"Generated",NOT_DOWNLOADED:"Not downloaded",LINKED:"Linked",OUTSIDE_ENT:"Outside Enterprise",NO_SHARING_KEYS:"No Sharing Keys",GENERATED_PREFIX:"Generated Password for",PURGE_ALL:"Purge All",LINKED_PERSONAL_ACCOUNT:"Linked Personal Account",
EMERGENCY_ACCESS:"Emergency Access",COLLAPSE_ALL:"Collapse All",EXPAND_ALL:"Expand All",COMPACT_VIEW:"Show Compact View",LARGE_VIEW:"Show Large View",SHOW_PASSWORD:"Show Password",HIDE_PASSWORD:"Hide Password",GENERATE_PASSWORD:"Generate Password",ERROR:"Error",YES:"Yes",NO:"No",OPEN_DASHBOARD:"Open Dashboard",UPGRADE_PREMIUM:"Upgrade to Premium",AGO:"ago",NEVER:"Never",JUST_NOW:"just now",SECOND:"second",SECONDS:"seconds",MINUTE:"minute",MINUTES:"minutes",HOUR:"hour",HOURS:"hours",DAY:"day",DAYS:"days",
WEEK:"week",WEEKS:"weeks",MONTH:"month",MONTHS:"months",YEAR:"year",YEARS:"years",SITE:"Site",APPLICATION:"Application:",GROUP:"Group:",SECURE_NOTE:"Secure Note",FORM_FILL:"Form Fill",IDENTITY:"Identity",USER:"User",USER_GROUP:"User Group",SHARED_FOLDER:"Shared Folder",ADD_FOLDER:"Add New Folder",SHARE_ITEMS:"Share Item",ADD_FORM_FILL:"Add Form Fill",ADD_NOTE:"Add Secure Note",ADD_SITE:"Add Site",ADD_SHARED_FOLDER:"Add Shared Folder",ADD_IDENTITY:"Add Identity",GIVE_EMER_ACCESS:"Give Emergency Access",
ADD_CREDIT_MON:"Enable Credit Monitoring",DUUMY_TERMINATING_ENTRY:""};g.VaultDynamic={CONFIRM_PURGE:"Are you sure you want to purge %1? It will be permanently deleted from LastPass.",CONFIRM_RESTORE:"Are you sure you want to restore %1 to your vault?"};g.translateString=function(a){"undefined"!==typeof bg?a=bg.StringUtils.translate.apply(bg.StringUtils,arguments):"undefined"!==typeof StringUtils&&(a=StringUtils.translate.apply(StringUtils,arguments));if(1<arguments.length){for(var b=[],e=1,d=arguments.length;e<
d;++e){var c=arguments[e];if("object"===typeof c){var f=a.indexOf("%"+e);b.push(document.createTextNode(a.substring(0,f)));b.push(LPTools.createElement(c.type,c.attributes,c.text));a=a.substring(f+2)}}if(0<b.length)return 0<a.length&&b.push(a),b}return a};g.translate=function(a){for(var b,e;a;){if(3===a.nodeType)a.textContent=this.translateString(a.textContent);else if(1===a.nodeType){var d=a.getAttribute("placeholder");null!==d&&a.setAttribute("placeholder",this.translateString(d));d=a.getAttribute("title");
null!==d&&a.setAttribute("title",this.translateString(d));if(null!==a.getAttribute("compoundtranslation")){d=a;b="";e=[];for(var c=d.firstChild;c;)3===c.nodeType?b+=c.textContent:1===c.nodeType&&(b+="%"+e.length+c.textContent+"%"+e.length,e.push(c)),c=c.nextSibling;b=g.translateString(b);LPTools.removeDOMChildren(d);for(var c=b.indexOf("%"),f=null;-1<c;){var h=b.substring(0,c);null===f?(d.appendChild(document.createTextNode(h)),f=parseInt(b.charAt(c+1))):((f=e[f])?(f.textContent=h,d.appendChild(f)):
d.appendChild(document.createTextNode(h)),f=null);b=b.substring(c+2);c=b.indexOf("%")}0<b.length&&d.appendChild(document.createTextNode(b))}else g.translate(a.firstChild)}a=a.nextSibling}};g.translateStrings=function(a){for(var b in a)a[b]=g.translateString(a[b])};return g})(Strings);
