function LP_getElementByXPath(a,b){return!a&&(a=LP_derive_doc(),!a)?null:LP_lookupElementByXPath(a,b)}function LP_getElementsByXPath(a,b){return!a&&(a=LP_derive_doc(),!a)?null:LP_lookupElementsByXPath(a,b)}
function LP_createXPathFromElement(a,b){if(!a&&(a=LP_derive_doc(),!a)||!b)return null;var e=a.getElementsByTagName("*"),c,d;if(0<e.length&&("undefined"==typeof e[0].hasAttribute||"undefined"==typeof e[0].localName))return LP_getXPath(b);for(segs=[];b&&1==b.nodeType;b=b.parentNode)if(b.hasAttribute("id")){for(d=c=0;d<e.length&&!(e[d].hasAttribute("id")&&e[d].id==b.id&&c++,1<c);d++);if(1==c)return segs.unshift('id("'+b.getAttribute("id")+'")'),segs.join("/");c=b.parentNode?b.parentNode.children:[];
for(var f=d=0;f<c.length&&!("undefined"!=typeof c[f].hasAttribute&&(c[f].hasAttribute("id")&&c[f].id==b.id)&&d++,1<d);f++);if(1<d){c=1;for(d=b.previousSibling;d;d=d.previousSibling)d.localName==b.localName&&c++;segs.unshift(b.localName.toLowerCase()+"["+c+"]")}else segs.unshift(b.localName.toLowerCase()+'[@id="'+b.getAttribute("id")+'"]')}else if(b.hasAttribute("name"))segs.unshift(b.localName.toLowerCase()+'[@name="'+b.getAttribute("name")+'"]');else if(b.hasAttribute("action")&&"FORM"==b.nodeName.toUpperCase())segs.unshift(b.localName.toLowerCase()+
'[@action="'+b.getAttribute("action")+'"]');else if(b.hasAttribute("class"))segs.unshift(b.localName.toLowerCase()+'[contains(@class,"'+b.getAttribute("class")+'")]');else{c=1;for(d=b.previousSibling;d;d=d.previousSibling)d.localName==b.localName&&c++;segs.unshift(b.localName.toLowerCase()+"["+c+"]")}return segs.length?"/"+segs.join("/"):null}
function LP_lookupElementByXPath(a,b){return!a||!a.documentElement||g_isfirefox&&a&&!a.defaultView||"undefined"==(g_isfirefox?typeof a.defaultView.XPathEvaluator:typeof XPathEvaluator)?null:(g_isfirefox?new a.defaultView.XPathEvaluator:new XPathEvaluator).evaluate(b,a.documentElement,null,g_isfirefox?a.defaultView.XPathResult.FIRST_ORDERED_NODE_TYPE:XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}
function LP_lookupElementsByXPath(a,b){var e=[];if(!a||!a.documentElement||"undefined"==(g_isfirefox?typeof a.defaultView.XPathEvaluator:typeof XPathEvaluator))return e;var c=(g_isfirefox?new a.defaultView.XPathEvaluator:new XPathEvaluator).evaluate(b,a.documentElement,null,g_isfirefox?a.defaultView.XPathResult.ORDERED_NODE_ITERATOR_TYPE:XPathResult.ORDERED_NODE_ITERATOR_TYPE,null);if(c)for(var d=c.iterateNext();d;)d&&e.push(d),d=c.iterateNext();return e}
if("undefined"==typeof Node)var Node={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12};
function LP_getXPath(a){function b(a){return"undefined"!=typeof Document?a instanceof Document:a&&a.nodeType==e}var e=9,c,d=[],f="";if(b(a))return"/";for(;a&&!b(a);a=2==a.nodeType?a.ownerElement:a.parentNode){c=d[d.length]={};switch(a.nodeType){case 1:c.name="text()";break;case 2:c.name="@"+a.nodeName;break;case 7:c.name="processing-instruction()";break;case 8:c.name="comment()";break;case 3:c.name=a.nodeName}var h;h=1;var g=void 0;if(2==a.nodeType)h=null;else for(g=a.previousSibling;g;g=g.previousSibling)g.nodeName==
a.nodeName&&++h;c.position=h}for(a=d.length-1;0<=a;a--)c=d[a],f+="/"+c.name,null!=c.position&&(f+="["+c.position+"]");return f};
